# -*- coding: utf-8 -*-
#################################################################################
# Author      : Acespritech Solutions Pvt. Ltd. (<www.acespritech.com>)
# Copyright(c): 2012-Present Acespritech Solutions Pvt. Ltd.
# All Rights Reserved.
#
# This program is copyright property of the author mentioned above.
# You can`t redistribute it and/or modify it.
#
#################################################################################
{
    'name': "POS Pharmacy (Community)",
    'summary': "POS Pharmacy",
    'description': """POS Pharmacy""",
    'category': 'Point of Sale',
    'author': 'Acespritech Solutions Pvt. Ltd.',
    'website': "http://www.acespritech.com",
    'version': '3.4.3',
    'depends': ['base', 'point_of_sale', 'sale_management', 'barcodes', 'stock', 'purchase', 'bus',
                'hr_attendance', 'account', 'pos_hr', 'product_expiry', 'hr', 'stock', 'hr_expense'],
    'price': 350.00,
    'currency': 'EUR',
    'images': [
        'static/description/main_screenshot.png',
    ],
    'data': [
        'security/ir.model.access.csv',
        'security/monitor_security.xml',
        'data/product_data.xml',
        'data/mail_template.xml',
        'data/ir_cron.xml',
        'views/pos_config_view.xml',
        'views/pharmacy_assets.xml',
        'views/pos_payment_method_view.xml',
        'views/pos_order_line_view.xml',
        'views/pos_promotion_view.xml',
        'views/res_users_view.xml',
        'views/res_partner_view.xml',
        'views/wallet_management_view.xml',
        'views/wallet_view.xml',
        'views/gift_card.xml',
        'views/gift_voucher_view.xml',
        'views/product_view.xml',
        'views/hr_employee_view.xml',
        'views/res_config_setting.xml',
        'views/loyalty_view.xml',
        'views/view_production_lot.xml',
        'wizard/non_moving_stock.xml',
        'data/send_mail.xml',
        'wizard/generate_product_barcode_view.xml',
        'report/pos_z_report_template.xml',
        'report/pos_z_thermal_report.xml',
        'report/report.xml',
        'report/pos_sales_report_pdf_template.xml',
        'report/front_sales_report_pdf_template.xml',
        'report/front_inventory_session_pdf_report_template.xml',
        'report/front_inventory_location_pdf_report_template.xml',
        'report/sales_details_template.xml',
        'report/sales_details_pdf_template.xml',
        'report/customer_sale_and_return_report_template.xml',
        'report/customer_sale_and_return_report.xml',
        'report/pos_sales_report_template.xml',
        'report/front_sales_thermal_report_template.xml',
        'report/non_moving_product_report.xml',
        'data/account_financial_report_data.xml',
        'wizard/tax_report_wiz_view.xml',
        'wizard/aged_payble_view.xml',
        'wizard/trial_balance_wiz_view.xml',
        'wizard/aged_receivable_view.xml',
        'wizard/account_report_partner_ledger_view.xml',
        'wizard/profit_and_loss.xml',
        'wizard/balance_sheet.xml',
        'report/account_report.xml',
        'report/report_financial.xml',
        'wizard/general_ledger_wiz_view.xml',
        'views/tax_report_template.xml',
        'views/trial_balance_template.xml',
        'views/aged_payble_template.xml',
        'views/aged_receivable_template.xml',
        'views/partner_ledger_template.xml',
        'views/account_pdf_reports.xml',
        'views/general_ledger_template.xml',
        'views/active_ingredient.xml',
        'views/recurrent_order.xml',
        'views/delivery_order_screen.xml',

        'report/grp_category_product_expiry_report_template.xml',
        'wizard/product_expiry_report_wizard_view.xml',
        'views/product_expiry_report_view.xml',
        'report/slow_moving_inventory.xml',
        'report/slow_moving_inventory_pdf.xml',
        'wizard/slow_moving_inventory_wizard.xml',
        'views/product_expiry_config_view.xml',
        'views/product_expiry_dashboard.xml',
        
        'report/slow_moving_inventory.xml', 
        'report/slow_moving_inventory_pdf.xml', 
        'wizard/slow_moving_inventory_wizard.xml', 
    ],
    'qweb': [
        'static/src/xml/*.xml',
        'static/src/xml/ChromeWidgets/SelectUserForOrder.xml',
        'static/src/xml/ChromeWidgets/PharmacyDetailSidebar.xml',
        'static/src/xml/ChromeWidgets/OpenDetailButton.xml',
        'static/src/xml/ChromeWidgets/LockPosScreen.xml',
        'static/src/xml/ChromeWidgets/UnlockPosScreen.xml',
        'static/src/xml/ChromeWidgets/CustomerScreenButton.xml',
        'static/src/xml/Screens/PackLotLineScreen/PackLotLineScreen.xml',
        'static/src/xml/Screens/PackLotLineScreen/SinglePackLotLine.xml',
        'static/src/xml/Screens/ReceiptScreen/PosSerialReceipt.xml',
        'static/src/xml/Popups/IngredientPopup.xml',
        'static/src/xml/Popups/IngredientsPopupLine.xml',
        'static/src/xml/Popups/Wallet/PaymentWalletPopup.xml',
        'static/src/xml/Popups/Wallet/WalletPopup.xml',
        'static/src/xml/Popups/loyaltyPoint/loyaltyPopup.xml',
        'static/src/xml/Popups/GiftCard/giftCardCreatePopup.xml',
        'static/src/xml/Popups/GiftCard/giftCardCreatePopupConform.xml',
        'static/src/xml/Popups/GiftCard/giftCardRedeemPopup.xml',
        'static/src/xml/Popups/GiftCard/giftCardRechargePopup.xml',
        'static/src/xml/Popups/GiftCard/giftCardExchangePopup.xml',
        'static/src/xml/Popups/GiftCard/giftCardEditExpirePopup.xml',
        'static/src/xml/Popups/PurchaseHistory/ProductHistoryPopup.xml',
        'static/src/xml/Popups/PurchaseHistory/PurchaseHistoryPopup.xml',
        'static/src/xml/Popups/GiftVoucher/giftVoucherRedeemPopup.xml',
        'static/src/xml/Popups/MoneyInOut/MoneyInOutPopup.xml',
        'static/src/xml/Popups/ProductDetail/PurchaseOrderCreate.xml',
        'static/src/xml/Popups/InternalTransfer/internalTransferPopup.xml',
        'static/src/xml/Popups/CloseSession/CloseSessionPopup.xml',
        'static/src/xml/Popups/SignaturePopup/SignaturePopup.xml',
        'static/src/xml/Popups/Reports/AuditReportPopup.xml',
        'static/src/xml/Popups/Reports/OrderSummaryPopup.xml',
        'static/src/xml/Popups/Reports/PaymentSummaryPopup.xml',
        'static/src/xml/Popups/Reports/ProductSummaryPopup.xml',
        'static/src/xml/Screens/ProductScreen/CustomControlButtons/MiddleCustomControlButton.xml',
        'static/src/xml/Screens/ProductScreen/PosProductScreen.xml',
        'static/src/xml/Screens/ProductScreen/ProductDetailScreen.xml',
        'static/src/xml/Screens/ProductScreen/WarehouseScreen.xml',
        'static/src/xml/Screens/ProductScreen/Orderline.xml',
        'static/src/xml/Screens/ProductScreen/ProductList.xml',
        'static/src/xml/Screens/ProductScreen/ProductsWidget.xml',
        'static/src/xml/Screens/ProductScreen/ActionpadWidget.xml',
        'static/src/xml/Screens/ProductScreen/ProductPurchaseHistoryButton.xml',
        'static/src/xml/Screens/ProductScreen/VerticalProductCategory.xml',
        'static/src/xml/Screens/ProductScreen/ProductsWidgetControlPanel.xml',
        'static/src/xml/Screens/ReceiptScreen/receipt.xml',
        'static/src/xml/Screens/ReceiptScreen/ReceiptScreen.xml',
        'static/src/xml/Screens/ReceiptScreen/WarehouseReceipt.xml',
        'static/src/xml/Screens/ReceiptScreen/InternalTransferReceipt.xml',
        'static/src/xml/Screens/ReceiptScreen/PurchaseHistoryReceipt.xml',
        'static/src/xml/Screens/ReceiptScreen/OrderReceipt.xml',
        'static/src/xml/Screens/ReceiptScreen/OrderSummaryReceipt.xml',
        'static/src/xml/Screens/ReceiptScreen/PaymentSummaryReceipt.xml',
        'static/src/xml/Screens/ReceiptScreen/ProductSummaryReceipt.xml',
        'static/src/xml/Screens/ClientListScreen/ReferenceClientLine.xml',
        'static/src/xml/Screens/ClientListScreen/ReferenceClientListScreen.xml',
        'static/src/xml/Screens/GiftCardScreen/GiftCardScreen.xml',
        'static/src/xml/Screens/GiftCardScreen/GiftCardLine.xml',
        'static/src/xml/Screens/GiftCardScreen/giftCardCreateScreen.xml',
        'static/src/xml/Screens/GiftVoucherScreen/GiftVoucherLine.xml',
        'static/src/xml/Screens/GiftVoucherScreen/GiftVoucherScreen.xml',
        'static/src/xml/Screens/PaymentScreen/PaymentScreen.xml',
        'static/src/xml/Screens/LoginScreen/LoginScreen.xml',
        'static/src/xml/Screens/OrderReturnScreen/OrderReturnScreen.xml',
        'static/src/xml/Screens/OrderReturnScreen/OrderReturnProductList.xml',
        'static/src/xml/Screens/CashControlScreen/CashControlScreen.xml',
        'static/src/xml/Screens/CashControlScreen/CashControlScreenInput.xml',
        'static/src/xml/Screens/CashControlScreen/StaticInputLines.xml',
        'static/src/xml/Screens/CloseCashControlScreen/CloseCashControlScreen.xml',
        'static/src/xml/Screens/CloseCashControlScreen/CloseCashControlScreenInput.xml',
        'static/src/xml/Screens/ReceiptScreen/MoneyInOutReceipt.xml',
        'static/src/xml/Screens/OrderManagementScreen/ControlButtons/ReturnOrderControlButton.xml',
        'static/src/xml/Chrome.xml',
        'static/src/xml/CustomerDisplayWidgets/RightWidget.xml',
        'static/src/xml/CustomerDisplayWidgets/LeftWidget.xml',
        'static/src/xml/CustomerDisplayWidgets/CustomerOrderline.xml',
        'static/src/xml/CustomerDisplayWidgets/VideoSlider.xml',
        'static/src/xml/CustomerDisplayWidgets/Ratings.xml',
        'static/src/xml/CustomerDisplayWidgets/PaymentDetail.xml',
        'static/src/xml/CustomerDisplayWidgets/PaymentLines.xml',
        'static/src/xml/CustomerDisplayWidgets/Slider/Slider.xml',
        'static/src/xml/CustomerDisplayWidgets/Slider/SliderContent.xml',
        'static/src/xml/CustomerDisplayWidgets/Slider/Slide.xml',
        'static/src/xml/CustomerDisplayWidgets/Slider/Arrow.xml',
        'static/src/xml/Popups/CustomerScreenPopup/CustomerCreatePopup.xml',
        'static/src/xml/Popups/CustomerScreenPopup/CustomerFeedbackPopup.xml',
        'static/src/xml/Popups/OrderNote/ProductNotePopup.xml',
        'static/src/xml/Screens/ProductScreen/AlternateProductScreen.xml',
        'static/src/xml/Screens/ProductScreen/AlternateProductLine.xml',
        'static/src/xml/Screens/ProductScreen/CrossSellingProductScreen.xml',
        'static/src/xml/Screens/ProductScreen/CrossSellingProductScreenLine.xml',
        'static/src/xml/Screens/ClientListScreen/CustomerScreen.xml',
        'static/src/xml/Screens/RefillMedicineScreen/RefillMedicineScreen.xml',
        'static/src/xml/Screens/RefillMedicineScreen/RefillMedicineScreenLine.xml',
        'static/src/xml/Popups/RefillMedicine/CreateRefillMedicinePopup.xml',
        'static/src/xml/Screens/ProductScreen/RefillProductDetailScreen.xml',
        'static/src/xml/Screens/RefillMedicineScreen/RefillMedicineOrderScreen.xml',
        'static/src/xml/Popups/DeliveryCharge/DeliveryChargePopup.xml',
        'static/src/xml/Popups/OrderReturn/SelectedSerialNumberPopup.xml',
        'static/src/xml/Screens/MaterialMonitorScreen/MateriaItem.xml',
        'static/src/xml/Screens/MaterialMonitorScreen/MaterialList.xml',
        'static/src/xml/Screens/MaterialMonitorScreen/MaterialMonitorControlPanel.xml',
        'static/src/xml/Screens/MaterialMonitorScreen/MaterialMonitordetail.xml',
        'static/src/xml/Screens/MaterialMonitorScreen/MaterialMonitorScreen.xml',
        'static/src/xml/expiry_dashboard/dashboard.xml',
    ],
    "installable": True,
    'auto_install': False
}
