from odoo import fields, models


ALLOWANCE_REASON_CODES = [
    ('41', "Bonus for works ahead of schedule"),
    ('42', "Other bonus"),
    ('60', "Manufacturer’s consumer discount"),
    ('62', "Due to military status"),
    ('63', "Due to work accident"),
    ('64', "Special agreement"),
    ('65', "Production error discount"),
    ('66', "New outlet discount"),
    ('67', "Sample discount"),
    ('68', "End-of-range discount"),
    ('70', "Incoterm discount"),
    ('71', "Point of sales threshold allowance"),
    ('88', "Material surcharge/deduction"),
    ('95', "Discount"),
    ('100', "Special rebate"),
    ('102', "Fixed long term"),
    ('103', "Temporary"),
    ('104', "Standard"),
    ('105', "Yearly turnover"),
]

CHARGE_REASON_CODES = [
    ('AA', 'Advertising'),
    ('AAA', 'Telecommunication'),
    ('AAC', 'Technical modification'),
    ('AAD', 'Job-order production'),
    ('AAE', 'Outlays'),
    ('AAF', 'Off-premises'),
    ('AAH', 'Additional processing'),
    ('AAI', 'Attesting'),
    ('AAS', 'Acceptance'),
    ('AAT', 'Rush delivery'),
    ('AAV', 'Special construction'),
    ('AAY', 'Airport facilities'),
    ('AAZ', 'Concession'),
    ('ABA', 'Compulsory storage'),
    ('ABB', 'Fuel removal'),
    ('ABC', 'Into plane'),
    ('ABD', 'Overtime'),
    ('ABF', 'Tooling'),
    ('ABK', 'Miscellaneous'),
    ('ABL', 'Additional packaging'),
    ('ABN', 'Dunnage'),
    ('ABR', 'Containerisation'),
    ('ABS', 'Carton packing'),
    ('ABT', 'Hessian wrapped'),
    ('ABU', 'Polyethylene wrap packing'),
    ('ACF', 'Miscellaneous treatment'),
    ('ACG', 'Enamelling treatment'),
    ('ACH', 'Heat treatment'),
    ('ACI', 'Plating treatment'),
    ('ACJ', 'Painting'),
    ('ACK', 'Polishing'),
    ('ACL', 'Priming'),
    ('ACM', 'Preservation treatment'),
    ('ACS', 'Fitting'),
    ('ADC', 'Consolidation'),
    ('ADE', 'Bill of lading'),
    ('ADJ', 'Airbag'),
    ('ADK', 'Transfer'),
    ('ADL', 'Slipsheet'),
    ('ADM', 'Binding'),
    ('ADN', 'Repair or replacement of broken returnable package'),
    ('ADO', 'Efficient logistics'),
    ('ADP', 'Merchandising'),
    ('ADQ', 'Product mix'),
    ('ADR', 'Other services'),
    ('ADT', 'Pick-up'),
    ('ADW', 'Chronic illness'),
    ('ADY', 'New product introduction'),
    ('ADZ', 'Direct delivery'),
    ('AEA', 'Diversion'),
    ('AEB', 'Disconnect'),
    ('AEC', 'Distribution'),
    ('AED', 'Handling of hazardous cargo'),
    ('AEF', 'Rents and leases'),
    ('AEH', 'Location differential'),
    ('AEI', 'Aircraft refueling'),
    ('AEJ', 'Fuel shipped into storage'),
    ('AEK', 'Cash on delivery'),
    ('AEL', 'Small order processing service'),
    ('AEM', 'Clerical or administrative services'),
    ('AEN', 'Guarantee'),
    ('AEO', 'Collection and recycling'),
    ('AEP', 'Copyright fee collection'),
    ('AES', 'Veterinary inspection service'),
    ('AET', 'Pensioner service'),
    ('AEU', 'Medicine free pass holder'),
    ('AEV', 'Environmental protection service'),
    ('AEW', 'Environmental clean-up service'),
    ('AEX', 'National cheque processing service outside account area'),
    ('AEY', 'National payment service outside account area'),
    ('AEZ', 'National payment service within account area'),
    ('AJ', 'Adjustments'),
    ('AU', 'Authentication'),
    ('CA', 'Cataloguing'),
    ('CAB', 'Cartage'),
    ('CAD', 'Certification'),
    ('CAE', 'Certificate of conformance'),
    ('CAF', 'Certificate of origin'),
    ('CAI', 'Cutting'),
    ('CAJ', 'Consular service'),
    ('CAK', 'Customer collection'),
    ('CAL', 'Payroll payment service'),
    ('CAM', 'Cash transportation'),
    ('CAN', 'Home banking service'),
    ('CAO', 'Bilateral agreement service'),
    ('CAP', 'Insurance brokerage service'),
    ('CAQ', 'Cheque generation'),
    ('CAR', 'Preferential merchandising location'),
    ('CAS', 'Crane'),
    ('CAT', 'Special colour service'),
    ('CAU', 'Sorting'),
    ('CAV', 'Battery collection and recycling'),
    ('CAW', 'Product take back fee'),
    ('CAX', 'Quality control released'),
    ('CAY', 'Quality control held'),
    ('CAZ', 'Quality control embargo'),
    ('CD', 'Car loading'),
    ('CG', 'Cleaning'),
    ('CS', 'Cigarette stamping'),
    ('CT', 'Count and recount'),
    ('DAB', 'Layout/design'),
    ('DAC', 'Assortment allowance'),
    ('DAD', 'Driver assigned unloading'),
    ('DAF', 'Debtor bound'),
    ('DAG', 'Dealer allowance'),
    ('DAH', 'Allowance transferable to the consumer'),
    ('DAI', 'Growth of business'),
    ('DAJ', 'Introduction allowance'),
    ('DAK', 'Multi-buy promotion'),
    ('DAL', 'Partnership'),
    ('DAM', 'Return handling'),
    ('DAN', 'Minimum order not fulfilled charge'),
    ('DAO', 'Point of sales threshold allowance'),
    ('DAP', 'Wholesaling discount'),
    ('DAQ', 'Documentary credits transfer commission'),
    ('DL', 'Delivery'),
    ('EG', 'Engraving'),
    ('EP', 'Expediting'),
    ('ER', 'Exchange rate guarantee'),
    ('FAA', 'Fabrication'),
    ('FAB', 'Freight equalization'),
    ('FAC', 'Freight extraordinary handling'),
    ('FC', 'Freight service'),
    ('FH', 'Filling/handling'),
    ('FI', 'Financing'),
    ('GAA', 'Grinding'),
    ('HAA', 'Hose'),
    ('HD', 'Handling'),
    ('HH', 'Hoisting and hauling'),
    ('IAA', 'Installation'),
    ('IAB', 'Installation and warranty'),
    ('ID', 'Inside delivery'),
    ('IF', 'Inspection'),
    ('IR', 'Installation and training'),
    ('IS', 'Invoicing'),
    ('KO', 'Koshering'),
    ('L1', 'Carrier count'),
    ('LA', 'Labelling'),
    ('LAA', 'Labour'),
    ('LAB', 'Repair and return'),
    ('LF', 'Legalisation'),
    ('MAE', 'Mounting'),
    ('MI', 'Mail invoice'),
    ('ML', 'Mail invoice to each location'),
    ('NAA', 'Non-returnable containers'),
    ('OA', 'Outside cable connectors'),
    ('PA', 'Invoice with shipment'),
    ('PAA', 'Phosphatizing (steel treatment)'),
    ('PC', 'Packing'),
    ('PL', 'Palletizing'),
    ('PRV', 'Price variation'),
    ('RAB', 'Repacking'),
    ('RAC', 'Repair'),
    ('RAD', 'Returnable container'),
    ('RAF', 'Restocking'),
    ('RE', 'Re-delivery'),
    ('RF', 'Refurbishing'),
    ('RH', 'Rail wagon hire'),
    ('RV', 'Loading'),
    ('SA', 'Salvaging'),
    ('SAA', 'Shipping and handling'),
    ('SAD', 'Special packaging'),
    ('SAE', 'Stamping'),
    ('SAI', 'Consignee unload'),
    ('SG', 'Shrink-wrap'),
    ('SH', 'Special handling'),
    ('SM', 'Special finish'),
    ('SU', 'Set-up'),
    ('TAB', 'Tank renting'),
    ('TAC', 'Testing'),
    ('TT', 'Transportation - third party billing'),
    ('TV', 'Transportation by vendor'),
    ('V1', 'Drop yard'),
    ('V2', 'Drop dock'),
    ('WH', 'Warehousing'),
    ('XAA', 'Combine all same day shipment'),
    ('YY', 'Split pick-up'),
    ('ZZZ', 'Mutually defined'),
]


class AccountTax(models.Model):
    _inherit = 'account.tax'

    ubl_cii_allowance_charge_reason = fields.Char(string="Allowance Charge Reason")
    ubl_cii_allowance_reason_code = fields.Selection(
        string="Allowance Reason Code",
        selection=[(k, f'{k} - {v}') for k, v in ALLOWANCE_REASON_CODES],
    )

    ubl_cii_charge_reason_code = fields.Selection(
        string="Charge Reason Code",
        selection=[(k, f'{k} - {v}') for k, v in CHARGE_REASON_CODES],
    )
