from odoo import api, fields, models


ALLOWANCE_REASON_CODES = [
    ('41', "Bonus for works ahead of schedule"),
    ('42', "Other bonus"),
    ('60', "Manufacturer’s consumer discount"),
    ('62', "Due to military status"),
    ('63', "Due to work accident"),
    ('64', "Special agreement"),
    ('65', "Production error discount"),
    ('66', "New outlet discount"),
    ('67', "Sample discount"),
    ('68', "End-of-range discount"),
    ('70', "Incoterm discount"),
    ('71', "Point of sales threshold allowance"),
    ('88', "Material surcharge/deduction"),
    ('95', "Discount"),
    ('100', "Special rebate"),
    ('102', "Fixed long term"),
    ('103', "Temporary"),
    ('104', "Standard"),
    ('105', "Yearly turnover"),
]

CHARGE_REASON_CODES = [
    ('AA', 'Advertising'),
    ('AAA', 'Telecommunication'),
    ('AAC', 'Technical modification'),
    ('AAD', 'Job-order production'),
    ('AAE', 'Outlays'),
    ('AAF', 'Off-premises'),
    ('AAH', 'Additional processing'),
    ('AAI', 'Attesting'),
    ('AAS', 'Acceptance'),
    ('AAT', 'Rush delivery'),
    ('AAV', 'Special construction'),
    ('AAY', 'Airport facilities'),
    ('AAZ', 'Concession'),
    ('ABA', 'Compulsory storage'),
    ('ABB', 'Fuel removal'),
    ('ABC', 'Into plane'),
    ('ABD', 'Overtime'),
    ('ABF', 'Tooling'),
    ('ABK', 'Miscellaneous'),
    ('ABL', 'Additional packaging'),
    ('ABN', 'Dunnage'),
    ('ABR', 'Containerisation'),
    ('ABS', 'Carton packing'),
    ('ABT', 'Hessian wrapped'),
    ('ABU', 'Polyethylene wrap packing'),
    ('ACF', 'Miscellaneous treatment'),
    ('ACG', 'Enamelling treatment'),
    ('ACH', 'Heat treatment'),
    ('ACI', 'Plating treatment'),
    ('ACJ', 'Painting'),
    ('ACK', 'Polishing'),
    ('ACL', 'Priming'),
    ('ACM', 'Preservation treatment'),
    ('ACS', 'Fitting'),
    ('ADC', 'Consolidation'),
    ('ADE', 'Bill of lading'),
    ('ADJ', 'Airbag'),
    ('ADK', 'Transfer'),
    ('ADL', 'Slipsheet'),
    ('ADM', 'Binding'),
    ('ADN', 'Repair or replacement of broken returnable package'),
    ('ADO', 'Efficient logistics'),
    ('ADP', 'Merchandising'),
    ('ADQ', 'Product mix'),
    ('ADR', 'Other services'),
    ('ADT', 'Pick-up'),
    ('ADW', 'Chronic illness'),
    ('ADY', 'New product introduction'),
    ('ADZ', 'Direct delivery'),
    ('AEA', 'Diversion'),
    ('AEB', 'Disconnect'),
    ('AEC', 'Distribution'),
    ('AED', 'Handling of hazardous cargo'),
    ('AEF', 'Rents and leases'),
    ('AEH', 'Location differential'),
    ('AEI', 'Aircraft refueling'),
    ('AEJ', 'Fuel shipped into storage'),
    ('AEK', 'Cash on delivery'),
    ('AEL', 'Small order processing service'),
    ('AEM', 'Clerical or administrative services'),
    ('AEN', 'Guarantee'),
    ('AEO', 'Collection and recycling'),
    ('AEP', 'Copyright fee collection'),
    ('AES', 'Veterinary inspection service'),
    ('AET', 'Pensioner service'),
    ('AEU', 'Medicine free pass holder'),
    ('AEV', 'Environmental protection service'),
    ('AEW', 'Environmental clean-up service'),
    ('AEX', 'National cheque processing service outside account area'),
    ('AEY', 'National payment service outside account area'),
    ('AEZ', 'National payment service within account area'),
    ('AJ', 'Adjustments'),
    ('AU', 'Authentication'),
    ('CA', 'Cataloguing'),
    ('CAB', 'Cartage'),
    ('CAD', 'Certification'),
    ('CAE', 'Certificate of conformance'),
    ('CAF', 'Certificate of origin'),
    ('CAI', 'Cutting'),
    ('CAJ', 'Consular service'),
    ('CAK', 'Customer collection'),
    ('CAL', 'Payroll payment service'),
    ('CAM', 'Cash transportation'),
    ('CAN', 'Home banking service'),
    ('CAO', 'Bilateral agreement service'),
    ('CAP', 'Insurance brokerage service'),
    ('CAQ', 'Cheque generation'),
    ('CAR', 'Preferential merchandising location'),
    ('CAS', 'Crane'),
    ('CAT', 'Special colour service'),
    ('CAU', 'Sorting'),
    ('CAV', 'Battery collection and recycling'),
    ('CAW', 'Product take back fee'),
    ('CAX', 'Quality control released'),
    ('CAY', 'Quality control held'),
    ('CAZ', 'Quality control embargo'),
    ('CD', 'Car loading'),
    ('CG', 'Cleaning'),
    ('CS', 'Cigarette stamping'),
    ('CT', 'Count and recount'),
    ('DAB', 'Layout/design'),
    ('DAC', 'Assortment allowance'),
    ('DAD', 'Driver assigned unloading'),
    ('DAF', 'Debtor bound'),
    ('DAG', 'Dealer allowance'),
    ('DAH', 'Allowance transferable to the consumer'),
    ('DAI', 'Growth of business'),
    ('DAJ', 'Introduction allowance'),
    ('DAK', 'Multi-buy promotion'),
    ('DAL', 'Partnership'),
    ('DAM', 'Return handling'),
    ('DAN', 'Minimum order not fulfilled charge'),
    ('DAO', 'Point of sales threshold allowance'),
    ('DAP', 'Wholesaling discount'),
    ('DAQ', 'Documentary credits transfer commission'),
    ('DL', 'Delivery'),
    ('EG', 'Engraving'),
    ('EP', 'Expediting'),
    ('ER', 'Exchange rate guarantee'),
    ('FAA', 'Fabrication'),
    ('FAB', 'Freight equalization'),
    ('FAC', 'Freight extraordinary handling'),
    ('FC', 'Freight service'),
    ('FH', 'Filling/handling'),
    ('FI', 'Financing'),
    ('GAA', 'Grinding'),
    ('HAA', 'Hose'),
    ('HD', 'Handling'),
    ('HH', 'Hoisting and hauling'),
    ('IAA', 'Installation'),
    ('IAB', 'Installation and warranty'),
    ('ID', 'Inside delivery'),
    ('IF', 'Inspection'),
    ('IR', 'Installation and training'),
    ('IS', 'Invoicing'),
    ('KO', 'Koshering'),
    ('L1', 'Carrier count'),
    ('LA', 'Labelling'),
    ('LAA', 'Labour'),
    ('LAB', 'Repair and return'),
    ('LF', 'Legalisation'),
    ('MAE', 'Mounting'),
    ('MI', 'Mail invoice'),
    ('ML', 'Mail invoice to each location'),
    ('NAA', 'Non-returnable containers'),
    ('OA', 'Outside cable connectors'),
    ('PA', 'Invoice with shipment'),
    ('PAA', 'Phosphatizing (steel treatment)'),
    ('PC', 'Packing'),
    ('PL', 'Palletizing'),
    ('PRV', 'Price variation'),
    ('RAB', 'Repacking'),
    ('RAC', 'Repair'),
    ('RAD', 'Returnable container'),
    ('RAF', 'Restocking'),
    ('RE', 'Re-delivery'),
    ('RF', 'Refurbishing'),
    ('RH', 'Rail wagon hire'),
    ('RV', 'Loading'),
    ('SA', 'Salvaging'),
    ('SAA', 'Shipping and handling'),
    ('SAD', 'Special packaging'),
    ('SAE', 'Stamping'),
    ('SAI', 'Consignee unload'),
    ('SG', 'Shrink-wrap'),
    ('SH', 'Special handling'),
    ('SM', 'Special finish'),
    ('SU', 'Set-up'),
    ('TAB', 'Tank renting'),
    ('TAC', 'Testing'),
    ('TT', 'Transportation - third party billing'),
    ('TV', 'Transportation by vendor'),
    ('V1', 'Drop yard'),
    ('V2', 'Drop dock'),
    ('WH', 'Warehousing'),
    ('XAA', 'Combine all same day shipment'),
    ('YY', 'Split pick-up'),
    ('ZZZ', 'Mutually defined'),
]


class AccountTax(models.Model):
    _inherit = 'account.tax'

    ubl_cii_tax_category_code = fields.Selection(
        help="The VAT category code used for electronic invoicing purposes.",
        string="Tax Category Code",
        compute='_compute_ubl_cii_tax_category_code',
        readonly=False,
        store=True,
        selection=[
            ('AE', 'AE - Vat Reverse Charge'),
            ('E', 'E - Exempt from Tax'),
            ('S', 'S - Standard rate'),
            ('Z', 'Z - Zero rated goods'),
            ('G', 'G - Free export item, VAT not charged'),
            ('O', 'O - Services outside scope of tax'),
            ('K', 'K - VAT exempt for EEA intra-community supply of goods and services'),
            ('L', 'L - Canary Islands general indirect tax'),
            ('M', 'M - Tax for production, services and importation in Ceuta and Melilla'),
            ('B', 'B - Transferred (VAT), In Italy')
        ]
    )

    ubl_cii_allowance_charge_reason = fields.Char(string="Allowance Charge Reason")
    ubl_cii_allowance_reason_code = fields.Selection(
        string="Allowance Reason Code",
        selection=[(k, f'{k} - {v}') for k, v in ALLOWANCE_REASON_CODES],
    )
    ubl_cii_charge_reason_code = fields.Selection(
        string="Charge Reason Code",
        selection=[(k, f'{k} - {v}') for k, v in CHARGE_REASON_CODES],
    )

    ubl_cii_tax_exemption_reason_code = fields.Selection(
        help="The reason why the amount is exempted from VAT or why no VAT is being charged, used for electronic invoicing purposes.",
        string="Tax Exemption Reason Code",
        selection=[
            ('VATEX-EU-AE', 'VATEX-EU-AE - Reverse charge'),
            ('VATEX-EU-D', 'VATEX-EU-D - Intra-Community acquisition from second hand means of transport'),
            ('VATEX-EU-F', 'VATEX-EU-F - Intra-Community acquisition of second hand goods'),
            ('VATEX-EU-G', 'VATEX-EU-G - Export outside the EU'),
            ('VATEX-EU-I', 'VATEX-EU-I - Intra-Community acquisition of works of art'),
            ('VATEX-EU-IC', 'VATEX-EU-IC - Intra-Community supply'),
            ('VATEX-EU-O', 'VATEX-EU-O - Not subject to VAT'),
            ('VATEX-EU-79-C', 'VATEX-EU-79-C - Exempt based on article 79, point c of Council Directive 2006/112/EC'),
            ('VATEX-EU-132', 'VATEX-EU-132 - Exempt based on article 132 of Council Directive 2006/112/EC'),
            ('VATEX-EU-132-1A', 'VATEX-EU-132-1A - Exempt based on article 132, section 1 (a) of Council Directive 2006/112/EC'),
            ('VATEX-EU-132-1B', 'VATEX-EU-132-1B - Exempt based on article 132, section 1 (b) of Council Directive 2006/112/EC'),
            ('VATEX-EU-132-1C', 'VATEX-EU-132-1C - Exempt based on article 132, section 1 (c) of Council Directive 2006/112/EC'),
            ('VATEX-EU-132-1D', 'VATEX-EU-132-1D - Exempt based on article 132, section 1 (d) of Council Directive 2006/112/EC'),
            ('VATEX-EU-132-1E', 'VATEX-EU-132-1E - Exempt based on article 132, section 1 (e) of Council Directive 2006/112/EC'),
            ('VATEX-EU-132-1F', 'VATEX-EU-132-1F - Exempt based on article 132, section 1 (f) of Council Directive 2006/112/EC'),
            ('VATEX-EU-132-1G', 'VATEX-EU-132-1G - Exempt based on article 132, section 1 (g) of Council Directive 2006/112/EC'),
            ('VATEX-EU-132-1H', 'VATEX-EU-132-1H - Exempt based on article 132, section 1 (h) of Council Directive 2006/112/EC'),
            ('VATEX-EU-132-1I', 'VATEX-EU-132-1I - Exempt based on article 132, section 1 (i) of Council Directive 2006/112/EC'),
            ('VATEX-EU-132-1J', 'VATEX-EU-132-1J - Exempt based on article 132, section 1 (j) of Council Directive 2006/112/EC'),
            ('VATEX-EU-132-1K', 'VATEX-EU-132-1K - Exempt based on article 132, section 1 (k) of Council Directive 2006/112/EC'),
            ('VATEX-EU-132-1L', 'VATEX-EU-132-1L - Exempt based on article 132, section 1 (l) of Council Directive 2006/112/EC'),
            ('VATEX-EU-132-1M', 'VATEX-EU-132-1M - Exempt based on article 132, section 1 (m) of Council Directive 2006/112/EC'),
            ('VATEX-EU-132-1N', 'VATEX-EU-132-1N - Exempt based on article 132, section 1 (n) of Council Directive 2006/112/EC'),
            ('VATEX-EU-132-1O', 'VATEX-EU-132-1O - Exempt based on article 132, section 1 (o) of Council Directive 2006/112/EC'),
            ('VATEX-EU-132-1P', 'VATEX-EU-132-1P - Exempt based on article 132, section 1 (p) of Council Directive 2006/112/EC'),
            ('VATEX-EU-132-1Q', 'VATEX-EU-132-1Q - Exempt based on article 132, section 1 (q) of Council Directive 2006/112/EC'),
            ('VATEX-EU-143', 'VATEX-EU-143 - Exempt based on article 143 of Council Directive 2006/112/EC'),
            ('VATEX-EU-143-1A', 'VATEX-EU-143-1A - Exempt based on article 143, section 1 (a) of Council Directive 2006/112/EC'),
            ('VATEX-EU-143-1B', 'VATEX-EU-143-1B - Exempt based on article 143, section 1 (b) of Council Directive 2006/112/EC'),
            ('VATEX-EU-143-1C', 'VATEX-EU-143-1C - Exempt based on article 143, section 1 (c) of Council Directive 2006/112/EC'),
            ('VATEX-EU-143-1D', 'VATEX-EU-143-1D - Exempt based on article 143, section 1 (d) of Council Directive 2006/112/EC'),
            ('VATEX-EU-143-1E', 'VATEX-EU-143-1E - Exempt based on article 143, section 1 (e) of Council Directive 2006/112/EC'),
            ('VATEX-EU-143-1F', 'VATEX-EU-143-1F - Exempt based on article 143, section 1 (f) of Council Directive 2006/112/EC'),
            ('VATEX-EU-143-1FA', 'VATEX-EU-143-1FA - Exempt based on article 143, section 1 (fa) of Council Directive 2006/112/EC'),
            ('VATEX-EU-143-1G', 'VATEX-EU-143-1G - Exempt based on article 143, section 1 (g) of Council Directive 2006/112/EC'),
            ('VATEX-EU-143-1H', 'VATEX-EU-143-1H - Exempt based on article 143, section 1 (h) of Council Directive 2006/112/EC'),
            ('VATEX-EU-143-1I', 'VATEX-EU-143-1I - Exempt based on article 143, section 1 (i) of Council Directive 2006/112/EC'),
            ('VATEX-EU-143-1J', 'VATEX-EU-143-1J - Exempt based on article 143, section 1 (j) of Council Directive 2006/112/EC'),
            ('VATEX-EU-143-1K', 'VATEX-EU-143-1K - Exempt based on article 143, section 1 (k) of Council Directive 2006/112/EC'),
            ('VATEX-EU-143-1L', 'VATEX-EU-143-1L - Exempt based on article 143, section 1 (l) of Council Directive 2006/112/EC'),
            ('VATEX-EU-148', 'VATEX-EU-148 - Exempt based on article 148 of Council Directive 2006/112/EC'),
            ('VATEX-EU-148-A', 'VATEX-EU-148-A - Exempt based on article 148, section (a) of Council Directive 2006/112/EC'),
            ('VATEX-EU-148-B', 'VATEX-EU-148-B - Exempt based on article 148, section (b) of Council Directive 2006/112/EC'),
            ('VATEX-EU-148-C', 'VATEX-EU-148-C - Exempt based on article 148, section (c) of Council Directive 2006/112/EC'),
            ('VATEX-EU-148-D', 'VATEX-EU-148-D - Exempt based on article 148, section (d) of Council Directive 2006/112/EC'),
            ('VATEX-EU-148-E', 'VATEX-EU-148-E - Exempt based on article 148, section (e) of Council Directive 2006/112/EC'),
            ('VATEX-EU-148-F', 'VATEX-EU-148-F - Exempt based on article 148, section (f) of Council Directive 2006/112/EC'),
            ('VATEX-EU-148-G', 'VATEX-EU-148-G - Exempt based on article 148, section (g) of Council Directive 2006/112/EC'),
            ('VATEX-EU-151', 'VATEX-EU-151 - Exempt based on article 151 of Council Directive 2006/112/EC'),
            ('VATEX-EU-151-1A', 'VATEX-EU-151-1A - Exempt based on article 151, section 1 (a) of Council Directive 2006/112/EC'),
            ('VATEX-EU-151-1AA', 'VATEX-EU-151-1AA - Exempt based on article 151, section 1 (aa) of Council Directive 2006/112/EC'),
            ('VATEX-EU-151-1B', 'VATEX-EU-151-1B - Exempt based on article 151, section 1 (b) of Council Directive 2006/112/EC'),
            ('VATEX-EU-151-1C', 'VATEX-EU-151-1C - Exempt based on article 151, section 1 (c) of Council Directive 2006/112/EC'),
            ('VATEX-EU-151-1D', 'VATEX-EU-151-1D - Exempt based on article 151, section 1 (d) of Council Directive 2006/112/EC'),
            ('VATEX-EU-151-1E', 'VATEX-EU-151-1E - Exempt based on article 151, section 1 (e) of Council Directive 2006/112/EC'),
            ('VATEX-EU-309', 'VATEX-EU-309 - Exempt based on article 309 of Council Directive 2006/112/EC'),
            ('VATEX-EU-J', 'VATEX-EU-J - Intra-Community acquisition of collectors items and antiques'),
            ('VATEX-FR-FRANCHISE', 'VATEX-FR-FRANCHISE - France domestic VAT franchise in base'),
            ('VATEX-FR-CNWVAT', 'VATEX-FR-CNWVAT - France domestic Credit Notes without VAT, due to supplier forfeit of VAT for discount'),
        ]
    )
    ubl_cii_requires_exemption_reason = fields.Boolean(compute='_compute_ubl_cii_requires_exemption_reason')

    @api.depends('ubl_cii_tax_category_code')
    def _compute_ubl_cii_requires_exemption_reason(self):
        for tax in self:
            tax.ubl_cii_requires_exemption_reason = tax.ubl_cii_tax_category_code in ['AE', 'E', 'G', 'O', 'K']

    @api.onchange('ubl_cii_requires_exemption_reason')
    def _onchange_ubl_cii_tax_category_code(self):
        for tax in self:
            if not tax.ubl_cii_requires_exemption_reason:
                tax.ubl_cii_tax_exemption_reason_code = False

    @api.depends('amount_type')
    def _compute_ubl_cii_tax_category_code(self):
        for tax in self:
            if tax.amount_type == 'percent' and not tax.ubl_cii_tax_category_code:
                code = 'S'
            elif tax.amount_type == 'fixed' and not tax.ubl_cii_tax_category_code:
                code = 'E'
            else:
                code = tax.ubl_cii_tax_category_code

            tax.ubl_cii_tax_category_code = code
