# Part of Odoo. See LICENSE file for full copyright and licensing details.

from . import test_access_rights
from . import test_automatic_leave_dates
from . import test_allocation_access_rights
from . import test_holidays_flow
from . import test_hr_holidays_cancel_leave
from . import test_hr_holidays_tour
from . import test_hr_leave_type
from . import test_accrual_allocations
from . import test_change_department
from . import test_leave_requests
from . import test_out_of_office
from . import test_company_leave
from . import test_res_partner
from . import test_mandatory_days
from . import test_global_leaves
from . import test_uninstall
from . import test_holidays_calendar
from . import test_holidays_mail
from . import test_negative
from . import test_past_accruals
from . import test_allocations
from . import test_multicompany
from . import test_timeoff_event
from . import test_working_hours
from . import test_dashboard
from . import test_expiring_leaves
from . import test_hr_departure_wizard
from . import test_time_off_card_tour
from . import test_hr_leave_type_tour
from . import test_time_off_graph_view_tour
from . import test_leave_type_data
from . import test_multi_contract
from . import test_time_off_allocation_tour
from . import test_flexible_resource_calendar
