{
    'name': 'Discuss Tracking',
    'category': 'Productivity/Discuss',
    'depends': ['mail'],
    'summary': 'Technical tracking of discussion and message-related data',
    'description': """
This module extends the mail.message model to enable
technical tracking of discussion-related data.

It captures and stores tracked values generated by
messages and system change operations.
The tracked information can be used for auditing,
debugging, and analysis purposes.

This is especially useful for:
- Investigating technical issues
- Supporting accounting or business process audits
""",
    'author': 'Odoo S.A.',
    'license': 'LGPL-3',
    'data': [
        'views/mail_message_views.xml',
        'views/mail_tracking_value_views.xml',
        'views/mail_menus.xml',
        'security/ir.model.access.csv',
    ],
}
