.TH openerp_serverrc 5

.SH NAME
openerp_serverrc \- configuration file for OpenERP

.SH SYNOPSIS
[options]
.br
$option\ =\ " someValue "
.br
 ...

.SH DESCRIPTION
A setup file consists of a section, lead by a "[options]" header,
.br
and followed by "option_name = value" entries, with continuations and such in
.br
the style of RFC 822.

.SH OPTIONS
.TP
.IR verbose
Enable the debugging mode
.br
(default False)
.TP
.IR pidfile
The file where the server pid will be stored
.br
(default False)
.TP
.IR logfile
The file where the server log will be stored
.br
(default False)
.TP
.IR interface
The IP address on which the server will bind.
.br
If empty, it will bind on all interfaces (default empty)
.TP
.IR port
The TCP port on which the server will listen.
.br
(default 8069)
.TP
.IR debug_mode
Enable debug mode
.br
(default False)
.TP
.IR secure
Launch server over https instead of http.
.br
(default False)
.TP
.IR smtp_server
Specify the SMTP server for sending email.
.br
(default localhost)
.TP
.IR smtp_user
Specify the SMTP user for sending email.
.br
(default False)
.TP
.IR smtp_password
Specify the SMTP password for sending email.
.br
(default False)
.TP
.IR db_name
Specify the database name.
.TP
.IR db_user
Specify the database user name.
.br
(default None)
.TP
.IR db_password
Specify the database password for db_user.
.br
(default None)
.TP
.IR pg_path
Specify the PostgreSQL executable path.
.br
(default None)
.TP
.IR db_host
Specify the database host.
.br
(default localhost)
.TP
.IR db_port
Specify the database port.
.br
(default None)
.TP
.IR price_accuracy
Specify the price accuracy.
.br

.SH AUTHORS

OpenERP is a product of \fBTiny.be\fR (\fIhttp://www.tiny.be\fR)

.SH SEE ALSO
openerp-server(1)
.br
\fIhttp://www.openerp.com\fR : Open ERP official website
.br
\fIhttp://doc.openerp.com\fR : Open ERP documentation
