from collections import defaultdict

from odoo import _, api, fields, models
from odoo.exceptions import UserError, ValidationError
from odoo.fields import Domain

from ..tools import debug_log as dbg
from odoo.addons.stock.const import ADVANCED_STOCK_OPTION_GROUPS


class ProductTemplate(models.Model):
    _inherit = "product.template"
    _check_company_auto = True

    is_storable = fields.Boolean(
        string="Track Inventory",
        compute="_compute_is_storable",
        precompute=True,
        default=False,
        store=True,
        readonly=False,
        tracking=True,
        help="A storable product is a product for which you manage stock.",
    )
    responsible_id = fields.Many2one(
        comodel_name="res.users",
        default=lambda self: self._default_responsible_id(),
        company_dependent=True,
        check_company=True,
        help="This user will be responsible of the next activities related to logistic operations for this product.",
    )
    property_stock_production = fields.Many2one(
        comodel_name="stock.location",
        string="Production Location",
        company_dependent=True,
        domain="[('usage', '=', 'production'), ('company_id', 'in', [False, allowed_company_ids[0]])]",
        check_company=True,
        help="This stock location will be used, instead of the default one, as the source location for stock moves generated by manufacturing orders.",
    )
    property_stock_inventory = fields.Many2one(
        comodel_name="stock.location",
        string="Inventory Location",
        company_dependent=True,
        domain="[('usage', '=', 'inventory'), ('company_id', 'in', [False, allowed_company_ids[0]])]",
        check_company=True,
        help="This stock location will be used, instead of the default one, as the source location for stock moves generated when you do an inventory.",
    )
    sale_delay = fields.Integer(
        string="Customer Lead Time",
        default=0,
        help="Delivery lead time, in days. It's the number of days, promised to the customer, between the confirmation of the sales order and the delivery.",
    )
    tracking = fields.Selection(
        selection=[
            ("serial", "By Unique Serial Number"),
            ("lot", "By Lots"),
            ("none", "By Quantity"),
        ],
        compute="_compute_tracking",
        precompute=True,
        default="none",
        store=True,
        readonly=False,
        required=True,
        help="Ensure the traceability of a storable product in your warehouse.",
    )
    lot_sequence_id = fields.Many2one(
        comodel_name="ir.sequence",
        string="Serial/Lot Numbers Sequence",
        default=lambda self: self._default_lot_sequence_id(),
        help="Technical Field: The Ir.Sequence record that is used to generate serial/lot numbers for this product",
    )
    lot_name_format = fields.Char(
        string="Lot/Serial Name Format",
        help="Shape this product's lot/serial names take, in the same "
        "placeholder form as a sequence prefix (%(year)s, %(month)s, %(day)s, "
        "...) plus %(ref)s for the manufacturer's lot number.\n"
        "Set it when the name has to carry information — a manufacturing date, "
        "a supplier's own lot number — rather than just be unique. Left empty, "
        "names are drawn from the sequence as usual.",
    )
    serial_prefix_format = fields.Char(
        string="Custom Lot/Serial",
        compute="_compute_serial_prefix_format",
        inverse="_inverse_serial_prefix_format",
        help="""
            If multiple products share the same prefix, they will share the same sequence, otherwise the sequence will be dedicated to the product.

            * Legend (for prefix):
            - Current Year with Century: %(year)s
            - Current Year without Century: %(y)s
            - Month: %(month)s
            - Day: %(day)s
            - Day of the Year: %(doy)s
            - Week of the Year: %(woy)s
            - Day of the Week (0:Monday): %(weekday)s
            - Hour 00->24: %(h24)s
            - Hour 00->12: %(h12)s
            - Minute: %(min)s
            - Second: %(sec)s
        """,
    )
    next_serial = fields.Char(compute="_compute_next_serial")
    description_picking = fields.Text(
        string="Description on Picking",
        translate=True,
    )
    description_pickingout = fields.Text(
        string="Description on Delivery Orders",
        translate=True,
    )
    description_pickingin = fields.Text(
        string="Description on Receptions",
        translate=True,
    )
    qty_available = fields.Float(
        string="Quantity On Hand",
        min_display_digits="Product Unit",
        compute="_compute_quantities",
        inverse="_inverse_qty_available",
        search="_search_qty_available",
        compute_sudo=False,
        help="Sum of the quantity on hand of every variant of this product, "
        "scoped by the location or warehouse selected in the search view.",
    )
    qty_available_virtual = fields.Float(
        string="Forecasted Quantity",
        min_display_digits="Product Unit",
        compute="_compute_quantities",
        search="_search_qty_available_virtual",
        compute_sudo=False,
        help="Sum of the forecasted quantity (on hand - outgoing + incoming) of "
        "every variant of this product.",
    )
    qty_incoming = fields.Float(
        string="Incoming",
        min_display_digits="Product Unit",
        compute="_compute_quantities",
        search="_search_qty_incoming",
        compute_sudo=False,
        help="Sum of the planned incoming quantity of every variant of this product.",
    )
    qty_outgoing = fields.Float(
        string="Outgoing",
        min_display_digits="Product Unit",
        compute="_compute_quantities",
        search="_search_qty_outgoing",
        compute_sudo=False,
        help="Sum of the planned outgoing quantity of every variant of this product.",
    )
    location_id = fields.Many2one(
        comodel_name="stock.location",
        store=False,
    )
    warehouse_id = fields.Many2one(
        comodel_name="stock.warehouse",
        store=False,
    )
    has_available_route_ids = fields.Boolean(
        string="Routes can be selected on this product",
        compute="_compute_has_available_route_ids",
        default=lambda self: self._default_has_available_route_ids(),
    )
    route_ids = fields.Many2many(
        comodel_name="stock.route",
        relation="stock_route_product",
        column1="product_id",
        column2="route_id",
        string="Routes",
        depends_context=["company", "allowed_companies"],
        domain=[("product_selectable", "=", True)],
        help="Depending on the modules installed, this will allow you to define the route of the product: whether it will be bought, manufactured, replenished on order, etc.",
    )
    count_moves_in = fields.Integer(
        compute="_compute_count_moves",
        compute_sudo=False,
        help="Number of incoming stock moves in the past 12 months",
    )
    count_moves_out = fields.Integer(
        compute="_compute_count_moves",
        compute_sudo=False,
        help="Number of outgoing stock moves in the past 12 months",
    )
    count_reordering_rules = fields.Integer(
        string="Reordering Rules",
        compute="_compute_reordering_rules",
        compute_sudo=False,
    )
    reordering_qty_min = fields.Float(
        compute="_compute_reordering_rules",
        compute_sudo=False,
    )
    reordering_qty_max = fields.Float(
        compute="_compute_reordering_rules",
        compute_sudo=False,
    )
    route_from_categ_ids = fields.Many2many(
        related="categ_id.total_route_ids",
        string="Category Routes",
        related_sudo=False,
    )
    show_on_hand_qty_status_button = fields.Boolean(
        compute="_compute_show_qty_status_button"
    )
    show_forecasted_qty_status_button = fields.Boolean(
        compute="_compute_show_qty_status_button"
    )
    show_qty_update_button = fields.Boolean(compute="_compute_show_qty_update_button")
    count_lot_ids = fields.Integer(
        string="Lots Count",
        compute="_compute_count_lot_ids",
    )

    @api.constrains("type", "is_storable")
    def _check_is_storable(self):
        for template in self:
            if template.type != "consu" and template.is_storable:
                raise ValidationError(
                    _(
                        "%(product)s is not a goods product, so it cannot track"
                        " inventory. Set its type to Goods, or leave Track"
                        " Inventory off.",
                        product=template.display_name,
                    ),
                )

    @api.constrains("is_storable", "tracking")
    def _check_tracking(self):
        for template in self:
            if not template.is_storable and template.tracking != "none":
                raise ValidationError(
                    _(
                        "%(product)s does not track inventory, so it cannot be"
                        " tracked by lot or serial number. Enable Track Inventory"
                        " first.",
                        product=template.display_name,
                    ),
                )

    @api.model_create_multi
    def create(self, vals_list):
        product_tmpl_quantities = [vals.get("qty_available") or 0 for vals in vals_list]
        if any("qty_available" in vals for vals in vals_list):
            vals_list = [
                {key: val for key, val in vals.items() if key != "qty_available"}
                for vals in vals_list
            ]

        product_templates = super().create(vals_list)

        if any(product_tmpl_quantities):
            template_ids = []
            quantities = []
            for product_tmpl, qty in zip(
                product_templates, product_tmpl_quantities, strict=True
            ):
                if not qty:
                    continue
                template_ids.append(product_tmpl.id)
                quantities.append(qty)
            dbg.pipeline.debug(
                "product.template.create: initial qty_available on %s", template_ids
            )
            self.browse(template_ids)._update_qty_available(quantities)
        return product_templates

    @dbg.timed
    def write(self, vals):
        if vals.get("company_id"):
            products_changing_company = self.filtered(
                lambda product: product.company_id.id != vals["company_id"],
            )
            dbg.logic.debug(
                "product.template.write: company change on %s, checking stock data",
                dbg.rec(products_changing_company),
            )
            if products_changing_company:
                variant_ids = products_changing_company.with_context(
                    active_test=False
                ).product_variant_ids.ids
                other_company = Domain(
                    "company_id", "not in", [vals["company_id"], False]
                )
                move = (
                    self.env["stock.move"]
                    .sudo()
                    .search(
                        Domain("product_id", "in", variant_ids) & other_company,
                        order=None,
                        limit=1,
                    )
                )
                if move:
                    raise UserError(
                        _(
                            "This product's company cannot be changed as long as there are stock moves of it belonging to another company.",
                        ),
                    )

                quant = (
                    self.env["stock.quant"]
                    .sudo()
                    .search(
                        Domain("product_id", "in", variant_ids)
                        & other_company
                        & Domain("quantity", "!=", 0),
                        order=None,
                        limit=1,
                    )
                )
                if quant:
                    raise UserError(
                        _(
                            "This product's company cannot be changed as long as there are quantities of it belonging to another company.",
                        ),
                    )

        was_storable = {tmpl.id: tmpl.is_storable for tmpl in self}

        res = super().write(vals)

        templates_to_reset = self.filtered(
            lambda tmpl: not was_storable[tmpl.id] and tmpl.is_storable
        )
        templates_losing_storage = self.filtered(
            lambda tmpl: was_storable[tmpl.id] and not tmpl.is_storable
        )
        Quant = self.env["stock.quant"].sudo()
        if templates_to_reset or templates_losing_storage:
            dbg.lifecycle.debug(
                "product.template.write: became storable %s, lost storage %s",
                dbg.rec(templates_to_reset),
                dbg.rec(templates_losing_storage),
            )
        if templates_to_reset:
            products = templates_to_reset.with_context(
                active_test=False
            ).product_variant_ids
            Quant._sync_reserved_quantities(products=products)
            templates_to_reset._apply_zero_inventory()
        if templates_losing_storage:
            Quant._sync_reserved_quantities(
                products=templates_losing_storage.with_context(
                    active_test=False
                ).product_variant_ids,
            )
        return res

    def copy(self, default=None):
        new_products = super().copy(default=default)
        Capacity = self.env["stock.storage.category.capacity"]
        storage_category_capacity_vals = []
        for old_template, new_template in zip(self, new_products, strict=True):
            new_variant_id_by_value = {
                variant.product_template_attribute_value_ids.product_attribute_value_id: variant.id
                for variant in new_template.with_context(
                    active_test=False
                ).product_variant_ids
            }
            capacities = old_template.with_context(
                active_test=False
            ).product_variant_ids.storage_category_capacity_ids
            for capacity, vals in zip(capacities, capacities.copy_data(), strict=True):
                attribute_value = capacity.product_id.product_template_attribute_value_ids.product_attribute_value_id
                new_variant_id = new_variant_id_by_value.get(attribute_value)
                if not new_variant_id or vals is None:
                    continue
                storage_category_capacity_vals.append(
                    {**vals, "product_id": new_variant_id},
                )
        Capacity.create(storage_category_capacity_vals)
        return new_products

    def _default_responsible_id(self):
        return False if self.env.user._is_superuser() else self.env.uid

    @api.model
    def _default_lot_sequence_id(self):
        return (
            self.env.ref("stock.sequence_production_lots", raise_if_not_found=False)
            or self.env["ir.sequence"]
        )

    @api.depends_context("allowed_company_ids", "uid")
    @api.depends(
        "product_variant_ids.orderpoint_ids.product_min_qty",
        "product_variant_ids.orderpoint_ids.product_max_qty",
    )
    def _compute_reordering_rules(self):
        res = defaultdict(lambda: {"count": 0, "min": 0.0, "max": 0.0})
        for product, count, product_min_qty, product_max_qty in self.env[
            "stock.warehouse.orderpoint"
        ]._read_group(
            [("product_id.product_tmpl_id", "in", self.ids)],
            ["product_id"],
            ["__count", "product_min_qty:sum", "product_max_qty:sum"],
        ):
            agg = res[product.product_tmpl_id.id]
            agg["count"] += count
            agg["min"] += product_min_qty
            agg["max"] += product_max_qty
        for template in self:
            agg = res[template._origin.id]
            template.count_reordering_rules = agg["count"]
            template.reordering_qty_min = agg["min"]
            template.reordering_qty_max = agg["max"]

    @api.depends("type")
    def _compute_is_storable(self):
        self.filtered(lambda t: t.type != "consu" and t.is_storable).is_storable = False

    @api.depends("is_storable")
    def _compute_tracking(self):
        self.filtered(
            lambda t: not t.is_storable and t.tracking != "none",
        ).tracking = "none"

    @api.depends("lot_sequence_id.prefix")
    def _compute_serial_prefix_format(self):
        for template in self:
            template.serial_prefix_format = template.lot_sequence_id.prefix or ""

    @api.depends(
        "lot_sequence_id.prefix",
        "lot_sequence_id.number_next_actual",
        "lot_sequence_id.padding",
        "lot_sequence_id.suffix",
    )
    def _compute_next_serial(self):
        default_sequence = self._default_lot_sequence_id()
        for template in self:
            sequence = template.lot_sequence_id or default_sequence
            template.next_serial = sequence.preview_next() if sequence else ""

    @api.depends("is_storable", "product_variant_ids")
    def _compute_show_qty_status_button(self):
        for template in self:
            template.show_on_hand_qty_status_button = template.is_storable
            template.show_forecasted_qty_status_button = bool(
                template.is_storable and template.product_variant_id
            )

    @api.depends_context("uid", "allowed_company_ids")
    def _compute_has_available_route_ids(self):
        self.has_available_route_ids = self._default_has_available_route_ids()

    @api.depends_context("uid")
    @api.depends("product_variant_count", "tracking")
    def _compute_show_qty_update_button(self):
        for product in self:
            product.show_qty_update_button = (
                product._is_product_quants_open_required()
                or product.product_variant_count > 1
            )

    @api.depends_context("allowed_company_ids", "uid")
    @api.depends(
        "product_variant_ids.count_moves_in",
        "product_variant_ids.count_moves_out",
    )
    def _compute_count_moves(self):
        fnames = ("count_moves_in", "count_moves_out")
        for template in self:
            variants = template.product_variant_ids._origin
            for fname in fnames:
                template[fname] = sum(variants.mapped(fname))

    @api.depends_context("allowed_company_ids", "uid")
    @api.depends("product_variant_ids.count_lot_ids")
    def _compute_count_lot_ids(self):
        for template in self:
            template.count_lot_ids = sum(
                template.product_variant_ids._origin.mapped("count_lot_ids"),
            )

    def _inverse_serial_prefix_format(self):
        default_sequence = self._default_lot_sequence_id()
        valid_sequences = self.env["ir.sequence"].search(
            [
                ("code", "=", "stock.lot.serial"),
                ("prefix", "in", self.mapped("serial_prefix_format")),
                ("company_id", "in", [*self.company_id.ids, False]),
            ],
        )
        sequences_by_key = {
            (seq.prefix, seq.company_id.id): seq for seq in valid_sequences
        }
        for template in self:
            if not template.serial_prefix_format:
                template.lot_sequence_id = default_sequence
                continue
            key = (template.serial_prefix_format, template.company_id.id)
            sequence = sequences_by_key.get(key)
            if not sequence:
                sequence = self.env["ir.sequence"].create(
                    {
                        "name": f"{template.name} Serial Sequence",
                        "code": "stock.lot.serial",
                        "prefix": template.serial_prefix_format,
                        "padding": default_sequence.padding or 7,
                        "company_id": template.company_id.id,
                    },
                )
                sequences_by_key[key] = sequence
            template.lot_sequence_id = sequence

    @api.onchange("tracking")
    def _onchange_tracking(self):
        return self.product_variant_ids._onchange_tracking()

    @api.onchange("type")
    def _onchange_type(self):
        res = super()._onchange_type()
        variant_ids = self.with_context(active_test=False).product_variant_ids.ids
        if (
            self.ids
            and variant_ids
            and self.env["stock.move.line"]
            .sudo()
            .search_count(
                [
                    ("product_id", "in", variant_ids),
                    ("state", "!=", "cancel"),
                ],
                limit=1,
            )
        ):
            res["warning"] = {
                "title": _("Warning!"),
                "message": _(
                    "This product has been used in at least one inventory movement. "
                    "It is not advised to change the Product Type since it can lead to inconsistencies. "
                    "A better solution could be to archive the product and create a new one instead."
                ),
            }
        return res

    def action_view_quants(self):
        variants = self.with_context(active_test=False).product_variant_ids
        return variants.filtered(
            lambda p: p.active or p.qty_available != 0,
        ).action_view_quants()

    def action_view_related_putaway_rules(self):
        self.check_singleton()
        domain = [
            "|",
            ("product_id.product_tmpl_id", "=", self.id),
            ("category_id", "=", self.categ_id.id),
        ]
        return self._prepare_action_view_putaway_rules(domain)

    def action_view_storage_category_capacity(self):
        self.check_singleton()
        return self.product_variant_ids.action_view_storage_category_capacity()

    def action_view_orderpoints(self):
        return self.product_variant_ids.action_view_orderpoints()

    def action_view_stock_move_lines(self):
        self.check_singleton()
        action = self.env["ir.actions.actions"]._get_action_dict_by_xml_id(
            "stock.stock_move_line_action",
        )
        action["domain"] = [("product_id.product_tmpl_id", "=", self.id)]
        return action

    def action_view_product_lot(self):
        self.check_singleton()
        action = self.env["ir.actions.actions"]._get_action_dict_by_xml_id(
            "stock.action_stock_lot_form_2",
        )
        action["domain"] = [
            ("product_id.product_tmpl_id", "=", self.id),
            *self.env["stock.lot"]._get_domain_accessible_location(),
        ]
        action["context"] = {
            "default_product_tmpl_id": self.id,
            "search_default_group_by_location": True,
        }
        if self.product_variant_count == 1:
            action["context"].update(
                {
                    "default_product_id": self.product_variant_id.id,
                },
            )
        return action

    def _get_diagram_products(self):
        Product = self.env["product.product"]
        if self.env.context.get("default_product_id"):
            products = Product.browse(self.env.context["default_product_id"])
            if products:
                return products
        if self.env.context.get("default_product_tmpl_id"):
            products = self.browse(
                self.env.context["default_product_tmpl_id"]
            ).product_variant_ids
            if products:
                return products
        templates = self or self.browse(self.env.context.get("active_id") or [])
        return templates.product_variant_ids

    def action_view_routes_diagram(self):
        products = self._get_diagram_products()
        if (
            not self.env.user.has_group("stock.group_stock_multi_warehouses")
            and len(products) == 1
        ):
            company = products.company_id or self.env.company
            warehouse = self.env["stock.warehouse"].search(
                [("company_id", "=", company.id)],
                limit=1,
            )
            if not warehouse:
                self.env["stock.warehouse"].with_company(
                    company
                )._raise_missing_warehouse()
            return self.env.ref("stock.action_report_stock_rule").report_action(
                None,
                data={
                    "product_id": products.id,
                    "warehouse_ids": warehouse.ids,
                },
                config=False,
            )
        action = self.env["ir.actions.actions"]._get_action_dict_by_xml_id(
            "stock.action_stock_rules_report",
        )
        action["context"] = {
            "default_product_id": products[:1].id,
            "default_product_tmpl_id": products[:1].product_tmpl_id.id,
        }
        return action

    def action_product_tmpl_forecast_report(self):
        self.check_singleton()
        if not self.env.user._get_default_warehouse_id():
            self.env["stock.warehouse"]._raise_missing_warehouse()
        return self.env["ir.actions.actions"]._get_action_dict_by_xml_id(
            "stock.stock_forecasted_product_template_action",
        )

    @api.model
    def _default_has_available_route_ids(self):
        return bool(
            self.env["stock.route"].search_count(
                [("product_selectable", "=", True)],
                limit=1,
            )
        )

    @dbg.timed
    def _apply_zero_inventory(self):
        move_line_domain = Domain(
            [
                (
                    "product_id",
                    "in",
                    self.with_context(active_test=False).product_variant_ids.ids,
                ),
                ("state", "=", "done"),
                "|",
                ("location_usage", "in", ("internal", "transit")),
                ("location_dest_usage", "in", ("internal", "transit")),
            ],
        )
        move_lines_to_match = self.env["stock.move.line"].search_fetch(
            move_line_domain,
            [
                "product_id",
                "location_id",
                "location_dest_id",
                "quantity_product_uom",
            ],
        )
        inventory_ledger = defaultdict(float)
        for move_line in move_lines_to_match:
            if move_line.location_usage in ("internal", "transit"):
                inventory_ledger[move_line.product_id, move_line.location_id] -= (
                    move_line.quantity_product_uom
                )
            if move_line.location_dest_usage in ("internal", "transit"):
                inventory_ledger[move_line.product_id, move_line.location_dest_id] += (
                    move_line.quantity_product_uom
                )
        dbg.logic.debug(
            "_apply_zero_inventory on %s: %d done lines -> %d (product, location) balances",
            dbg.rec(self),
            len(move_lines_to_match),
            len(inventory_ledger),
        )
        quants_to_reset = self.env["stock.quant"].create(
            [
                {
                    "product_id": product.id,
                    "location_id": location.id,
                    "quantity": quantity,
                    "inventory_quantity": 0.0,
                }
                for (product, location), quantity in inventory_ledger.items()
                if not product.uom_id.is_zero(quantity)
            ],
        )
        quants_to_reset._apply_inventory()

    @api.model
    def _prepare_action_view_putaway_rules(self, domain):
        return {
            "name": _("Putaway Rules"),
            "type": "ir.actions.act_window",
            "res_model": "stock.putaway.rule",
            "view_mode": "list",
            "domain": domain,
        }

    @api.model
    def _has_advanced_stock_option(self):
        return any(
            self.env.user.has_group(group) for group in ADVANCED_STOCK_OPTION_GROUPS
        )

    def _is_product_quants_open_required(self):
        self.check_singleton()
        return self._has_advanced_stock_option() or self.tracking != "none"
