#!/bin/sh
#
# Called by "git push" after it has checked the remote status, but before
# anything has been pushed.  If this script exits with a non-zero status
# nothing will be pushed. Read the /.git/hooks/pre-push.sample file for more
# information

set -eu
for script in $0.d/*
do
	if [ -x $script ]
	then
		echo -n [..] $script
		$script
		echo '\r[ok]'
	fi
done
