{
    "name": "Inventory",
    "version": "1.18",
    "category": "Supply Chain/Inventory",
    "sequence": 25,
    "summary": "Manage your stock and logistics activities",
    "author": "Odoo S.A.",
    "website": "https://www.odoo.com/app/inventory",
    "license": "LGPL-3",
    "depends": [
        "product",
        "barcodes_gs1_nomenclature",
        "digest",
    ],
    "data": [
        "security/stock_security.xml",
        "security/ir.model.access.csv",
        "data/digest_data.xml",
        "data/mail_templates.xml",
        "data/default_barcode_patterns.xml",
        "data/stock_data.xml",
        "data/stock_sequence_data.xml",
        "data/stock_picking_batch_data.xml",
        "data/stock_traceability_report_data.xml",
        "reports/report_stock_quantity.xml",
        "reports/report_stock_reception.xml",
        "reports/stock_report_views.xml",
        "reports/report_package_barcode.xml",
        "reports/report_lot_barcode.xml",
        "reports/report_location_barcode.xml",
        "reports/report_stockpicking_operations.xml",
        "reports/report_deliveryslip.xml",
        "reports/report_stockinventory.xml",
        "reports/report_stock_rule.xml",
        "reports/package_templates.xml",
        "reports/packaging_barcode.xml",
        "reports/picking_templates.xml",
        "reports/product_templates.xml",
        "reports/report_return_slip.xml",
        "data/mail_template_data.xml",
        "wizards/stock_picking_return_views.xml",
        "wizards/stock_inventory_conflict.xml",
        "wizards/stock_backorder_confirmation_views.xml",
        "wizards/stock_quantity_history.xml",
        "wizards/stock_request_count.xml",
        "wizards/stock_replenishment_info.xml",
        "wizards/stock_rules_report_views.xml",
        "wizards/stock_warn_insufficient_qty_views.xml",
        "wizards/product_replenish_views.xml",
        "wizards/product_label_layout_views.xml",
        "wizards/stock_orderpoint_snooze_views.xml",
        "wizards/stock_package_destination_views.xml",
        "wizards/stock_inventory_adjustment_name.xml",
        "wizards/stock_inventory_warning.xml",
        "wizards/stock_label_type.xml",
        "wizards/stock_lot_label_layout.xml",
        "wizards/stock_quant_relocate.xml",
        "wizards/stock_put_in_pack_views.xml",
        "views/res_partner_views.xml",
        "views/product_strategy_views.xml",
        "views/stock_lot_views.xml",
        "views/stock_scrap_views.xml",
        "views/stock_quant_views.xml",
        "views/stock_warehouse_views.xml",
        "views/stock_move_line_views.xml",
        "views/stock_move_views.xml",
        "views/stock_picking_views.xml",
        "views/stock_picking_type_views.xml",
        "views/product_category_views.xml",
        "views/product_views.xml",
        "views/stock_location_views.xml",
        "views/stock_route_views.xml",
        "views/stock_orderpoint_views.xml",
        "views/stock_storage_category_views.xml",
        "wizards/res_config_settings_views.xml",
        "views/report_stock_traceability.xml",
        "views/stock_template.xml",
        "views/stock_rule_views.xml",
        "views/stock_package_history_views.xml",
        "views/stock_package_type_view.xml",
        "views/stock_package_views.xml",
        "views/stock_forecasted.xml",
        "views/stock_reference_views.xml",
        "views/uom_uom_views.xml",
        "views/stock_menus.xml",
    ],
    "demo": [
        "demo/stock_demo_pre.xml",
        "demo/stock_demo.xml",
        "demo/stock_demo2.xml",
        "demo/stock_orderpoint_demo.xml",
        "demo/stock_storage_category_demo.xml",
    ],
    "assets": {
        "web.report_assets_common": [
            "stock/static/src/scss/report_stock_reception.scss",
            "stock/static/src/scss/report_stock_rule.scss",
            "stock/static/src/scss/report_stockpicking_operations.scss",
        ],
        "web.assets_backend": [
            "stock/static/src/**/*.js",
            "stock/static/src/**/*.xml",
            "stock/static/src/**/*.scss",
        ],
        "web.assets_frontend": [
            "stock/static/src/scss/stock_traceability_report.scss",
        ],
        "web.assets_tests": [
            "stock/static/tests/tours/*.js",
        ],
        "web.assets_unit_tests": [
            "stock/static/tests/*.test.js",
        ],
    },
    "application": True,
    "pre_init_hook": "pre_init_hook",
    "uninstall_hook": "uninstall_hook",
}
