{
    "name": "Google Map Locator",
    "description": """The Google Map Locator app provides the address input functionality to the users by integrating Google Maps through Google API Integration.""",
    "summary": "The Google Map Locator app enables users to easily input addresses by integrating Google Maps through the Google API. It allows users to enter an address, automatically display the location on a map, and auto-populate related address fields such as country, state, and city. This integration streamlines address input and improves accuracy by using real-time data from Google Maps, ensuring a smooth and efficient user experience.",
    "category": "Services",
    "version": "16.0.1.0.0",
    "author": "Zehntech Technologies Inc.",
    "company": "Zehntech Technologies Inc.",
    "maintainer": "Zehntech Technologies Inc.",
    "contributor": "Zehntech Technologies Inc.",
    "website": "https://www.zehntech.com/",
    "support": "odoo-support@zehntech.com",
    "depends": ['base', 'contacts', 'crm'],
    "data":[
        'views/res_partner_views.xml',    
        'views/res_config_settings_views.xml',
        'views/crm_lead_views.xml',
        'security/ir.model.access.csv',
    ],
    'assets': {
        'web.assets_backend': [
            'zt_google_map_locater/static/src/js/map_widget.js',  
            'zt_google_map_locater/static/src/xml/zt_google_map_locater_widget.xml',   
            'zt_google_map_locater/static/src/css/style.css',     
        ],
    },
    'images': ['static/description/banner.png'],
    "license": "OPL-1",
    "installable": True,
    "application": True,
    "auto_install": False,
    "price": 00.00,
    "currency": "USD",
}