response = {'address': {'city': '',
             'country': 'US',
             'line1': '250 executiv prk blvd',
             'line2': '3400',
             'postalCode': '94134',
             'region': '',
             'textCase': 'Mixed'},
 'coordinates': {'latitude': 37.71116, 'longitude': -122.391717},
 'resolutionQuality': 'Intersection',
 'taxAuthorities': [{'avalaraId': '275',
                     'jurisdictionName': 'SAN FRANCISCO',
                     'jurisdictionType': 'County',
                     'signatureCode': 'AIUQ'},
                    {'avalaraId': '5000531',
                     'jurisdictionName': 'CALIFORNIA',
                     'jurisdictionType': 'State',
                     'signatureCode': 'AGAM'},
                    {'avalaraId': '2001061430',
                     'jurisdictionName': 'SAN FRANCISCO COUNTY DISTRICT TAX SP',
                     'jurisdictionType': 'Special',
                     'signatureCode': 'EMBE'},
                    {'avalaraId': '2001061792',
                     'jurisdictionName': 'SAN FRANCISCO CO LOCAL TAX SL',
                     'jurisdictionType': 'Special',
                     'signatureCode': 'EMTV'},
                    {'avalaraId': '2001067344',
                     'jurisdictionName': 'MOSCONE EXPANSION DISTRICT ZONE 2',
                     'jurisdictionType': 'Special',
                     'signatureCode': 'MHZT'},
                    {'avalaraId': '2001077295',
                     'jurisdictionName': 'SAN FRANCISCO TOURISM IMPROVEMENT '
                                         'DISTRICT (ZONE 2)',
                     'jurisdictionType': 'Special',
                     'signatureCode': 'NQPB'}],
 'validatedAddresses': [{'addressType': 'HighRiseOrBusinessComplex',
                         'city': 'San Francisco',
                         'country': 'US',
                         'latitude': 37.71116,
                         'line1': '250 Executive Park Blvd Ste 3400',
                         'line2': '',
                         'line3': '',
                         'longitude': -122.391717,
                         'postalCode': '94134-3349',
                         'region': 'CA'}]}
