from . import product_template
from . import delivery_carrier
from . import res_company
from . import res_partner
from . import sale_order
from . import shopee_attribute
from . import shopee_category
from . import shopee_item
from . import shopee_shop
from . import shopee_order
from . import shopee_history_api
from . import shopee_product
from . import shopee_product_image