from . import hr_payroll_structure_type
from . import hr_job
from . import hr_version
from . import hr_contract_type
from . import hr_employee
from . import hr_employee_convergence
from . import mixin_hr
from . import hr_department
from . import hr_departure_reason
from . import hr_work_location
from . import mail_activity_plan
from . import mail_activity_plan_template
from . import mail_alias
from . import discuss_channel
from . import models
from . import res_config_settings
from . import res_users
from . import res_company
from . import res_partner
from . import res_partner_tag
from . import res_partner_bank
from . import resource
from . import resource_assignment
from . import resource_calendar
from . import resource_schedule_exception
from . import ir_ui_menu
from . import hr_employee_change_request
