# Part of Odoo. See LICENSE file for full copyright and licensing details.

from . import hr_payroll_structure_type
from . import hr_job
from . import hr_version
from . import hr_contract_type
from . import hr_employee
from . import hr_employee_category
from . import hr_employee_public
from . import hr_department
from . import hr_departure_reason
from . import hr_work_location
from . import mail_activity_plan
from . import mail_activity_plan_template
from . import mail_alias
from . import discuss_channel
from . import models
from . import res_config_settings
from . import res_users
from . import res_company
from . import res_partner
from . import res_partner_bank
from . import resource
from . import resource_calendar
from . import resource_calendar_leaves
from . import ir_ui_menu
from . import hr_resume_line
from . import hr_resume_line_type
from . import hr_skill
from . import hr_individual_skill_mixin
from . import hr_employee_skill
from . import hr_skill_level
from . import hr_skill_type
