Mexico, 2016-05-02
Soluciones Globales en software S.A de S.V.  Agrees to the terms of the Odoo Corporate Contributor License Agreement v1.0.
I declare that I am authorized and able to make this agreement and sign this
declaration.
Signed,
Mauricio Nuñez mauricio.nunez@sgsoft.com.mx https://github.com/mnunez-sgsoft
List of contributors:
mnunez-sgsoft mauricio.nunez@cedetecgrupomc.com https://github.com/mnunez-sgsoft 
juanhernandez9 jose.hernandez@cedetecgrupomc.com https://github.com/juanhernandez94
ragnheidur arturo.palmero@cedetecgrupomc.com https://github.com/ragnheidur
CesarCedetec cesar.olvera@cedetecgrupomc.com https://github.com/CesarCedetec
MauricioPiCa mauricio.pina@grupoceti.com https://github.com/MauricioPiCa
