version: '3.9'

services:
  odoo:
    image: ghcr.io/mohammedj-sadiq/kswco-odoo:latest
    env_file:
      - .env.prod
    network_mode: host
    volumes:
      - /home/odoo/.local/share/Odoo:/var/lib/odoo
    restart: unless-stopped
