[options]
addons_path = /home/odoo/Odoo/odoo/custom_addons,/home/odoo/Odoo/odoo/custom_addons/cybrosys,/home/odoo/Odoo/odoo/custom_addons/Odoo Mates - hr_payroll_community-19.0.1.0.1,/home/odoo/Odoo/odoo/custom_addons/KSW
admin_passwd = $pbkdf2-sha512$600000$wTjHeA/hXKu1FgKA0Pp/Tw$cd6nUhNGDtuS5r7uKvj6byXthLW.GC5aHr.qnSouenCPzwietFgrYZNB/t8Qk7dHOFgXUxBfnnSBsbVLRRcFGA
data_dir = /home/odoo/.local/share/Odoo-dev
db_host =
db_maxconn = 64
db_name = odoo_dev
db_password =
db_port = None
db_user =
dbfilter = ^odoo_dev$
http_port = 8070
gevent_port = 8073
list_db = False
log_level = debug
max_cron_threads = 1
proxy_mode = False
workers = 0
