#!/usr/bin/env python3
import warnings
import sys
import os.path
import textwrap

# Deprecation warnings are hidden by default
warnings.warn("\n\n  %s\n" % "\n  ".join(textwrap.wrap(textwrap.dedent("""\
    The Odoo module has been made module-executable. Executing Odoo
    via the {odoobin} script is deprecated. Make sure Odoo is installed
    in your python environment or change your current working directory
    to {path} then start Odoo as a module: {exec} -m odoo
    """.format(
        odoobin=os.path.basename(__file__),
        path=os.path.dirname(os.path.abspath(__file__)),
        exec=sys.executable
    )))),
    DeprecationWarning,
)

import odoo.__main__
