#! /usr/bin/env python2

if __name__ == '__main__':
    import sys
    if len(sys.argv) > 1 and sys.argv[1] == 'run-tests':
        sys.exit(0)
    import openerpcommand.main
    openerpcommand.main.run()
