from . import test_attendances
from . import test_calendar_sync
from . import test_hr_employee
from . import test_employee_profile_access
from . import test_channel
from . import test_self_user_access
from . import test_mail_activity_plan
from . import test_mail_features
from . import test_multi_company
from . import test_payroll_fields_access
from . import test_employee_resource_party
from . import test_resource
from . import test_ui
from . import test_scenario
from . import test_hr_department
from . import test_hr_version
from . import test_hr_contract_versions
from . import test_flexible_resource_calendar
from . import test_multiple_bank_accounts
from . import test_hr_audit_fixes
from . import test_partner_shadow_gate
from . import test_party_convergence
from . import test_private_address_access
from . import test_hr_audit_round3
from . import test_hr_audit_round4
from . import test_hr_audit_round5
from . import test_version_delegation_gate
from . import test_private_facet_identity
from . import test_party_delegation
from . import test_party_identifiers
from . import test_party_link
from . import test_party_create_path
from . import test_party_stored_mirrors
from . import test_employee_change_request
from . import test_employee_copy
from . import test_hr_department_company_on_create
from . import test_version_structure_type
