from . import account_tax
from . import pos_config
from . import pricer_store
from . import pricer_tag
from . import product_product
from . import product_supplierinfo
from . import product_template
from . import res_partner
from . import stock_move
