from . import account_edi_common
from . import account_edi_ubl
from . import account_edi_xml_cii_facturx
from . import account_edi_xml_cii_fr
from . import account_edi_xml_cii_fr_extended
from . import account_edi_xml_facturx_fr_basicwl
from . import account_edi_xml_facturx_fr_en16931
from . import account_edi_xml_facturx_fr_extended
from . import account_edi_xml_ubl_20
from . import account_edi_xml_ubl_21
from . import account_edi_xml_ubl_bis3
from . import account_edi_xml_ubl_fr
from . import account_edi_xml_ubl_fr_extended
from . import account_edi_xml_ubl_xrechnung
from . import account_edi_xml_ubl_nlcius
from . import account_edi_xml_ubl_efff
from . import account_edi_xml_ubl_a_nz
from . import account_edi_xml_ubl_sg
from . import account_move
from . import account_move_send
from . import ir_actions_report
from . import res_partner
