from odoo import api, fields, models

ALLOWANCE_REASON_CODES = [
    ('41', "41 - Bonus for works ahead of schedule"),
    ('42', "42 - Other bonus"),
    ('60', "60 - Manufacturer’s consumer discount"),
    ('62', "62 - Due to military status"),
    ('63', "63 - Due to work accident"),
    ('64', "64 - Special agreement"),
    ('65', "65 - Production error discount"),
    ('66', "66 - New outlet discount"),
    ('67', "67 - Sample discount"),
    ('68', "68 - End-of-range discount"),
    ('70', "70 - Incoterm discount"),
    ('71', "71 - Point of sales threshold allowance"),
    ('88', "88 - Material surcharge/deduction"),
    ('95', "95 - Discount"),
    ('100', "100 - Special rebate"),
    ('102', "102 - Fixed long term"),
    ('103', "103 - Temporary"),
    ('104', "104 - Standard"),
    ('105', "105 - Yearly turnover"),
]

CHARGE_REASON_CODES = [
    ('AA', "AA - Advertising"),
    ('AAA', "AAA - Telecommunication"),
    ('AAC', "AAC - Technical modification"),
    ('AAD', "AAD - Job-order production"),
    ('AAE', "AAE - Outlays"),
    ('AAF', "AAF - Off-premises"),
    ('AAH', "AAH - Additional processing"),
    ('AAI', "AAI - Attesting"),
    ('AAS', "AAS - Acceptance"),
    ('AAT', "AAT - Rush delivery"),
    ('AAV', "AAV - Special construction"),
    ('AAY', "AAY - Airport facilities"),
    ('AAZ', "AAZ - Concession"),
    ('ABA', "ABA - Compulsory storage"),
    ('ABB', "ABB - Fuel removal"),
    ('ABC', "ABC - Into plane"),
    ('ABD', "ABD - Overtime"),
    ('ABF', "ABF - Tooling"),
    ('ABK', "ABK - Miscellaneous"),
    ('ABL', "ABL - Additional packaging"),
    ('ABN', "ABN - Dunnage"),
    ('ABR', "ABR - Containerisation"),
    ('ABS', "ABS - Carton packing"),
    ('ABT', "ABT - Hessian wrapped"),
    ('ABU', "ABU - Polyethylene wrap packing"),
    ('ACF', "ACF - Miscellaneous treatment"),
    ('ACG', "ACG - Enamelling treatment"),
    ('ACH', "ACH - Heat treatment"),
    ('ACI', "ACI - Plating treatment"),
    ('ACJ', "ACJ - Painting"),
    ('ACK', "ACK - Polishing"),
    ('ACL', "ACL - Priming"),
    ('ACM', "ACM - Preservation treatment"),
    ('ACS', "ACS - Fitting"),
    ('ADC', "ADC - Consolidation"),
    ('ADE', "ADE - Bill of lading"),
    ('ADJ', "ADJ - Airbag"),
    ('ADK', "ADK - Transfer"),
    ('ADL', "ADL - Slipsheet"),
    ('ADM', "ADM - Binding"),
    ('ADN', "ADN - Repair or replacement of broken returnable package"),
    ('ADO', "ADO - Efficient logistics"),
    ('ADP', "ADP - Merchandising"),
    ('ADQ', "ADQ - Product mix"),
    ('ADR', "ADR - Other services"),
    ('ADT', "ADT - Pick-up"),
    ('ADW', "ADW - Chronic illness"),
    ('ADY', "ADY - New product introduction"),
    ('ADZ', "ADZ - Direct delivery"),
    ('AEA', "AEA - Diversion"),
    ('AEB', "AEB - Disconnect"),
    ('AEC', "AEC - Distribution"),
    ('AED', "AED - Handling of hazardous cargo"),
    ('AEF', "AEF - Rents and leases"),
    ('AEH', "AEH - Location differential"),
    ('AEI', "AEI - Aircraft refueling"),
    ('AEJ', "AEJ - Fuel shipped into storage"),
    ('AEK', "AEK - Cash on delivery"),
    ('AEL', "AEL - Small order processing service"),
    ('AEM', "AEM - Clerical or administrative services"),
    ('AEN', "AEN - Guarantee"),
    ('AEO', "AEO - Collection and recycling"),
    ('AEP', "AEP - Copyright fee collection"),
    ('AES', "AES - Veterinary inspection service"),
    ('AET', "AET - Pensioner service"),
    ('AEU', "AEU - Medicine free pass holder"),
    ('AEV', "AEV - Environmental protection service"),
    ('AEW', "AEW - Environmental clean-up service"),
    ('AEX', "AEX - National cheque processing service outside account area"),
    ('AEY', "AEY - National payment service outside account area"),
    ('AEZ', "AEZ - National payment service within account area"),
    ('AJ', "AJ - Adjustments"),
    ('AU', "AU - Authentication"),
    ('CA', "CA - Cataloguing"),
    ('CAB', "CAB - Cartage"),
    ('CAD', "CAD - Certification"),
    ('CAE', "CAE - Certificate of conformance"),
    ('CAF', "CAF - Certificate of origin"),
    ('CAI', "CAI - Cutting"),
    ('CAJ', "CAJ - Consular service"),
    ('CAK', "CAK - Customer collection"),
    ('CAL', "CAL - Payroll payment service"),
    ('CAM', "CAM - Cash transportation"),
    ('CAN', "CAN - Home banking service"),
    ('CAO', "CAO - Bilateral agreement service"),
    ('CAP', "CAP - Insurance brokerage service"),
    ('CAQ', "CAQ - Cheque generation"),
    ('CAR', "CAR - Preferential merchandising location"),
    ('CAS', "CAS - Crane"),
    ('CAT', "CAT - Special colour service"),
    ('CAU', "CAU - Sorting"),
    ('CAV', "CAV - Battery collection and recycling"),
    ('CAW', "CAW - Product take back fee"),
    ('CAX', "CAX - Quality control released"),
    ('CAY', "CAY - Quality control held"),
    ('CAZ', "CAZ - Quality control embargo"),
    ('CD', "CD - Car loading"),
    ('CG', "CG - Cleaning"),
    ('CS', "CS - Cigarette stamping"),
    ('CT', "CT - Count and recount"),
    ('DAB', "DAB - Layout/design"),
    ('DAC', "DAC - Assortment allowance"),
    ('DAD', "DAD - Driver assigned unloading"),
    ('DAF', "DAF - Debtor bound"),
    ('DAG', "DAG - Dealer allowance"),
    ('DAH', "DAH - Allowance transferable to the consumer"),
    ('DAI', "DAI - Growth of business"),
    ('DAJ', "DAJ - Introduction allowance"),
    ('DAK', "DAK - Multi-buy promotion"),
    ('DAL', "DAL - Partnership"),
    ('DAM', "DAM - Return handling"),
    ('DAN', "DAN - Minimum order not fulfilled charge"),
    ('DAO', "DAO - Point of sales threshold allowance"),
    ('DAP', "DAP - Wholesaling discount"),
    ('DAQ', "DAQ - Documentary credits transfer commission"),
    ('DL', "DL - Delivery"),
    ('EG', "EG - Engraving"),
    ('EP', "EP - Expediting"),
    ('ER', "ER - Exchange rate guarantee"),
    ('FAA', "FAA - Fabrication"),
    ('FAB', "FAB - Freight equalization"),
    ('FAC', "FAC - Freight extraordinary handling"),
    ('FC', "FC - Freight service"),
    ('FH', "FH - Filling/handling"),
    ('FI', "FI - Financing"),
    ('GAA', "GAA - Grinding"),
    ('HAA', "HAA - Hose"),
    ('HD', "HD - Handling"),
    ('HH', "HH - Hoisting and hauling"),
    ('IAA', "IAA - Installation"),
    ('IAB', "IAB - Installation and warranty"),
    ('ID', "ID - Inside delivery"),
    ('IF', "IF - Inspection"),
    ('IR', "IR - Installation and training"),
    ('IS', "IS - Invoicing"),
    ('KO', "KO - Koshering"),
    ('L1', "L1 - Carrier count"),
    ('LA', "LA - Labelling"),
    ('LAA', "LAA - Labour"),
    ('LAB', "LAB - Repair and return"),
    ('LF', "LF - Legalisation"),
    ('MAE', "MAE - Mounting"),
    ('MI', "MI - Mail invoice"),
    ('ML', "ML - Mail invoice to each location"),
    ('NAA', "NAA - Non-returnable containers"),
    ('OA', "OA - Outside cable connectors"),
    ('PA', "PA - Invoice with shipment"),
    ('PAA', "PAA - Phosphatizing (steel treatment)"),
    ('PC', "PC - Packing"),
    ('PL', "PL - Palletizing"),
    ('PRV', "PRV - Price variation"),
    ('RAB', "RAB - Repacking"),
    ('RAC', "RAC - Repair"),
    ('RAD', "RAD - Returnable container"),
    ('RAF', "RAF - Restocking"),
    ('RE', "RE - Re-delivery"),
    ('RF', "RF - Refurbishing"),
    ('RH', "RH - Rail wagon hire"),
    ('RV', "RV - Loading"),
    ('SA', "SA - Salvaging"),
    ('SAA', "SAA - Shipping and handling"),
    ('SAD', "SAD - Special packaging"),
    ('SAE', "SAE - Stamping"),
    ('SAI', "SAI - Consignee unload"),
    ('SG', "SG - Shrink-wrap"),
    ('SH', "SH - Special handling"),
    ('SM', "SM - Special finish"),
    ('SU', "SU - Set-up"),
    ('TAB', "TAB - Tank renting"),
    ('TAC', "TAC - Testing"),
    ('TT', "TT - Transportation - third party billing"),
    ('TV', "TV - Transportation by vendor"),
    ('V1', "V1 - Drop yard"),
    ('V2', "V2 - Drop dock"),
    ('WH', "WH - Warehousing"),
    ('XAA', "XAA - Combine all same day shipment"),
    ('YY', "YY - Split pick-up"),
    ('ZZZ', "ZZZ - Mutually defined"),
]


class AccountTax(models.Model):
    _inherit = 'account.tax'

    ubl_cii_type = fields.Selection(
        selection=[
            ('tax', "Tax"),
            ('allowance_charge', "Charges or Allowance"),
        ],
        default='tax',
        required=True,
    )
    ubl_cii_tax_category_code = fields.Selection(
        help="The VAT category code used for electronic invoicing purposes.",
        string="Tax Category Code",
        selection=[
            ('AE', 'AE - Vat Reverse Charge'),
            ('E', 'E - Exempt from Tax'),
            ('S', 'S - Standard rate'),
            ('Z', 'Z - Zero rated goods'),
            ('G', 'G - Free export item, VAT not charged'),
            ('O', 'O - Services outside scope of tax'),
            ('K', 'K - VAT exempt for EEA intra-community supply of goods and services'),
            ('L', 'L - Canary Islands general indirect tax'),
            ('M', 'M - Tax for production, services and importation in Ceuta and Melilla'),
            ('B', 'B - Transferred (VAT), In Italy')
        ]
    )
    ubl_cii_tax_exemption_reason = fields.Char(string="Tax Exemption Reason")
    ubl_cii_tax_exemption_reason_code = fields.Selection(
        help="The reason why the amount is exempted from VAT or why no VAT is being charged, used for electronic invoicing purposes.",
        string="Tax Exemption Reason Code",
        selection=[
            ('VATEX-EU-79-C', 'VATEX-EU-79-C - Exempt based on article 79, point c of Council Directive 2006/112/EC'),
            ('VATEX-EU-132', 'VATEX-EU-132 - Exempt based on article 132 of Council Directive 2006/112/EC'),
            ('VATEX-EU-132-1A', 'VATEX-EU-132-1A - Exempt based on article 132, section 1 (a) of Council Directive 2006/112/EC'),
            ('VATEX-EU-132-1B', 'VATEX-EU-132-1B - Exempt based on article 132, section 1 (b) of Council Directive 2006/112/EC'),
            ('VATEX-EU-132-1C', 'VATEX-EU-132-1C - Exempt based on article 132, section 1 (c) of Council Directive 2006/112/EC'),
            ('VATEX-EU-132-1D', 'VATEX-EU-132-1D - Exempt based on article 132, section 1 (d) of Council Directive 2006/112/EC'),
            ('VATEX-EU-132-1E', 'VATEX-EU-132-1E - Exempt based on article 132, section 1 (e) of Council Directive 2006/112/EC'),
            ('VATEX-EU-132-1F', 'VATEX-EU-132-1F - Exempt based on article 132, section 1 (f) of Council Directive 2006/112/EC'),
            ('VATEX-EU-132-1G', 'VATEX-EU-132-1G - Exempt based on article 132, section 1 (g) of Council Directive 2006/112/EC'),
            ('VATEX-EU-132-1H', 'VATEX-EU-132-1H - Exempt based on article 132, section 1 (h) of Council Directive 2006/112/EC'),
            ('VATEX-EU-132-1I', 'VATEX-EU-132-1I - Exempt based on article 132, section 1 (i) of Council Directive 2006/112/EC'),
            ('VATEX-EU-132-1J', 'VATEX-EU-132-1J - Exempt based on article 132, section 1 (j) of Council Directive 2006/112/EC'),
            ('VATEX-EU-132-1K', 'VATEX-EU-132-1K - Exempt based on article 132, section 1 (k) of Council Directive 2006/112/EC'),
            ('VATEX-EU-132-1L', 'VATEX-EU-132-1L - Exempt based on article 132, section 1 (l) of Council Directive 2006/112/EC'),
            ('VATEX-EU-132-1M', 'VATEX-EU-132-1M - Exempt based on article 132, section 1 (m) of Council Directive 2006/112/EC'),
            ('VATEX-EU-132-1N', 'VATEX-EU-132-1N - Exempt based on article 132, section 1 (n) of Council Directive 2006/112/EC'),
            ('VATEX-EU-132-1O', 'VATEX-EU-132-1O - Exempt based on article 132, section 1 (o) of Council Directive 2006/112/EC'),
            ('VATEX-EU-132-1P', 'VATEX-EU-132-1P - Exempt based on article 132, section 1 (p) of Council Directive 2006/112/EC'),
            ('VATEX-EU-132-1Q', 'VATEX-EU-132-1Q - Exempt based on article 132, section 1 (q) of Council Directive 2006/112/EC'),
            ('VATEX-EU-135-1', 'VATEX-EU-135-1 - Exempt based on article 135, section 1 of Council Directive 2006/112/EC'),
            ('VATEX-EU-143', 'VATEX-EU-143 - Exempt based on article 143 of Council Directive 2006/112/EC'),
            ('VATEX-EU-143-1A', 'VATEX-EU-143-1A - Exempt based on article 143, section 1 (a) of Council Directive 2006/112/EC'),
            ('VATEX-EU-143-1B', 'VATEX-EU-143-1B - Exempt based on article 143, section 1 (b) of Council Directive 2006/112/EC'),
            ('VATEX-EU-143-1C', 'VATEX-EU-143-1C - Exempt based on article 143, section 1 (c) of Council Directive 2006/112/EC'),
            ('VATEX-EU-143-1D', 'VATEX-EU-143-1D - Exempt based on article 143, section 1 (d) of Council Directive 2006/112/EC'),
            ('VATEX-EU-143-1E', 'VATEX-EU-143-1E - Exempt based on article 143, section 1 (e) of Council Directive 2006/112/EC'),
            ('VATEX-EU-143-1F', 'VATEX-EU-143-1F - Exempt based on article 143, section 1 (f) of Council Directive 2006/112/EC'),
            ('VATEX-EU-143-1FA', 'VATEX-EU-143-1FA - Exempt based on article 143, section 1 (fa) of Council Directive 2006/112/EC'),
            ('VATEX-EU-143-1G', 'VATEX-EU-143-1G - Exempt based on article 143, section 1 (g) of Council Directive 2006/112/EC'),
            ('VATEX-EU-143-1H', 'VATEX-EU-143-1H - Exempt based on article 143, section 1 (h) of Council Directive 2006/112/EC'),
            ('VATEX-EU-143-1I', 'VATEX-EU-143-1I - Exempt based on article 143, section 1 (i) of Council Directive 2006/112/EC'),
            ('VATEX-EU-143-1J', 'VATEX-EU-143-1J - Exempt based on article 143, section 1 (j) of Council Directive 2006/112/EC'),
            ('VATEX-EU-143-1K', 'VATEX-EU-143-1K - Exempt based on article 143, section 1 (k) of Council Directive 2006/112/EC'),
            ('VATEX-EU-143-1L', 'VATEX-EU-143-1L - Exempt based on article 143, section 1 (l) of Council Directive 2006/112/EC'),
            ('VATEX-EU-144', 'VATEX-EU-144 - Exempt based on article 144 of Council Directive 2006/112/EC'),
            ('VATEX-EU-146-1E', 'VATEX-EU-146-1E - Exempt based on article 146 section 1 (e) of Council Directive 2006/112/EC'),
            ('VATEX-EU-148', 'VATEX-EU-148 - Exempt based on article 148 of Council Directive 2006/112/EC'),
            ('VATEX-EU-148-A', 'VATEX-EU-148-A - Exempt based on article 148, section (a) of Council Directive 2006/112/EC'),
            ('VATEX-EU-148-B', 'VATEX-EU-148-B - Exempt based on article 148, section (b) of Council Directive 2006/112/EC'),
            ('VATEX-EU-148-C', 'VATEX-EU-148-C - Exempt based on article 148, section (c) of Council Directive 2006/112/EC'),
            ('VATEX-EU-148-D', 'VATEX-EU-148-D - Exempt based on article 148, section (d) of Council Directive 2006/112/EC'),
            ('VATEX-EU-148-E', 'VATEX-EU-148-E - Exempt based on article 148, section (e) of Council Directive 2006/112/EC'),
            ('VATEX-EU-148-F', 'VATEX-EU-148-F - Exempt based on article 148, section (f) of Council Directive 2006/112/EC'),
            ('VATEX-EU-148-G', 'VATEX-EU-148-G - Exempt based on article 148, section (g) of Council Directive 2006/112/EC'),
            ('VATEX-EU-151', 'VATEX-EU-151 - Exempt based on article 151 of Council Directive 2006/112/EC'),
            ('VATEX-EU-151-1A', 'VATEX-EU-151-1A - Exempt based on article 151, section 1 (a) of Council Directive 2006/112/EC'),
            ('VATEX-EU-151-1AA', 'VATEX-EU-151-1AA - Exempt based on article 151, section 1 (aa) of Council Directive 2006/112/EC'),
            ('VATEX-EU-151-1B', 'VATEX-EU-151-1B - Exempt based on article 151, section 1 (b) of Council Directive 2006/112/EC'),
            ('VATEX-EU-151-1C', 'VATEX-EU-151-1C - Exempt based on article 151, section 1 (c) of Council Directive 2006/112/EC'),
            ('VATEX-EU-151-1D', 'VATEX-EU-151-1D - Exempt based on article 151, section 1 (d) of Council Directive 2006/112/EC'),
            ('VATEX-EU-151-1E', 'VATEX-EU-151-1E - Exempt based on article 151, section 1 (e) of Council Directive 2006/112/EC'),
            ('VATEX-EU-153', 'VATEX-EU-153 - Exempt based on article 153 of Council Directive 2006/112/EC'),
            ('VATEX-EU-159', 'VATEX-EU-159 - Exempt based on article 159 of Council Directive 2006/112/EC'),
            ('VATEX-EU-309', 'VATEX-EU-309 - Exempt based on article 309 of Council Directive 2006/112/EC'),
            ('VATEX-EU-AE', 'VATEX-EU-AE - Reverse charge'),
            ('VATEX-EU-D', 'VATEX-EU-D - Intra-Community acquisition from second hand means of transport'),
            ('VATEX-EU-F', 'VATEX-EU-F - Intra-Community acquisition of second hand goods'),
            ('VATEX-EU-G', 'VATEX-EU-G - Export outside the EU'),
            ('VATEX-EU-I', 'VATEX-EU-I - Intra-Community acquisition of works of art'),
            ('VATEX-EU-IC', 'VATEX-EU-IC - Intra-Community supply'),
            ('VATEX-EU-O', 'VATEX-EU-O - Not subject to VAT'),
            ('VATEX-EU-J', 'VATEX-EU-J - Intra-Community acquisition of collectors items and antiques'),
            ('VATEX-FR-FRANCHISE', 'VATEX-FR-FRANCHISE - France domestic VAT franchise in base'),
            ('VATEX-FR-CNWVAT', 'VATEX-FR-CNWVAT - France domestic Credit Notes without VAT, due to supplier forfeit of VAT for discount'),
            ('VATEX-FR-CGI261-1', 'VATEX-FR-CGI261-1 - Exempt based on 1 of article 261 of the Code Général des Impôts (CGI ; General tax code)'),
            ('VATEX-FR-CGI261-2', 'VATEX-FR-CGI261-2 - Exempt based on 2 of article 261 of the Code Général des Impôts (CGI ; General tax code)'),
            ('VATEX-FR-CGI261-3', 'VATEX-FR-CGI261-3 - Exempt based on 3 of article 261 of the Code Général des Impôts (CGI ; General tax code)'),
            ('VATEX-FR-CGI261-4', 'VATEX-FR-CGI261-4 - Exempt based on 4 of article 261 of the Code Général des Impôts (CGI ; General tax code)'),
            ('VATEX-FR-CGI261-5', 'VATEX-FR-CGI261-5 - Exempt based on 5 of article 261 of the Code Général des Impôts (CGI ; General tax code)'),
            ('VATEX-FR-CGI261-7', 'VATEX-FR-CGI261-7 - Exempt based on 7 of article 261 of the Code Général des Impôts (CGI ; General tax code)'),
            ('VATEX-FR-CGI261-8', 'VATEX-FR-CGI261-8 - Exempt based on 8 of article 261 of the Code Général des Impôts (CGI ; General tax code)'),
            ('VATEX-FR-CGI261A', 'VATEX-FR-CGI261A - Exempt based on article 261 A of the Code Général des Impôts (CGI ; General tax code)'),
            ('VATEX-FR-CGI261B', 'VATEX-FR-CGI261B - Exempt based on article 261 B of the Code Général des Impôts (CGI ; General tax code)'),
            ('VATEX-FR-CGI261C-1', 'VATEX-FR-CGI261C-1 - Exempt based on 1° of article 261 C of the Code Général des Impôts (CGI ; General tax code)'),
            ('VATEX-FR-CGI261C-2', 'VATEX-FR-CGI261C-2 - Exempt based on 2° of article 261 C of the Code Général des Impôts (CGI ; General tax code)'),
            ('VATEX-FR-CGI261C-3', 'VATEX-FR-CGI261C-3 - Exempt based on 3° of article 261 C of the Code Général des Impôts (CGI ; General tax code)'),
            ('VATEX-FR-CGI261D-1', 'VATEX-FR-CGI261D-1 - Exempt based on 1° of article 261 D of the Code Général des Impôts (CGI ; General tax code)'),
            ('VATEX-FR-CGI261D-1BIS', 'VATEX-FR-CGI261D-1BIS - Exempt based on 1°bis of article 261 D of the Code Général des Impôts (CGI ; General tax code)'),
            ('VATEX-FR-CGI261D-2', 'VATEX-FR-CGI261D-2 - Exempt based on 2° of article 261 D of the Code Général des Impôts (CGI ; General tax code)'),
            ('VATEX-FR-CGI261D-3', 'VATEX-FR-CGI261D-3 - Exempt based on 3° of article 261 D of the Code Général des Impôts (CGI ; General tax code) Exonération de TVA - Article 261 D-3° du Code Général des Impôts'),
            ('VATEX-FR-CGI261D-4', 'VATEX-FR-CGI261D-4 - Exempt based on 4° of article 261 D of the Code Général des Impôts (CGI ; General tax code)'),
            ('VATEX-FR-CGI261E-1', 'VATEX-FR-CGI261E-1 - Exempt based on 1° of article 261 E of the Code Général des Impôts (CGI ; General tax code)'),
            ('VATEX-FR-CGI261E-2', 'VATEX-FR-CGI261E-2 - Exempt based on 2° of article 261 E of the Code Général des Impôts (CGI ; General tax code)'),
            ('VATEX-FR-CGI277A', 'VATEX-FR-CGI277A - Exempt based on article 277 A of the Code Général des Impôts (CGI ; General tax code)'),
            ('VATEX-FR-CGI275', 'VATEX-FR-CGI275 - Exempt based on article 275 of the Code Général des Impôts (CGI ; General tax code)'),
            ('VATEX-FR-298SEXDECIESA', 'VATEX-FR-298SEXDECIESA - Exempt based on article 298 sexdecies A of the Code Général des Impôts (CGI ; General tax code)'),
            ('VATEX-FR-CGI295', 'VATEX-FR-CGI295 - Exempt based on article 295 of the Code Général des Impôts (CGI ; General tax code)'),
            ('VATEX-FR-AE', 'VATEX-FR-AE - Exempt based on 2 of article 283 of the Code Général des Impôts (CGI ; General tax code)'),
        ]
    )
    ubl_cii_requires_exemption_reason = fields.Boolean(compute='_compute_ubl_cii_requires_exemption_reason')
    ubl_cii_allowance_reason_code = fields.Selection(
        string="Allowance Reason Code",
        selection=ALLOWANCE_REASON_CODES,
    )
    ubl_cii_charge_reason_code = fields.Selection(
        string="Charge Reason Code",
        selection=CHARGE_REASON_CODES,
    )
    ubl_cii_allowance_charge_reason = fields.Char()
    ubl_cii_is_charge = fields.Boolean(
        string="Is a Charge",
        help="Indicates whether this tax represents a charge or an allowance for electronic invoicing purposes.",
        default="True",
    )

    @api.depends('ubl_cii_tax_category_code')
    def _compute_ubl_cii_requires_exemption_reason(self):
        for tax in self:
            tax.ubl_cii_requires_exemption_reason = tax.ubl_cii_tax_category_code in ['AE', 'E', 'G', 'O', 'K']

    @api.onchange('ubl_cii_requires_exemption_reason')
    def _onchange_ubl_cii_tax_category_code(self):
        for tax in self:
            if not tax.ubl_cii_requires_exemption_reason:
                tax.ubl_cii_tax_exemption_reason = False
                tax.ubl_cii_tax_exemption_reason_code = False
