{
    "name": "AGI Gov - Knowledge Bridge",
    "version": "19.0.1.0.0",
    "category": "Government",
    "summary": "Integra Document Page com Processo e Documento da suite AGI Gov",
    "depends": ["gov_processos", "document_page"],
    "data": [
        "security/ir.model.access.csv",
        "data/gov_knowledge_group_bridge.xml",
        "views/gov_knowledge_processo_views.xml",
        "views/gov_knowledge_doc_views.xml",
        "views/gov_knowledge_article_views.xml",
        "views/gov_ai_template_knowledge_views.xml",
        "wizard/gov_knowledge_template_import_wizard_views.xml",
    ],
    "installable": True,
    "application": False,
    "author": "AGI Gov",
    "license": "LGPL-3",
}
