{
    "name": """Customer Chat""",
    "summary": """Be in touch with your partners via any supported channels (Telegram, WhatsApp, Viber, etc.)""",
    "category": "Marketing",
    "images": ['static/description/banner.png'],
    "version": "16.0.1.2.0",
    "application": False,
    "author": "UnitSoft",
    "support": "",
    "website": "https://unitsoft.com.ua/",
    "depends": ["mail"],
    "license": "LGPL-3",
    "external_dependencies": {"python": [], "bin": []},
    "data": ["views/mail_channel_views.xml"],
    "assets": {
        "web.assets_backend": [
            "us_multichat/static/src/models/channel.js",
            "us_multichat/static/src/models/discuss.js",
            "us_multichat/static/src/models/thread.js",
            "us_multichat/static/src/models/messaging.js",
            "us_multichat/static/src/models/discuss_sidebar_category_item.js",
            "us_multichat/static/src/components/discuss_sidebar/discuss_sidebar.xml",
        ],
    },
    "post_load": None,
    "pre_init_hook": None,
    "post_init_hook": None,
    "uninstall_hook": None,
    "auto_install": False,
    "installable": True,
}
