from . import mixin_resource_ledger
from . import res_company
from . import res_partner
from . import res_users
from . import resource_time_type
from . import resource_calendar
from . import resource_calendar_attendance
from . import resource_schedule_exception
from . import mixin_resource
from . import resource_resource
from . import resource_role
from . import mixin_resource_scheduling_tools
from . import mixin_resource_scheduling
from . import mixin_resource_allocation
from . import resource_reservation
from . import resource_assignment
from . import utils
