{
    "name": "Web",
    "version": "2.4",
    "category": "Hidden",
    "description": """
Odoo Web core module.
========================

This module provides the core of the Odoo Web Client.
""",
    "author": "Odoo S.A.",
    "license": "LGPL-3",
    "depends": [
        "base",
    ],
    "data": [
        "security/ir.model.access.csv",
        "security/web_security.xml",
        "views/webclient_templates.xml",
        "views/report_templates.xml",
        "reports/ir_model_report.xml",
        "reports/ir_model_templates.xml",
        "reports/ir_module_reports.xml",
        "reports/ir_module_report_templates.xml",
        "views/base_document_layout_views.xml",
        "views/partner_view.xml",
        "views/speedscope_template.xml",
        "views/memory_template.xml",
        "views/speedscope_config_wizard.xml",
        "views/neutralize_views.xml",
        "views/ir_ui_view_views.xml",
        "views/res_config_settings_views.xml",
        "views/res_users_views.xml",
        "views/web_cwv_metric_views.xml",
        "views/web_js_error_views.xml",
        "data/ir_attachment.xml",
        "data/report_theme.xml",
        "data/report_layout.xml",
        "data/web_cwv_metric_data.xml",
        "data/web_js_error_data.xml",
        "views/web_menus.xml",
    ],
    "assets": {
        "web.assets_emoji": [
            "web/static/src/components/emoji_picker/emoji_data.js",
        ],
        "web.assets_backend": [
            (
                "include",
                "web._assets_helpers",
            ),
            (
                "include",
                "web._assets_backend_helpers",
            ),
            "web/static/src/scss/pre_variables.scss",
            "web/static/lib/bootstrap/scss/_variables.scss",
            "web/static/lib/bootstrap/scss/_variables-dark.scss",
            "web/static/lib/bootstrap/scss/_maps.scss",
            (
                "include",
                "web._assets_bootstrap_backend",
            ),
            "web/static/src/scss/tokens.scss",
            "web/static/src/scss/scheme_rules.scss",
            (
                "include",
                "web._assets_core",
            ),
            "web/static/src/scss/fonts.scss",
            "web/static/src/libs/fontawesome7/css/fontawesome.css",
            "web/static/src/libs/fontawesome7/css/solid.css",
            "web/static/src/libs/fontawesome7/css/regular.css",
            "web/static/src/libs/fontawesome7/css/brands.css",
            "web/static/src/libs/fontawesome7/css/v4-shims.css",
            "web/static/lib/odoo_ui_icons/*",
            "web/static/src/webclient/navbar/navbar.scss",
            "web/static/src/scss/animation.scss",
            "web/static/src/scss/rtl_icon_flip.scss",
            "web/static/src/scss/mimetypes.scss",
            "web/static/src/scss/ui.scss",
            "web/static/src/fields/translation_dialog.scss",
            "base/static/src/css/modules.css",
            "web/static/src/model/**/*",
            "web/static/src/search/**/*",
            "web/static/src/webclient/icons.scss",
            "web/static/src/fields/**/*",
            "web/static/src/views/**/*",
            "web/static/src/webclient/**/*",
            (
                "remove",
                "web/static/src/webclient/clickbot/clickbot.js",
            ),
            (
                "remove",
                "web/static/src/views/form/button_box/*.scss",
            ),
            (
                "remove",
                "web/static/src/webclient/actions/reports/**/*",
            ),
            "web/static/src/webclient/actions/reports/*.js",
            "web/static/src/webclient/actions/reports/*.xml",
            "web/static/src/scss/ace.scss",
            "web/static/src/scss/base_document_layout.scss",
            "base/static/src/scss/res_partner.scss",
            "base/static/src/scss/res_users.scss",
            "web/static/src/views/form/button_box/*.scss",
            "web/static/src/scss/view_skins.scss",
            (
                "remove",
                "web/static/src/**/*.dark.scss",
            ),
        ],
        "web.assets_web": [
            (
                "include",
                "web.assets_backend",
            ),
            "web/static/src/boot/start.js",
            "web/static/src/boot/main.js",
        ],
        "web.assets_frontend_minimal": [
            "web/static/src/session.js",
            "web/static/src/core/browser/cookie.js",
            "web/static/src/core/utils/dom/ui.js",
            "web/static/src/public/minimal_dom.js",
            "web/static/src/public/lazyloader.js",
        ],
        "web.assets_frontend": [
            (
                "include",
                "web._assets_helpers",
            ),
            (
                "include",
                "web._assets_frontend_helpers",
            ),
            "web/static/src/scss/pre_variables.scss",
            "web/static/lib/bootstrap/scss/_variables.scss",
            "web/static/lib/bootstrap/scss/_variables-dark.scss",
            "web/static/lib/bootstrap/scss/_maps.scss",
            (
                "include",
                "web._assets_bootstrap_frontend",
            ),
            "web/static/src/scss/tokens.scss",
            "web/static/src/scss/fonts.scss",
            "web/static/src/libs/fontawesome7/css/fontawesome.css",
            "web/static/src/libs/fontawesome7/css/solid.css",
            "web/static/src/libs/fontawesome7/css/regular.css",
            "web/static/src/libs/fontawesome7/css/brands.css",
            "web/static/src/libs/fontawesome7/css/v4-shims.css",
            "web/static/lib/odoo_ui_icons/*",
            "web/static/src/webclient/navbar/navbar.scss",
            "web/static/src/webclient/home_menu/home_menu_background.scss",
            "web/static/src/scss/animation.scss",
            "web/static/src/scss/base_frontend.scss",
            "web/static/src/scss/rtl_icon_flip.scss",
            "web/static/src/scss/mimetypes.scss",
            "web/static/src/scss/ui.scss",
            "web/static/src/fields/translation_dialog.scss",
            "web/static/src/fields/media/signature/signature_field.scss",
            (
                "include",
                "web.assets_frontend_minimal",
            ),
            "web/static/src/libs/popper_compat.js",
            "web/static/src/libs/bootstrap.js",
            "web/static/src/env.js",
            "web/static/src/ui/**/*",
            (
                "remove",
                "web/static/src/ui/commands/**/*",
            ),
            (
                "remove",
                "web/static/src/ui/commands.js",
            ),
            "web/static/src/components/**/*",
            "web/static/src/core/**/*",
            (
                "remove",
                "web/static/src/core/flow_editor/**/*",
            ),
            "web/static/src/webclient/debug/debug_menu_basic.js",
            "web/static/src/webclient/debug/debug_affordances.js",
            "web/static/src/webclient/debug/debug_menu_items.js",
            "web/static/src/webclient/debug/debug_providers.js",
            "web/static/src/webclient/debug/debug_menu.scss",
            "web/static/src/webclient/debug/debug_menu.xml",
            "web/static/src/webclient/debug/debug_menu_items.xml",
            "web/static/src/webclient/install_scoped_app/install_scoped_app.js",
            "web/static/src/webclient/install_scoped_app/install_scoped_app.xml",
            (
                "remove",
                "web/static/src/components/emoji_picker/emoji_data.js",
            ),
            (
                "remove",
                "web/static/src/**/*.dark.scss",
            ),
            "web/static/src/webclient/errors/visitor_error_handler.js",
            "web/static/src/public/**/*.js",
            "web/static/src/public/**/*.xml",
            (
                "remove",
                "web/static/src/public/database_manager.js",
            ),
            (
                "remove",
                "web/static/src/public/database_manager_page.js",
            ),
        ],
        "web.assets_frontend_lazy": [
            (
                "include",
                "web.assets_frontend",
            ),
            (
                "remove",
                "web/static/src/session.js",
            ),
            (
                "remove",
                "web/static/src/core/browser/cookie.js",
            ),
            (
                "remove",
                "web/static/src/core/utils/dom/ui.js",
            ),
            (
                "remove",
                "web/static/src/public/minimal_dom.js",
            ),
            (
                "remove",
                "web/static/src/public/lazyloader.js",
            ),
        ],
        "web.report_assets_common": [
            "web/static/src/scss/functions.scss",
            "web/static/src/scss/utils.scss",
            (
                "include",
                "web._assets_primary_variables",
            ),
            (
                "include",
                "web._assets_secondary_variables",
            ),
            "web/static/src/webclient/actions/reports/bootstrap_overridden_report.scss",
            (
                "include",
                "web._assets_helpers",
            ),
            (
                "include",
                "web._assets_backend_helpers",
            ),
            "web/static/src/scss/pre_variables.scss",
            "web/static/lib/bootstrap/scss/_variables.scss",
            "web/static/lib/bootstrap/scss/_variables-dark.scss",
            "web/static/lib/bootstrap/scss/_maps.scss",
            (
                "include",
                "web._assets_bootstrap_backend",
            ),
            "web/static/src/scss/tokens.scss",
            (
                "remove",
                "web/static/src/scss/utilities_custom_backend.scss",
            ),
            (
                "remove",
                "web/static/src/scss/bootstrap_review_backend.scss",
            ),
            (
                "after",
                "web/static/src/scss/utilities_custom.scss",
                "web/static/src/webclient/actions/reports/utilities_custom_report.scss",
            ),
            "web/static/src/libs/popper_compat.js",
            "web/static/src/libs/bootstrap.js",
            "base/static/src/css/description.css",
            "web/static/src/libs/fontawesome7/css/fontawesome.css",
            "web/static/src/libs/fontawesome7/css/solid.css",
            "web/static/src/libs/fontawesome7/css/regular.css",
            "web/static/src/libs/fontawesome7/css/brands.css",
            "web/static/src/libs/fontawesome7/css/v4-shims.css",
            "web/static/src/scss/rtl_icon_flip.scss",
            "web/static/lib/odoo_ui_icons/*",
            "web/static/fonts/fonts.scss",
            "web/static/src/webclient/actions/reports/bootstrap_review_report.scss",
            "web/static/src/webclient/actions/reports/report.scss",
            "web/static/src/webclient/actions/reports/report_tables.scss",
            "web/static/src/webclient/actions/reports/layout_assets/layout_*.scss",
            "web/static/asset_styles_company_report.scss",
        ],
        "web.report_assets_pdf": [
            "web/static/src/webclient/actions/reports/reset.min.css",
            "web/static/src/webclient/actions/reports/report_paged_media.css",
            "web/static/src/webclient/actions/reports/report_pdf_layout.css",
        ],
        "web.ace_lib": [
            "web/static/lib/ace/ace.js",
            "web/static/lib/ace/mode-javascript.js",
            "web/static/lib/ace/mode-xml.js",
            "web/static/lib/ace/mode-qweb.js",
            "web/static/lib/ace/mode-python.js",
            "web/static/lib/ace/mode-scss.js",
            "web/static/lib/ace/mode-json.js",
            "web/static/lib/ace/theme-monokai.js",
        ],
        "web.assets_web_print": [
            "web/static/src/scss/functions.scss",
            "web/static/src/scss/primary_variables_print.scss",
            "web/static/src/**/*.print_variables.scss",
            (
                "include",
                "web.assets_backend",
            ),
        ],
        "web._dark_mode_variables": [
            (
                "before",
                "web/static/src/scss/primitives.scss",
                "web/static/src/scss/primitives.dark.scss",
            ),
            (
                "before",
                "web/static/src/scss/primary_variables.scss",
                "web/static/src/scss/primary_variables.dark.scss",
            ),
        ],
        "web.assets_web_dark": [
            (
                "include",
                "web.assets_web",
            ),
            (
                "include",
                "web._dark_mode_variables",
            ),
            (
                "after",
                "web/static/lib/bootstrap/scss/_functions.scss",
                "web/static/src/scss/bs_functions_overridden.dark.scss",
            ),
            (
                "before",
                "web/static/src/scss/bootstrap_overridden.scss",
                "web/static/src/scss/bootstrap_overridden.dark.scss",
            ),
            "web/static/src/**/*.dark.scss",
        ],
        "web.assets_backend_dark": [
            (
                "include",
                "web._assets_helpers",
            ),
            (
                "include",
                "web._assets_backend_helpers",
            ),
            (
                "include",
                "web._dark_mode_variables",
            ),
            (
                "after",
                "web/static/lib/bootstrap/scss/_functions.scss",
                "web/static/src/scss/bs_functions_overridden.dark.scss",
            ),
            (
                "before",
                "web/static/src/scss/bootstrap_overridden.scss",
                "web/static/src/scss/bootstrap_overridden.dark.scss",
            ),
            "web/static/src/**/*.dark.scss",
        ],
        "web._assets_core": [
            "web/static/src/session.js",
            "web/static/src/env.js",
            "web/static/src/ui/**/*",
            "web/static/src/components/**/*",
            "web/static/src/core/**/*",
            (
                "remove",
                "web/static/src/components/emoji_picker/emoji_data.js",
            ),
            (
                "remove",
                "web/static/src/**/*.dark.scss",
            ),
        ],
        "web._assets_primary_variables": [
            "web/static/src/scss/palette_dark.scss",
            "web/static/src/scss/primitives.scss",
            "web/static/src/scss/primary_variables.scss",
            "web/static/src/**/*.variables.scss",
        ],
        "web._assets_secondary_variables": [
            "web/static/src/scss/secondary_variables.scss",
        ],
        "web._assets_helpers": [
            "web/static/lib/bootstrap/scss/_functions.scss",
            "web/static/lib/bootstrap/scss/_mixins.scss",
            "web/static/src/scss/functions.scss",
            "web/static/src/scss/mixins_forwardport.scss",
            "web/static/src/scss/bs_mixins_overrides.scss",
            "web/static/src/scss/utils.scss",
            (
                "include",
                "web._assets_primary_variables",
            ),
            (
                "include",
                "web._assets_secondary_variables",
            ),
        ],
        "web._assets_bootstrap": [
            "web/static/src/scss/import_bootstrap.scss",
            "web/static/src/scss/utilities_custom.scss",
            "web/static/lib/bootstrap/scss/utilities/_api.scss",
            "web/static/src/scss/bootstrap_review.scss",
        ],
        "web._assets_bootstrap_backend": [
            (
                "include",
                "web._assets_bootstrap",
            ),
            (
                "after",
                "web/static/src/scss/utilities_custom.scss",
                "web/static/src/scss/utilities_custom_backend.scss",
            ),
            "web/static/src/scss/bootstrap_review_backend.scss",
        ],
        "web._assets_bootstrap_frontend": [
            (
                "include",
                "web._assets_bootstrap",
            ),
            "web/static/src/scss/bootstrap_review_frontend.scss",
        ],
        "web._assets_backend_helpers": [
            "web/static/src/scss/bootstrap_overridden.scss",
            "web/static/src/scss/bs_mixins_overrides_backend.scss",
        ],
        "web._assets_frontend_helpers": [
            "web/static/src/scss/bootstrap_overridden_frontend.scss",
        ],
        "web.assets_tests": [
            "web/static/tests/helpers/cleanup.js",
            "web/static/tests/helpers/utils.js",
            "web/static/tests/utils.js",
            "web/static/tests/tours/**/*",
        ],
        "web.assets_unit_tests_setup": [
            "web/static/src/libs/popper_compat.js",
            "web/static/src/libs/bootstrap.js",
            "web/static/lib/hoot/**/*",
            "web/static/lib/hoot-dom/**/*",
            (
                "remove",
                "web/static/lib/hoot/ui/hoot_style.css",
            ),
            (
                "remove",
                "web/static/lib/hoot/tests/**/*",
            ),
            (
                "include",
                "web.assets_backend",
            ),
            "web/static/src/public/minimal_dom.js",
            "web/static/src/public/lazyloader.js",
            "web/static/src/public/**/*.js",
            "web/static/src/public/**/*.xml",
            "web/static/tests/public/**/*.xml",
            (
                "remove",
                "web/static/src/public/database_manager.js",
            ),
            (
                "remove",
                "web/static/src/public/public_boot_instance.js",
            ),
            (
                "remove",
                "web/static/src/public/error_notifications.js",
            ),
            "web/static/src/boot/**/*.js",
            (
                "remove",
                "web/static/src/boot/main.js",
            ),
            "web/static/src/webclient/clickbot/clickbot.js",
        ],
        "web.assets_unit_tests_setup_ui": [
            "web/static/lib/diff_match_patch/diff_match_patch.js",
            "web/static/lib/prismjs/prism.js",
        ],
        "web.assets_unit_tests": [
            "web/static/tests/**/*",
            (
                "remove",
                "web/static/tests/tours/**/*",
            ),
            (
                "remove",
                "web/static/tests/utils.js",
            ),
        ],
        "web.assets_clickbot": [
            "web/static/src/webclient/clickbot/clickbot.js",
        ],
    },
    "esm": {
        "bundles": [
            "web.assets_web",
            "web.assets_web_dark",
            "web.assets_web_print",
            "web.assets_frontend",
            "web.assets_frontend_lazy",
            "web.assets_frontend_minimal",
            "web.assets_inside_builder_iframe",
            "web.report_assets_common",
            "web.report_assets_pdf",
            "web.assets_tests",
            "web.assets_unit_tests",
            "web.assets_unit_tests_setup",
            "web.assets_clickbot",
            "web.assets_emoji",
        ],
        "exports": [
            "@web/webclient/clickbot/clickbot_loader",
        ],
        "dynamic_children": {
            "web.assets_web": [
                "web.assets_clickbot",
                "web.assets_emoji",
            ],
            "web.assets_frontend": [
                "web.assets_emoji",
            ],
        },
        "external_libs": {
            "@odoo/owl": "/web/static/lib/owl/owl.es.js",
            "@odoo/hoot": "/web/static/lib/hoot/hoot.js",
            "@odoo/hoot-dom": "/web/static/lib/hoot-dom/hoot-dom.js",
            "@odoo/hoot-mock": "/web/static/lib/hoot/hoot-mock.js",
            "@odoo/hoot-dom-helpers-dom": "/web/static/lib/hoot-dom/helpers/dom.js",
            "@odoo/hoot-dom-helpers-events": "/web/static/lib/hoot-dom/helpers/events.js",
            "@odoo/hoot-dom-helpers-time": "/web/static/lib/hoot-dom/helpers/time.js",
            "@odoo/hoot-dom-utils": "/web/static/lib/hoot-dom/hoot_dom_utils.js",
            "@popperjs/core": "/web/static/lib/popper_compat/popper_compat.esm.js",
            "luxon": "/web/static/lib/luxon/luxon.js",
            "dompurify": "/web/static/lib/dompurify/purify.es.js",
            "signature_pad": "/web/static/lib/signature_pad/signature_pad.js",
            "zxing-library": "/web/static/lib/zxing-library/zxing-library.js",
            "joint": "/web/static/lib/joint/joint.esm.js",
            "pdfjs-dist": "/web/static/lib/pdfjs/build/pdf.js",
            "chart.js": "/web/static/lib/Chart/Chart.js",
            "chart.js/helpers": "/web/static/lib/Chart/helpers.js",
            "chartjs-adapter-luxon": "/web/static/lib/chartjs-adapter-luxon/chartjs-adapter-luxon.js",
            "@fullcalendar/core": "/web/static/lib/fullcalendar/fullcalendar.esm.js",
            "@fullcalendar/core/locales-all": "/web/static/lib/fullcalendar/locales-all.esm.js",
        },
        "import_map_includes": {
            "web.assets_unit_tests_setup": [
                "web.assets_unit_tests",
            ],
        },
        "secondary_import_map_includes": {
            "web.assets_web": [
                "web.assets_tests",
            ],
            "web.assets_frontend": [
                "web.assets_tests",
            ],
            "web.assets_frontend_lazy": [
                "web.assets_tests",
            ],
            "web.assets_frontend_minimal": [
                "web.assets_tests",
            ],
        },
    },
    "bootstrap": True,
    "auto_install": True,
}
