{
    "name": "Custom Document Layouts",
    "version": "1.0",
    "category": "Tools",
    "summary": "Agencements personnalisés pour les documents PDF",
    "description": "Ajoute de nouveaux agencements pour les factures, devis, bons, etc.",
    "author": "Alain Gansonré",
    "depends": ["base","sale","web","account"],
    "data": [
        'views/external_layout_modern.xml',
        'views/external_layout_sale_order.xml',
        'views/report_invoice_numbering.xml',
        'views/report_invoice_total_bold.xml',
        'views/report_invoice_add_reference.xml',
        'views/report_saleorder_line_numbering.xml',
        'data/report_layouts.xml',
        'data/report_layout_sale_order.xml',
        'data/report_invoice_compact.xml',
        'data/report_saleorder_compact.xml',
    ],
    "installable": True,
    "application": False,
    "auto_install": False,
}
