{
    'name': 'Presenly Attendance Tools',
    'version': '19.0.14.0.0',
    'category': 'Human Resources/Attendances',
    'summary': 'Attendance geofence, evidence, permissions and multilevel approvals',
    'description': """
Technical tools extending Odoo Attendances with multi-company and
multi-work-location geofencing, selfie evidence, permissions, mobile APIs,
and multilevel approvals.
    """,
    'author': 'Presenly',
    'license': 'LGPL-3',
    'depends': ['hr', 'hr_attendance', 'hr_holidays', 'hr_homeworking', 'mail'],
    'data': [
        'security/presenly_groups.xml',
        'security/ir.model.access.csv',
        'security/presenly_rules.xml',
        'wizard/presenly_leave_reject_views.xml',
        'wizard/presenly_permission_reject_views.xml',
        'wizard/presenly_schedule_generate_views.xml',
        'wizard/presenly_overtime_reject_views.xml',
        'data/presenly_data.xml',
        'data/presenly_migration.xml',
        'views/presenly_location_views.xml',
        'views/presenly_schedule_views.xml',
        'views/presenly_permission_views.xml',
        'views/presenly_approval_views.xml',
        'views/presenly_attendance_views.xml',
        'views/presenly_overtime_views.xml',
        'views/hr_attendance_integration_views.xml',
        'views/hr_employee_integration_views.xml',
        'views/presenly_leave_views.xml',
        'views/hr_leave_report_calendar_views.xml',
        'views/hr_attendance_presenly_actions.xml',
        'views/presenly_menus.xml',
        'views/presenly_deletion_log_views.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'presenly/static/src/fields/attachment_image_viewer/attachment_image_viewer.js',
            'presenly/static/src/fields/attachment_image_viewer/attachment_image_viewer.xml',
        ],
    },
    'test': [
        'tests/test_attendance.py',
        'tests/test_approval.py',
        'tests/test_permission.py',
    ],
    'installable': True,
    'application': False,
}
