from . import product_template_attribuite_value
from . import pos_store_timing
from . import res_partner
from . import pos_config
from . import product
from . import pos_order
from . import res_config_settings
from . import pos_session
from . import preparation_display_order
