from . import ir_actions_report
from . import mail_message
from . import mail_notification
from . import snailmail_config
from . import res_company
from . import res_config_settings
from . import res_partner
from . import snailmail_letter
from . import mixin_mail_thread
