from . import test_workorder
from . import test_workorder_hr
from . import test_basic
from . import test_duplicates
from . import test_quality
from . import test_dependencies
from . import test_tablet_client_action
from . import test_consume_component
from . import test_shopfloor
from . import test_bom
