from . import (
    account_move,
    account_move_line,
    product_template,
    res_company,
    res_users,
    sale_order,
    sale_order_line,
    stock_lot,
    stock_move,
    stock_move_line,
    stock_picking,
    stock_reference,
    stock_route,
    stock_rule,
)
