{
    "name": "Calendar",
    "version": "2.6",
    "category": "Productivity/Calendar",
    "sequence": 165,
    "summary": "Meetings, resource bookings and public appointment scheduling",
    "description": "Manage meetings, recurring events, booking offers, public scheduling and resource allocations in one calendar.",
    "author": "Odoo S.A.",
    "license": "OEEL-1",
    "depends": [
        "mail",
        "resource",
        "phone_validation",
        "portal",
        "survey",
    ],
    "data": [
        "security/ir.model.access.csv",
        "security/calendar_security.xml",
        "data/calendar_cron.xml",
        "data/mail_template_data.xml",
        "data/calendar_data.xml",
        "data/mail_activity_type_data.xml",
        "data/mail_message_subtype_data.xml",
        "views/mail_activity_views.xml",
        "views/calendar_templates.xml",
        "views/calendar_views.xml",
        "views/res_config_settings_views.xml",
        "views/res_partner_views.xml",
        "views/res_users_views.xml",
        "wizards/calendar_provider_config.xml",
        "wizards/calendar_popover_delete_wizard.xml",
        "wizards/mail_activity_schedule_views.xml",
        "data/booking/appointment_question_data.xml",
        "data/booking/calendar_data.xml",
        "data/booking/mail_message_subtype_data.xml",
        "data/booking/mail_template_data.xml",
        "data/booking/resource_calendar_data.xml",
        "security/booking/res_groups_data.xml",
        "security/booking/ir_rule_data.xml",
        "security/booking/ir.model.access.csv",
        "views/booking/calendar_alarm_views.xml",
        "views/booking/calendar_event_views.xml",
        "views/booking/appointment_answer_input_views.xml",
        "views/booking/appointment_answer_views.xml",
        "views/booking/appointment_invite_views.xml",
        "views/booking/appointment_question_views.xml",
        "views/booking/resource_resource_views.xml",
        "views/booking/appointment_type_views.xml",
        "views/booking/appointment_slot_views.xml",
        "views/booking/resource_schedule_exception_views.xml",
        "views/booking/calendar_menus.xml",
        "views/booking/appointment_menus.xml",
        "views/booking/appointment_templates_appointments.xml",
        "views/booking/appointment_templates_registration.xml",
        "views/booking/appointment_templates_validation.xml",
        "views/booking/portal_templates.xml",
        "wizards/booking/appointment_manage_leaves.xml",
    ],
    "demo": [
        "demo/calendar_demo.xml",
        "demo/booking/res_partner_demo.xml",
        "demo/booking/appointment_type_demo.xml",
        "demo/booking/resource_resource_demo.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "calendar/static/src/**/*",
            (
                "remove",
                "calendar/static/src/booking/**/*",
            ),
            "calendar/static/src/booking/scss/appointment_type_views.scss",
            "calendar/static/src/booking/scss/calendar_event_views.scss",
            "calendar/static/src/booking/scss/web_calendar.scss",
            "calendar/static/src/booking/views/**/*",
            "calendar/static/src/booking/fields/**/*",
            "calendar/static/src/booking/components/**/*",
            "calendar/static/src/booking/js/appointment_insert_link_form_controller.js",
            "calendar/static/src/booking/appointment_plugin.js",
            "calendar/static/src/booking/xml/appointment_svg.xml",
        ],
        "web.assets_unit_tests": [
            "calendar/static/tests/**/*.js",
            (
                "remove",
                "calendar/static/tests/tours/**/*",
            ),
            "calendar/static/tests/booking/*",
        ],
        "web.assets_tests": [
            "calendar/static/tests/tours/**/*",
        ],
        "web.assets_frontend": [
            "calendar/static/src/booking/js/utils.js",
            "calendar/static/src/booking/scss/appointment.scss",
            "calendar/static/src/booking/interactions/appointment_select_appointment_type.js",
            "calendar/static/src/booking/interactions/appointment_validation.js",
            "calendar/static/src/booking/interactions/appointment_select_appointment_slot.js",
            "calendar/static/src/booking/interactions/appointment_form.js",
            "calendar/static/src/booking/xml/*.xml",
        ],
    },
    "application": True,
}
