from . import account_account
from . import account_chart_template
from . import account_move
from . import account_move_line
from . import stock_config
from . import res_company
from . import product
from . import product_value
from . import stock_move
from . import stock_location
from . import stock_lot
from . import stock_move_line
from . import stock_picking
from . import stock_picking_type
from . import stock_quant
from . import res_config_settings
