upstream odoo_app {
    server odoo:8069;
}

upstream odoo_bus {
    server odoo:8072;
}

map $http_upgrade $connection_upgrade {
    default upgrade;
    '' close;
}

map $http_x_forwarded_proto $proxy_x_forwarded_proto {
    default $scheme;
    "~*https" https;
    "~*http" http;
}

map $proxy_x_forwarded_proto $proxy_x_forwarded_port {
    default 80;
    https 443;
}

server {
    listen 80;
    server_name kodoo.online www.kodoo.online;

    if ($host = www.kodoo.online) {
        return 301 https://kodoo.online$request_uri;
    }

    client_max_body_size 100m;
    proxy_read_timeout 900s;
    proxy_connect_timeout 30s;
    proxy_send_timeout 900s;
    proxy_buffers 16 64k;
    proxy_buffer_size 128k;
    proxy_busy_buffers_size 256k;
    proxy_temp_file_write_size 256k;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location /longpolling {
        proxy_pass http://odoo_bus;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $proxy_x_forwarded_proto;
        proxy_set_header X-Forwarded-Port $proxy_x_forwarded_port;
        proxy_redirect off;
        proxy_buffering off;
    }

    location /websocket {
        proxy_pass http://odoo_bus;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $proxy_x_forwarded_proto;
        proxy_set_header X-Forwarded-Port $proxy_x_forwarded_port;
        proxy_redirect off;
    }

    location / {
        proxy_pass http://odoo_app;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $proxy_x_forwarded_proto;
        proxy_set_header X-Forwarded-Port $proxy_x_forwarded_port;
        proxy_redirect off;
    }
}
