from . import account_edi_common
from . import account_edi_proxy_user
from . import account_edi_ubl_xml
from . import account_journal
from . import account_move
from . import account_move_send
from . import res_company
from . import res_config_settings
from . import res_partner
