# Part of Odoo. See LICENSE file for full copyright and licensing details.

{
    'name': 'Employees',
    'version': '1.1',
    'category': 'Human Resources/Employees',
    'sequence': 95,
    'summary': 'Centralize employee information',
    'website': 'https://www.odoo.com/app/employees',
    'images': [
        'static/src/img/default_image.png',
    ],
    'depends': [
        'base_setup',
        'digest',
        'phone_validation',
        'resource_mail',
        'web_hierarchy',
    ],
    'data': [
        'security/hr_security.xml',
        'security/hr_skills_security.xml',
        'security/ir.model.access.csv',
        'data/digest_data.xml',
        'data/report_paperformat.xml',
        'data/hr_data.xml',
        'data/ir_cron_data.xml',
        'data/hr_resume_data.xml',
        'data/hr_skill_data.xml',
        'data/hr_skills_ir_actions_server_data.xml',
        'data/hr_skills_ir_cron_data.xml',
        'data/hr_skills_mail_activity_type_data.xml',
        'data/hr_skills_report_paperformat.xml',
        'wizard/hr_departure_wizard_views.xml',
        'wizard/mail_activity_schedule_views.xml',
        'wizard/hr_bank_account_allocation_wizard.xml',
        'wizard/hr_bank_account_allocation_wizard_line.xml',
        'wizard/hr_employee_cv_wizard_views.xml',
        'views/mail_activity_plan_views.xml',
        'report/hr_employee_cv_report.xml',
        'report/hr_employee_skill_report_views.xml',
        'report/hr_employee_skill_history_report_views.xml',
        'views/hr_resume_line_views.xml',
        'views/hr_resume_line_type_views.xml',
        'views/hr_skill_type_views.xml',
        'views/hr_skill_level_views.xml',
        'views/hr_skill_views.xml',
        'views/hr_employee_skill_views.xml',
        'views/hr_version_views.xml',
        'views/hr_contract_template_views.xml',
        'views/hr_departure_reason_views.xml',
        'views/hr_contract_type_views.xml',
        'views/hr_job_views.xml',
        'views/hr_employee_category_views.xml',
        'views/hr_employee_public_views.xml',
        'report/hr_employee_badge.xml',
        'views/hr_employee_views.xml',
        'views/hr_employee_departure_views.xml',
        'views/hr_department_views.xml',
        'views/hr_work_location_views.xml',
        'views/res_config_settings_views.xml',
        'views/res_partner_views.xml',
        'views/res_partner_bank_views.xml',
        'views/discuss_channel_views.xml',
        'views/res_users.xml',
        'views/hr_templates.xml',
        'views/hr_export_mixin_views.xml',
        'views/hr_views.xml',
    ],
    'demo': [
        'data/hr_demo.xml',
        'data/hr_resume_demo.xml',
        'data/hr_skill_demo.xml',
        'data/hr_job_skill_demo.xml',
        'data/hr.job.skill.csv',
        'data/hr.employee.skill.csv',
        'data/hr_employee_skill_demo.xml',
        'data/hr.resume.line.csv',
    ],
    'application': True,
    'assets': {
        'web._assets_primary_variables': [
            'hr/static/src/scss/variables.scss',
        ],
        'web.assets_backend': [
            'hr/static/src/**/*',
            ('remove', 'hr/static/src/views/hr_employee_hierarchy/*'),
        ],
        'web.assets_backend_lazy': [
            'hr/static/src/views/hr_employee_hierarchy/*',
        ],
        'im_livechat.assets_embed_core': [
            'hr/static/src/core/common/**/*',
        ],
        'mail.assets_public': [
            'hr/static/src/core/common/**/*',
        ],
        'portal.assets_chatter_helpers': [
            'hr/static/src/core/common/**/*',
        ],
        'web.assets_unit_tests': [
            'hr/static/tests/**/*',
            ('remove', 'hr/static/tests/tours/**/*'),
            ('remove', 'hr/static/tests/legacy/**/*'),
        ],
        'web.assets_tests': [
            'hr/static/tests/tours/**/*',
        ],
    },
    'author': 'Odoo S.A.',
    'license': 'LGPL-3',
}
