{
    "name": "Employees",
    "version": "1.24",
    "category": "Human Resources/Employees",
    "sequence": 95,
    "summary": "Centralize employee information",
    "author": "Odoo S.A.",
    "website": "https://www.odoo.com/app/employees",
    "images": [
        "static/src/img/default_image.png",
    ],
    "license": "LGPL-3",
    "depends": [
        "approval",
        "digest",
        "phone_validation",
        "resource_mail",
    ],
    "data": [
        "security/hr_security.xml",
        "security/ir.model.access.csv",
        "data/approval_category_data.xml",
        "data/digest_data.xml",
        "data/res_partner_identifier_type_data.xml",
        "data/report_paperformat.xml",
        "wizards/hr_departure_wizard_views.xml",
        "wizards/hr_contract_template_wizard.views.xml",
        "wizards/mail_activity_schedule_views.xml",
        "wizards/hr_bank_account_allocation_wizard.xml",
        "wizards/hr_bank_account_allocation_wizard_line.xml",
        "views/mail_activity_plan_views.xml",
        "views/hr_version_views.xml",
        "views/hr_contract_template_views.xml",
        "views/hr_departure_reason_views.xml",
        "views/hr_contract_type_views.xml",
        "views/hr_job_views.xml",
        "reports/hr_employee_badge.xml",
        "views/hr_employee_category_views.xml",
        "views/hr_employee_views.xml",
        "views/hr_employee_change_request_views.xml",
        "views/hr_department_views.xml",
        "views/resource_assignment_views.xml",
        "views/hr_work_location_views.xml",
        "views/res_config_settings_views.xml",
        "views/hr_menus.xml",
        "views/res_partner_views.xml",
        "views/res_partner_bank_views.xml",
        "views/discuss_channel_views.xml",
        "views/res_users.xml",
        "views/hr_templates.xml",
        "data/hr_data.xml",
    ],
    "demo": [
        "demo/hr_demo.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "hr/static/src/**/*",
        ],
        "im_livechat.assets_embed_core": [
            "hr/static/src/core/common/**/*",
        ],
        "mail.assets_public": [
            "hr/static/src/core/common/**/*",
        ],
        "web.assets_unit_tests": [
            "hr/static/tests/**/*",
            (
                "remove",
                "hr/static/tests/tours/**/*",
            ),
        ],
        "web.assets_tests": [
            "hr/static/tests/tours/**/*",
        ],
    },
    "application": True,
}
