from . import test_controller_attachment
from . import test_controller_reaction
from . import test_controller_update
from . import test_controller_thread
from . import test_ir_mail_server
from . import test_mail_bot
from . import test_mail_performance
from . import test_mail_thread_internals
from . import test_mass_mailing
from . import test_portal
from . import test_rating
from . import test_res_users
from . import test_ui
from . import test_portal_mixin_sharing
from . import test_portal_share_invitation
