from . import test_phonenumbers
from . import test_phonenumbers_patch
from . import test_phonenumbers_blacklist
from . import test_phone_format_tools
from . import test_phone_blacklist_ops
from . import test_phone_format_variants
from . import test_phone_mobile_search
from . import test_partner_phone_name_search
from . import test_contact_preference
