{
    "name": "GOV - Auditoria e Prestacao de Contas",
    "version": "19.0.1.0.0",
    "summary": "Ciclo completo de prestacao de contas anuais ate acordao",
    "category": "Government/Audit",
    "author": "Kodoo",
    "license": "LGPL-3",
    "depends": [
        "gov_processos",
        "gov_account_fiscal_year",
        "gov_empenho",
        "gov_liquidacao",
        "gov_pagamento",
        "gov_public_accounting",
        "mail",
        "base_setup",
    ],
    "data": [
        "security/gov_auditoria_groups.xml",
        "security/ir.model.access.csv",
        "security/gov_auditoria_rules.xml",
        "data/gov_auditoria_orgao_data.xml",
        "data/gov_auditoria_checklist_tmpl.xml",
        "views/gov_auditoria_ciclo_views.xml",
        "views/gov_auditoria_support_views.xml",
        "views/gov_auditoria_orgao_views.xml",
        "wizard/gov_auditoria_espelho_import_views.xml",
        "wizard/gov_auditoria_operational_views.xml",
        "views/gov_auditoria_menus.xml",
    ],
    "installable": True,
    "application": False,
    "auto_install": False,
}
