{
    "name": "Purchase Stock",
    "version": "1.6",
    "category": "Supply Chain/Purchase",
    "sequence": 60,
    "summary": "Purchase Orders, Receipts, Vendor Bills for Stock",
    "author": "Odoo S.A.",
    "license": "LGPL-3",
    "depends": [
        "stock_account",
        "purchase",
        "base_order_stock",
    ],
    "data": [
        "security/ir.access.csv",
        "reports/purchase_receipt_line_match_views.xml",
        "data/purchase_stock_data.xml",
        "data/mail_templates.xml",
        "reports/vendor_delay_report.xml",
        "views/purchase_order_views.xml",
        "views/purchase_order_line_views.xml",
        "views/stock_move_views.xml",
        "views/stock_warehouse_views.xml",
        "views/stock_warehouse_orderpoint_views.xml",
        "views/stock_picking_views.xml",
        "views/stock_rule_views.xml",
        "views/res_partner_views.xml",
        "views/stock_lot_views.xml",
        "views/stock_orderpoint_views.xml",
        "views/stock_reference_views.xml",
        "views/product_product_views.xml",
        "reports/purchase_report_views.xml",
        "reports/purchase_report_templates.xml",
        "reports/report_stock_rule.xml",
        "wizards/res_config_settings_views.xml",
        "wizards/stock_replenishment_info.xml",
        "wizards/product_replenish_views.xml",
    ],
    "demo": [
        "demo/purchase_stock_demo.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "purchase_stock/static/src/**/*",
        ],
        "web.assets_tests": [
            "purchase_stock/static/tests/tours/**/*",
        ],
        "web.assets_unit_tests": [
            "purchase_stock/static/tests/*.test.js",
        ],
    },
    "auto_install": [
        "purchase",
        "stock_account",
    ],
    "post_init_hook": "_create_buy_rules",
}
