#!/bin/bash
# run tooling only on branches that start with master to avoid linting noise in stable
if [[ $(git branch --show-current) == master* || $(git branch --show-current) == 16.0* ]]; then
    tooling_dir=$(cd -- "$(dirname "$0")" &> /dev/null && cd .. && pwd)
    if ! cmp -s -- "$tooling_dir/_package.json" package.json; then
        echo "Your package.json is out of date, reloading the tooling using the reload script"
        "$tooling_dir/reload.sh"
    elif
        ! cmp -s -- "$tooling_dir/_eslintignore" .eslintignore ||
        ! cmp -s -- "$tooling_dir/_prettierignore" .prettierignore ||
        ! cmp -s -- "$tooling_dir/_eslintrc.json" .eslintrc.json ||
        ! cmp -s -- "$tooling_dir/_prettierrc.json" .prettierrc.json
    then
        echo "Some of your eslint/prettier config files are out of date, refreshing them using the refresh script"
        "$tooling_dir/refresh.sh"
    fi
    npm run format-staged
fi
