#!/bin/bash
tooling_dir=$(cd -- "$(dirname "$0")" &> /dev/null && cd .. && pwd)
if ! cmp -s -- "$tooling_dir/_package.json" package.json; then
    echo "Your package.json is out of date, reloading the tooling using the reload script"
    "$tooling_dir/reload.sh"
elif ! cmp -s -- "$tooling_dir/_eslint.config.mjs" eslint.config.mjs; then
    echo "Your eslint config is out of date, refreshing using the refresh script"
    "$tooling_dir/refresh.sh"
fi
npm run format-staged
