upstream netdata_http { server netdata:19999; }

server {
    listen 80;
    server_name netdataclub26.rkposinc.com;

    proxy_set_header X-Forwarded-Proto https;

    location / {
        proxy_pass          http://netdata_http;
        proxy_set_header    Host              $host;
        proxy_set_header    X-Real-IP         $remote_addr;
        proxy_set_header    X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_read_timeout  60s;
    }
}
