{
    "name": "Spreadsheet",
    "version": "1.0",
    "category": "Productivity/Dashboard",
    "summary": "Spreadsheet",
    "description": "Spreadsheet",
    "author": "Odoo S.A.",
    "license": "LGPL-3",
    "depends": [
        "portal",
    ],
    "data": [
        "views/public_readonly_spreadsheet_templates.xml",
    ],
    "assets": {
        "spreadsheet.o_spreadsheet": [
            "spreadsheet/static/src/o_spreadsheet/chartjs_setup.js",
            "spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js",
            "spreadsheet/static/src/**/*.js",
            "spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml",
            "spreadsheet/static/src/**/*.xml",
            (
                "remove",
                "spreadsheet/static/src/assets_backend/**/*",
            ),
            (
                "remove",
                "spreadsheet/static/src/public_readonly_app/**/*",
            ),
        ],
        "spreadsheet.assets_print": [
            "spreadsheet/static/src/print_assets/**/*",
        ],
        "spreadsheet.public_spreadsheet": [
            (
                "include",
                "web.assets_frontend_minimal",
            ),
            (
                "include",
                "web._assets_helpers",
            ),
            "web/static/src/scss/bootstrap_overridden.scss",
            "web/static/src/scss/pre_variables.scss",
            "web/static/lib/bootstrap/scss/_variables.scss",
            "web/static/lib/bootstrap/scss/_variables-dark.scss",
            "web/static/lib/bootstrap/scss/_maps.scss",
            (
                "include",
                "web._assets_bootstrap",
            ),
            "web/static/src/libs/bootstrap.js",
            "web/static/src/libs/fontawesome7/css/fontawesome.css",
            "web/static/src/libs/fontawesome7/css/solid.css",
            "web/static/src/libs/fontawesome7/css/regular.css",
            "web/static/src/libs/fontawesome7/css/brands.css",
            "web/static/src/core/utils/**/*.js",
            "web/static/src/core/browser/browser.js",
            "web/static/src/core/browser/feature_detection.js",
            "web/static/src/core/registry.js",
            "web/static/src/core/assets.js",
            "web/static/src/core/templates.js",
            "web/static/src/core/template_inheritance.js",
            "web/static/src/session.js",
            "web/static/src/env.js",
            "web/static/src/ui/**/*",
            (
                "remove",
                "web/static/src/ui/commands/**/*",
            ),
            (
                "remove",
                "web/static/src/ui/commands.js",
            ),
            "web/static/src/core/**/*.js",
            "spreadsheet/static/src/o_spreadsheet/chartjs_setup.js",
            "spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js",
            "spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml",
            "spreadsheet/static/src/o_spreadsheet/o_spreadsheet_variables.scss",
            "spreadsheet/static/src/o_spreadsheet/o_spreadsheet.scss",
            "spreadsheet/static/src/o_spreadsheet/icons.xml",
            "spreadsheet/static/src/o_spreadsheet/o_spreadsheet_extended.scss",
            "spreadsheet/static/src/o_spreadsheet/migration.js",
            "spreadsheet/static/src/helpers/odoo_functions_helpers.js",
            "spreadsheet/static/src/pivot/pivot_helpers.js",
            "spreadsheet/static/src/helpers/helpers.js",
            "spreadsheet/static/src/public_readonly_app/**/*.xml",
            "spreadsheet/static/src/public_readonly_app/**/*.scss",
            "spreadsheet/static/src/public_readonly_app/**/*",
            "spreadsheet/static/src/hooks.js",
            "spreadsheet/static/src/plugins.js",
        ],
        "web.assets_backend": [
            "spreadsheet/static/src/o_spreadsheet/o_spreadsheet_variables.scss",
            "spreadsheet/static/src/**/*.scss",
            "spreadsheet/static/src/assets_backend/**/*",
            (
                "remove",
                "spreadsheet/static/src/public_readonly_app/**/*.scss",
            ),
            (
                "remove",
                "spreadsheet/static/src/print_assets/**/*",
            ),
        ],
        "web.assets_web_dark": [],
        "web.assets_unit_tests": [
            "spreadsheet/static/tests/**/*",
            (
                "include",
                "spreadsheet.o_spreadsheet",
            ),
            "spreadsheet/static/src/public_readonly_app/**/*.xml",
            "spreadsheet/static/src/public_readonly_app/**/*.js",
            (
                "remove",
                "spreadsheet/static/src/public_readonly_app/main.js",
            ),
        ],
    },
    "esm": {
        "bundles": [
            "spreadsheet.assets_print",
            "spreadsheet.o_spreadsheet",
            "spreadsheet.public_spreadsheet",
        ],
        "external_libs": {
            "chartjs-chart-geo": "/spreadsheet/static/lib/chartjs-chart-geo/chartjs-chart-geo.js",
            "chartjs-chart-treemap": "/spreadsheet/static/lib/chart_js_treemap.js",
        },
        "dynamic_children": {
            "web.assets_web": [
                "spreadsheet.o_spreadsheet",
                "spreadsheet.assets_print",
            ],
        },
    },
}
