from . import ga_ciclo_academico
from . import ga_gestion
from . import ga_grado
from . import ga_materia
from . import ga_nivel
from . import ga_plan_estudio
from . import ga_unidad_educativa
from . import ga_profesor
from . import ga_aula
from . import ga_chofer
from . import ga_paralelo
from . import ga_paralelo_profesor
from . import ga_ruta
from . import ga_actividad_academica
from . import ga_alumno
from . import ga_apoderado
from . import ga_registro_academico
from . import ga_ruta_chofer
from . import ga_inscripcion_alumno
