{
    'name': 'Woocommerce Integration',
    'version': '16.0',
    'website': 'www.inkerp.com',
    'category': 'website',
    'author': 'INKERP',
    'summary': 'API integration Woocommerce to Odoo Pro Version',
    'description': """
        - This app create api and Integration with Odoo to Woocommerce Pro Version.
    """,
    'depends': ["eg_ecommerce_base", "sale_management"],
    'data': [
        'security/ir.model.access.csv',
        'wizards/import_from_ecom_provider_view.xml',
        'views/eg_product_product_view.xml',
        'views/eg_product_template_view.xml',
        'views/eg_sale_order_view.xml',
        'views/eg_account_journal_view.xml',
        'views/eg_attribute_value_view.xml',
        'views/eg_ecom_instance_view.xml',
        'views/eg_product_attribute.xml',
        'views/eg_product_category_view.xml',
        'views/eg_res_partner_view.xml',
        'views/res_config_settings_view.xml',
        'views/woo_product_coupon_view.xml',
        'views/woo_tax_class_view.xml',
        'views/woo_tax_rate_view.xml',
        'data/import_sale_order_cron.xml',
        'wizards/product_template_instance.xml',
        'wizards/sale_order_wizard_view.xml',
        'views/sale_order_view.xml',
    ],
    'images': ['static/description/banner.png'],
    'license': "OPL-1",
    'installable': True,
    'application': True,
    'auto_install': False,
}
