{
    "name": "Synconics BI Dashboard",
    "summary": """Build powerful dashboard charts that transform complex data into clear, actionable insights.
""",
    "description": """
Synconics BI Dashboard empowers you to create dynamic and interactive dashboards
    """,
    "author": "Synconics Technologies Pvt. Ltd.",
    "website": "https://www.synconics.com",
    "category": "web",
    "version": "1.0.3",
    "depends": ["web", "mail"],
    "assets": {
        "web.assets_backend": [
            "synconics_bi_dashboard/static/src/lib/html2canvas.js",
            "synconics_bi_dashboard/static/src/lib/jspdf.js",
            "synconics_bi_dashboard/static/src/lib/amcharts/index.js",
            "synconics_bi_dashboard/static/src/lib/amcharts/xy.js",
            "synconics_bi_dashboard/static/src/lib/amcharts/exporting.js",
            "synconics_bi_dashboard/static/src/lib/amcharts/map.js",
            "synconics_bi_dashboard/static/src/lib/amcharts/worldLow.js",
            "synconics_bi_dashboard/static/src/lib/amcharts/radar.js",
            "synconics_bi_dashboard/static/src/lib/amcharts/flow.js",
            "synconics_bi_dashboard/static/src/lib/amcharts/percent.js",
            "synconics_bi_dashboard/static/src/lib/amcharts/hierarchy.js",
            "synconics_bi_dashboard/static/src/lib/themes/**/*",
            "synconics_bi_dashboard/static/src/lib/gridstack/**/*",
            "synconics_bi_dashboard/static/src/js/dashboard_form_view.js",
            "synconics_bi_dashboard/static/src/scss/dashboard_form_view.scss",
            "synconics_bi_dashboard/static/src/js/form_dashboard_preview.js",
            "synconics_bi_dashboard/static/src/xml/form_dashboard_preview.xml",
            "synconics_bi_dashboard/static/src/js/fa_icon_widget.js",
            "synconics_bi_dashboard/static/src/xml/fa_icon_widget.xml",
            "synconics_bi_dashboard/static/src/js/dashboard_chart_wrapper.js",
            "synconics_bi_dashboard/static/src/scss/dashboard_chart_wrapper.scss",
            "synconics_bi_dashboard/static/src/xml/dashboard_chart_wrapper.xml",
            "synconics_bi_dashboard/static/src/js/dashboard_amcharts.js",
            "synconics_bi_dashboard/static/src/xml/dashboard_amcharts.xml",
            "synconics_bi_dashboard/static/src/js/dashboard_selection/*",
            "synconics_bi_dashboard/static/src/components/**/*",
            "synconics_bi_dashboard/static/src/components/KPILayouts/**/*",
            "synconics_bi_dashboard/static/src/components/TileLayouts/**/*",
        ]
    },
    "cloc_exclude": [
        "static/src/lib/**/*",
    ],
    "data": [
        "security/dashboard_security.xml",
        "security/ir.model.access.csv",
        "data/mail_template.xml",
        "views/ir_ui_menu_views.xml",
        "wizard/dashboard_access_view.xml",
        "wizard/mail_compose_message_views.xml",
        "views/dashboard_view.xml",
        "data/dashboard_data.xml",
        "views/dashboard_chart_view.xml",
        "views/res_users_view.xml",
    ],
    "images": ["static/description/main_screen.gif"],
    "license": "OPL-1",
    "uninstall_hook": "uninstall_hook",
    "installable": True,
    "application": True,
    "auto_install": False,
}
