from . import hr_attendance
from . import hr_employee
from . import hr_leave
from . import hr_payslip
from . import hr_payslip_run
from . import hr_salary_rule
from . import hr_version
from . import biometric_attendance_sync
from . import res_config_settings
from . import res_partner_bank
