#!/usr/bin/env python3
"""Compile the many small SPA sources into one pasteable Embed Code block.

    python3 build.py                     -> dist/spa.html, dist/dev.html
    python3 build.py --deploy            -> also publish to the database in
                                            build.json, then open the page
    python3 build.py --deploy <database> -> publish to another database instead

Sources are concatenated in filename order (hence the numeric prefixes), lib/
before screens/. See README.md section 4.
"""

import argparse
import json
import os
import subprocess
import sys
import webbrowser

HERE = os.path.dirname(os.path.abspath(__file__))
DIST = os.path.join(HERE, 'dist')

# A page is stored as XML, where a bare "&" or "<" inside <script>/<style> is a
# parse error. Data files are escaped when inlined, so this only applies to
# hand-written code. See README.md section 3.6.
FORBIDDEN = ('&', '<')


def read_dir(name, suffix):
    """Return [(filename, contents)] for one source directory, in name order."""
    path = os.path.join(HERE, name)
    if not os.path.isdir(path):
        return []
    out = []
    for filename in sorted(os.listdir(path)):
        if filename.startswith('.') or not filename.endswith(suffix):
            continue
        with open(os.path.join(path, filename), encoding='utf-8') as fh:
            out.append((filename, fh.read()))
    return out


def check_xml_safe(files, kind):
    """Refuse to emit code that would break the view's XML."""
    problems = []
    for filename, content in files:
        for lineno, line in enumerate(content.splitlines(), start=1):
            for char in FORBIDDEN:
                if char in line:
                    problems.append('  %s/%s:%d  contains %r\n    %s'
                                    % (kind, filename, lineno, char, line.strip()))
    if problems:
        sys.exit("Build failed: XML-unsafe characters in hand-written %s.\n"
                 "A bare '&' or '<' inside <script>/<style> breaks the page's XML.\n"
                 "Use nested ifs instead of '&&', and flip '<' comparisons around.\n\n%s"
                 % (kind, '\n'.join(problems)))


def load_data():
    """Every data/*.json file, keyed by filename without extension."""
    data = {}
    for filename, content in read_dir('data', '.json'):
        key = filename[:-len('.json')]
        try:
            data[key] = json.loads(content)
        except ValueError as err:
            sys.exit("Build failed: data/%s is not valid JSON.\n  %s" % (filename, err))
    return data


def encode_data(data):
    """Inline the data as a JS object literal that is safe inside XML.

    The escapes are valid JSON and valid JS, so content is free to use any
    character even though the surrounding code cannot.
    """
    return (json.dumps(data, indent=4, sort_keys=True, ensure_ascii=False)
            .replace('&', '\\u0026')
            .replace('<', '\\u003c'))


def build_script(libs, screens, data, dev):
    parts = ['(function () {', '"use strict";', '']
    for filename, content in libs + screens:
        parts.append('/* ===== %s ===== */' % filename)
        parts.append(content.strip())
        parts.append('')
    parts.append('/* ===== injected by build.py ===== */')
    parts.append('JM.data = %s;' % encode_data(data))
    if dev:
        parts.append('JM.data.config.mock = true;')
        parts.append('window.JM = JM;  /* dev build only, for console poking */')
    parts.append('JM.boot();')
    parts.append('})();')
    return '\n'.join(parts)


# A double hyphen is illegal inside an XML comment, so this banner must not use
# one -- the view would refuse to parse. Arrows are single hyphens on purpose.
HEADER = """<!-- =============================================================
     GENERATED by SPA/build.py. Do not edit this file.
     Edit the sources in SPA/{lib,screens,styles,data} and rebuild.

     DEPLOY
       Website -> Edit -> drag the "Embed Code" snippet onto a page
       -> Edit Code -> paste all of this -> Save -> Publish.
       The app is inert in edit mode; test on the published page.

     ONE-TIME DB CONFIG (developer mode on, no code needed)
       1. Settings > Technical > Models > %(model)s
          -> "Website Forms" tab -> tick "Allowed to use in forms"
       2. On that model's fields, untick "Blacklisted in web forms" for:
          %(fields)s
       Skipping step 2 still creates the record, but the values land in the
       chatter instead of the fields.
     ============================================================= -->
"""


def compose(markup, css, script, header):
    return '%s\n%s\n<style>\n%s\n</style>\n\n<script>\n%s\n</script>\n' % (
        header, markup, css, script)


DEV_PAGE = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<title>%(title)s -- dev preview</title>
<style>
body { margin: 0; font-family: system-ui, sans-serif; color: #111;
       background: #fff; padding: 2rem 1rem; }
.jm_dev_banner { max-width: 34rem; margin: 0 auto 1.5rem; padding: .5rem .75rem;
       border-radius: .375rem; background: #fff3cd; color: #664d03;
       font-size: .8125rem; text-align: center; }
</style>
</head>
<body>
<div class="jm_dev_banner">
    Dev preview -- nothing is saved. Built from SPA sources; submitting returns a
    fake record id.
</div>
%(markup)s
<style>
%(css)s
</style>
<script>
%(script)s
</script>
</body>
</html>
"""

# Rebuilt wholesale on every deploy: the page is build output, not something to
# edit in the builder. Mirrors the arch that website.new_page produces.
DEPLOY = r'''
import json
SECTION = json.loads(%(section)s)
URL = %(url)s
NAME = %(name)s
HIDE_HEADER = %(hide_header)s
HIDE_FOOTER = %(hide_footer)s

section = ('<section class="s_embed_code text-center pt16 pb16">'
           '<template class="s_embed_code_saved">' + SECTION + '</template>'
           '<div class="s_embed_code_embedded container o_not_editable">' + SECTION + '</div>'
           '</section>')

website = env['website'].search([], limit=1)
page = env['website.page'].search([('url', '=', URL)], limit=1)
if page:
    view = page.view_id
    view.arch = ('<t t-name="%%s">\n    <t t-call="website.layout">\n'
                 '        <div id="wrap" class="oe_structure oe_empty">%%s</div>\n'
                 '    </t>\n</t>' %% (view.key, section))
    action = 'updated'
else:
    res = env['website'].with_context(website_id=website.id).new_page(
        name=NAME, sections_arch=section, page_values={'is_published': True})
    page = env['website.page'].search([('url', '=', res['url'])], limit=1)
    action = 'created'

page.write({
    'is_published': True,
    'header_visible': not HIDE_HEADER,
    'footer_visible': not HIDE_FOOTER,
})
env.cr.commit()
print('DEPLOYED %%s %%s' %% (action, page.url))
'''


def deploy(database, payload, settings):
    script = DEPLOY % {
        'section': json.dumps(json.dumps(payload)),
        'url': json.dumps(settings['page_url']),
        'name': json.dumps(settings['page_name']),
        'hide_header': settings.get('hide_header', True),
        'hide_footer': settings.get('hide_footer', True),
    }
    cmd = [
        settings['python'], settings['odoo_bin'], 'shell',
        '-d', database,
        '--addons-path=%s' % settings['addons_path'],
        '--no-http', '--log-level=warn',
    ]
    print('Deploying to %s ...' % database)
    done = subprocess.run(cmd, input=script, capture_output=True, text=True)
    for line in done.stdout.splitlines():
        if line.startswith('DEPLOYED'):
            print('  %s' % line)
            return
    sys.exit('Deploy failed.\n%s\n%s' % (done.stdout[-2000:], done.stderr[-2000:]))


def page_url(settings):
    return settings['base_url'].rstrip('/') + settings['page_url']


def open_page(settings):
    """Show the freshly deployed page. Harmless when there is no browser."""
    url = page_url(settings)
    print('  opening %s' % url)
    try:
        if not webbrowser.open(url):
            print('  (no browser available -- open it yourself)')
    except Exception as err:
        print('  (could not open a browser: %s)' % err)


def main():
    with open(os.path.join(HERE, 'build.json'), encoding='utf-8') as fh:
        settings = json.load(fh)

    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument('--deploy', nargs='?', const=settings['database'],
                        metavar='DATABASE',
                        help='publish the built page, then open it. Defaults to '
                             'the database in build.json (%s).' % settings['database'])
    args = parser.parse_args()

    libs = read_dir('lib', '.js')
    screen_js = read_dir('screens', '.js')
    screen_html = read_dir('screens', '.html')
    css = read_dir('styles', '.css')
    data = load_data()

    check_xml_safe(libs + screen_js, 'js')
    check_xml_safe(css, 'css')

    if not libs:
        sys.exit('Build failed: no lib/*.js found.')
    if not screen_html:
        sys.exit('Build failed: no screens/*.html found.')

    config = data.get('config', {})
    markup = '<div id="jm_app">\n%s\n</div>' % '\n'.join(
        content.strip() for _name, content in screen_html)
    stylesheet = '\n'.join(content.strip() for _name, content in css)

    header = HEADER % {
        'model': config.get('model', '?'),
        'fields': ', '.join(sorted(filter(None, [
            config.get('name_field'), config.get('note_field')]))) or '?',
    }

    os.makedirs(DIST, exist_ok=True)
    payload = compose(markup, stylesheet,
                      build_script(libs, screen_js, data, dev=False), header)
    with open(os.path.join(DIST, 'spa.html'), 'w', encoding='utf-8') as fh:
        fh.write(payload)

    preview = DEV_PAGE % {
        'title': config.get('title', 'SPA'),
        'markup': markup,
        'css': stylesheet,
        'script': build_script(libs, screen_js, data, dev=True),
    }
    with open(os.path.join(DIST, 'dev.html'), 'w', encoding='utf-8') as fh:
        fh.write(preview)

    sources = len(libs) + len(screen_js) + len(screen_html) + len(css) + len(data)
    print('Built dist/spa.html (%d bytes) and dist/dev.html from %d source files.'
          % (len(payload), sources))
    print('  screens: %s' % ', '.join(name for name, _c in screen_html))
    print('  data:    %s' % ', '.join(sorted(data)))

    if args.deploy:
        deploy(args.deploy, payload, settings)
        open_page(settings)


if __name__ == '__main__':
    main()
