from . import test_action
from . import test_controllers_audit
from . import test_assets
from . import test_base_document_layout
from . import test_click_everywhere
from . import test_color_scheme
from . import test_database_controller
from . import test_db_manager
from . import test_design_system
from . import test_domain
from . import test_esm_pipeline
from . import test_export
from . import test_home_menu_badge
from . import test_json_export
from . import test_favorite
from . import test_feature_flags
from . import test_fontawesome
from . import test_health
from . import test_image
from . import test_ir_asset_scope
from . import test_ir_actions_report_audit
from . import test_ir_exports
from . import test_ir_model
from . import test_ir_qweb
from . import test_ir_qweb_fields
from . import test_ir_ui_view
from . import test_js
from . import test_js_addons
from . import test_js_error_taxonomy
from . import test_load_menus
from . import test_login
from . import test_module_layering
from . import test_onchange
from . import test_partner
from . import test_pdfjs_dist
from . import test_perf_load_menu
from . import test_pivot_export
from . import test_profiler
from . import test_promote_studio
from . import test_report_theme
from . import test_report_introspection
from . import test_report_layout_audit
from . import test_report_modernization
from . import test_report_rendering
from . import test_reports
from . import test_res_partner_properties
from . import test_res_users
from . import test_res_users_settings
from . import test_router
from . import test_scss_design_system
from . import test_search_panel_version
from . import test_session_info
from . import test_translate
from . import test_typed_services_consistency
from . import test_web_redirect
from . import test_web_benchmark
from . import test_web_bundle_size
from . import test_web_cwv_metric
from . import test_web_js_error
from . import test_web_perf_regression
from . import test_web_read
from . import test_web_read_group
from . import test_web_save
from . import test_web_search_read
from . import test_webmanifest
from . import test_res_config_settings
from . import test_res_config_doc_links
from . import test_trace_probes
