from . import hr_department
from . import hr_applicant
from . import hr_applicant_category
from . import hr_applicant_refuse_reason
from . import hr_recruitment_degree
from . import hr_recruitment_source
from . import hr_recruitment_stage
from . import hr_employee
from . import hr_job
from . import res_config_settings
from . import calendar
from . import digest
from . import utm_campaign
from . import utm_source
from . import res_users
from . import ir_ui_menu
