from .test_assetsbundle import (
    test_assetsbundle,
    test_js_transpiler,
    test_js_transpiler_regex,
)

# from .test_core import (
#     test_cli,
#     test_core_init,
#     test_monkeypatch_lxml,
#     test_monkeypatch_num2words,
#     test_monkeypatch_zoneinfo,
# )
#
# from .test_modules import (
#     test_loading,
#     test_manifest,
#     test_module_graph,
#     test_neutralize,
# )
#
# from .test_orm import (
#     common,
#     test_access,
#     test_access_feedback,
#     test_access_monetary_related,
#     test_acl,
#     test_action_bindings,
#     test_all_models,
#     test_autovacuum,
#     test_cache,
#     test_check_access,
#     test_company_checks,
#     test_config_settings,
#     test_copy,
#     test_create,
#     test_domain,
#     test_domain_expression,
#     test_fields,
#     test_index_method,
#     test_indexed_translation,
#     test_inherits,
#     test_ir_qweb_fields,
#     test_ir_rules,
#     test_json_field,
#     test_many2many,
#     test_models,
#     test_modules_db,
#     test_one2many,
#     test_parent_store,
#     test_performance,
#     test_prefetch,
#     test_properties,
#     test_query,
#     test_read_group_override,
#     test_read_group_private,
#     test_read_grouping_sets,
#     test_registry,
#     test_registry_signaling,
#     test_schema,
#     test_search,
#     test_search_order,
#     test_sort,
#     test_timeit,
#     test_transactions,
#     # test_uninstall  # Cannot be handled by the runbot. Makes Odoo loop forever when done during an installation.
#     test_views,
# )
#
# from .test_tools import (
#     test_barcode,
#     test_binary,
#     test_cloc,
#     test_config,
#     test_convert,
#     test_date_utils,
#     test_float_utils,
#     test_func,
#     test_i18n,
#     test_image,
#     test_intervals,
#     test_mail,
#     test_mimetypes,
#     test_misc,
#     test_pdf,
#     test_profiler,
#     test_safe_eval,
#     test_safe_eval_expr,
#     test_set_expression,
#     test_sql,
#     test_translate,
#     test_xml_utils,
# )
