from . import common
from . import test_access
from . import test_access_feedback
from . import test_access_monetary_related
from . import test_action_bindings
from . import test_all_models
from . import test_autovacuum
from . import test_cache
from . import test_check_access
from . import test_company_checks
from . import test_config_settings
from . import test_create
from . import test_index_method
from . import test_indexed_translation
from . import test_inherits
from . import test_ir_qweb_fields
from . import test_ir_rules
from . import test_json_field
from . import test_many2many
from . import test_modules_db
from . import test_one2many
from . import test_parent_store
from . import test_performance
