from . import hr_employee_inherit
from . import res_users
from . import website_publication 
from . import publication_interaction
from . import website_gallery
from . import publication_view_log
from . import res_company
from . import news_article
from . import hr_leave
