{
    "name": "Gelato",
    "version": "1.2",
    "category": "Sales/Sales",
    "summary": "Place orders through Gelato's print-on-demand service",
    "author": "Odoo S.A.",
    "license": "LGPL-3",
    "depends": [
        "credential",
        "document",
        "integration",
        "sale",
        "delivery",
    ],
    "data": [
        "data/product_data.xml",
        "data/delivery_carrier_data.xml",
        "data/mail_template_data.xml",
        "views/delivery_carrier_views.xml",
        "views/product_document_views.xml",
        "views/product_product_views.xml",
        "views/product_template_views.xml",
        "wizards/res_config_settings_views.xml",
    ],
}
