{
    'name': 'Invoice Agent',
    'version': '19.0.0.3.0',
    'category': 'Accounting/Accounting',
    'summary': 'AI Extraction capabilities for account.move — queue views, vendor matching, journal config, bulk re-extraction wizard, security groups',
    'depends': ['account', 'sale'],
    'data': [
        'security/invoice_agent_groups.xml',
        'security/ir.model.access.csv',
        'security/invoice_agent_rules.xml',
        'views/account_move_views.xml',
        'views/res_partner_views.xml',
        'views/account_journal_views.xml',
        'views/invoice_agent_views.xml',
        'wizard/bulk_process_wizard_views.xml',
    ],
    'installable': True,
    'application': False,
    'license': 'LGPL-3',
}
