{
    "name": "Base",
    "version": "1.84",
    "category": "Hidden",
    "description": """
The kernel of Odoo, needed for all installation.
===================================================
""",
    "author": "Odoo S.A.",
    "license": "LGPL-3",
    "data": [
        "data/res_bank.xml",
        "data/res.lang.csv",
        "data/res_lang_data.xml",
        "data/res_partner_data.xml",
        "data/res_currency_data.xml",
        "data/res_company_data.xml",
        "data/res_users_data.xml",
        "data/report_paperformat_data.xml",
        "data/res_country_data.xml",
        "data/ir_demo_data.xml",
        "security/base_groups.xml",
        "security/base_security.xml",
        "wizards/wizard_ir_model_menu_create_views.xml",
        "views/decimal_precision_views.xml",
        "data/res.country.state.csv",
        "views/ir_actions_views.xml",
        "views/ir_asset_views.xml",
        "views/ir_config_parameter_views.xml",
        "views/ir_cron_views.xml",
        "views/ir_cron_trigger_views.xml",
        "views/ir_job_views.xml",
        "views/ir_filters_views.xml",
        "views/ir_model_views.xml",
        "views/ir_attachment_views.xml",
        "views/ir_rule_views.xml",
        "views/ir_sequence_views.xml",
        "views/ir_ui_menu_views.xml",
        "views/ir_ui_view_views.xml",
        "views/ir_default_views.xml",
        "data/ir_config_parameter_data.xml",
        "data/res_config_settings_data.xml",
        "data/ir_cron_data.xml",
        "views/ir_logging_views.xml",
        "views/ir_qweb_widget_templates.xml",
        "views/ir_module_views.xml",
        "data/ir_module_category_data.xml",
        "data/ir_module_module.xml",
        "wizards/base_module_update_views.xml",
        "wizards/base_language_install_views.xml",
        "wizards/base_import_language_views.xml",
        "wizards/base_module_upgrade_views.xml",
        "wizards/base_module_uninstall_views.xml",
        "wizards/base_export_language_views.xml",
        "wizards/base_partner_merge_views.xml",
        "data/ir_demo_failure_data.xml",
        "views/ir_profile_views.xml",
        "views/res_company_views.xml",
        "views/res_lang_views.xml",
        "views/res_partner_tag_views.xml",
        "views/res_partner_industry_views.xml",
        "views/res_partner_identifier_views.xml",
        "views/res_partner_views.xml",
        "views/res_bank_views.xml",
        "views/res_country_views.xml",
        "views/res_currency_views.xml",
        "views/res_groups_views.xml",
        "views/res_users_views.xml",
        "views/res_users_apikeys_views.xml",
        "views/res_device_views.xml",
        "views/res_users_identitycheck_views.xml",
        "views/res_config_settings_views.xml",
        "views/report_paperformat_views.xml",
        "views/tag_tag_views.xml",
        "views/base_menus.xml",
        "security/ir.model.access.csv",
    ],
    "demo": [
        "demo/res_users_demo.xml",
        "demo/res_partner_bank_demo.xml",
        "demo/res_currency_demo.xml",
        "demo/res_currency_rate_demo.xml",
        "demo/res_bank_demo.xml",
        "demo/res_partner_demo.xml",
        "demo/res_partner_image_demo.xml",
    ],
    "assets": {
        "web.assets_tests": [
            "base/static/tests/**/*",
        ],
    },
    "auto_install": True,
    "post_init_hook": "post_init",
}
