{
	"name":"Service company profile",
	"version":"1.0",
	"author":"Tiny",
	"category":"Profile",
	"depends":[
		"hr", 
		"hr_timesheet", 
		"hr_timesheet_invoice", 
		"hr_timesheet_project", 
		"crm", 
		"project"], 
	#"board_project", 
	#"board_account"],
	"demo_xml":[],
	"update_xml":[],
	"active":False,
	"installable":True,
}
