from odoo import fields, models

ALLOWANCE_REASON_CODES = [
    ('41', "41 - Bonus for works ahead of schedule"),
    ('42', "42 - Other bonus"),
    ('60', "60 - Manufacturer’s consumer discount"),
    ('62', "62 - Due to military status"),
    ('63', "63 - Due to work accident"),
    ('64', "64 - Special agreement"),
    ('65', "65 - Production error discount"),
    ('66', "66 - New outlet discount"),
    ('67', "67 - Sample discount"),
    ('68', "68 - End-of-range discount"),
    ('70', "70 - Incoterm discount"),
    ('71', "71 - Point of sales threshold allowance"),
    ('88', "88 - Material surcharge/deduction"),
    ('95', "95 - Discount"),
    ('100', "100 - Special rebate"),
    ('102', "102 - Fixed long term"),
    ('103', "103 - Temporary"),
    ('104', "104 - Standard"),
    ('105', "105 - Yearly turnover"),
]

CHARGE_REASON_CODES = [
    ('AA', "AA - Advertising"),
    ('AAA', "AAA - Telecommunication"),
    ('AAC', "AAC - Technical modification"),
    ('AAD', "AAD - Job-order production"),
    ('AAE', "AAE - Outlays"),
    ('AAF', "AAF - Off-premises"),
    ('AAH', "AAH - Additional processing"),
    ('AAI', "AAI - Attesting"),
    ('AAS', "AAS - Acceptance"),
    ('AAT', "AAT - Rush delivery"),
    ('AAV', "AAV - Special construction"),
    ('AAY', "AAY - Airport facilities"),
    ('AAZ', "AAZ - Concession"),
    ('ABA', "ABA - Compulsory storage"),
    ('ABB', "ABB - Fuel removal"),
    ('ABC', "ABC - Into plane"),
    ('ABD', "ABD - Overtime"),
    ('ABF', "ABF - Tooling"),
    ('ABK', "ABK - Miscellaneous"),
    ('ABL', "ABL - Additional packaging"),
    ('ABN', "ABN - Dunnage"),
    ('ABR', "ABR - Containerisation"),
    ('ABS', "ABS - Carton packing"),
    ('ABT', "ABT - Hessian wrapped"),
    ('ABU', "ABU - Polyethylene wrap packing"),
    ('ACF', "ACF - Miscellaneous treatment"),
    ('ACG', "ACG - Enamelling treatment"),
    ('ACH', "ACH - Heat treatment"),
    ('ACI', "ACI - Plating treatment"),
    ('ACJ', "ACJ - Painting"),
    ('ACK', "ACK - Polishing"),
    ('ACL', "ACL - Priming"),
    ('ACM', "ACM - Preservation treatment"),
    ('ACS', "ACS - Fitting"),
    ('ADC', "ADC - Consolidation"),
    ('ADE', "ADE - Bill of lading"),
    ('ADJ', "ADJ - Airbag"),
    ('ADK', "ADK - Transfer"),
    ('ADL', "ADL - Slipsheet"),
    ('ADM', "ADM - Binding"),
    ('ADN', "ADN - Repair or replacement of broken returnable package"),
    ('ADO', "ADO - Efficient logistics"),
    ('ADP', "ADP - Merchandising"),
    ('ADQ', "ADQ - Product mix"),
    ('ADR', "ADR - Other services"),
    ('ADT', "ADT - Pick-up"),
    ('ADW', "ADW - Chronic illness"),
    ('ADY', "ADY - New product introduction"),
    ('ADZ', "ADZ - Direct delivery"),
    ('AEA', "AEA - Diversion"),
    ('AEB', "AEB - Disconnect"),
    ('AEC', "AEC - Distribution"),
    ('AED', "AED - Handling of hazardous cargo"),
    ('AEF', "AEF - Rents and leases"),
    ('AEH', "AEH - Location differential"),
    ('AEI', "AEI - Aircraft refueling"),
    ('AEJ', "AEJ - Fuel shipped into storage"),
    ('AEK', "AEK - Cash on delivery"),
    ('AEL', "AEL - Small order processing service"),
    ('AEM', "AEM - Clerical or administrative services"),
    ('AEN', "AEN - Guarantee"),
    ('AEO', "AEO - Collection and recycling"),
    ('AEP', "AEP - Copyright fee collection"),
    ('AES', "AES - Veterinary inspection service"),
    ('AET', "AET - Pensioner service"),
    ('AEU', "AEU - Medicine free pass holder"),
    ('AEV', "AEV - Environmental protection service"),
    ('AEW', "AEW - Environmental clean-up service"),
    ('AEX', "AEX - National cheque processing service outside account area"),
    ('AEY', "AEY - National payment service outside account area"),
    ('AEZ', "AEZ - National payment service within account area"),
    ('AJ', "AJ - Adjustments"),
    ('AU', "AU - Authentication"),
    ('CA', "CA - Cataloguing"),
    ('CAB', "CAB - Cartage"),
    ('CAD', "CAD - Certification"),
    ('CAE', "CAE - Certificate of conformance"),
    ('CAF', "CAF - Certificate of origin"),
    ('CAI', "CAI - Cutting"),
    ('CAJ', "CAJ - Consular service"),
    ('CAK', "CAK - Customer collection"),
    ('CAL', "CAL - Payroll payment service"),
    ('CAM', "CAM - Cash transportation"),
    ('CAN', "CAN - Home banking service"),
    ('CAO', "CAO - Bilateral agreement service"),
    ('CAP', "CAP - Insurance brokerage service"),
    ('CAQ', "CAQ - Cheque generation"),
    ('CAR', "CAR - Preferential merchandising location"),
    ('CAS', "CAS - Crane"),
    ('CAT', "CAT - Special colour service"),
    ('CAU', "CAU - Sorting"),
    ('CAV', "CAV - Battery collection and recycling"),
    ('CAW', "CAW - Product take back fee"),
    ('CAX', "CAX - Quality control released"),
    ('CAY', "CAY - Quality control held"),
    ('CAZ', "CAZ - Quality control embargo"),
    ('CD', "CD - Car loading"),
    ('CG', "CG - Cleaning"),
    ('CS', "CS - Cigarette stamping"),
    ('CT', "CT - Count and recount"),
    ('DAB', "DAB - Layout/design"),
    ('DAC', "DAC - Assortment allowance"),
    ('DAD', "DAD - Driver assigned unloading"),
    ('DAF', "DAF - Debtor bound"),
    ('DAG', "DAG - Dealer allowance"),
    ('DAH', "DAH - Allowance transferable to the consumer"),
    ('DAI', "DAI - Growth of business"),
    ('DAJ', "DAJ - Introduction allowance"),
    ('DAK', "DAK - Multi-buy promotion"),
    ('DAL', "DAL - Partnership"),
    ('DAM', "DAM - Return handling"),
    ('DAN', "DAN - Minimum order not fulfilled charge"),
    ('DAO', "DAO - Point of sales threshold allowance"),
    ('DAP', "DAP - Wholesaling discount"),
    ('DAQ', "DAQ - Documentary credits transfer commission"),
    ('DL', "DL - Delivery"),
    ('EG', "EG - Engraving"),
    ('EP', "EP - Expediting"),
    ('ER', "ER - Exchange rate guarantee"),
    ('FAA', "FAA - Fabrication"),
    ('FAB', "FAB - Freight equalization"),
    ('FAC', "FAC - Freight extraordinary handling"),
    ('FC', "FC - Freight service"),
    ('FH', "FH - Filling/handling"),
    ('FI', "FI - Financing"),
    ('GAA', "GAA - Grinding"),
    ('HAA', "HAA - Hose"),
    ('HD', "HD - Handling"),
    ('HH', "HH - Hoisting and hauling"),
    ('IAA', "IAA - Installation"),
    ('IAB', "IAB - Installation and warranty"),
    ('ID', "ID - Inside delivery"),
    ('IF', "IF - Inspection"),
    ('IR', "IR - Installation and training"),
    ('IS', "IS - Invoicing"),
    ('KO', "KO - Koshering"),
    ('L1', "L1 - Carrier count"),
    ('LA', "LA - Labelling"),
    ('LAA', "LAA - Labour"),
    ('LAB', "LAB - Repair and return"),
    ('LF', "LF - Legalisation"),
    ('MAE', "MAE - Mounting"),
    ('MI', "MI - Mail invoice"),
    ('ML', "ML - Mail invoice to each location"),
    ('NAA', "NAA - Non-returnable containers"),
    ('OA', "OA - Outside cable connectors"),
    ('PA', "PA - Invoice with shipment"),
    ('PAA', "PAA - Phosphatizing (steel treatment)"),
    ('PC', "PC - Packing"),
    ('PL', "PL - Palletizing"),
    ('PRV', "PRV - Price variation"),
    ('RAB', "RAB - Repacking"),
    ('RAC', "RAC - Repair"),
    ('RAD', "RAD - Returnable container"),
    ('RAF', "RAF - Restocking"),
    ('RE', "RE - Re-delivery"),
    ('RF', "RF - Refurbishing"),
    ('RH', "RH - Rail wagon hire"),
    ('RV', "RV - Loading"),
    ('SA', "SA - Salvaging"),
    ('SAA', "SAA - Shipping and handling"),
    ('SAD', "SAD - Special packaging"),
    ('SAE', "SAE - Stamping"),
    ('SAI', "SAI - Consignee unload"),
    ('SG', "SG - Shrink-wrap"),
    ('SH', "SH - Special handling"),
    ('SM', "SM - Special finish"),
    ('SU', "SU - Set-up"),
    ('TAB', "TAB - Tank renting"),
    ('TAC', "TAC - Testing"),
    ('TT', "TT - Transportation - third party billing"),
    ('TV', "TV - Transportation by vendor"),
    ('V1', "V1 - Drop yard"),
    ('V2', "V2 - Drop dock"),
    ('WH', "WH - Warehousing"),
    ('XAA', "XAA - Combine all same day shipment"),
    ('YY', "YY - Split pick-up"),
    ('ZZZ', "ZZZ - Mutually defined"),
]


class AccountTax(models.Model):
    _inherit = 'account.tax'

    ubl_cii_type = fields.Selection(
        selection=[
            ('tax', "Tax"),
            ('allowance_charge', "Charges or Allowance"),
        ],
        default='tax',
        required=True,
    )
    ubl_cii_allowance_reason_code = fields.Selection(
        string="Allowance Reason Code",
        selection=ALLOWANCE_REASON_CODES,
    )
    ubl_cii_charge_reason_code = fields.Selection(
        string="Charge Reason Code",
        selection=CHARGE_REASON_CODES,
    )
    ubl_cii_allowance_charge_reason = fields.Char()
