from . import test_dunderinit
from . import test_checkers
from . import test_pylint
from . import test_pofile
from . import test_docstring
from . import test_eslint
from . import test_index
from . import test_jstranslate
from . import test_l10n
from . import test_manifests
from . import test_markers
from . import test_naming
from . import test_onchange_domains
from . import test_orm_import
from . import test_override_signatures
from . import test_routes
from . import test_i18n
from . import test_test_holes
