import typing

if typing.TYPE_CHECKING:
    from collections.abc import (
        Callable,
        Collection,
        Iterable,
        Iterator,
        Mapping,
        Reversible,
    )
    from typing import Self

    from odoo.tools import SQL, Query

    from ..._typing import DomainType, IdType, ValuesType
    from ...domain import Domain
    from ...fields.base import Field
    from ...runtime import Environment


class _ModelStubs:
    if typing.TYPE_CHECKING:
        __slots__ = ("_ids", "_prefetch_ids", "env")

        env: typing.Any
        _ids: tuple
        _prefetch_ids: typing.Any
    else:
        __slots__ = ()

    if typing.TYPE_CHECKING:
        pool: typing.Any
        _fields: Mapping[str, Field]
        _name: str
        _table: str
        _transient: bool
        id: int

        @property
        def ids(self) -> list[int]: ...

        display_name: str | typing.Literal[False]
        _log_access: bool
        _active_name: str | None
        _parent_name: str
        _parent_store: bool

        @property
        def _ondelete_methods(self) -> list: ...

        def _as_query(self, ordered: bool = True) -> Query: ...

        _inherits: dict
        _inherits_children: set[str]
        _description: str | None
        _abstract: bool
        _auto: bool
        _order: str
        _rec_name: str | None
        _rec_names_search: list[str] | None
        _name_create_on_import: bool
        _display_name_column: str | tuple[str, ...] | None
        _display_name_column_guard: str | None
        _display_name_context_keys: tuple[str, ...]
        _display_name_search_default: bool
        _display_name_search_exact: tuple[str, ...]
        _table_objects: dict
        _table_inheritance_root: str
        _check_company_auto: bool

        def _is_table_inheritance_root(self) -> bool: ...
        def _get_root_model_name(self) -> str: ...
        def _invalidate_table_inheritance_siblings(
            self, fnames: Collection[str]
        ) -> None: ...
        def _flush_table_inheritance_siblings(
            self, fnames: Collection[str] | None
        ) -> None: ...

        def browse(self, ids: int | typing.Iterable[IdType] = ()) -> Self: ...
        def new(
            self,
            values: ValuesType | None = None,
            origin: Self | None = None,
            ref: str | None = None,
        ) -> Self: ...
        def check_singleton(self) -> Self: ...
        def exists(self) -> Self: ...
        def sudo(self, flag: bool = True) -> Self: ...
        def with_env(self, env: Environment) -> Self: ...
        def filtered(self, func: str | Callable[[Self], bool] | Domain) -> Self: ...
        def __iter__(self) -> Iterator[Self]: ...
        def __len__(self) -> int: ...
        @typing.overload
        def __getitem__(self, key: int | slice) -> Self: ...
        @typing.overload
        def __getitem__(self, key: str) -> typing.Any: ...
        def __getitem__(self, key: int | slice | str) -> Self | typing.Any: ...

        def with_context(
            self, ctx: dict[str, typing.Any] | None = None, /, **overrides
        ) -> Self: ...
        def with_user(self, user) -> Self: ...
        def with_company(self, company: Self | int | None) -> Self: ...
        def with_prefetch(
            self, prefetch_ids: Reversible[IdType] | None = None
        ) -> Self: ...
        def union(self, *args: Self) -> Self: ...
        def __sub__(self, other: typing.Any) -> Self: ...
        def __contains__(self, item: object) -> bool: ...
        def __int__(self) -> int: ...
        def __setitem__(self, key: str, value: typing.Any) -> None: ...

        mapped: typing.Any
        grouped: typing.Any

        def fields_get(self, *args: typing.Any, **kwargs: typing.Any) -> dict: ...
        def _get_field_descriptions_static(
            self,
            attributes: tuple[str, ...] | None,
            field_names: tuple[str, ...] | None,
        ) -> typing.Mapping[str, tuple[typing.Mapping, tuple[str, ...]]]: ...
        def invalidate_model(
            self, fnames: typing.Any = None, flush: bool = True
        ) -> None: ...
        def _invalidate_cache(
            self,
            fnames: Collection[str] | None = None,
            ids: typing.Sequence[IdType] | None = None,
            flush: bool = True,
        ) -> None: ...
        def _evict_x2many_scopes_reading_through(
            self, fnames: Collection[str]
        ) -> None: ...
        def update_field_translations(
            self, field_name: str, translations: dict, source_lang: str = ""
        ) -> bool: ...

        def _read_format(
            self, *args: typing.Any, **kwargs: typing.Any
        ) -> list[dict]: ...
        def _fetch_query(self, query: typing.Any, fields: typing.Any) -> Self: ...
        def _is_an_ordinary_table(self) -> bool: ...

        _write_multi: typing.Any

        def _update_cache(self, values: typing.Any, validate: bool = True) -> None: ...
        def concat(self, *args: Self) -> Self: ...

        def check_access(self, operation: str) -> None: ...
        def _check_access(self, operation: str) -> tuple[Self, Callable] | None: ...
        def _search(
            self,
            domain: DomainType,
            offset: int = 0,
            limit: int | None = None,
            order: str | None = None,
            *,
            active_test: bool = True,
            bypass_access: bool = False,
        ) -> Query: ...
        def _field_to_sql(
            self, alias: str, field_expr: str, query: Query | None = None
        ) -> SQL: ...

        def create(self, vals_list: ValuesType | list[ValuesType]) -> Self: ...
        def write(self, vals: ValuesType) -> typing.Literal[True]: ...
        def fetch(self, field_names: Collection[str] | None = None) -> None: ...
        def flush_model(self, fnames: Collection[str] | None = None) -> None: ...
        def filtered_domain(self, domain: DomainType) -> Self: ...
        def _check_fields(
            self, field_names: Iterable[str], excluded_names: Iterable[str] = ()
        ) -> None: ...
        @property
        def _constrained_field_names(self) -> frozenset[str]: ...
        @property
        def _constrained_projection_names(self) -> frozenset[str]: ...
        def _aggregates_through_records(self, field: Field, func: str) -> bool: ...
        def get_property_definition(self, full_name: str) -> dict: ...
        def _has_field_access(
            self, field: Field, operation: typing.Literal["read", "write"]
        ) -> bool: ...
        def _get_fields_default_read(self) -> list[str]: ...
        def _check_fields_write_access(
            self, field_names: typing.Iterable[str]
        ) -> None: ...

        def _check_field_access(
            self, field: Field, operation: typing.Literal["read", "write"]
        ) -> None: ...
        def _check_company(self, fnames: Collection[str] | None = None) -> None: ...
        def modified(
            self,
            fnames: Collection[str],
            create: bool = False,
            before: bool = False,
        ) -> None: ...
        def _modified_before(self, fnames: Collection[str]) -> None: ...
        def _recompute_recordset(
            self, fnames: Collection[str] | None = None
        ) -> None: ...
        def _compute_field_value(self, field: Field, validate: bool = True) -> None: ...

        def _check_computed(self, field: Field) -> None: ...

        def _order_to_sql(
            self,
            order: str,
            query: typing.Any,
            alias: str | None = None,
            reverse: bool = False,
        ) -> typing.Any: ...

        def _traverse_related_sql(
            self, alias: str, field: Field, query: typing.Any
        ) -> tuple[typing.Any, Field, str]: ...

        def _sql_error_to_message(self, exc: typing.Any) -> str: ...

        def _remove_stale_properties(self) -> None: ...

        def search(
            self,
            domain: typing.Any,
            offset: int = 0,
            limit: int | None = None,
            order: str | None = None,
        ) -> Self: ...
        def invalidate_recordset(
            self, fnames: Collection[str] | None = None, flush: bool = True
        ) -> None: ...
        def flush_recordset(self, fnames: Collection[str] | None = None) -> None: ...
        def _has_rows_in_table(self) -> bool: ...
        def _init_column(
            self, column_name: str, *, new_column: bool = False
        ) -> None: ...
        @classmethod
        def is_transient(cls) -> bool: ...
        def _get_base_lang(self) -> str: ...
        def _convert_to_cache_properties_definition(
            self, value: typing.Any
        ) -> typing.Any: ...
        def _convert_to_column_properties_definition(
            self, value: typing.Any
        ) -> typing.Any: ...
        def _get_fields_to_fetch(
            self,
            field_names: Collection[str] | None = None,
            ignore_when_in_cache: bool = False,
        ) -> list[Field]: ...
        @classmethod
        def _spawn(
            cls,
            env: Environment,
            ids: tuple[IdType, ...],
            prefetch_ids: Reversible[IdType],
        ) -> Self: ...
        def _narrow(self, ids: Iterable[IdType]) -> Self: ...

        @property
        def _origin(self) -> Self: ...
        @property
        def _has_origin(self) -> bool: ...
        @property
        def _table_sql(self) -> SQL: ...
        @property
        def _onchange_methods(self) -> dict[str, list]: ...
