sass:
	sass -t expanded --unix-newlines --watch website.sass:website.css&
	sass -t expanded --unix-newlines --watch website-flatly.sass:website-flatly.css&
	sass -t expanded --unix-newlines --watch editor.sass:editor.css&
