sass:
	sass -t expanded --compass --unix-newlines --watch website.sass:website.css&
	sass -t expanded --compass --unix-newlines --watch editor.sass:editor.css&
	sass -t expanded --compass --unix-newlines --watch snippets.sass:snippets.css&
