{
    "name": "AGI Gov - Gestão de Processos",
    "version": "19.0.5.0.0",
    "category": "Government",
    "depends": ["gov_base", "mail", "base_automation", "web"],
    "data": [
        "security/ir.model.access.csv",
        "security/gov_processos_rules.xml",
        "data/gov_ai_template_seed.xml",
        "data/gov_ai_template_grp_dfd_seed.xml",
        "data/gov_ai_template_grp_procurement_suite_seed.xml",
        "data/gov_ai_template_procurement_seed.xml",
        "data/gov_ai_template_direct_seed.xml",
        "data/gov_ai_quality_policy_seed.xml",
        "data/gov_timbre_seed.xml",
        "data/gov_xlsx_worker_cron.xml",
        "data/gov_document_ingest_worker_cron.xml",
        "data/gov_render_worker_cron.xml",
        "views/gov_ai_provider_views.xml",
        "views/gov_ai_memory_views.xml",
        "views/gov_ai_run_views.xml",
        "views/gov_ai_memory_ingest_wizard_views.xml",
        "views/gov_ai_template_views.xml",
        "views/gov_ai_quality_policy_views.xml",
        "views/gov_ai_orchestrator_views.xml",
        "views/gov_processo_doc_views.xml",
        "views/gov_processo_doc_render_job_views.xml",
        "views/gov_processo_doc_ingest_job_views.xml",
        "views/gov_processo_planilha_item_views.xml",
        "views/gov_processo_planilha_lote_views.xml",
        "views/gov_processo_planilha_job_views.xml",
        "views/gov_processo_parametro_views.xml",
        "views/gov_processo_dotacao_views.xml",
        "views/gov_dotacao_wizard_views.xml",
        "views/gov_processo_fase_wizard_views.xml",
        "views/gov_processo_views.xml",
        "views/gov_dashboard_views.xml",
        "views/gov_dashboard_action.xml",
        "views/gov_relatorio_wizard_views.xml",
        "views/gov_timbre_views.xml",
        "views/gov_siafi_wizard_views.xml",
        "views/gov_execucao_wizard_views.xml",
        "views/gov_processo_wizard.xml",
        "views/gov_processo_doc_typst_wizard_views.xml",
        "views/gov_processo_tramite_wizard.xml",
        "views/gov_processo_menus.xml",
        "data/gov_processo_sequence.xml",
        "data/gov_processo_cron.xml",
        "data/gov_automation_rules.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "gov_processos/static/src/css/gov_dashboard.css",
            "gov_processos/static/src/css/gov_document_builder.css",
            "gov_processos/static/src/js/gov_dashboard.js",
            "gov_processos/static/src/js/gov_document_builder.js",
            "gov_processos/static/src/xml/gov_dashboard.xml",
            "gov_processos/static/src/xml/gov_document_builder.xml",
        ],
    },
    "installable": True,
    "application": False,
    "author": "AGI Gov",
    "license": "LGPL-3",
    "external_dependencies": {"python": ["xlsxwriter"]},
}
