# Part of Odoo. See LICENSE file for full copyright and licensing details.

from . import account_move
from . import crm_team
from . import delivery_carrier
from . import digest
from . import ir_http
from . import ir_module_module
from . import payment_token
from . import product_attribute
from . import product_document
from . import product_feed
from . import product_image
from . import product_pricelist
from . import product_pricelist_item
from . import product_product
from . import product_public_category
from . import product_ribbon
from . import product_tag
from . import product_template
from . import product_template_attribute_line
from . import product_template_attribute_value
from . import res_company
from . import res_config_settings
from . import res_partner
from . import sale_order
from . import sale_order_line
from . import theme_utils
from . import website
from . import website_base_unit
from . import website_checkout_step
from . import website_menu
from . import website_page
from . import website_sale_extra_field
from . import website_snippet_filter
from . import website_track
from . import website_visitor
