# Part of Odoo. See LICENSE file for full copyright and licensing details.

from .account_move import AccountMove
from .crm_team import CrmTeam
from .delivery_carrier import DeliveryCarrier
from .digest import DigestDigest
from .ir_http import IrHttp
from .payment_token import PaymentToken
from .product_attribute import ProductAttribute
from .product_document import ProductDocument
from .product_image import ProductImage
from .product_pricelist import ProductPricelist
from .product_product import ProductProduct
from .product_public_category import ProductPublicCategory
from .product_ribbon import ProductRibbon
from .product_tag import ProductTag
from .product_template import ProductTemplate
from .product_template_attribute_line import ProductTemplateAttributeLine
from .product_template_attribute_value import ProductTemplateAttributeValue
from .res_company import ResCompany
from .res_config_settings import ResConfigSettings
from .res_partner import ResPartner
from .sale_order import SaleOrder
from .sale_order_line import SaleOrderLine
from .website import Website
from .website_base_unit import WebsiteBaseUnit
from .website_menu import WebsiteMenu
from .website_sale_extra_field import WebsiteSaleExtraField
from .website_snippet_filter import WebsiteSnippetFilter
from .website_track import WebsiteTrack
from .website_visitor import WebsiteVisitor
