# Part of Odoo. See LICENSE file for full copyright and licensing details.

from . import (  # noqa: I001
    account_move,
    crm_team,
    delivery_carrier,
    digest,
    ir_http,
    ir_module_module,
    payment_token,
    payment_transaction,
    product_attribute,
    product_attribute_category,
    product_document,
    product_feed,
    product_image,
    product_pricelist,
    product_pricelist_item,
    product_product,
    product_public_category,
    product_ribbon,
    product_tag,
    product_template,
    product_template_attribute_line,
    product_template_attribute_value,
    product_wishlist,
    res_company,
    res_config_settings,
    res_partner,
    res_users,
    website_checkout_alert_mixin,  # Dependency of sale.order and sale.order.line
    sale_order,
    sale_order_line,
    theme_utils,
    website,
    website_base_unit,
    website_checkout_step,
    website_menu,
    website_page,
    website_sale_extra_field,
    website_snippet_filter,
    website_track,
    website_visitor,
)
