[options]
admin_passwd = admin
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo
addons_path = /opt/odoo/addons,/mnt/custom_addons
data_dir = /var/lib/odoo
http_interface = 0.0.0.0
http_port = 8069
logfile = False
proxy_mode = True
