# -*- coding: utf-8 -*-
# Part of Odoo. See LICENSE file for full copyright and licensing details.

from .test_new_api import (
    DecimalPrecisionTest, DomainBool, Test_New_ApiAnyChild,
    Test_New_ApiAnyParent, Test_New_ApiAnyTag, Test_New_ApiAttachment, Test_New_ApiAttachmentHost,
    Test_New_ApiAutovacuumed, Test_New_ApiBar, Test_New_ApiBinary_Svg, Test_New_ApiCascade,
    Test_New_ApiCategory, Test_New_ApiCity, Test_New_ApiCompany, Test_New_ApiCompanyAttr,
    Test_New_ApiComputeContainer, Test_New_ApiComputeDynamicDepends, Test_New_ApiComputeInverse,
    Test_New_ApiComputeMember, Test_New_ApiComputeOnchange, Test_New_ApiComputeOnchangeLine,
    Test_New_ApiComputeReadonly, Test_New_ApiComputeReadwrite, Test_New_ApiComputeSudo,
    Test_New_ApiComputeUnassigned, Test_New_ApiCompute_Editable, Test_New_ApiCompute_EditableLine,
    Test_New_ApiComputedModifier, Test_New_ApiCountry, Test_New_ApiCreativeworkBook,
    Test_New_ApiCreativeworkEdition, Test_New_ApiCreativeworkMovie, Test_New_ApiCrew,
    Test_New_ApiCustomTable_Query, Test_New_ApiCustomTable_Query_Sql, Test_New_ApiCustomView,
    Test_New_ApiDiscussion, Test_New_ApiDisplay, Test_New_ApiEmailmessage, Test_New_ApiEmpty_Char,
    Test_New_ApiEmpty_Int, Test_New_ApiField_With_Caps, Test_New_ApiFoo, Test_New_ApiGroup,
    Test_New_ApiHierarchyHead, Test_New_ApiHierarchyNode, Test_New_ApiIndexed_Translation,
    Test_New_ApiInverse_M2o_Ref, Test_New_ApiMessage, Test_New_ApiMixed, Test_New_ApiMixin,
    Test_New_ApiModel2Some_Access, Test_New_ApiModel3Some_Access, Test_New_ApiModelAll_Access,
    Test_New_ApiModelNo_Access, Test_New_ApiModelSome_Access, Test_New_ApiModel_A,
    Test_New_ApiModel_Active_Field, Test_New_ApiModel_B, Test_New_ApiModel_Binary,
    Test_New_ApiModel_Child, Test_New_ApiModel_Child_M2o, Test_New_ApiModel_Child_Nocheck,
    Test_New_ApiModel_Constrained_Unlinks, Test_New_ApiModel_Image,
    Test_New_ApiModel_Many2one_Reference, Test_New_ApiModel_Parent, Test_New_ApiModel_Parent_M2o,
    Test_New_ApiModel_Selection_Base, Test_New_ApiModel_Selection_Non_Stored,
    Test_New_ApiModel_Selection_Related, Test_New_ApiModel_Selection_Related_Updatable,
    Test_New_ApiModel_Selection_Required, Test_New_ApiModel_Selection_Required_For_Write_Override,
    Test_New_ApiModel_Shared_Cache_Compute_Line, Test_New_ApiModel_Shared_Cache_Compute_Parent,
    Test_New_ApiModified, Test_New_ApiModifiedLine, Test_New_ApiMonetary_Base,
    Test_New_ApiMonetary_Custom, Test_New_ApiMonetary_Inherits, Test_New_ApiMonetary_Order,
    Test_New_ApiMonetary_Order_Line, Test_New_ApiMonetary_Related, Test_New_ApiMove,
    Test_New_ApiMove_Line, Test_New_ApiMulti, Test_New_ApiMultiLine, Test_New_ApiMultiLine2,
    Test_New_ApiMultiTag, Test_New_ApiMulti_Compute_Inverse, Test_New_ApiOne2many,
    Test_New_ApiOne2manyLine, Test_New_ApiOrder, Test_New_ApiOrderLine, Test_New_ApiPartner,
    Test_New_ApiPayment, Test_New_ApiPirate, Test_New_ApiPrecompute, Test_New_ApiPrecomputeCombo,
    Test_New_ApiPrecomputeEditable, Test_New_ApiPrecomputeLine, Test_New_ApiPrecomputeMonetary,
    Test_New_ApiPrecomputeReadonly, Test_New_ApiPrecomputeRequired, Test_New_ApiPrefetch,
    Test_New_ApiPrefetchLine, Test_New_ApiPrisoner, Test_New_ApiRecursive,
    Test_New_ApiRecursiveLine, Test_New_ApiRecursiveOrder, Test_New_ApiRecursiveTask,
    Test_New_ApiRecursiveTree, Test_New_ApiRelated, Test_New_ApiRelated_Bar,
    Test_New_ApiRelated_Foo, Test_New_ApiRelated_Inherits, Test_New_ApiRelated_Translation_1,
    Test_New_ApiRelated_Translation_2, Test_New_ApiRelated_Translation_3, Test_New_ApiReq_M2o,
    Test_New_ApiReq_M2o_Transient, Test_New_ApiSelection, Test_New_ApiSharedCompute,
    Test_New_ApiShip, Test_New_ApiState_Mixin, Test_New_ApiTeam, Test_New_ApiTeamMember,
    Test_New_ApiTransient_Model, Test_New_ApiTriggerLeft, Test_New_ApiTriggerMiddle,
    Test_New_ApiTriggerRight, Test_New_ApiUnsearchableO2m, Test_New_ApiUser,
)
from .test_unity_read import (
    Test_New_ApiCourse, Test_New_ApiEmployer, Test_New_ApiLesson,
    Test_New_ApiPerson, Test_New_ApiPersonAccount,
)
