{
    "name": "Extensión Website Sidebar",
    "version": "18.0",
    "category": "Website",
    "depends": ["website", "web"],
    "assets": {
        "web.assets_frontend": [
            "mi_website_ext/static/src/js/bio_modal.js",
            "mi_website_ext/static/src/js/tooltip_handler.js",
            "mi_website_ext/static/src/css/tooltip_styles.css",
            "mi_website_ext/static/src/css/gallery.css",
            "mi_website_ext/static/src/css/anniversary_single.css",
            "mi_website_ext/static/src/css/anniversary_all.css",
            "mi_website_ext/static/src/css/activity.css",
            "mi_website_ext/static/src/css/activity_all.css",
            "mi_website_ext/static/src/css/announce.css",
            "mi_website_ext/static/src/css/birthday_single.css",
            "mi_website_ext/static/src/css/birthday_all.css",
            "mi_website_ext/static/src/css/blog.css",
            "mi_website_ext/static/src/css/program.css",
            "mi_website_ext/static/src/css/intern_all.css",
            "mi_website_ext/static/src/css/news.css",
            "mi_website_ext/static/src/css/policy.css",
            "mi_website_ext/static/src/css/task.css",
        ],
        "web.assets_backend": [],
    },
    "data": [
        "views/modal_bio_editor_views.xml",
        "views/bio_modal_in_body.xml",
        "views/sidebar_template.xml",
        "views/gallery_template.xml",
        "views/blog_template.xml",
        "views/news_template.xml",
        "views/task_template.xml",
        "views/policy_template.xml",
        "views/birthday_single_template.xml",
        "views/birthday_all_template.xml",
        "views/anniversary_single_template.xml",
        "views/anniversary_all_template.xml",
        "views/activity_template.xml",
        "views/activity_all_template.xml",
        "views/announce_template.xml",
        "views/intern_all_template.xml",
        "views/program.xml",
    ],
    "installable": True,
    "application": True,
}
