{
    "name": "Extensión Website Sidebar",
    "version": "18.0",
    "category": "Website",
    "depends": [
        "website",
        "web",
        "hr",
        "hr_contract",
        "hr_holidays",
        "mail",
        "calendar",
        "portal",
    ],
    "assets": {
        'web.assets_backend': [
            ('after', 'hr_holidays/static/src/components/float_time_selection/float_time_selection_popover.js', 'mi_website_ext/static/src/js/time_format_widget_override.js'),
            'mi_website_ext/static/src/js/kiosk_mode.js',
            'mi_website_ext/static/src/css/kiosk_mode.css'
            
        ],
        "web.assets_frontend": [
            "mi_website_ext/static/src/js/notify_button_handler.js",
            'mi_website_ext/static/src/js/manual_viewer.js',
            'mi_website_ext/static/src/js/back_button_refresh.js',
            "mi_website_ext/static/src/js/startup_popups.js",
            'mi_website_ext/static/src/js/policy_viewer.js',
            "mi_website_ext/static/src/js/read_tracker.js",
            "mi_website_ext/static/src/js/tooltip_handler.js",
            "mi_website_ext/static/src/js/comment_handler.js",
            'mi_website_ext/static/src/js/splash_loader.js',
            "mi_website_ext/static/src/css/splash_loader.css",
            "mi_website_ext/static/src/css/comment.css",
            "mi_website_ext/static/src/css/tooltip_styles.css",
            "mi_website_ext/static/src/css/gallery.css",
            "mi_website_ext/static/src/css/anniversary_single.css",
            "mi_website_ext/static/src/css/anniversary_all.css",
            "mi_website_ext/static/src/css/activity.css",
            "mi_website_ext/static/src/css/activity_all.css",
            "mi_website_ext/static/src/css/announce.css",
            "mi_website_ext/static/src/css/birthday_single.css",
            "mi_website_ext/static/src/css/birthday_all.css",
            "mi_website_ext/static/src/css/blog.css",
            "mi_website_ext/static/src/css/program.css",
            "mi_website_ext/static/src/css/intern_all.css",
            "mi_website_ext/static/src/css/news.css",
            "mi_website_ext/static/src/css/policy.css",
            "mi_website_ext/static/src/css/task.css",
            "mi_website_ext/static/src/css/modal.css",
            "mi_website_ext/static/src/css/profile.css"
        ],
    },
    "data": [
        "security/ir.model.access.csv",
        'data/mail_templates.xml',
        'wizards/publication_view_wizard_views.xml',
        'views/pdf_viewer_modal.xml',
        "views/website_publication_views.xml",
        'views/theming.xml',
        "views/sidebar_template.xml",
        "views/gallery_template.xml",
        "views/blog_template.xml",
        "views/blog_post_detail_template.xml",
        "views/news_template.xml",
        "views/news_detail_template.xml",
        "views/task_template.xml",
        "views/policy_template.xml",
        "views/birthday_single_template.xml",
        "views/birthday_all_template.xml",
        "views/anniversary_single_template.xml",
        "views/anniversary_all_template.xml",
        "views/activity_template.xml",
        "views/activity_all_template.xml",
        "views/announce_template.xml",
        "views/intern_all_template.xml",
        "views/program.xml",
        "views/comment_section_template.xml",
        'views/notify_absence_modal.xml',
        'views/startup_modals.xml',
        'views/sidebar_fragment.xml',
        'views/website_gallery_views.xml',
        'views/gallery_detail_template.xml',
        'views/tracking_views.xml',
        'views/res_company_views.xml',
        'views/my_account_menu.xml',
        "views/mail_systray.xml",
        "data/ir_cron.xml",
        'views/manual_viewer_modal.xml',
        'views/mandatory_policies_modal.xml'
    ],
    "installable": True,
    "application": True,
}
