# -*- coding: utf-8 -*-
# Part of Odoo. See LICENSE file for full copyright and licensing details.

from werkzeug.exceptions import NotFound
from werkzeug.urls import url_encode, url_parse

from odoo import http
from odoo.http import request


class LinkTracker(http.Controller):

    @http.route('/r/<string:code>', type='http', auth='public', website=True)
    def full_url_redirect(self, code, **post):
        if not request.env['ir.http'].is_a_bot():
            request.env['link.tracker.click'].sudo().add_click(
                code,
                ip=request.httprequest.remote_addr,
                country_code=request.geoip.country_code,
            )
        redirect_url = request.env['link.tracker'].get_url_from_code(code)
        if not redirect_url:
            raise NotFound()

        # Preserve query parameters supplied to the tracked link. The destination
        # URL remains authoritative when it already defines a key, including the
        # UTM values generated by Link Tracker.
        parsed_redirect_url = url_parse(redirect_url)
        redirect_query = parsed_redirect_url.decode_query()
        for key, values in request.httprequest.args.lists():
            if key not in redirect_query:
                for value in values:
                    redirect_query.add(key, value)
        redirect_url = parsed_redirect_url.replace(query=url_encode(redirect_query)).to_url()
        return request.redirect(redirect_url, code=301, local=False)
