
OpenERP Server Documentation
''''''''''''''''''''''''''''

.. toctree::
   :maxdepth: 2

   01_getting_started
   02_architecture
   03_module_dev
   04_user_roles
   90_using_gunicorn
   99_test_framework

OpenERP Server API
''''''''''''''''''

.. toctree::
   :maxdepth: 1

   api/core
   api/models
   api/startup

Main revisions and new features
'''''''''''''''''''''''''''''''

.. toctree::
   :maxdepth: 1

   revisions/user_img_specs
   revisions/need_action_specs
