#!/bin/bash

DAEMON=/home/pi/odoo/odoo-bin
CONFIG=/home/pi/odoo/addons/point_of_sale/tools/posbox/configuration/odoo.conf
MODULES=$(ls /home/pi/odoo/addons/ -m -w0 | tr -d ' ')

$DAEMON --load=$MODULES --config $CONFIG --log-level info
