#!/bin/bash
xset s off
xset -dpms

export HOME=/tmp

DISPLAY_URL='http://localhost:8069/point_of_sale/display'

# wait until odoo is ready, otherwise you will have to plug a
# keyboard into the posbox just to refresh firefox
until wget -q "${DISPLAY_URL}" -O /dev/null ; do sleep 1 ; done

/usr/bin/firefox "${DISPLAY_URL}" &
