{
    "name": "CRM",
    "version": "2.0",
    "category": "Sales/CRM",
    "sequence": 15,
    "summary": "Track leads and close opportunities",
    "author": "Odoo S.A.",
    "website": "https://www.odoo.com/app/crm",
    "license": "LGPL-3",
    "depends": [
        "sale",
        "sale_team",
        "mail",
        "calendar",
        "utm",
        "web_tour",
        "partner",
        "digest",
        "phone_validation",
    ],
    "data": [
        "security/crm_security.xml",
        "security/ir.model.access.csv",
        "data/crm_lead_merge_template.xml",
        "data/crm_lead_prediction_data.xml",
        "data/crm_lost_reason_data.xml",
        "data/crm_stage_data.xml",
        "data/crm_team_data.xml",
        "data/digest_data.xml",
        "data/ir_action_data.xml",
        "data/ir_cron_data.xml",
        "data/mail_message_subtype_data.xml",
        "data/crm_recurring_plan_data.xml",
        "data/crm_tour.xml",
        "wizards/crm_lead_lost_views.xml",
        "wizards/crm_lead_to_opportunity_views.xml",
        "wizards/crm_lead_to_opportunity_mass_views.xml",
        "wizards/crm_merge_opportunities_views.xml",
        "wizards/crm_lead_pls_update_views.xml",
        "views/calendar_views.xml",
        "views/crm_recurring_plan_views.xml",
        "views/crm_lost_reason_views.xml",
        "views/crm_stage_views.xml",
        "views/crm_lead_views.xml",
        "views/team_member_views.xml",
        "views/digest_views.xml",
        "views/mail_activity_plan_views.xml",
        "views/mail_activity_views.xml",
        "views/res_config_settings_views.xml",
        "views/res_partner_views.xml",
        "views/utm_campaign_views.xml",
        "reports/crm_activity_report_views.xml",
        "reports/crm_opportunity_report_views.xml",
        "views/team_team_views.xml",
        "views/crm_menu_views.xml",
        "views/crm_helper_templates.xml",
    ],
    "demo": [
        "demo/crm_team_demo.xml",
        "demo/crm_stage_demo.xml",
        "demo/mail_template_demo.xml",
        "demo/crm_team_member_demo.xml",
        "demo/crm_lead_demo.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "crm/static/src/**",
        ],
        "web.assets_tests": [
            "crm/static/tests/tours/**/*",
        ],
        "web.assets_unit_tests": [
            "crm/static/tests/mock_server/**/*",
            "crm/static/tests/crm_test_helpers.js",
            "crm/static/tests/**/*.test.js",
            "crm/static/tests/crm_mock_server.js",
        ],
    },
    "application": True,
}
