# Part of Odoo. See LICENSE file for full copyright and licensing details.

from . import (
    chatbot_message,
    chatbot_script,
    chatbot_script_answer,
    chatbot_script_step,
    digest,
    discuss_call_history,
    discuss_channel,
    discuss_channel_member,
    discuss_channel_rtc_session,
    im_livechat_channel,
    im_livechat_channel_member_history,
    im_livechat_expertise,
    ir_http,
    ir_qweb,
    ir_websocket,
    mail_message,
    res_groups,
    res_partner,
    res_users,
    res_users_settings,
    utm,
)
