from . import res_config_settings
from . import hr_attendance
from . import hr_attendance_overtime
from . import hr_attendance_overtime_rule
from . import hr_attendance_overtime_ruleset
from . import hr_employee
from . import hr_version
from . import ir_http
from . import hr_attendance_config
from . import resource_calendar
from . import res_company
from . import res_users
