from openerp.tests.common import TransactionCase

ofx_file = """PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iQVNDSUkiPz4NCjw/
        T0ZYIE9GWEhFQURFUj0iMjAwIiBWRVJTSU9OPSIyMTEiIFNFQ1VSSVRZPSJOT05FIiBPTE
        RGSUxFVUlEPSJOT05FIiBORVdGSUxFVUlEPSJOT05FIj8+DQo8T0ZYPg0KICA8U0lHTk9O
        TVNHU1JTVjE+DQogICAgPFNPTlJTPg0KICAgICAgPFNUQVRVUz4NCiAgICAgICAgPENPRE
        U+MDwvQ09ERT4NCiAgICAgICAgPFNFVkVSSVRZPklORk88L1NFVkVSSVRZPg0KICAgICAg
        PC9TVEFUVVM+DQogICAgICA8RFRTRVJWRVI+MjAwNTA4MzExNjUxNTMuMDAwWy04OlBTVF
        08L0RUU0VSVkVSPg0KICAgICAgPExBTkdVQUdFPkVORzwvTEFOR1VBR0U+DQogICAgPC9T
        T05SUz4NCiAgPC9TSUdOT05NU0dTUlNWMT4NCiAgPEJBTktNU0dTUlNWMT4NCiAgICA8U1
        RNVFRSTlJTPg0KICAgICAgPFRSTlVJRD4wPC9UUk5VSUQ+DQogICAgICA8U1RBVFVTPg0K
        ICAgICAgICA8Q09ERT4wPC9DT0RFPg0KICAgICAgICA8U0VWRVJJVFk+SU5GTzwvU0VWRV
        JJVFk+DQogICAgICA8L1NUQVRVUz4NCiAgICAgIDxTVE1UUlM+DQogICAgICAgIDxDVVJE
        RUY+VVNEPC9DVVJERUY+DQogICAgICAgIDxCQU5LQUNDVEZST00+DQogICAgICAgICAgPE
        JBTktJRD4wMDAwMDAxMjM8L0JBTktJRD4NCiAgICAgICAgICA8QUNDVElEPjEyMzQ1Njwv
        QUNDVElEPg0KICAgICAgICAgIDxBQ0NUVFlQRT5DSEVDS0lORzwvQUNDVFRZUEU+DQogIC
        AgICAgIDwvQkFOS0FDQ1RGUk9NPg0KICAgICAgICA8QkFOS1RSQU5MSVNUPg0KICAgICAg
        ICAgIDxEVFNUQVJUPjIwMTQwODAxPC9EVFNUQVJUPg0KICAgICAgICAgIDxEVEVORD4yMD
        E0MDgzMTE2NTE1My4wMDBbLTg6UFNUXTwvRFRFTkQ+DQogICAgICAgICAgPFNUTVRUUk4+
        DQogICAgICAgICAgICA8VFJOVFlQRT5QT1M8L1RSTlRZUEU+DQogICAgICAgICAgICA8RF
        RQT1NURUQ+MjAwNTA4MjQwODAwMDA8L0RUUE9TVEVEPg0KICAgICAgICAgICAgPFRSTkFN
        VD4tODA8L1RSTkFNVD4NCiAgICAgICAgICAgIDxGSVRJRD4yMTkzNzg8L0ZJVElEPg0KIC
        AgICAgICAgICAgPE5BTUU+RnJvZ0tpY2sgU2N1YmEgR2VhcjwvTkFNRT4NCiAgICAgICAg
        ICA8L1NUTVRUUk4+DQogICAgICAgIDwvQkFOS1RSQU5MSVNUPg0KICAgICAgICA8TEVER0
        VSQkFMPg0KICAgICAgICAgIDxCQUxBTVQ+MjE1Ni41NjwvQkFMQU1UPg0KICAgICAgICAg
        IDxEVEFTT0Y+MjAwNTA4MzExNjUxNTM8L0RUQVNPRj4NCiAgICAgICAgPC9MRURHRVJCQU
        w+DQogICAgICA8L1NUTVRSUz4NCiAgICA8L1NUTVRUUk5SUz4NCiAgPC9CQU5LTVNHU1JT
        VjE+DQogIDxDUkVESVRDQVJETVNHU1JTVjE+DQogICAgPENDU1RNVFRSTlJTPg0KICAgIC
        AgPFRSTlVJRD4wPC9UUk5VSUQ+DQogICAgICA8U1RBVFVTPg0KICAgICAgICA8Q09ERT4w
        PC9DT0RFPg0KICAgICAgICA8U0VWRVJJVFk+SU5GTzwvU0VWRVJJVFk+DQogICAgICA8L1
        NUQVRVUz4NCiAgICAgIDxDQ1NUTVRSUz4NCiAgICAgICAgPENVUkRFRj5VU0Q8L0NVUkRF
        Rj4NCiAgICAgICAgPENDQUNDVEZST00+DQogICAgICAgICAgPEFDQ1RJRD4xMjM0MTIzND
        EyMzQ8L0FDQ1RJRD4NCiAgICAgICAgPC9DQ0FDQ1RGUk9NPg0KICAgICAgICA8QkFOS1RS
        QU5MSVNUPg0KICAgICAgICAgIDxEVFNUQVJUPjIwMTQwODAxPC9EVFNUQVJUPg0KICAgIC
        AgICAgIDxEVEVORD4yMDE0MDgzMTE2NTE1My4wMDBbLTg6UFNUXTwvRFRFTkQ+DQogICAg
        ICAgICAgPFNUTVRUUk4+DQogICAgICAgICAgICA8VFJOVFlQRT5JTlQ8L1RSTlRZUEU+DQ
        ogICAgICAgICAgICA8RFRQT1NURUQ+MjAwNTA4MTEwODAwMDA8L0RUUE9TVEVEPg0KICAg
        ICAgICAgICAgPFRSTkFNVD4tMjMuMDA8L1RSTkFNVD4NCiAgICAgICAgICAgIDxGSVRJRD
        4yMTk4Njc8L0ZJVElEPg0KICAgICAgICAgICAgPE5BTUU+SW50ZXJlc3QgQ2hhcmdlPC9O
        QU1FPg0KICAgICAgICAgIDwvU1RNVFRSTj4NCiAgICAgICAgICA8U1RNVFRSTj4NCiAgIC
        AgICAgICAgIDxUUk5UWVBFPkNSRURJVDwvVFJOVFlQRT4NCiAgICAgICAgICAgIDxEVFBP
        U1RFRD4yMDA1MDgxMTA4MDAwMDwvRFRQT1NURUQ+DQogICAgICAgICAgICA8VFJOQU1UPj
        M1MC4wMDwvVFJOQU1UPg0KICAgICAgICAgICAgPEZJVElEPjIxOTg2ODwvRklUSUQ+DQog
        ICAgICAgICAgICA8TkFNRT5QYXltZW50IC0gVGhhbmsgWW91PC9OQU1FPg0KICAgICAgIC
        AgIDwvU1RNVFRSTj4NCiAgICAgICAgPC9CQU5LVFJBTkxJU1Q+DQogICAgICAgIDxMRURH
        RVJCQUw+DQogICAgICAgICAgPEJBTEFNVD4tNTYyLjAwPC9CQUxBTVQ+DQogICAgICAgIC
        AgPERUQVNPRj4yMDA1MDgzMTE2NTE1MzwvRFRBU09GPg0KICAgICAgICA8L0xFREdFUkJB
        TD4NCiAgICAgIDwvQ0NTVE1UUlM+DQogICAgPC9DQ1NUTVRUUk5SUz4NCiAgPC9DUkVESV
        RDQVJETVNHU1JTVjE+DQo8L09GWD4NCg=="""

class TestOfxFile(TransactionCase):
    """Tests for import bank statement ofx file format (account.bank.statement.import)
    """

    def setUp(self):
        super(TestOfxFile, self).setUp()
        self.statement_import_model = self.registry('account.bank.statement.import')
        self.bank_statement_model = self.registry('account.bank.statement')

    def test_ofx_file_import(self):
        try:
            from ofxparse import OfxParser as ofxparser
        except ImportError:
            #the Python library isn't installed on the server, the OFX import is unavailable and the test cannot be run
            return True
        cr, uid = self.cr, self.uid
        bank_statement_id = self.statement_import_model.create(cr, uid, dict(
                            file_type='ofx',
                            data_file=ofx_file,
                            ))
        self.statement_import_model.parse_file(cr, uid, [bank_statement_id])
        statement_id = self.bank_statement_model.search(cr, uid, [('name', '=', '000000123')])[0]
        bank_st_record = self.bank_statement_model.browse(cr, uid, statement_id)
        self.assertEquals(bank_st_record.balance_start, 2156.56)
        self.assertEquals(bank_st_record.balance_end_real, 2076.56)
