{
    "name": "MRP Subcontracting",
    "version": "0.3",
    "category": "Supply Chain/Manufacturing",
    "summary": "Subcontract Productions",
    "author": "Odoo S.A.",
    "website": "https://www.odoo.com/app/manufacturing",
    "license": "LGPL-3",
    "depends": [
        "mrp",
    ],
    "data": [
        "data/mrp_subcontracting_data.xml",
        "security/ir.access.csv",
        "views/mrp_bom_views.xml",
        "views/res_partner_views.xml",
        "views/stock_warehouse_views.xml",
        "views/stock_move_views.xml",
        "views/stock_quant_views.xml",
        "views/stock_picking_views.xml",
        "views/supplier_info_views.xml",
        "views/mrp_production_views.xml",
        "views/subcontracting_portal_views.xml",
        "views/subcontracting_portal_templates.xml",
    ],
    "demo": [
        "demo/mrp_subcontracting_demo.xml",
    ],
    "assets": {
        "web.assets_tests": [
            "mrp_subcontracting/static/tests/tours/subcontracting_portal_tour.js",
        ],
        "web.assets_backend": [
            "mrp_subcontracting/static/src/components/**/*",
            "mrp_subcontracting/static/src/subcontracting_portal/move_list_view.js",
        ],
        "web.assets_frontend": [
            "mrp_subcontracting/static/src/scss/subcontracting_portal.scss",
        ],
        "mrp_subcontracting.webclient": [
            (
                "include",
                "web._assets_helpers",
            ),
            (
                "include",
                "web._assets_backend_helpers",
            ),
            "web/static/src/scss/pre_variables.scss",
            "web/static/lib/bootstrap/scss/_variables.scss",
            "web/static/lib/bootstrap/scss/_variables-dark.scss",
            "web/static/lib/bootstrap/scss/_maps.scss",
            (
                "include",
                "web._assets_bootstrap",
            ),
            "web/static/src/scss/tokens.scss",
            "web/static/src/libs/fontawesome7/css/fontawesome.css",
            "web/static/src/libs/fontawesome7/css/solid.css",
            "web/static/src/libs/fontawesome7/css/regular.css",
            "web/static/src/libs/fontawesome7/css/brands.css",
            "web/static/lib/odoo_ui_icons/*",
            "web/static/src/webclient/navbar/navbar.scss",
            "web/static/src/scss/animation.scss",
            "web/static/src/components/color_picker/color_picker.scss",
            "web/static/src/scss/mimetypes.scss",
            "web/static/src/scss/ui.scss",
            "web/static/src/fields/translation_dialog.scss",
            "web/static/src/scss/rtl_icon_flip.scss",
            "web/static/src/session.js",
            "web/static/src/libs/bootstrap.js",
            "base/static/src/css/modules.css",
            "web/static/src/core/**/*",
            "web/static/src/components/**/*",
            (
                "remove",
                "web/static/src/components/emoji_picker/emoji_data.js",
            ),
            "web/static/src/ui/**/*",
            "web/static/src/search/**/*",
            "web/static/src/views/*.js",
            "web/static/src/views/*.xml",
            "web/static/src/views/*.scss",
            "web/static/src/fields/**/*",
            "web/static/src/views/form/**/*",
            "web/static/src/views/kanban/**/*",
            "web/static/src/views/list/**/*",
            "web/static/src/model/**/*",
            "web/static/src/views/view_button/**/*",
            "web/static/src/views/view_components/**/*",
            "web/static/src/views/view_dialogs/**/*",
            "web/static/src/views/widgets/**/*",
            "web/static/src/webclient/**/*",
            (
                "remove",
                "web/static/src/webclient/clickbot/clickbot.js",
            ),
            (
                "remove",
                "web/static/src/webclient/settings_form_view/res_config_edition.xml",
            ),
            (
                "remove",
                "web/static/src/views/form/button_box/*.scss",
            ),
            (
                "remove",
                "web/static/src/webclient/share_target/*",
            ),
            (
                "remove",
                "web/static/src/**/*.dark.scss",
            ),
            (
                "remove",
                "web/static/src/webclient/actions/reports/**/*",
            ),
            "web/static/src/webclient/actions/reports/*.js",
            "web/static/src/webclient/actions/reports/*.xml",
            "web/static/src/env.js",
            "base/static/src/scss/res_partner.scss",
            "web/static/src/views/form/button_box/*.scss",
            "mrp_subcontracting/static/src/subcontracting_portal/*",
            "web/static/src/boot/start.js",
            "stock/static/src/widgets/*",
            "stock/static/src/fields/*",
            "mrp_subcontracting/static/src/components/subcontracting_production_form_controller.js",
            "mrp_subcontracting/static/src/components/subcontracting_production_list_controller.js",
        ],
    },
    "esm": {
        "bundles": [
            "mrp_subcontracting.webclient",
        ],
    },
    "uninstall_hook": "uninstall_hook",
}
