# Part of Odoo. See LICENSE file for full copyright and licensing details.

from . import (
    test_access_rights,
    test_accrued_sale_orders,
    test_analytic_to_sale_to_invoice,
    test_common,
    test_controllers,
    test_credit_limit,
    test_import_files,
    test_ir_config_parameter,
    test_onchange,
    test_payment_flow,
    test_product_attribute_value,
    test_product_catalog,
    test_product_configurator_data,
    test_sale_combo_configurator,
    test_sale_flow,
    test_sale_order,
    test_sale_order_product_catalog,
    test_sale_order_ui,
    test_sale_prices,
    test_sale_product_attribute_value_config,
    test_sale_product_template,
    test_sale_refund,
    test_sale_report,
    test_sale_sections,
    test_sale_to_invoice,
    test_taxes_downpayment,
    test_taxes_global_discount,
    test_taxes_tax_totals_summary,
)
