from . import test_access_rights
from . import test_chart_template
from . import test_accrued_sale_orders
from . import test_common
from . import test_controllers
from . import test_credit_limit
from . import test_ir_config_parameter
from . import test_onchange
from . import test_price_display_seam
from . import test_payment_flow
from . import test_performance_price_computation
from . import test_product_attribute_value
from . import test_product_catalog
from . import test_product_configurator_data
from . import test_sale_combo_configurator
from . import test_sale_flow
from . import test_sale_order
from . import test_sale_order_product_catalog
from . import test_sale_order_state_machine
from . import test_sale_order_template
from . import test_sale_order_template_apply
from . import test_sale_order_template_portal
from . import test_sale_order_ui
from . import test_sale_prices
from . import test_sale_product_attribute_value_config
from . import test_sale_product_template
from . import test_sale_refund
from . import test_sale_to_invoice
from . import test_sale_tour
from . import test_sale_report
from . import test_sale_sections
from . import test_taxes_downpayment
from . import test_taxes_global_discount
from . import test_taxes_tax_totals_summary
from . import test_import_files
from . import test_partner_order_activity
from . import test_partner_sale_guards
from . import test_utm_campaign_revenue
from . import test_expense_reinvoice_price
from . import test_expense_reinvoice_lines
from . import test_percentage_messages
from . import test_invoice_line_classification
from . import test_invoice_line_match
from . import test_account_move_create_sale
from . import test_sale_price_history
from . import test_group_readonly
