from . import account
from . import account_asset_group
from . import account_assets_report
from . import account_chart_template
from . import account_depreciation_profile
from . import account_move
from . import account_return
from . import res_company
from . import resource_asset
