[options]
db_host = localhost
db_port = 5432
db_user = admin
db_password = admin
default_productivity_apps = True
admin_passwd = $pbkdf2-sha512$600000$p3JnM8kpAlXDqdiu2/7jCg==$NtEFgM55qKkesBEWZoO1fMdjStcmLHWZZYf0yna9zthniQfoG7Uq5r/0LMGFRQpXSnabNK4cdTwJKbQ

