[options]
db_host = localhost
db_port = 5432
db_user = pablo
db_password = Pablo1234
default_productivity_apps = True
admin_passwd = admin
addons_path = /home/pablo/odoo/addons,/home/pablo/odoo/custom/helpdesk,/home/pablo/odoo/custom/field-service,/home/pablo/odoo/custom/rma,/home/pablo/odoo/custom/product-attribute
db_name = mydb18
