[options]
; This is the password that allows database operations:
db_host = False
db_port = False
db_user = odoo
db_password = True
;addons_path = /usr/lib/python3/dist-packages/odoo/addons
default_productivity_apps = True
