#!/bin/sh

set -e

case "${1}" in
    remove)
        deluser --quiet --system "openerp" || true
        delgroup --quiet --system --only-if-empty "openerp" || true
        find /var/lib/openerp -path '/var/lib/openerp/*' ! -path '/var/lib/openerp/filestore*' -delete
        ;;

    purge)
        rm -rf /var/lib/openerp
        ;;

    upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
        ;;

esac

#DEBHELPER#

exit 0
