#!/bin/sh

set -e

case "${1}" in
	remove)
        deluser --quiet --system "openerp" || true
        delgroup --quiet --system --only-if-empty "openerp" || true
        ;;

    purge)
        rm -rf /var/lib/openerp-server
        ;;

    upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
        ;;

    *)
        echo "postrm called with unknown argument \`${1}'" >&2
        exit 1
        ;;
esac

#DEBHELPER#

exit 0
