{
    "name": "Custom_layouts_models_Future_Télécom_V19",
    "version": "1.0",
    "category": "Tools",
    "summary": "Agencements personnalisés pour les documents PDF",
    "description": "Ajoute de nouveaux agencements pour les factures, devis, bons, etc.",
    "author": "Alain Gansonré",
    "depends": ["base","sale","web","account", "uom"],
    "data": [
        'views/external_layouts.xml',
        'views/report_invoice_hide.xml',
        'views/contenue_principal.xml',
        'views/contenue_principal_sale_order.xml',
        'views/saleorder_hide_info.xml',
        'views/saleorder_hide_total.xml',
        'views/report_invoice_hide_total.xml',
        'views/report_invoice_hide_payment_term.xml',
        'data/report_layouts.xml',
        'data/paperformat_no_header.xml',
    ],
    "installable": True,
    "application": False,
    "auto_install": False,
}
