[options]
; Database
db_host = tnpd-prison-postgres
db_port = 5432
db_user = odoo
db_password = odoo
db_name = tnpd-prison-db

; Addons paths
addons_path = /usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons

; Performance
workers = 0
max_cron_threads = 1

; Logging
log_level = info

; Interface
http_interface = 0.0.0.0
http_port = 8069
longpolling_port = 8072
