[options]

admin_passwd = odoo_password

db_host = db

db_port = 5432

db_user = odoo

db_password = odoo_password

 

# Banco de dados padrão criado automaticamente no primeiro boot

db_name = odoo_dev

 

# Demo data ativado (False = instala com dados de demonstração)

without_demo = False

 

# Mapeando os diretórios onde seus módulos locais

addons_path = /mnt/extra-addons,/mnt/enterprise,/usr/lib/python3/dist-packages/odoo/addons

 

# Ajustes úteis para ambiente local/desenvolvedor

list_db = True

proxy_mode = False

log_level = info

limit_memory_hard = 2684354560

limit_memory_soft = 2147483648

limit_request = 8192

limit_time_cpu = 600

limit_time_real = 1200

max_cron_threads = 1

workers = 0