{
    "name": "Manufacturing",
    "version": "2.10",
    "category": "Supply Chain/Manufacturing",
    "sequence": 55,
    "summary": "Manufacturing Orders & BOMs",
    "author": "Odoo S.A.",
    "website": "https://www.odoo.com/app/manufacturing",
    "license": "LGPL-3",
    "depends": [
        "document_product",
        "stock",
        "resource",
    ],
    "data": [
        "security/mrp_security.xml",
        "security/ir.model.access.csv",
        "data/digest_data.xml",
        "data/mail_templates.xml",
        "data/mrp_data.xml",
        "data/mail_message_subtype_data.xml",
        "wizards/change_production_qty_views.xml",
        "wizards/mrp_workcenter_block_view.xml",
        "wizards/stock_warn_insufficient_qty_views.xml",
        "wizards/mrp_production_backorder.xml",
        "wizards/mrp_consumption_warning_views.xml",
        "wizards/mrp_production_split.xml",
        "wizards/mrp_production_serial_numbers.xml",
        "views/stock_move_views.xml",
        "reports/mrp_report_views_main.xml",
        "views/mrp_workorder_views.xml",
        "views/mrp_workcenter_views.xml",
        "views/mrp_bom_views.xml",
        "views/mrp_production_views.xml",
        "views/mrp_routing_views.xml",
        "views/product_document_views.xml",
        "views/product_views.xml",
        "views/stock_orderpoint_views.xml",
        "views/stock_warehouse_views.xml",
        "views/stock_picking_views.xml",
        "views/stock_rule_views.xml",
        "views/mrp_unbuild_views.xml",
        "views/res_config_settings_views.xml",
        "views/stock_scrap_views.xml",
        "wizards/stock_replenishment_info.xml",
        "reports/report_deliveryslip.xml",
        "reports/mrp_report_bom_structure.xml",
        "reports/mrp_report_mo_overview.xml",
        "reports/mrp_production_templates.xml",
        "reports/report_stock_reception.xml",
        "reports/report_stock_rule.xml",
        "reports/mrp_zebra_production_templates.xml",
        "reports/mrp_workorder_templates.xml",
        "views/mrp_menus.xml",
    ],
    "demo": [
        "demo/mrp_demo.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "mrp/static/src/**/*",
        ],
        "web.assets_tests": [
            "mrp/static/tests/tours/**/*",
        ],
        "web.assets_unit_tests": [
            "mrp/static/tests/**/*",
            (
                "remove",
                "mrp/static/tests/tours/**/*",
            ),
        ],
    },
    "application": True,
    "pre_init_hook": "_pre_init_mrp",
    "post_init_hook": "_create_warehouse_data",
    "uninstall_hook": "uninstall_hook",
}
