from . import base_module_update
from . import base_language_install
from . import base_import_language
from . import base_module_upgrade
from . import base_module_uninstall
from . import base_export_language
from . import base_partner_merge
from . import change_password
from . import reset_view_arch
from . import wizard_ir_model_menu_create
