# Part of Odoo. See LICENSE file for full copyright and licensing details.
from . import common_setup_methods
from . import test_point_of_sale_flow
from . import test_frontend
from . import test_backend
from . import test_digest
from . import test_performances
from . import test_point_of_sale_ui
from . import test_point_of_sale
from . import test_pos_controller
from . import test_pos_invoice_consolidation
from . import test_pos_cash_difference_tax
from . import test_pos_cash_rounding
from . import test_pos_setup
from . import test_pos_basic_config
from . import test_pos_products_with_tax
from . import test_pos_margin
from . import test_pos_other_currency_config
from . import test_report_pos_order
from . import test_report_session
from . import test_res_config_settings
from . import test_pos_product_variants
from . import test_generic_localization
from . import test_order_receipt
from . import test_pos_accounting
from . import test_pos_accounting_http
