from . import common_setup_methods
from . import test_common_harness
from . import test_point_of_sale_flow
from . import test_frontend
from . import test_performances
from . import test_point_of_sale_ui
from . import test_anglo_saxon
from . import test_continental
from . import test_point_of_sale
from . import test_pos_controller
from . import test_pos_invoice_consolidation
from . import test_pos_cash_rounding
from . import test_pos_setup
from . import test_pos_access_rights
from . import test_pos_cash_in_out
from . import test_pos_order_lookup
from . import test_pos_robustness
from . import test_pos_simple_orders
from . import test_pos_simple_invoiced_orders
from . import test_pos_basic_config
from . import test_pos_products_with_tax
from . import test_pos_margin
from . import test_pos_order_line_pricing
from . import test_pos_multiple_receivable_accounts
from . import test_pos_other_currency_config
from . import test_pos_with_fiscal_position
from . import test_pos_stock_account
from . import test_pos_stock_display
from . import test_report_pos_order
from . import test_report_session
from . import test_res_config_settings
from . import test_pos_product_variants
from . import test_pos_product_template
from . import test_generic_localization
from . import test_pos_accounting_units
from . import test_pos_closing_rounding
from . import test_pos_invoice_guards
from . import test_pos_session_concurrency
from . import test_pos_order_costing
from . import test_pos_order_unit_cost
from . import test_pos_picking
from . import test_pos_sale_details
from . import test_zzz_audit
from . import test_zzz_audit2

from . import test_js
from . import test_zzz_audit3
from . import test_zzz_audit4
from . import test_pos_load_scoping
from . import test_esm_registration

from . import test_pos_data_integrity
from . import test_pos_ticket_validation
from . import test_pos_session_contracts
from . import test_pos_config_audit
from . import test_pos_config_challenge
from . import test_pos_config_provisioning
from . import test_pos_config_synchronization
from . import test_pos_wizards

from . import test_pos_model_regressions
from . import test_pos_order_audit
from . import test_pos_session_audit
from . import test_pos_session_closing_integrity
from . import test_pos_session_amounts
from . import test_pos_session_challenge
