from . import assets
from . import base_partner_merge
from . import html_text_processor
from . import ir_actions_server
from . import ir_asset
from . import ir_attachment
from . import ir_binary
from . import ir_http
from . import ir_model
from . import ir_model_data
from . import ir_module_module
from . import ir_qweb
from . import ir_qweb_fields
from . import mixin_website_seo_metadata
from . import mixin_website_cover_properties
from . import mixin_website_page_visibility_options
from . import mixin_website_page_options
from . import mixin_website_multi
from . import mixin_website_published
from . import mixin_website_published_multi
from . import mixin_website_searchable
from . import models
from . import website
from . import website_configurator
from . import website_search
from . import website_menu
from . import website_page_properties
from . import website_page
from . import website_rewrite
from . import ir_access
from . import ir_ui_menu
from . import ir_ui_view
from . import res_company
from . import res_partner
from . import res_users
from . import res_config_settings
from . import res_lang
from . import theme_models
from . import website_configurator_feature
from . import website_form
from . import website_snippet_filter
from . import website_visitor
from . import website_controller_page
from . import website_technical_page
