<definitions name="Ship" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:ns="http://www.dhl.com" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" targetNamespace="http://www.dhl.com">
  <types>
      <xsd:schema>
        <xsd:import namespace="http://www.dhl.com" schemaLocation="ship-val-global-req-10.0.xsd"/>
        <xsd:import namespace="http://www.dhl.com" schemaLocation="ship-val-global-res-10.0.xsd"/>
        <xsd:import namespace="http://www.dhl.com" schemaLocation="ship-val-err-res-10.0.xsd"/>
        <xsd:import namespace="http://www.dhl.com" schemaLocation="err-res.xsd"/>
      </xsd:schema>
  </types>
</definitions>
