from . import mail_alias
from . import mail_alias_domain
from . import base

from . import mixin_delay
from . import mixin_mail_activity
from . import mixin_mail_alias_optional
from . import mixin_mail_alias
from . import mixin_mail_presence
from . import mixin_mail_render
from . import mixin_mail_composer
from . import mixin_mail_gateway
from . import mixin_mail_thread
from . import mixin_mail_thread_blacklist
from . import mixin_mail_thread_cc
from . import mixin_mail_thread_main_attachment
from . import mixin_mail_tracking_duration
from . import mixin_store_sync
from . import mixin_template_reset

from . import fetchmail_server
from . import mixin_mail_attachment_owner
from . import mail_notification
from . import mail_activity_type
from . import mail_activity
from . import mail_activity_plan
from . import mail_activity_plan_template
from . import mail_blacklist
from . import mail_followers
from . import mail_followers_access
from . import mail_gateway_allowed
from . import mail_link_preview
from . import mail_message_link_preview
from . import mail_message_reaction
from . import mail_message_schedule
from . import mail_message_subtype
from . import mail_message_translation
from . import mail_message
from . import mail_message_access
from . import mail_message_store
from . import mail_message_fetch
from . import mail_mail
from . import mail_presence
from . import mail_push
from . import mail_push_device
from . import mail_scheduled_message
from . import mail_tracking_value
from . import mail_template

from . import mail_ice_server
from . import mail_canned_response
from . import res_users_settings
from . import res_users_settings_volumes

from . import ir_actions_server
from . import ir_attachment
from . import ir_config_parameter
from . import ir_cron
from . import ir_http
from . import ir_mail_server
from . import ir_model
from . import ir_model_fields
from . import ir_ui_menu
from . import ir_ui_view
from . import ir_qweb
from . import ir_websocket
from . import mail_config
from . import res_company
from . import res_config_settings
from . import res_role
from . import res_users
from . import update

from . import discuss

from . import res_partner
