import json
import logging as logger
import typing
from datetime import UTC, datetime
from typing import Literal

from odoo import _, api, fields, models
from odoo.exceptions import UserError
from odoo.libs.debug_log import DebugLog

from ..tools.jwt import InvalidVapidError, generate_vapid_keys
from ..tools.web_push import decode_browser_keys

if typing.TYPE_CHECKING:
    from .res_partner import ResPartner

_logger = logger.getLogger(__name__)
_debug = DebugLog(__name__)

MAX_DEVICES_PER_PARTNER = 20


class MailPushDevice(models.Model):
    _name = "mail.push.device"
    _description = "Push Notification Device"

    partner_id: ResPartner = fields.Many2one(
        comodel_name="res.partner",
        default=lambda self: self.env.user.partner_id,
        index=True,
        required=True,
    )
    endpoint = fields.Char(
        string="Browser endpoint",
        required=True,
    )
    keys = fields.Char(
        string="Browser keys",
        required=True,
        help="It's refer to browser keys used by the notification: \n"
        "- p256dh: It's the subscription public key generated by the browser. The browser will \n"
        "          keep the private key secret and use it for decrypting the payload\n"
        "- auth: The auth value should be treated as a secret and not shared outside of Odoo",
    )
    expiration_time = fields.Datetime(string="Expiration Token Date")

    _endpoint_unique = models.Constraint(
        "unique(endpoint)",
        "The endpoint must be unique !",
    )

    @api.model
    def get_or_create_web_push_vapid_public_key(self) -> str | bool:
        ir_params_sudo = self.env["ir.config_parameter"].sudo()
        credentials = self.env["credential.credential"]
        public_key = "mail.web_push_vapid_public_key"
        private_key = "mail.web_push_vapid_private_key"
        public_key_value = ir_params_sudo.get_param(public_key)
        if public_key_value and credentials._has_system_secret(private_key):
            return public_key_value
        if not credentials._is_encryption_key_configured():
            _logger.warning(
                "WebPush: VAPID keys need ODOO_API_ENCRYPTION_KEY, push is off"
            )
            return False
        devices = self.sudo().search([])
        _debug.lifecycle("vapid_keys_generated", devices_dropped=len(devices))
        devices.unlink()
        private_key_value, public_key_value = generate_vapid_keys()
        credentials._set_system_secret(private_key, private_key_value)
        ir_params_sudo.set_param(public_key, public_key_value)
        _logger.info("WebPush: missing VAPID key, new VAPID keys generated")
        return public_key_value

    @api.model
    def register_devices(self, **kw) -> None:
        sw_vapid_public_key = kw.get("vapid_public_key")
        valid_sub = self._is_vapid_public_key_current(sw_vapid_public_key)
        if not valid_sub:
            _debug.logic("register_refused", reason="stale_vapid_key", uid=self.env.uid)
            raise InvalidVapidError("Invalid VAPID public key")
        endpoint = kw.get("endpoint")
        browser_keys = kw.get("keys")
        if not endpoint or not browser_keys:
            return
        try:
            decode_browser_keys(browser_keys)
        except ValueError as error:
            raise UserError(
                _("Invalid push subscription keys: %(reason)s", reason=error)
            ) from error
        expiration_time = self._parse_expiration_time(
            kw.get("expirationTime", kw.get("expiration_time"))
        )
        search_endpoint = (
            kw.get("previousEndpoint") or kw.get("previous_endpoint") or endpoint
        )
        partner = self.env.user.partner_id
        mail_push_device = self.sudo().search(
            [("endpoint", "=", search_endpoint), ("partner_id", "=", partner.id)]
        )
        if mail_push_device:
            conflicting = self.sudo().search(
                [("endpoint", "=", endpoint), ("id", "!=", mail_push_device.id)]
            )
            _debug.lifecycle(
                "device_updated",
                device=mail_push_device.id,
                partner=partner.id,
                moved=search_endpoint != endpoint,
                conflicting=len(conflicting),
            )
            if conflicting:
                conflicting.unlink()
            mail_push_device.write(
                {
                    "endpoint": endpoint,
                    "expiration_time": expiration_time,
                    "keys": json.dumps(browser_keys),
                }
            )
        elif not self.sudo().search_count([("endpoint", "=", endpoint)], limit=1):
            self.sudo().create(
                [
                    {
                        "endpoint": endpoint,
                        "expiration_time": expiration_time,
                        "keys": json.dumps(browser_keys),
                        "partner_id": partner.id,
                    }
                ]
            )
            devices = self.sudo().search(
                [("partner_id", "=", partner.id)], order="id desc"
            )
            _debug.lifecycle(
                "device_registered",
                partner=partner.id,
                devices=len(devices),
                pruned=max(len(devices) - MAX_DEVICES_PER_PARTNER, 0),
            )
            if len(devices) > MAX_DEVICES_PER_PARTNER:
                devices[MAX_DEVICES_PER_PARTNER:].unlink()

    @api.model
    def unregister_devices(self, **kw) -> None:
        endpoint = kw.get("endpoint")
        if not endpoint:
            return
        mail_push_device = self.sudo().search(
            [
                ("endpoint", "=", endpoint),
                ("partner_id", "=", self.env.user.partner_id.id),
            ]
        )
        _debug.lifecycle(
            "device_unregistered",
            partner=self.env.user.partner_id.id,
            found=bool(mail_push_device),
        )
        if mail_push_device:
            mail_push_device.unlink()

    @api.model
    def _parse_expiration_time(self, value: typing.Any) -> datetime | Literal[False]:
        if value in (None, False, ""):
            return False
        if isinstance(value, int | float):
            try:
                return datetime.fromtimestamp(value / 1000, tz=UTC).replace(tzinfo=None)
            except (OverflowError, OSError, ValueError) as error:
                raise UserError(
                    _(
                        "Invalid push subscription expiration time %(value)s",
                        value=value,
                    )
                ) from error
        return fields.Datetime.to_datetime(value)

    def _is_vapid_public_key_current(self, sw_public_key: str) -> bool:
        ir_params_sudo = self.env["ir.config_parameter"].sudo()
        db_public_key = ir_params_sudo.get_param("mail.web_push_vapid_public_key")
        return db_public_key == sw_public_key
