//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by dialogs.rc
//
#define IDD_MANAGER                     101
#define IDD_TRAINING                    102
#define IDD_FILTER                      103
#define IDD_FILTER_NOW                  104
#define IDD_FOLDER_SELECTOR             105
#define IDD_ABOUT                    	106
#define IDD_GENERAL                     108

//#define IDD_FILTER_SPAM                 110
#define IDD_FILTER_UNSURE               111
#define IDD_DIAGNOSTIC                  113
#define IDD_WIZARD                      114
#define IDD_WIZARD_WELCOME              115
#define IDD_WIZARD_FINISHED_UNTRAINED   116
#define IDD_WIZARD_FOLDERS_REST         117
#define IDD_WIZARD_FOLDERS_WATCH        118
#define IDD_WIZARD_FINISHED_UNCONFIGURED 119
#define IDD_WIZARD_FOLDERS_TRAIN        120
#define IDD_WIZARD_TRAIN                121
#define IDD_WIZARD_FINISHED_TRAINED     122
#define IDD_WIZARD_TRAINING_IS_IMPORTANT 123
#define IDD_WIZARD_FINISHED_TRAIN_LATER 124
#define IDB_SBWIZLOGO                   125
#define IDB_FOLDERS                     127
#define IDC_PROGRESS                    1000
#define IDC_PROGRESS_TEXT               1001
#define IDC_STATIC_HAM                  1002
#define IDC_STATIC_SPAM                 1003
#define IDC_BROWSE_HAM                  1004
#define IDC_BROWSE_SPAM                 1005
#define IDC_START                       1006
#define IDC_BUT_REBUILD                 1007
#define IDC_BUT_RESCORE                 1008
#define IDC_VERSION                     1009
#define IDC_BUT_TRAIN_FROM_SPAM_FOLDER  1010
#define IDC_BUT_TRAIN_TO_SPAM_FOLDER    1011
#define IDC_BUT_TRAIN_NOW               1012
#define IDC_BUT_FILTER_ENABLE           1013
#define IDC_FILTER_STATUS               1014
#define IDC_BUT_FILTER_DEFINE           1016
#define IDC_BUT_ABOUT                   1017
#define IDC_BUT_ACT_SCORE               1018
#define IDC_BUT_ACT_ALL                 1019
#define IDC_BUT_UNREAD                  1020
#define IDC_BUT_UNSEEN                  1021
#define IDC_SLIDER_CERTAIN              1023
#define IDC_EDIT_CERTAIN                1024
#define IDC_ACTION_CERTAIN              1025
#define IDC_FOLDER_CERTAIN              1027
#define IDC_BROWSE_CERTAIN              1028
#define IDC_SLIDER_UNSURE               1029
#define IDC_EDIT_UNSURE                 1030
#define IDC_ACTION_UNSURE               1031
#define IDC_FOLDER_UNSURE               1033
#define IDC_BROWSE_UNSURE               1034
#define IDC_TRAINING_STATUS             1035
#define IDC_FOLDER_NAMES                1036
#define IDC_BROWSE                      1037
#define IDC_FOLDER_WATCH                1038
#define IDC_BROWSE_WATCH                1039
#define IDC_LIST_FOLDERS                1040
#define IDC_BUT_SEARCHSUB               1041
#define IDC_BUT_CLEARALL                1042
#define IDC_STATUS1                     1043
#define IDC_STATUS2                     1044
#define IDC_BUT_NEW                     1046
#define IDC_MARK_SPAM_AS_READ           1047
#define IDC_SAVE_SPAM_SCORE             1048
#define IDC_MARK_UNSURE_AS_READ         1051
#define IDC_DELAY1_SLIDER               1056
#define IDC_DELAY1_TEXT                 1057
#define IDC_DELAY2_SLIDER               1058
#define IDC_DELAY2_TEXT                 1059
#define IDC_INBOX_TIMER_ONLY            1060
#define IDC_VERBOSE_LOG                 1061
#define IDB_OPENERPLOGO                 1062
#define IDC_TAB                         1068
#define IDC_BACK_BTN                    1069
#define IDC_BUT_WIZARD                  1070
#define IDC_SHOW_DATA_FOLDER            1071
#define IDC_ABOUT_BTN                   1072
#define IDC_BUT_RESET                   1073
#define IDC_DEL_SPAM_RS                 1074
#define IDC_RECOVER_RS                  1075
#define IDC_FORWARD_BTN                 1077
#define IDC_PAGE_PLACEHOLDER            1078
#define IDC_BUT_SHOW_DIAGNOSTICS        1080
#define IDC_BUT_PREPARATION             1081
#define IDC_FOLDER_HAM                  1083
#define IDC_BUT_UNTRAINED               1088
#define IDC_BUT_TRAIN                   1089
#define IDC_BUT_TIMER_ENABLED           1091
#define IDC_WIZ_GRAPHIC                 1092
#define IDC_BUT_VIEW_LOG                1093
#define IDC_EDIT1                       1094
#define IDC_STATISTICS                  1095

#define ID_SERVER						2001
#define ID_PORT							2002
#define ID_SERVER_PORT					2003
#define ID_DB_DROPDOWNLIST				2004
#define ID_USERNAME						2005
#define ID_PASSWORD						2006
#define ID_BUT_TESTCONNECTION			2007
#define ID_DONE							2008
#define IDD_OBJECT_SETTINGS				2009
#define IDC_BUT_LOAD_IMAGE				2010
#define	IDC_BUT_SAVE_OBJECT				2011
#define IDC_BUT_DEL_OBJECT				2012
#define IDC_OBJECT_TITLE				2013
#define IDC_OBJECT_NAME					2014
#define IDC_IMAGE_PATH					2015
#define IDC_LIST						2016
#define IDC_HEADER						2017
#define ID_CREATE_CONTACT				2018
#define ID_MAKE_ATTACHMENT				2019
#define ID_CREATE_CASE					2020
#define IDC_BUT_SET_SERVER_PORT			2021
#define IDD_SERVER_PORT_DIALOG			2022
#define IDC_CHKBX						2023
#define IDC_STATIC_GROUP				2024
#define ID_ATT_METHOD_DROPDOWNLIST		2025
#define IDC_NAME_LIST					2026
#define IDD_ABOUT						2027
#define IDC_ABOUT						2028
#define IDC_CONTACT_LIST				2029
#define ID_NAME_TEXT					2030
#define IDD_NEW_CONTACT_DIALOG			2031
#define ID_PARTNER_DROPDOWNLIST			2032
#define ID_NEW_PARTNER_BUTTON			2033
#define IDD_NEW_PARTNER_DIALOG			2034
#define ID_SAVE_PARTNER_BUTTON			2035
#define ID_PARTNER_NAME_TEXT			2036
#define IDC_NAME_LIST1					2037
#define IDC_RELOAD						2038
#define ID_PROTOCOL_GRP					2040
#define IDR_XML_PROTOCOL				2041
#define IDR_XMLS_PROTOCOL				2042
#define IDR_NETRPC_PROTOCOL				2043
#define IDD_VIEW_PARTNER_DIALOG			2044
#define IDET_PARTNER_NAME				2045
#define IDET_PARTNER_CONTACT_NAME   	2046
#define IDET_PARTNER_EMAIL				2047
#define IDET_PARTNER_OFFICENO			2048
#define	IDET_PARTNER_MOBILENO			2050
#define IDET_SEARCH_PARTNER    			2051
#define IDPB_SEARCH_PARTNER  			2052
#define IDET_PARTNER_STREET				2053
#define	IDET_PARTNER_STREET2			2054
#define IDET_PARTNER_COUNTRY			2057
#define IDET_PARTNER_FAX				2058
#define IDPB_WRITE_CHANGES				2059
#define ID_ALL_STATE_DROPDOWNLIST		2060
#define ID_ALL_COUNTRY_DROPDOWNLIST		2061
#define IDET_PARTNER_STATE				2062
#define IDET_PARTNER_COUNTRY			2063
#define IDET_PARTNER					2064
//
#define ID_STREET_TEXT					2062
#define ID_STREET2_TEXT					2063
#define ID_FED_STATE_DROPLIST			2064
#define ID_COUNTRY_DROPLIST				2065
#define ID_FAX_TEXT						2066
#define ID_PARTNER_CITY_TEXT			2067
#define ID_ZIP_TEXT						2068
#define ID_PARTNER_DROPLIST				2069
#define ID_NEW_PART_BUTTON				2070
#define IDPB_NEWPARTNER_BUTTON			2071
#define IDD_SELECT_PARTNER				2073
#define IDC_LIST_PARTNER				2072
#define IDPB_SELECT_PARTNER				2075
#define IDET_PARTNER_SEARCH_NAME		2076
#define IDPB_PARTNER_SEARCH				2077
#define IDPB_CREATE_NEW_PARTNER			2078
#define ID_PARTNER_TEXT					2079
#define IDET_WED_SERVER					2080
#define IDET_WEB_PORT					2081
#define ID_SET_WEB_CONNECTION			2082
#define IDPB_WEB_CONNECTION				2083
#define IDD_OPEN_PARTNER_DIALOG			2084
#define IDET_PARTNER_LINK_TEXT			2085
#define IDEB_OPENDOC_LINK_TEXT			2086
#define IDD_OPEN_DOCUEMNT_DIALOG		2087
#define IDD_WEB_SERVER_PORT_DIALOG		2088
#define IDET_WEB_SERVER					2089
#define IDET_WEB_PORT					2090
#define ID_WEB_OK						2091
#define IDPB_NEW_PARTNER_BUTTON			2092
#define IDPB_NEW_PART_BUTTON			2093
#define	IDD_SELECT_COUNTRY				2094
#define IDET_COUNTRY_SEARCH_NAME		2095
#define IDC_LIST_COUNTRY				2096
#define IDPB_SELECT_COUNTRY				2097
#define IDPB_SEARCH_COUNTRY				2098
#define	IDD_SELECT_STATE				2099
#define IDET_STATE_SEARCH_NAME			2100
#define IDC_LIST_STATE					2101
#define IDPB_SELECT_STATE				2102
#define IDPB_SEARCH_STATE				2103
#define IDPB_SEARCH_STATE1				2104
#define IDPB_SEARCH_COUNTRY1			2105

#define IDET_NC_PARTNER_STATE			2106
#define IDPB_NC_SEARCH_STATE1			2107
#define IDET_NC_PARTNER_COUNTRY			2108
#define IDPB_NC_SEARCH_COUNTRY1			2109
// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        128
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1096
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif


