from . import test_access_rights
from . import test_burndown_chart
from . import test_js
from . import test_project_base
from . import test_project_config
from . import test_project_embedded_action_settings
from . import test_project_flow
from . import test_project_mail_features
from . import test_project_milestone
from . import test_project_profitability
from . import test_project_recurrence
from . import test_project_sharing
from . import test_project_sharing_portal_access
from . import test_project_sharing_ui
from . import test_project_stage_multicompany
from . import test_project_subtasks
from . import test_project_tags_filter
from . import test_project_workflow_step
from . import test_get_template_tasks_version
from . import test_project_template
from . import test_project_template_ui
from . import test_project_ui
from . import test_project_update_access_rights
from . import test_project_update_flow
from . import test_project_update_ui
from . import test_portal
from . import test_multicompany
from . import test_personal_stages
from . import test_pm_models
from . import test_task_dependencies
from . import test_task_follow
from . import test_task_templates
from . import test_task_templates_ui
from . import test_task_tracking
from . import test_project_report
from . import test_project_task_quick_create
from . import test_task_state
from . import test_project_task_mail_tracking_duration
from . import test_task_link_preview_name
from . import test_import_files
from . import test_task_reservation
from . import test_digest
from . import test_planned_hours
from . import test_project_metrics
from . import test_resource_levelling
from . import test_task_archiving
from . import test_task_triage_lifecycle
from . import test_burnup_history
from . import test_cfd_report
from . import test_critical_path
from . import test_dependency_blocking
from . import test_elapsed_metrics
from . import test_forecast_wizard
from . import test_portal_field_access
from . import test_project_dates
from . import test_share_wizard
from . import test_sprint_commitment
from . import test_tag_uniqueness
from . import test_task_closure
from . import test_workflow_step_lifecycle
from . import test_project_duplication
from . import test_status_change_stamp
from . import test_phase_mail_template
from . import test_project_dates_alias
from . import test_workflow_step_state
from . import test_planning_overlap
from . import test_task_planning_flow
from . import test_task_state_on_create
from . import test_project_access
from . import test_rating_stats
from . import test_rating_mixin_collision
