{
    'name': 'Social Share',
    'version': '1.0',
    'category': 'Marketing/Social Marketing',
    'summary': 'Generate dynamic shareable cards',
    'depends': ['link_tracker'],
    'data': [
        'security/social_share_security.xml',
        'security/ir.model.access.csv',
        'data/font_data.xml',
        'data/model_field_allow_list.xml',
        'data/share_campaign_template_1_data.xml',
        'data/share_campaign_template_2_data.xml',
        'views/share_campaign_views.xml',
        'views/share_campaign_render_element_views.xml',
        'views/share_campaign_template_views.xml',
        'views/share_campaign_template_element_views.xml',
        'views/share_campaign_templates_frontend.xml',
        'views/social_share_field_allow_views.xml',
        'views/text_font_views.xml',
        'views/social_share_menus.xml',
        'views/url_views.xml',
        'wizards/share_url_views.xml',
        'wizards/share_url_multi_views.xml',
    ],
    'assets': {
        'social_share.assets_share_campaign': [
            'social_share/static/src/share_campaign/**/*',
        ],
    },
    'application': True,
    'installable': True,
    'license': 'LGPL-3',
}
