from . import eg_account_journal
from . import eg_attribute_value
from . import eg_product_attribute
from . import eg_product_category
from . import eg_product_product
from . import eg_product_template
from . import eg_res_partner
from . import eg_sale_order
from . import product_template
from . import woo_product_coupon
from . import woo_tax_rate
from . import eg_ecom_instance
from . import order_state_line
from . import res_config_settings
from . import sale_order
from . import woo_tax_class
