{
    "name": "GRP - Gestão de Processos",
    "version": "19.0.4.0.0",
    "category": "Government",
    "depends": ["gov_base", "mail", "base_automation", "web"],
    "data": [
        "security/ir.model.access.csv",
        "data/gov_ai_template_seed.xml",
        "data/gov_ai_template_procurement_seed.xml",
        "data/gov_ai_template_direct_seed.xml",
        "data/gov_ai_quality_policy_seed.xml",
        "data/gov_timbre_seed.xml",
        "views/gov_ai_provider_views.xml",
        "views/gov_ai_memory_views.xml",
        "views/gov_ai_run_views.xml",
        "views/gov_ai_memory_ingest_wizard_views.xml",
        "views/gov_ai_template_views.xml",
        "views/gov_ai_quality_policy_views.xml",
        "views/gov_ai_orchestrator_views.xml",
        "views/gov_processo_doc_views.xml",
        "views/gov_processo_dotacao_views.xml",
        "views/gov_dotacao_wizard_views.xml",
        "views/gov_processo_fase_wizard_views.xml",
        "views/gov_processo_views.xml",
        "views/gov_dashboard_views.xml",
        "views/gov_dashboard_action.xml",
        "views/gov_relatorio_wizard_views.xml",
        "views/gov_timbre_views.xml",
        "views/gov_siafi_wizard_views.xml",
        "views/gov_execucao_wizard_views.xml",
        "views/gov_processo_wizard.xml",
        "views/gov_processo_tramite_wizard.xml",
        "views/gov_processo_menus.xml",
        "data/gov_processo_sequence.xml",
        "data/gov_processo_cron.xml",
        "data/gov_automation_rules.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "gov_processos/static/src/css/gov_dashboard.css",
            "gov_processos/static/src/css/gov_processo_wizard.css",
            "gov_processos/static/src/js/gov_dashboard.js",
            "gov_processos/static/src/js/gov_processo_form_ui.js",
            "gov_processos/static/src/xml/gov_dashboard.xml",
        ],
    },
    "installable": True,
    "application": True,
    "author": "GRP",
    "license": "LGPL-3",
}

