# -*- coding: utf-8 -*-
# Generated by marathon_ventures Salesforce->Odoo migration generator.
# Do not edit by hand if you plan to regenerate; instead update the SF metadata
# and re-run the generator.

import logging
import re
from odoo import models, fields, api, _
from odoo.exceptions import ValidationError

_logger = logging.getLogger(__name__)


class MvBundlePricing(models.Model):
    _name = 'mv.bundle_pricing'
    _description = 'Bundle Pricing'
    # === Identification ===
    name = fields.Char(string='Bundle Daypart Pricing Name', default=lambda self: self.env['ir.sequence'].next_by_code('mv.bundle_pricing.name') or 'New', copy=False, readonly=True)
    sf_external_id = fields.Char(string='SF External ID', index=True, copy=False)
    sf_legacy_data = fields.Json(string='SF Legacy Payload')
    currency_id = fields.Many2one('res.currency', string='Currency', default=lambda self: self.env.company.currency_id)

    # === SF Custom Fields ===
    active = fields.Boolean(string='Active?')  # SF: Active__c
    call_letters = fields.Char(string='Call Letters', compute='_compute_call_letters', store=True)  # SF: Call_Letters__c
    days = fields.Many2many(string='Days', comodel_name='mv.days.tag', relation='mv_bundle_pricing_days_rel')  # SF: Days__c
    edited_days = fields.Char(string='Edited Days', compute='_compute_edited_days', store=True)  # SF: Edited_Days__c
    end_time = fields.Selection(string='End Time', selection=[('v_01_00a', '01:00A'), ('v_01_30a', '01:30A'), ('v_01_35a', '01:35A'), ('v_02_00a', '02:00A'), ('v_02_30a', '02:30A'), ('v_03_00a', '03:00A'), ('v_03_30a', '03:30A'), ('v_04_00a', '04:00A'), ('v_04_30a', '04:30A'), ('v_05_00a', '05:00A'), ('v_05_30a', '05:30A'), ('v_06_00a', '06:00A'), ('v_06_30a', '06:30A'), ('v_07_00a', '07:00A'), ('v_07_30a', '07:30A'), ('v_08_00a', '08:00A'), ('v_08_30a', '08:30A'), ('v_09_00a', '09:00A'), ('v_09_30a', '09:30A'), ('v_10_00a', '10:00A'), ('v_10_30a', '10:30A'), ('v_11_00a', '11:00A'), ('v_11_30a', '11:30A'), ('v_12_00p', '12:00P'), ('v_12_30p', '12:30P'), ('v_01_00p', '01:00P'), ('v_01_30p', '01:30P'), ('v_02_00p', '02:00P'), ('v_02_30p', '02:30P'), ('v_03_00p', '03:00P'), ('v_03_30p', '03:30P'), ('v_04_00p', '04:00P'), ('v_04_30p', '04:30P'), ('v_05_00p', '05:00P'), ('v_05_30p', '05:30P'), ('v_06_00p', '06:00P'), ('v_06_30p', '06:30P'), ('v_07_00p', '07:00P'), ('v_07_30p', '07:30P'), ('v_08_00p', '08:00P'), ('v_08_30p', '08:30P'), ('v_09_00p', '09:00P'), ('v_09_30p', '09:30P'), ('v_10_00p', '10:00P'), ('v_10_30p', '10:30P'), ('v_11_00p', '11:00P'), ('v_11_30p', '11:30P'), ('v_12_00a', '12:00A'), ('v_12_30a', '12:30A'), ('v_12_00x', '12:00X'), ('v_12_30x', '12:30X'), ('v_01_00x', '01:00X'), ('v_01_30x', '01:30X'), ('v_02_00x', '02:00X'), ('v_02_30x', '02:30X'), ('v_03_00x', '03:00X'), ('v_03_30x', '03:30X'), ('v_04_00x', '04:00X'), ('v_04_30x', '04:30X'), ('v_05_00x', '05:00X'), ('v_05_30x', '05:30X'), ('v_06_00x', '06:00X')])  # SF: End_Time__c | SF Unrestricted picklist
    group = fields.Selection(string='Group', selection=[('group_1', 'Group 1'), ('group_2', 'Group 2'), ('group_3', 'Group 3'), ('group_4', 'Group 4'), ('group_5', 'Group 5'), ('group_6', 'Group 6')])  # SF: Group__c | SF Unrestricted picklist
    market = fields.Char(string='Market', compute='_compute_market', store=True)  # SF: Market__c
    program = fields.Many2one(string='Program', comodel_name='mv.programs', ondelete='cascade', required=True)  # SF: Program__c
    rate_per_30 = fields.Monetary(string='Rate per 30', currency_field='currency_id', required=True)  # SF: Rate_per_30__c
    start_end_time = fields.Char(string='Start End Time', compute='_compute_start_end_time', store=True)  # SF: Start_End_Time__c
    start_time = fields.Selection(string='Start Time', selection=[('v_01_00a', '01:00A'), ('v_01_30a', '01:30A'), ('v_01_35a', '01:35A'), ('v_02_00a', '02:00A'), ('v_02_30a', '02:30A'), ('v_03_00a', '03:00A'), ('v_03_30a', '03:30A'), ('v_04_00a', '04:00A'), ('v_04_30a', '04:30A'), ('v_05_00a', '05:00A'), ('v_05_30a', '05:30A'), ('v_06_00a', '06:00A'), ('v_06_30a', '06:30A'), ('v_07_00a', '07:00A'), ('v_07_30a', '07:30A'), ('v_08_00a', '08:00A'), ('v_08_30a', '08:30A'), ('v_09_00a', '09:00A'), ('v_09_30a', '09:30A'), ('v_10_00a', '10:00A'), ('v_10_30a', '10:30A'), ('v_11_00a', '11:00A'), ('v_11_30a', '11:30A'), ('v_12_00p', '12:00P'), ('v_12_30p', '12:30P'), ('v_01_00p', '01:00P'), ('v_01_30p', '01:30P'), ('v_02_00p', '02:00P'), ('v_02_30p', '02:30P'), ('v_03_00p', '03:00P'), ('v_03_30p', '03:30P'), ('v_04_00p', '04:00P'), ('v_04_30p', '04:30P'), ('v_05_00p', '05:00P'), ('v_05_30p', '05:30P'), ('v_06_00p', '06:00P'), ('v_06_30p', '06:30P'), ('v_07_00p', '07:00P'), ('v_07_30p', '07:30P'), ('v_08_00p', '08:00P'), ('v_08_30p', '08:30P'), ('v_09_00p', '09:00P'), ('v_09_30p', '09:30P'), ('v_10_00p', '10:00P'), ('v_10_30p', '10:30P'), ('v_11_00p', '11:00P'), ('v_11_30p', '11:30P'), ('v_12_00a', '12:00A'), ('v_12_30a', '12:30A'), ('v_12_00x', '12:00X'), ('v_12_30x', '12:30X'), ('v_01_00x', '01:00X'), ('v_01_30x', '01:30X'), ('v_02_00x', '02:00X'), ('v_02_30x', '02:30X'), ('v_03_00x', '03:00X'), ('v_03_30x', '03:30X'), ('v_04_00x', '04:00X'), ('v_04_30x', '04:30X'), ('v_05_00x', '05:00X'), ('v_05_30x', '05:30X')])  # SF: Start_Time__c | SF Unrestricted picklist
    station = fields.Many2one(string='Station', comodel_name='mv.station', ondelete='restrict', required=True)  # SF: Station__c
    tier = fields.Selection(string='Tier', selection=[('v_1', '1'), ('v_2', '2'), ('v_3', '3'), ('v_4', '4')])  # SF: Tier__c
    total = fields.Monetary(string='Total', currency_field='currency_id', compute='_compute_total', store=True)  # SF: Total__c
    units = fields.Integer(string='Units')  # SF: Units__c

    # === Computed / Roll-Up ===

    @api.depends('station.call_letters')
    def _compute_call_letters(self):
        # SF formula (verbatim, may need translation):
        #   Station__r.Call_Letters__c
        for rec in self:
            # TODO: translate SF formula to Python
            rec.call_letters = rec.station.call_letters or False

    @api.depends('days')
    def _compute_edited_days(self):
        # SF formula (verbatim, may need translation):
        #   if(INCLUDES(Days__c,"Monday"),"M","-")&
        #   if(INCLUDES(Days__c,"Tuesday"),"T","-")&
        #   if(INCLUDES(Days__c,"Wednesday"),"W","-")&
        #   if(INCLUDES(Days__c,"Thursday"),"T","-")&
        #   if(INCLUDES(Days__c,"Friday"),"F","-")&
        #   if(INCLUDES(Days__c,"Saturday"),"S","-")&
        #   if(INCLUDES(Days__c,"Sunday"),"S","-")
        day_map = [
            ('Monday', 'M'),
            ('Tuesday', 'T'),
            ('Wednesday', 'W'),
            ('Thursday', 'T'),
            ('Friday', 'F'),
            ('Saturday', 'S'),
            ('Sunday', 'S'),
        ]
        for rec in self:
            selected = {d.name for d in rec.days}
            rec.edited_days = ''.join(
                letter if day in selected else '-' for day, letter in day_map
            )

    @api.depends('station.market.name')
    def _compute_market(self):
        # SF formula (verbatim, may need translation):
        #   Station__r.Market__r.Name
        for rec in self:
            # TODO: translate SF formula to Python
            rec.market = rec.station.market.name or False

    @api.depends('start_time', 'end_time')
    def _compute_start_end_time(self):
        # SF formula (verbatim, may need translation):
        #   text(Start_Time__c )&"-"&text( End_Time__c )
        start_labels = dict(self._fields['start_time']._description_selection(self.env))
        end_labels = dict(self._fields['end_time']._description_selection(self.env))
        for rec in self:
            start = start_labels.get(rec.start_time, '') if rec.start_time else ''
            end = end_labels.get(rec.end_time, '') if rec.end_time else ''
            rec.start_end_time = '%s-%s' % (start, end)

    @api.depends('rate_per_30', 'units')
    def _compute_total(self):
        # SF formula (verbatim, may need translation):
        #   Rate_per_30__c  *  Units__c
        for rec in self:
            rec.total = (rec.rate_per_30 or 0.0) * (rec.units or 0)
