# -*- coding: utf-8 -*-
# Generated by marathon_ventures Salesforce->Odoo migration generator.
# Do not edit by hand if you plan to regenerate; instead update the SF metadata
# and re-run the generator.

import logging
import re
from odoo import models, fields, api, _
from odoo.exceptions import ValidationError

_logger = logging.getLogger(__name__)


class MvCreditApplication(models.Model):
    _name = 'mv.credit_application'
    _description = 'Credit Application'
    # === Identification ===
    name = fields.Char(string='Credit Application Name', default=lambda self: self.env['ir.sequence'].next_by_code('mv.credit_application.name') or 'New', copy=False, readonly=True)
    sf_external_id = fields.Char(string='SF External ID', index=True, copy=False)
    sf_legacy_data = fields.Json(string='SF Legacy Payload')
    currency_id = fields.Many2one('res.currency', string='Currency', default=lambda self: self.env.company.currency_id)

    # === SF Custom Fields ===
    aor_received = fields.Selection(string='AOR Received', selection=[('yes', 'Yes'), ('no', 'No'), ('n_a', 'N/A')])  # SF: AOR_Received__c | SF Unrestricted picklist
    account = fields.Many2one(string='Account', comodel_name='res.partner', ondelete='restrict')  # SF: Account__c
    active = fields.Boolean(string='Active')  # SF: Active__c
    advertiser_open_balance = fields.Monetary(string='Advertiser Open Balance', currency_field='currency_id')  # SF: Advertiser_Open_Balance__c
    advertiser_website = fields.Char(string='[Dep]Advertiser Website', required=True)  # SF: Advertiser_Website__c
    advertiser = fields.Many2one(string='Advertiser', comodel_name='mv.advertiser', ondelete='restrict')  # SF: Advertiser__c
    agency_log_comments = fields.Text(string='Comments')  # SF: Agency_LOG_Comments__c
    agency_log = fields.Boolean(string='Agency LOG')  # SF: Agency_LOG__c
    agency_website = fields.Char(string='[Dep]Agency Website', required=True)  # SF: Agency_Website__c
    application_status = fields.Selection(string='Application Status', selection=[('submitted', 'Submitted'), ('pending_finance_manager_review', 'Pending Finance Manager Review'), ('complete', 'Complete'), ('pending_upper_management_review', 'Pending Upper Management Review'), ('closed', 'Closed'), ('pending_partner_review', 'Pending Partner Review'), ('pending_controller_review', 'Pending Controller Review')])  # SF: Application_Status__c | SF Unrestricted picklist
    application_submitted = fields.Date(string='Application Submitted')  # SF: Application_Submitted__c
    application_type = fields.Selection(string='Application Type', selection=[('new_advertiser', 'New Advertiser'), ('new_agency', 'New Agency'), ('credit_limit_review', 'Credit Limit Review'), ('new_agency_nosey', 'New Agency - Nosey')])  # SF: Application_Type__c | SF Unrestricted picklist
    avg_days_to_pay_6_months = fields.Integer(string='Avg. Days to Pay (6 months)')  # SF: Avg_Days_to_Pay_6_months__c
    business_type = fields.Many2many(string='Business Type', comodel_name='mv.business_type.tag', relation='mv_credit_application_business_type_rel')  # SF: Business_Type__c
    cs_risk = fields.Integer(string='CS Risk')  # SF: CS_Risk__c
    cs_score = fields.Selection(string='CS Score', selection=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D'), ('e', 'E')])  # SF: CS_Score__c
    cs_trade_lines = fields.Char(string='CS Trade Lines', size=5)  # SF: CS_Trade_Lines__c
    client_information = fields.Text(string='Client Information', help='Please provide details related to company applying for credit. Make sure to identify the industry and brief background of the client.')  # SF: Client_Information__c
    comments = fields.Text(string='Comments (comments)')  # SF: Comments__c
    credit_application = fields.Many2one(string='Credit Application', comodel_name='mv.credit_application', ondelete='set null')  # SF: Credit_Application__c
    credit_granted = fields.Monetary(string='Credit Granted', currency_field='currency_id')  # SF: Credit_Granted__c
    credit_limit_details = fields.Selection(string='Credit Limit Details', selection=[('advertiser', 'Advertiser'), ('agency', 'Agency'), ('cia_agency', 'CIA - Agency'), ('cia_advertiser', 'CIA - Advertiser')])  # SF: Credit_Limit_Details__c
    current_credit_limit = fields.Monetary(string='Current Credit Limit', currency_field='currency_id')  # SF: Current_Credit_Limit__c
    db = fields.Selection(string='DB', selection=[('low', 'Low'), ('low_moderate', 'Low-moderate'), ('moderate', 'Moderate'), ('moderate_high', 'Moderate-high'), ('high', 'High')])  # SF: DB__c
    finance_credit_term_support = fields.Text(string='Finance Credit Term Support', help='Comments used to support terms granted')  # SF: Finance_Credit_Term_Support__c
    finance_recommended_credit = fields.Monetary(string='Finance Recommended Credit', currency_field='currency_id')  # SF: Finance_Recommended_Credit__c
    finance_recommended_terms = fields.Selection(string='Finance Recommended Terms', selection=[('cia', 'CIA'), ('due_upon_receipt', 'Due Upon Receipt'), ('net_10', 'Net 10'), ('net_15', 'Net 15'), ('net_30', 'Net 30'), ('net_45', 'Net 45'), ('net_60', 'Net 60')])  # SF: Finance_Recommended_Terms__c | SF Unrestricted picklist
    finance_review_comments = fields.Text(string='Finance Review Comments', help='These are the comments that will support the review of the credit application process.')  # SF: Finance_Review_Comments__c
    google_search_comments = fields.Text(string='[Dep]Google Search Comments')  # SF: Google_Search_Comments__c
    google_search = fields.Char(string='[Dep]Google Search')  # SF: Google_Search__c
    hold_placed_on_account_advertiser = fields.Boolean(string='HOLD Placed on Account/Advertiser')  # SF: HOLD_Placed_on_Account_Advertiser__c
    log_expiration_date = fields.Date(string='LOG Expiration Date', help='This field preserves the expiration date supplied by the Account in accordance to this Credit Application\'s business relationship.')  # SF: LOG_Expiration_Date__c
    last_sale_date = fields.Char(string='Last Sale Date', size=10)  # SF: Last_Sale_Date__c
    last_year_gross_sales = fields.Monetary(string='Last Year Gross Sales', currency_field='currency_id')  # SF: Last_Year_Gross_Sales__c
    new_credit_limit = fields.Monetary(string='New Credit Limit', currency_field='currency_id')  # SF: New_Credit_Limit__c
    old_credit_limit = fields.Monetary(string='Old Credit Limit', currency_field='currency_id')  # SF: Old_Credit_Limit__c
    open_balance = fields.Monetary(string='Open Balance', currency_field='currency_id', compute='_compute_open_balance', store=True, help='Advertiser Open Balance             or             Account Netsuite Balance (update CIA ispickval to netsuite_balance from balance)')  # SF: Open_Balance__c
    sf_bookings_avg_type = fields.Selection(string='[Dep]SF Bookings (AVG) Type', selection=[('n_a', 'N/A'), ('weekly', 'Weekly'), ('bi_weekly', 'Bi-Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly')])  # SF: SF_Bookings_AVG_Type__c
    sf_bookings_notes = fields.Text(string='[Dep]SF Bookings Notes')  # SF: SF_Bookings_Notes__c
    sf_bookings = fields.Monetary(string='SF Bookings (AVG)', currency_field='currency_id')  # SF: SF_Bookings__c
    sf_ref_id = fields.Char(string='SF Ref ID', compute='_compute_sf_ref_id', store=True)  # SF: SF_Ref_ID__c
    start_date = fields.Char(string='Start Date', size=10)  # SF: Start_Date__c
    terms_granted = fields.Selection(string='Terms Granted', selection=[('cia', 'CIA'), ('due_upon_receipt', 'Due Upon Receipt'), ('net_10', 'Net 10'), ('net_15', 'Net 15'), ('net_30', 'Net 30'), ('net_45', 'Net 45'), ('net_60', 'Net 60')])  # SF: Terms_Granted__c | SF Unrestricted picklist

    # === Computed / Roll-Up ===

    @api.depends('sf_external_id')
    def _compute_open_balance(self):
        # SF formula (verbatim, may need translation):
        #   IF(
        #   ISPICKVAL(Credit_Limit_Details__c , "CIA - Advertiser"),
        #   Advertiser_Open_Balance__c,
        #   IF(
        #   ISPICKVAL(Credit_Limit_Details__c , "CIA - Agency"),
        #   Account__r.Netsuite_Balance__c,
        #   IF(
        #   ISPICKVAL(Credit_Limit_Details__c , "Advertiser"),
        #   Advertiser_Open_Balance__c,
        #   IF(
        #   ISPICKVAL(Credit_Limit_Details__c , "Agency"),
        #   Account__r.Netsuite_Balance__c ,
        #   0
        #   )
        #   )
        #   )
        #   )
        for rec in self:
            # TODO: translate SF formula to Python
            rec.open_balance = False

    @api.depends('sf_external_id')
    def _compute_sf_ref_id(self):
        # SF formula (verbatim, may need translation):
        #   "(ref:" & Id & ")"
        for rec in self:
            # TODO: translate SF formula to Python
            rec.sf_ref_id = False

    # === Constraints (translated from SF Validation Rules) ===

    @api.constrains('sf_external_id')
    def _check_aor_review_required(self):
        # SF Validation Rule: AOR_Review_Required
        # SF condition (fires when TRUE):
        #   AND(ISPICKVAL(Application_Status__c ,"Pending Finance Manager Review"),ISPICKVAL( Application_Type__c , "New Advertiser"), AOR_Received__c = FALSE )
        for rec in self:
            # TODO: translate SF formula; the condition below is a placeholder
            condition = False
            if condition:
                raise ValidationError(_("Finance must obtain an AOR. The AOR must be reviewed and authorized by Finance Manager before credit application can be approved and completed."))

    @api.constrains('sf_external_id')
    def _check_cloned_ca_cannot_start_as_completed(self):
        # SF Validation Rule: Cloned_CA_cannot_start_as_Completed
        # SF condition (fires when TRUE):
        #   AND(ISNEW(), ISCLONE(),
        #   OR(
        #   ISPICKVAL(Application_Status__c, "Complete"),
        #   ISPICKVAL(Application_Status__c, "Pending Finance Manager Review"),
        #   ISPICKVAL(Application_Status__c, "Pending Upper Management Review"),
        #   ISPICKVAL(Application_Status__c, "Pending Partner Review"),
        #   ISPICKVAL(Application_Status__c, "Pending Controller Review")
        #   ))
        for rec in self:
            # TODO: translate SF formula; the condition below is a placeholder
            condition = False
            if condition:
                raise ValidationError(_("Please set the status to \"Submitted\"  or \"--None--\" before saving."))

    @api.constrains('sf_external_id')
    def _check_finance_credit_term_support_required(self):
        # SF Validation Rule: Finance_Credit_Term_Support_Required
        # SF condition (fires when TRUE):
        #   AND(ISPICKVAL(Application_Status__c ,"Pending Finance Manager Review"),ISBLANK(Finance_Credit_Term_Support__c))
        for rec in self:
            # TODO: translate SF formula; the condition below is a placeholder
            condition = False
            if condition:
                raise ValidationError(_("Finance Manager must provide comments supporting credit limit/ terms granted"))
