# -*- coding: utf-8 -*-
# Generated by marathon_ventures Salesforce->Odoo migration generator.
# Do not edit by hand if you plan to regenerate; instead update the SF metadata
# and re-run the generator.

import logging
import re
from odoo import models, fields, api, _
from odoo.exceptions import ValidationError

_logger = logging.getLogger(__name__)


class MvDisableRelatedScheduleEmail(models.Model):
    _name = 'mv.disable_related_schedule_email'
    _description = 'Disable Related Schedule Email'

    # === Identification ===
    name = fields.Char(string='Name', default='New', copy=False)
    sf_external_id = fields.Char(string='SF External ID', index=True, copy=False)
    sf_legacy_data = fields.Json(string='SF Legacy Payload')

    # === SF Custom Fields ===
    disable_emails = fields.Boolean(string='Disable Emails')  # SF: Disable_Emails__c
