# -*- coding: utf-8 -*-
# Generated by marathon_ventures Salesforce->Odoo migration generator.
# Do not edit by hand if you plan to regenerate; instead update the SF metadata
# and re-run the generator.

import logging
import re
from odoo import models, fields, api, _
from odoo.exceptions import ValidationError

_logger = logging.getLogger(__name__)


class MvSpotData(models.Model):
    _name = 'mv.spot_data'
    _description = 'Spot Data'
    # === Identification ===
    name = fields.Char(string='Spot Data Name', default=lambda self: self.env['ir.sequence'].next_by_code('mv.spot_data.name') or 'New', copy=False, readonly=True)
    sf_external_id = fields.Char(string='SF External ID', index=True, copy=False)
    sf_legacy_data = fields.Json(string='SF Legacy Payload')
    currency_id = fields.Many2one('res.currency', string='Currency', default=lambda self: self.env.company.currency_id)

    # === SF Custom Fields ===
    am_pm = fields.Char(string='AM/PM', compute='_compute_am_pm', store=True)  # SF: AM_PM__c
    agency_commission = fields.Monetary(string='Agency Commission', currency_field='currency_id', compute='_compute_agency_commission', store=True)  # SF: Agency_Commission__c
    air_date_time = fields.Char(string='Air Date/Time', compute='_compute_air_date_time', store=True)  # SF: Air_Date_Time__c
    air_date_yyyy = fields.Char(string='Air Date YYYYMMDD', compute='_compute_air_date_yyyy', store=True)  # SF: Air_Date_YYYY__c
    air_date = fields.Date(string='Air Date')  # SF: Air_Date__c
    air_time = fields.Char(string='Air Time', size=50)  # SF: Air_Time__c
    agency = fields.Char(string='Agency', size=255)
    aired_ad_id = fields.Char(string='Aired Ad ID', size=255)
    availability = fields.Boolean(string='Availability')  # SF: Availability__c
    brand = fields.Char(string='Brand', compute='_compute_brand', store=True)  # SF: Brand__c
    broadcast_network = fields.Char(string='Broadcast Network', size=120)  # SF: Broadcast_Network__c
    bundle_avail_30 = fields.Float(string='Bundle Avail :30', digits=(18, 2), compute='_compute_bundle_avail_30', store=True)  # SF: Bundle_Avail_30__c
    bundle_spot_30 = fields.Float(string='Bundle Spot :30', digits=(18, 2), compute='_compute_bundle_spot_30', store=True)  # SF: Bundle_Spot_30__c
    bundle_spot_rate = fields.Monetary(string='Bundle Spot Rate', currency_field='currency_id', compute='_compute_bundle_spot_rate', store=True)  # SF: Bundle_Spot_Rate__c
    bundle = fields.Monetary(string='Bundle Avail Rate', currency_field='currency_id', compute='_compute_bundle', store=True)  # SF: Bundle__c
    commercial_title = fields.Char(string='Commercial Title', size=255)  # SF: Commercial_Title__c
    day_of_week = fields.Char(string='Day of Week', compute='_compute_day_of_week', store=True)  # SF: Day_of_Week__c
    daypart = fields.Char(string='Daypart', compute='_compute_daypart', store=True)  # SF: Daypart__c
    error_mirror = fields.Text(string='Error (Mirror)')  # SF: Error_Mirror__c
    error = fields.Many2many(string='Error', comodel_name='mv.error.tag', relation='mv_spot_data_error_rel')  # SF: Error__c
    hour = fields.Char(string='Hour', compute='_compute_hour', store=True)  # SF: Hour__c
    hour_of_day = fields.Char(string='Hour of Day', compute='_compute_hour_of_day', store=True)  # SF: Hour_of_Day__c
    isci = fields.Char(string='ISCI', size=255)  # SF: ISCI__c
    impressions = fields.Integer(string='Impressions')  # SF: Impressions__c
    length = fields.Selection(string='Length', selection=[('v_15', '15'), ('v_30', '30'), ('v_45', '45'), ('v_60', '60'), ('v_90', '90'), ('v_120', '120'), ('v_5', '5'), ('v_10', '10'), ('v_75', '75'), ('v_180', '180'), ('v_300', '300'), ('v_3510', '3510')])  # SF: Length__c | SF Unrestricted picklist
    line_number = fields.Char(string='Line Number', size=5)  # SF: Line_Number__c
    log_schedule_mismatch = fields.Boolean(string='Log Schedule Mismatch', compute='_compute_log_schedule_mismatch', store=True)  # SF: Log_Schedule_Mismatch__c
    long_form_match = fields.Boolean(string='Long Form Match', compute='_compute_long_form_match', store=True)  # SF: Long_Form_Match__c
    long_form_rate = fields.Monetary(string='Long Form Rate', currency_field='currency_id', compute='_compute_long_form_rate', store=True)  # SF: Long_Form_Rate__c
    long_form = fields.Char(string='Long Form', size=255)  # SF: Long_Form__c
    main_broadcast_program = fields.Char(string='Main Broadcast Program', size=18)  # SF: Main_Broadcast_Program__c
    main_network = fields.Integer(string='Main Network', compute='_compute_main_network', store=True)  # SF: Main_Network__c
    materialdescription = fields.Char(string='Material Description', size=255)
    net_total = fields.Monetary(string='Net Total', currency_field='currency_id', compute='_compute_net_total', store=True)  # SF: Net_Total__c
    network_deal_number = fields.Char(string='Network Deal Number', compute='_compute_network_deal_number', store=True)  # SF: Network_Deal_Number__c
    orderproductdescription = fields.Char(string='Order Product Description', size=255)
    pod = fields.Char(string='Pod', size=155)  # SF: Pod__c
    prelog_data = fields.Many2one(string='Prelog Data', comodel_name='mv.prelog_data', ondelete='set null')  # SF: Prelog_Data__c
    product = fields.Char(string='Product', compute='_compute_product', store=True)  # SF: Product__c
    program_id = fields.Char(string='Program ID', size=255)  # SF: Program_ID__c
    program = fields.Char(string='Program', size=255)  # SF: Program__c
    rate_check = fields.Char(string='Rate Check', compute='_compute_rate_check', store=True)  # SF: Rate_Check__c
    raycom_invoice_number = fields.Char(string='Invoice Number', size=100)  # SF: Raycom_Invoice_Number__c
    raycom_order_account_brand = fields.Char(string='Order + Account + Brand', compute='_compute_raycom_order_account_brand', store=True)  # SF: Raycom_Order_Account_Brand__c
    raycom_order_number = fields.Char(string='Order Number', size=255)  # SF: Raycom_Order_Number__c
    sdm_created_by = fields.Char(string='SDM Created By', compute='_compute_sdm_created_by', store=True)  # SF: SDM_Created_By__c
    schedule_id = fields.Char(string='Schedule ID', compute='_compute_schedule_id', store=True)  # SF: Schedule_ID__c
    schedule_rate = fields.Monetary(string='Schedule Rate', currency_field='currency_id', compute='_compute_schedule_rate', store=True)  # SF: Schedule_Rate__c
    schedule = fields.Many2one(string='Schedule', comodel_name='mv.schedules', ondelete='cascade')  # SF: Schedule__c
    snowflake_transferred = fields.Boolean(string='Snowflake Transferred')  # SF: Snowflake_Transferred__c
    spotdatamirror_reference = fields.Char(string='SpotDataMirror Reference', size=255)  # SF: SpotDataMirror_Reference__c
    spotdatamirror = fields.Many2one(string='SpotDataMirror', comodel_name='mv.spot_data_mirror', ondelete='set null')  # SF: SpotDataMirror__c
    spotdatarefequal = fields.Boolean(string='SpotDataRefEqual', compute='_compute_spotdatarefequal', store=True)  # SF: SpotDataRefEqual__c
    spotdataref = fields.Char(string='SpotDataRef', compute='_compute_spotdataref', store=True)  # SF: SpotDataRef__c
    spot_30_rate = fields.Monetary(string='Spot :30 Rate', currency_field='currency_id', compute='_compute_spot_30_rate', store=True, help='Field used to calculate :30 Rate of Spot Data where these rates may vary by station for some Bundles.')  # SF: Spot_30_Rate__c
    spot_equiv_30 = fields.Float(string='Spot Equiv :30', digits=(18, 1), compute='_compute_spot_equiv_30', store=True)  # SF: Spot_Equiv_30__c
    spot_rate = fields.Monetary(string='Spot Rate', currency_field='currency_id')  # SF: Spot_Rate__c
    spot_week = fields.Date(string='Spot Week', compute='_compute_spot_week', store=True)  # SF: Spot_Week__c
    station_market_affiliate = fields.Char(string='Station Market Affiliate', compute='_compute_station_market_affiliate', store=True)  # SF: Station_Market_Affiliate__c
    station = fields.Many2one(string='Station', comodel_name='mv.station', ondelete='set null')  # SF: Station__c
    status = fields.Selection(string='Status', selection=[('aired', 'Aired'), ('credited', 'Credited'), ('credited_partial', 'Credited - Partial')])  # SF: Status__c | SF Unrestricted picklist
    time_period = fields.Char(string='Time Period', size=255)  # SF: Time_Period__c
    x800 = fields.Char(string='800 #', size=100)  # SF: X800__c

    # === Postlog Workbench fields (mirrors mv.prelog_data) ===
    # Plain indexed fields written by the Postlog import. Deliberately separate
    # from the generated `program` Char (which holds the show name, e.g.
    # "NEW DETECTIVES") and from the stubbed `spot_week` compute.
    # NOTE: there is no `version` / `removed` here - a postlog is one upload per
    # week of what actually aired, so neither concept applies.

    import_job = fields.Many2one(string='Import Job', comodel_name='mv.postlog_import_job', ondelete='set null', index=True)
    import_program = fields.Many2one(string='Import Program', comodel_name='mv.programs', ondelete='restrict', index=True)
    import_week_value = fields.Date(string='Import Week', index=True)
    import_match_status = fields.Selection(
        string='Import Match Status',
        selection=[
            ('matched', 'Matched'),
            ('created_without_schedule', 'Created Without Schedule'),
            ('failed_to_create', 'Failed to Create'),
        ],
    )
    import_match_detail = fields.Text(string='Import Match Detail')
    batch_id = fields.Char(string='Batch', size=255)

    # === Computed / Roll-Up ===

    @api.depends()
    def _compute_am_pm(self):
        # SF formula (verbatim, may need translation):
        #   IF( RIGHT( Air_Time__c ,2)="am","am",
        #   IF( RIGHT( Air_Time__c ,2)="AM","am",
        #   IF( RIGHT( Air_Time__c ,2)="pm","pm",
        #   IF( RIGHT( Air_Time__c ,2)="PM","pm",
        #   IF( RIGHT( Air_Time__c ,2)="XM","am",
        #   IF( RIGHT( Air_Time__c ,2)="xm","am",
        #   "False"))))))
        for rec in self:
            # TODO: translate SF formula to Python
            rec.am_pm = False

    @api.depends()
    def _compute_agency_commission(self):
        # SF formula (verbatim, may need translation):
        #   Spot_Rate__c *15/100
        for rec in self:
            # TODO: translate SF formula to Python
            rec.agency_commission = False

    @api.depends()
    def _compute_air_date_time(self):
        # SF formula (verbatim, may need translation):
        #   TEXT(Air_Date__c ) &" - "& Air_Time__c
        for rec in self:
            # TODO: translate SF formula to Python
            rec.air_date_time = False

    @api.depends()
    def _compute_air_date_yyyy(self):
        # SF formula (verbatim, may need translation):
        #   text( Air_Date__c )
        for rec in self:
            # TODO: translate SF formula to Python
            rec.air_date_yyyy = False

    @api.depends()
    def _compute_brand(self):
        # SF formula (verbatim, may need translation):
        #   Schedule__r.DealBrand__c
        for rec in self:
            # TODO: translate SF formula to Python
            rec.brand = False

    @api.depends()
    def _compute_bundle_avail_30(self):
        # SF formula (verbatim, may need translation):
        #   IF( Availability__c = TRUE, (VALUE(TEXT(Length__c)) / 30)*   Schedule__r.Units_Available__c   , 0)
        for rec in self:
            # TODO: translate SF formula to Python
            rec.bundle_avail_30 = False

    @api.depends()
    def _compute_bundle_spot_30(self):
        # SF formula (verbatim, may need translation):
        #   IF( AND(Availability__c = FALSE,  NOT(CONTAINS(TEXT(Length__c),":"))), VALUE(TEXT( Schedule__r.Deal_Parent__r.Length__c )) / 30 , 0)
        for rec in self:
            # TODO: translate SF formula to Python
            rec.bundle_spot_30 = False

    @api.depends()
    def _compute_bundle_spot_rate(self):
        # SF formula (verbatim, may need translation):
        #   IF( Availability__c = FALSE, Spot_Rate__c , 0)
        for rec in self:
            # TODO: translate SF formula to Python
            rec.bundle_spot_rate = False

    @api.depends()
    def _compute_bundle(self):
        # SF formula (verbatim, may need translation):
        #   IF( Availability__c = TRUE, Spot_Rate__c *  Schedule__r.CALC_EQUIV_30__c    , 0)
        for rec in self:
            # TODO: translate SF formula to Python
            rec.bundle = False

    @api.depends()
    def _compute_day_of_week(self):
        # SF formula (verbatim, may need translation):
        #   CASE(
        #   MOD(  Air_Date__c  - DATE(1900, 1, 7), 7),
        #   0, "7Sun",
        #   1, "1Mon",
        #   2, "2Tues",
        #   3, "3Wed",
        #   4, "4Th",
        #   5, "5Fri",
        #   6, "6Sat", "Error")
        for rec in self:
            # TODO: translate SF formula to Python
            rec.day_of_week = False

    @api.depends()
    def _compute_daypart(self):
        # SF formula (verbatim, may need translation):
        #   IF(AND(
        #   OR(LEFT(Air_Time__c,2)="6:",LEFT(Air_Time__c,2)="7:",LEFT(Air_Time__c,2)="8:",LEFT(Air_Time__c,2)="9:"),
        #   OR(RIGHT( Air_Time__c ,2)="AM",RIGHT( Air_Time__c ,2)="am")),"EM",
        #   "FALSE")
        for rec in self:
            # TODO: translate SF formula to Python
            rec.daypart = False

    @api.depends()
    def _compute_hour(self):
        # SF formula (verbatim, may need translation):
        #   IF(LEFT( Air_Time__c , 2)="1:","1",
        #   IF(LEFT( Air_Time__c , 2)="2:","2",
        #   IF(LEFT( Air_Time__c , 2)="3:","3",
        #   IF(LEFT( Air_Time__c , 2)="4:","4",
        #   IF(LEFT( Air_Time__c , 2)="5:","5",
        #   IF(LEFT( Air_Time__c , 2)="6:","6",
        #   IF(LEFT( Air_Time__c , 2)="7:","7",
        #   IF(LEFT( Air_Time__c , 2)="8:","8",
        #   IF(LEFT( Air_Time__c , 2)="9:","9",
        #   IF(LEFT( Air_Time__c , 2)="10","10",
        #   IF(LEFT( Air_Time__c , 2)="11","11",
        #   IF(LEFT( Air_Time__c , 2)="12","12",
        #   IF(LEFT( Air_Time__c , 2)="01","1",
        #   IF(LEFT( Air_Time__c , 2)="02","2",
        #   IF(LEFT( Air_Time__c , 2)="03","3",
        #   IF(LEFT( Air_Time__c , 2)="04","4",
        #   IF(LEFT( Air_Time__c , 2)="05","5",
        #   IF(LEFT( Air_Time__c , 2)="06","6",
        #   IF(LEFT( Air_Time__c , 2)="07","7",
        #   IF(LEFT( Air_Time__c , 2)="08","8",
        #   IF(LEFT( Air_Time__c , 2)="09","9",
        #   "FALSE")))))))))))))))))))))
        for rec in self:
            # TODO: translate SF formula to Python
            rec.hour = False

    @api.depends()
    def _compute_hour_of_day(self):
        # SF formula (verbatim, may need translation):
        #   Hour__c  & AM_PM__c
        for rec in self:
            # TODO: translate SF formula to Python
            rec.hour_of_day = False

    @api.depends()
    def _compute_log_schedule_mismatch(self):
        # SF formula (verbatim, may need translation):
        #   Schedule__r.Name != SpotDataMirror__r.Log_Schedule__c
        for rec in self:
            # TODO: translate SF formula to Python
            rec.log_schedule_mismatch = False

    @api.depends()
    def _compute_long_form_match(self):
        # SF formula (verbatim, may need translation):
        #   And(TEXT(Schedule__r.Long_Form__c) = Long_Form__c,  Air_Date__c  =  Schedule__r.Week__c )
        for rec in self:
            # TODO: translate SF formula to Python
            rec.long_form_match = False

    @api.depends()
    def _compute_long_form_rate(self):
        # SF formula (verbatim, may need translation):
        #   IF(And(TEXT(Schedule__r.Long_Form__c) = Long_Form__c,  Air_Date__c  =  Schedule__r.Week__c ),  Schedule__r.Rate__c , 0)
        for rec in self:
            # TODO: translate SF formula to Python
            rec.long_form_rate = False

    @api.depends()
    def _compute_main_network(self):
        # SF formula (verbatim, may need translation):
        #   if(Broadcast_Network__c =  Main_Broadcast_Program__c , 1,0)
        for rec in self:
            # TODO: translate SF formula to Python
            rec.main_network = False

    @api.depends()
    def _compute_net_total(self):
        # SF formula (verbatim, may need translation):
        #   Spot_Rate__c *85/100
        for rec in self:
            # TODO: translate SF formula to Python
            rec.net_total = False

    @api.depends()
    def _compute_network_deal_number(self):
        # SF formula (verbatim, may need translation):
        #   Schedule__r.Deal_Parent__r.Network_Deal_Number__c
        for rec in self:
            # TODO: translate SF formula to Python
            rec.network_deal_number = False

    @api.depends()
    def _compute_product(self):
        # SF formula (verbatim, may need translation):
        #   SpotDataMirror__r.Product__c
        for rec in self:
            # TODO: translate SF formula to Python
            rec.product = False

    @api.depends()
    def _compute_program(self):
        # SF formula (verbatim, may need translation):
        #   Schedule__r.DealProgram__c
        for rec in self:
            # TODO: translate SF formula to Python
            rec.program = False

    @api.depends()
    def _compute_rate_check(self):
        # SF formula (verbatim, may need translation):
        #   if( Schedule_Rate__c = Spot_Rate__c ,"True","False")
        for rec in self:
            # TODO: translate SF formula to Python
            rec.rate_check = False

    @api.depends()
    def _compute_raycom_order_account_brand(self):
        # SF formula (verbatim, may need translation):
        #   Raycom_Order_Number__c &" - "&  Raycom_Invoice_Number__c  &" - "& Schedule__r.DealAccount__c &" - "& Brand__c
        for rec in self:
            # TODO: translate SF formula to Python
            rec.raycom_order_account_brand = False

    @api.depends()
    def _compute_sdm_created_by(self):
        # SF formula (verbatim, may need translation):
        #   SpotDataMirror__r.CreatedBy.Username
        for rec in self:
            # TODO: translate SF formula to Python
            rec.sdm_created_by = False

    @api.depends()
    def _compute_schedule_id(self):
        # SF formula (verbatim, may need translation):
        #   Schedule__r.Id
        for rec in self:
            # TODO: translate SF formula to Python
            rec.schedule_id = False

    @api.depends()
    def _compute_schedule_rate(self):
        # SF formula (verbatim, may need translation):
        #   Schedule__r.Rate__c
        for rec in self:
            # TODO: translate SF formula to Python
            rec.schedule_rate = False

    @api.depends()
    def _compute_spotdatarefequal(self):
        # SF formula (verbatim, may need translation):
        #   IF ( OR ( LEFT(Id,15) = LEFT(SpotDataRef__c,15), ISBLANK(SpotDataMirror__c)) , true, false)
        for rec in self:
            # TODO: translate SF formula to Python
            rec.spotdatarefequal = False

    @api.depends()
    def _compute_spotdataref(self):
        # SF formula (verbatim, may need translation):
        #   SpotDataMirror__r.Spot_Data__c
        for rec in self:
            # TODO: translate SF formula to Python
            rec.spotdataref = False

    @api.depends()
    def _compute_spot_30_rate(self):
        # SF formula (verbatim, may need translation):
        #   Spot_Rate__c  / (VALUE(TEXT( Schedule__r.Deal_Parent__r.Length__c ))/30)
        for rec in self:
            # TODO: translate SF formula to Python
            rec.spot_30_rate = False

    @api.depends()
    def _compute_spot_equiv_30(self):
        # SF formula (verbatim, may need translation):
        #   IF(NOT(CONTAINS(TEXT(Length__c),':')),VALUE(TEXT(Length__c)) / 30,0)
        for rec in self:
            # TODO: translate SF formula to Python
            rec.spot_equiv_30 = False

    @api.depends()
    def _compute_spot_week(self):
        # SF formula (verbatim, may need translation):
        #   CASE(
        #   MOD( Air_Date__c - DATE(1900, 1, 7), 7),
        #   0, Air_Date__c - 6,
        #   1, Air_Date__c ,
        #   2, Air_Date__c -1,
        #   3, Air_Date__c - 2,
        #   4,Air_Date__c - 3,
        #   5, Air_Date__c - 4,
        #   6, Air_Date__c - 5, DATE(2001, 1, 1))
        for rec in self:
            # TODO: translate SF formula to Python
            rec.spot_week = False

    @api.depends()
    def _compute_station_market_affiliate(self):
        # SF formula (verbatim, may need translation):
        #   Station__r.Call_Letters__c &" - "& Station__r.Market__r.Name &" - "& Station__r.Affiliate__c
        for rec in self:
            # TODO: translate SF formula to Python
            rec.station_market_affiliate = False

    # === Constraints (translated from SF Validation Rules) ===

    @api.constrains('sf_external_id')
    def _check_bundles_needs_markets(self):
        # SF Validation Rule: Bundles_Needs_Markets
        # SF condition (fires when TRUE):
        #   If(
        #   AND(  ISBLANK(Station__c),
        #   OR(Schedule__r.DealProgram__c ="Tribune Multicast Connect",Schedule__r.DealProgram__c ="Retro Raycom",Schedule__r.DealProgram__c ="Media General Connect", Schedule__r.DealProgram__c ="Raycom Bounce Locals")),TRUE, FALSE)
        for rec in self:
            # TODO: translate SF formula; the condition below is a placeholder
            condition = False
            if condition:
                raise ValidationError(_("Spot Data attached to bundle properties need to be linked to a Station."))

    @api.constrains('sf_external_id')
    def _check_commercial_type_on_deal_doesnt_match(self):
        # SF Validation Rule: Commercial_Type_on_Deal_Doesnt_Match
        # SF condition (fires when TRUE):
        #   Commercial_Type__c  = Schedule__r.Deal_Parent__r.Commercial_Type__c
        for rec in self:
            # TODO: translate SF formula; the condition below is a placeholder
            condition = False
            if condition:
                raise ValidationError(_("Commercial Type needs to match the Commercial Type on the Deal"))

    @api.constrains('sf_external_id')
    def _check_network_deal_must_match(self):
        # SF Validation Rule: Network_Deal_Must_Match
        # SF condition (fires when TRUE):
        #   AND(Network_Deal_Number__c  <>  Schedule__r.Network_Deal_Number__c , Schedule__r.Deal_Parent__r.Cable_Synd_PP_del__c = "Cable")
        for rec in self:
            # TODO: translate SF formula; the condition below is a placeholder
            condition = False
            if condition:
                raise ValidationError(_("This network deal number of this spot does not match the schedule. Please find the correct schedule."))

    @api.constrains('sf_external_id')
    def _check_rates_must_match(self):
        # SF Validation Rule: Rates_Must_Match
        # SF condition (fires when TRUE):
        #   AND(Spot_Rate__c  <>  Schedule_Rate__c,  Schedule__r.Deal_Parent__r.Cable_Synd_PP_del__c = "Cable")
        for rec in self:
            # TODO: translate SF formula; the condition below is a placeholder
            condition = False
            if condition:
                raise ValidationError(_("The rate of this spot data does not match the rate on the schedule.  Please find the correct schedule."))

    @api.constrains('sf_external_id')
    def _check_the_spot_data_has_been_invoiced(self):
        # SF Validation Rule: The_spot_data_has_been_invoiced
        # SF condition (fires when TRUE):
        #   NOT(ISBLANK(Schedule__r.Intacct_SI_Number__c))
        for rec in self:
            # TODO: translate SF formula; the condition below is a placeholder
            condition = False
            if condition:
                raise ValidationError(_("The spot data has been invoiced."))

    @api.constrains('sf_external_id')
    def _check_weeks_must_match(self):
        # SF Validation Rule: Weeks_Must_Match
        # SF condition (fires when TRUE):
        #   IF(ISPICKVAL(Schedule__r.Deal_Parent__r.Program__r.Cable_Synd__c,'PP') || ISPICKVAL(Schedule__r.Deal_Parent__r.Program__r.Cable_Synd__c,'Digital') ||
        #   ISPICKVAL(Schedule__r.Deal_Parent__r.Program__r.Cable_Synd__c,'Bundle'),
        #   Spot_Week__c <> Schedule__r.LF_Week__c, Spot_Week__c <> Schedule__r.Week__c)
        for rec in self:
            # TODO: translate SF formula; the condition below is a placeholder
            condition = False
            if condition:
                raise ValidationError(_("This air date of this spot data does not match the week on the schedule.  Please find the correct schedule."))
