# -*- coding: utf-8 -*-
# Generated by marathon_ventures Salesforce->Odoo migration generator.
# Do not edit by hand if you plan to regenerate; instead update the SF metadata
# and re-run the generator.

import logging
import re
from odoo import models, fields, api, _
from odoo.exceptions import ValidationError

_logger = logging.getLogger(__name__)


class MvSpotDataMirrors(models.Model):
    _name = 'mv.spot_data_mirrors'
    _description = 'Spot Data Mirrors'

    # === Identification ===
    sf_external_id = fields.Char(string='SF External ID', index=True, copy=False)
    sf_legacy_data = fields.Json(string='SF Legacy Payload')

    # === SF Custom Fields ===
    air_date_c = fields.Date(string='AIR_DATE__C')  # SF: AIR_DATE_C__c
    air_date_time_c = fields.Text(string='AIR_DATE_TIME__C')  # SF: AIR_DATE_TIME_C__c
    air_date_yyyy_c = fields.Text(string='AIR_DATE_YYYY__C')  # SF: AIR_DATE_YYYY_C__c
    air_time_c = fields.Text(string='AIR_TIME__C')  # SF: AIR_TIME_C__c
    air_time_hour_c = fields.Float(string='AIR_TIME_HOUR__C', digits=(18, 8))  # SF: AIR_TIME_HOUR_C__c
    attributes = fields.Char(string='ATTRIBUTES', size=255)  # SF: ATTRIBUTES__c
    commercial_title_c = fields.Text(string='COMMERCIAL_TITLE__C')  # SF: COMMERCIAL_TITLE_C__c
    createdbyid = fields.Text(string='CREATEDBYID')  # SF: CREATEDBYID__c
    createddate = fields.Datetime(string='CREATEDDATE')  # SF: CREATEDDATE__c
    x_id = fields.Text(string='SF Id Field')  # SF: ID__c
    isci_c = fields.Text(string='ISCI__C')  # SF: ISCI_C__c
    isdeleted = fields.Boolean(string='ISDELETED')  # SF: ISDELETED__c
    lastmodifiedbyid = fields.Text(string='LASTMODIFIEDBYID')  # SF: LASTMODIFIEDBYID__c
    lastmodifieddate = fields.Datetime(string='LASTMODIFIEDDATE')  # SF: LASTMODIFIEDDATE__c
    lastreferenceddate = fields.Text(string='LASTREFERENCEDDATE')  # SF: LASTREFERENCEDDATE__c
    lastvieweddate = fields.Text(string='LASTVIEWEDDATE')  # SF: LASTVIEWEDDATE__c
    length_c = fields.Text(string='LENGTH__C')  # SF: LENGTH_C__c
    line_number_c = fields.Text(string='LINE_NUMBER__C')  # SF: LINE_NUMBER_C__c
    name = fields.Char(string='Name', size=255, default='New', copy=False)  # SF: NAME__c
    network_c = fields.Text(string='NETWORK__C')  # SF: NETWORK_C__c
    network_deal_number_c = fields.Text(string='NETWORK_DEAL_NUMBER__C')  # SF: NETWORK_DEAL_NUMBER_C__c
    ownerid = fields.Text(string='OWNERID')  # SF: OWNERID__c
    product_c = fields.Text(string='PRODUCT__C')  # SF: PRODUCT_C__c
    program_id_c = fields.Text(string='PROGRAM_ID__C')  # SF: PROGRAM_ID_C__c
    raycom_invoice_number_c = fields.Text(string='RAYCOM_INVOICE_NUMBER__C')  # SF: RAYCOM_INVOICE_NUMBER_C__c
    reason_for_unmatched_c = fields.Text(string='REASON_FOR_UNMATCHED__C')  # SF: REASON_FOR_UNMATCHED_C__c
    scheduleweek_c = fields.Date(string='SCHEDULEWEEK__C')  # SF: SCHEDULEWEEK_C__c
    schedule_c = fields.Text(string='SCHEDULE__C')  # SF: SCHEDULE_C__c
    spot_data_c = fields.Text(string='SPOT_DATA__C')  # SF: SPOT_DATA_C__c
    spot_equiv_30_c = fields.Float(string='SPOT_EQUIV_30__C', digits=(18, 8))  # SF: SPOT_EQUIV_30_C__c
    spot_rate_c = fields.Float(string='SPOT_RATE__C', digits=(18, 8))  # SF: SPOT_RATE_C__c
    status_c = fields.Text(string='STATUS__C')  # SF: STATUS_C__c
    systemmodstamp = fields.Datetime(string='SYSTEMMODSTAMP')  # SF: SYSTEMMODSTAMP__c
    time_period_c = fields.Text(string='TIME_PERIOD__C')  # SF: TIME_PERIOD_C__c
    week_c = fields.Date(string='WEEK__C')  # SF: WEEK_C__c
    x800_c = fields.Text(string='X800__C')  # SF: X800_C__c
