# -*- coding: utf-8 -*-
# Generated by marathon_ventures Salesforce->Odoo migration generator.
# Do not edit by hand if you plan to regenerate; instead update the SF metadata
# and re-run the generator.

import logging
import re
from odoo import models, fields, api, _
from odoo.exceptions import ValidationError

_logger = logging.getLogger(__name__)


class MvTraffic(models.Model):
    _name = 'mv.traffic'
    _description = 'Traffic Instructions'
    # === Identification ===
    name = fields.Char(string='Traffic Instructions Name', default=lambda self: self.env['ir.sequence'].next_by_code('mv.traffic.name') or 'New', copy=False, readonly=True)
    sf_external_id = fields.Char(string='SF External ID', index=True, copy=False)
    sf_legacy_data = fields.Json(string='SF Legacy Payload')

    # === SF Custom Fields ===
    access_code = fields.Char(string='Access Code', size=255)  # SF: Access_Code__c
    advertiser = fields.Char(string='Advertiser', compute='_compute_advertiser', store=True)  # SF: Advertiser__c
    agency = fields.Many2one(string='Agency', comodel_name='res.partner', ondelete='restrict', required=True)  # SF: Agency__c
    brands = fields.Many2one(string='Brands', comodel_name='mv.brands', ondelete='restrict', required=True)  # SF: Brands__c
    campaign = fields.Char(string='Campaign', size=255)  # SF: Campaign__c
    client_code = fields.Char(string='Client Code', size=18)  # SF: Client_Code__c
    deal = fields.Many2one(string='Deal', comodel_name='mv.deal', ondelete='set null')  # SF: Deal__c
    end_date = fields.Char(string='End Date', compute='_compute_end_date', store=True)  # SF: End_Date__c | TODO unknown SF type: Summary
    estimate = fields.Char(string='Estimate', size=255)  # SF: Estimate__c
    hiatused_dates = fields.Char(string='Hiatused Dates', size=255)  # SF: Hiatused_Dates__c
    length = fields.Selection(string='Length', selection=[('v_15', '15'), ('v_20', '20'), ('v_30', '30'), ('v_45', '45'), ('v_60', '60'), ('v_90', '90'), ('v_120', '120'), ('v_150', '150'), ('v_180', '180'), ('v_240', '240'), ('v_300', '300'), ('v_1710', '1710')])  # SF: Length__c
    product_code = fields.Char(string='Product Code', size=18)  # SF: Product_Code__c
    product_description = fields.Char(string='Product Description', size=120)  # SF: Product_Description__c
    program = fields.Many2one(string='Program', comodel_name='mv.programs', ondelete='restrict')  # SF: Program__c
    quarter = fields.Integer(string='Quarter', compute='_compute_quarter', store=True)  # SF: Quarter__c
    start_date = fields.Char(string='Start Date', compute='_compute_start_date', store=True)  # SF: Start_Date__c | TODO unknown SF type: Summary
    traffic_contact = fields.Many2one(string='Traffic Contact', comodel_name='res.partner', ondelete='restrict')  # SF: Traffic_Contact__c
    year = fields.Char(string='Year', compute='_compute_year', store=True)  # SF: Year__c

    # === Computed / Roll-Up ===

    @api.depends()
    def _compute_advertiser(self):
        # SF formula (verbatim, may need translation):
        #   Brands__r.Advertiser__r.Name
        for rec in self:
            # TODO: translate SF formula to Python
            rec.advertiser = False

    @api.depends()
    def _compute_end_date(self):
        # SF formula (verbatim, may need translation):
        for rec in self:
            # TODO: translate SF formula to Python
            rec.end_date = False

    @api.depends()
    def _compute_quarter(self):
        # SF formula (verbatim, may need translation):
        #   IF( MONTH( Start_Date__c) < 4, 1, IF( ((MONTH( Start_Date__c) >3) && (MONTH( Start_Date__c) < 7)), 2, IF( ((MONTH( Start_Date__c) >6) && (MONTH( Start_Date__c) <10)),3, IF(( MONTH( Start_Date__c) >9), 4, 0) ) ) )
        for rec in self:
            # TODO: translate SF formula to Python
            rec.quarter = False

    @api.depends()
    def _compute_start_date(self):
        # SF formula (verbatim, may need translation):
        for rec in self:
            # TODO: translate SF formula to Python
            rec.start_date = False

    @api.depends()
    def _compute_year(self):
        # SF formula (verbatim, may need translation):
        #   TEXT(YEAR( Start_Date__c ))
        for rec in self:
            # TODO: translate SF formula to Python
            rec.year = False

    # === Constraints (translated from SF Validation Rules) ===

    @api.constrains('sf_external_id')
    def _check_deal_traffic_field_match_validation(self):
        # SF Validation Rule: Deal_Traffic_Field_Match_Validation
        # SF condition (fires when TRUE):
        #   AND(
        #       NOT(ISBLANK(Deal__c)),
        #       Deal__r.Brands__c <> Brands__c,
        #       Deal__r.ContactAccount__c <> Agency__c,
        #       Deal__r.Program__c <> Program__c,
        #       TEXT(Deal__r.Length__c) <> TEXT(Length__c)
        #   )
        for rec in self:
            # TODO: translate SF formula; the condition below is a placeholder
            condition = False
            if condition:
                raise ValidationError(_("Deal fields do not match Traffic fields. Ensure that the Brands, Agency, Program, and Length fields are the same between the Deal and Traffic record."))
