from . import common
from . import test_acl
from . import test_x2many_cache_scope
from . import test_api
from . import test_barcode
from . import test_base
from . import test_basecase
from . import test_cache
from . import test_framework_contracts
from . import test_date_utils
from . import test_deprecation
from . import test_db_cursor
from . import test_display_name
from . import test_export_import_roundtrip
from . import test_expression
from . import test_float
from . import test_format_address_mixin
from . import test_groups
from . import test_http_case
from . import test_i18n
from . import test_image
from . import test_install
from . import test_avatar_mixin
from . import test_catalog_mixin
from . import test_init
from . import test_ir_actions
from . import test_ir_actions_audit
from . import test_ir_actions_reach
from . import test_ir_actions_tree
from . import test_ir_actions_report_audit
from . import test_ir_actions_server_audit
from . import test_ir_actions_server_regressions
from . import test_ir_actions_server_ssrf
from . import test_ir_asset
from . import test_ir_asset_audit
from . import test_ir_attachment
from . import test_ir_attachment_storage
from . import test_ir_binary
from . import test_ir_cron
from . import test_ir_cron_audit
from . import test_ir_job
from . import test_ir_filters
from . import test_ir_http
from . import test_ir_model
from . import test_table_object_conversion
from . import test_ir_model_data
from . import test_ir_module
from . import test_ir_sequence
from . import test_ir_sequence_date_range
from . import test_ir_embedded_actions
from . import test_ir_default
from . import test_ir_default_audit
from . import test_ir_autovacuum_audit
from . import test_ir_demo
from . import test_ir_logging
from . import test_cache_scan_predicates
from . import test_log_access_cache
from . import test_sort_collation
from . import test_unaccent_parity

from . import test_base_language_wizards_audit
from . import test_base_module_wizards
from . import test_change_password_wizard_audit
from . import test_decimal_precision_audit
from . import test_depends_audit
from . import test_depends_completeness
from . import test_inverse_cache_alignment
from . import test_field_description_audit
from . import test_report_paperformat_audit
from . import test_menu
from . import test_misc
from . import test_mixin_profiler
from . import test_module
from . import test_module_data_rename_model
from . import test_module_data_remove_xmlid_records
from . import test_module_data_rename_in_view_arches
from . import test_module_data_rename_module
from . import test_orm
from . import test_ormcache
from . import test_properties_base_definition
from . import test_tag_tag
from . import test_overrides
from . import test_query
from . import test_qweb_field
from . import test_qweb
from . import test_res_config
from . import test_res_lang
from . import test_search
from . import test_sql
from . import test_translate
from . import test_tz

from . import test_user_has_group
from . import test_views
from . import test_view_provenance
from . import test_view_payload
from . import test_res_bank
from . import test_res_company
from . import test_res_currency
from . import test_res_country
from . import test_res_partner
from . import test_res_partner_sync
from . import test_res_partner_bank
from . import test_res_partner_main_channels
from . import test_res_partner_identifier
from . import test_partner_identifier_confidentiality
from . import test_partner_private_address_access
from . import test_res_partner_merge
from . import test_mixin_merge
from . import test_res_users
from . import test_res_users_apikeys
from . import test_res_users_identitycheck
from . import test_res_users_log
from . import test_res_users_settings
from . import test_test_retry
from . import test_seeded_users
from . import test_test_suite
from . import test_tests_tags
from . import test_transactions
from . import test_form_create
from . import test_cloc
from . import test_populate
from . import test_profiler
from . import test_pdf
from . import test_neutralize
from . import test_config_parameter
from . import test_copy
from . import test_ir_module_category
from . import test_configmanager
from . import test_num2words_ar
from . import test_cli
from . import test_signature
from . import test_import_files
from . import test_nplusone
from . import test_orm_profiler
from . import test_base_perf_regression
from . import test_backend_integration

from . import test_res_config_install
from . import test_default_group
from . import test_ir_actions_webhook
from . import test_xml_utils
from . import test_device_log_isolation
from . import test_id_sequence_names
