{
    'name': 'HR Schedule & Time Capture ERP',
    'version': '1.0.0',
    'category': 'Services/Scheduling',
    'summary': 'Scheduling, resource assignment & automated time tracking',
    'description': """HR Scheduling module with resource assignment & time capture""",
    'author': 'Cesar Orozco',
    'depends': ['base', 'hr', 'web'],
    'post_init_hook': 'post_init_hook',
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'views/cliente_views.xml',
        'views/auxiliar_views.xml',
        'views/reasignacion_wizard.xml',
        'views/servicio_views.xml',
        'views/time_event_views.xml',
        'views/service_session_views.xml',
        'views/dispute_case_views.xml',
        'views/schedule_dashboard.xml',
        'reports/quincenal_report.xml',
        'reports/schedule_report.xml',
    ],
    'installable': True,
    'auto_install': False,
    'license': 'LGPL-3',
}