import unicodedata

# Diccionario de provincias de España y estados de la India a sus XML IDs de Odoo
state_map = {
                # Corrección de XML-ID erróneos generados por datos previos
                "base.es_asturias": "base.state_es_o",  # Asturias
                "base.es_madrid": "base.state_es_m",    # Madrid
                "base.es_galicia": "",                  # Galicia no es provincia, se deja vacío
            # GA es el código de provincia de A Coruña (Galicia), pero en Odoo es 'base.state_es_c'
            "GA": "base.state_es_c",  # A Coruña
            "ga": "base.state_es_c",  # Variante minúscula
            "base.state_es_ga": "base.state_es_c",  # Corrige XML-ID erróneo a A Coruña
        "galicia": "",  # Variante en minúsculas, comunidad autónoma, se deja vacío
        "asturias": "base.state_es_o",  # Variante en minúsculas, Asturias
    "Asturias": "base.state_es_o",  # Asturias
    "Galicia": "",  # Galicia es una comunidad autónoma, no provincia. Se deja vacío para evitar error.
    "Asturias": "base.state_es_o",
    "Principado de Asturias": "base.state_es_o",
    "Madrid": "base.state_es_m",
    "Barcelona": "base.state_es_b",
    "A Coruña": "base.state_es_c",
    "Coruña": "base.state_es_c",
    "Lugo": "base.state_es_lu",
    "Ourense": "base.state_es_or",
    "Pontevedra": "base.state_es_po",
    "León": "base.state_es_le",
    "Zaragoza": "base.state_es_z",
    "Murcia": "base.state_es_mu",
    "Valencia": "base.state_es_v",
    "Vizcaya": "base.state_es_bi",
    "Bizkaia": "base.state_es_bi",
    "Sevilla": "base.state_es_se",
    "Cádiz": "base.state_es_ca",
    "Granada": "base.state_es_gr",
    "Málaga": "base.state_es_ma",
    "Almería": "base.state_es_al",
    "Jaén": "base.state_es_j",
    "Huelva": "base.state_es_h",
    "Córdoba": "base.state_es_co",
    "Baleares": "base.state_es_pm",
    "Islas Baleares": "base.state_es_pm",
    "Santa Cruz de Tenerife": "base.state_es_tf",
    "Las Palmas": "base.state_es_gc",
    "Tarragona": "base.state_es_t",
    "Girona": "base.state_es_gi",
    "Lleida": "base.state_es_l",
    "Castellón": "base.state_es_cs",
    "Alicante": "base.state_es_a",
    "Toledo": "base.state_es_to",
    "Ciudad Real": "base.state_es_cr",
    "Cuenca": "base.state_es_cu",
    "Guadalajara": "base.state_es_gu",
    "Albacete": "base.state_es_ab",
    "Segovia": "base.state_es_sg",
    "Ávila": "base.state_es_av",
    "Salamanca": "base.state_es_sa",
    "Zamora": "base.state_es_za",
    "Palencia": "base.state_es_p",
    "Soria": "base.state_es_so",
    "Valladolid": "base.state_es_va",
    "Burgos": "base.state_es_bu",
    "Navarra": "base.state_es_na",
    "La Rioja": "base.state_es_lo",
    "Álava": "base.state_es_vi",
    "Guipúzcoa": "base.state_es_ss",
    "Huesca": "base.state_es_hu",
    "Teruel": "base.state_es_te",
    "Ceuta": "base.state_es_ce",
    "Melilla": "base.state_es_ml",
    # --- Ampliaciones automáticas por errores detectados ---
    # Localidades/parroquias que requieren revisión manual:
    # Llanera (parroquia de Pruvia) pertenece a Asturias
    "Llanera - Pruvia": "base.state_es_o",  # Asturias
    "Llanera": "base.state_es_o",  # Asturias
    # Errores de escritura frecuentes
    "Asturoas": "base.state_es_o",  # Asturias (error tipográfico)
    "Principado de Asturias": "base.state_es_o",
    "Asturias": "base.state_es_o",
    "Vigo": "base.state_es_po",  # Vigo está en Pontevedra
    "Tenerife": "base.state_es_tf",  # Santa Cruz de Tenerife
    "Lleida": "base.state_es_l",  # Lleida
    "La Rioja": "base.state_es_lo",
    "Sevilla": "base.state_es_se",
    "Murcia": "base.state_es_mu",
    "Zaragoza": "base.state_es_z",
    "León": "base.state_es_le",
    "Valencia": "base.state_es_v",
    # Galicia y Madrid no son provincias, pero a veces se usan así
    "Galicia": "",  # REVISAR: Galicia es una comunidad, no provincia
    "Madrid": "base.state_es_m",
    # Para revisión manual:
    # "base.es_asturias": "",  # No es un XML-ID válido, revisar
    # "base.es_galicia": "",  # No es un XML-ID válido, revisar
    # "base.es_madrid": "",  # No es un XML-ID válido, revisar
}

country_map = {
        "espana": "base.es",  # Variante en minúsculas
        "espan": "base.es",   # Error tipográfico frecuente
    "Andorra": "base.ad",
    "United Arab Emirates": "base.ae",
    "Afghanistan": "base.af",
    "Antigua and Barbuda": "base.ag",
    "Anguilla": "base.ai",
    "Albania": "base.al",
    "Armenia": "base.am",
    "Angola": "base.ao",
    "Antarctica": "base.aq",
    "Argentina": "base.ar",
    "American Samoa": "base.as",
    "Austria": "base.at",
    "Australia": "base.au",
    "Aruba": "base.aw",
    "Åland Islands": "base.ax",
    "Azerbaijan": "base.az",
    "Bosnia and Herzegovina": "base.ba",
    "Barbados": "base.bb",
    "Bangladesh": "base.bd",
    "Belgium": "base.be",
    "Burkina Faso": "base.bf",
    "Bulgaria": "base.bg",
    "Bahrain": "base.bh",
    "Burundi": "base.bi",
    "Benin": "base.bj",
    "Saint Barthélémy": "base.bl",
    "Bermuda": "base.bm",
    "Brunei Darussalam": "base.bn",
    "Bolivia": "base.bo",
    "Bonaire, Sint Eustatius and Saba": "base.bq",
    "Brazil": "base.br",
    "Bahamas": "base.bs",
    "Bhutan": "base.bt",
    "Bouvet Island": "base.bv",
    "Botswana": "base.bw",
    "Belarus": "base.by",
    "Belize": "base.bz",
    "Canada": "base.ca",
    "Cocos (Keeling) Islands": "base.cc",
    "Central African Republic": "base.cf",
    "Democratic Republic of the Congo": "base.cd",
    "Congo": "base.cg",
    "Switzerland": "base.ch",
    "Côte d'Ivoire": "base.ci",
    "Cook Islands": "base.ck",
    "Chile": "base.cl",
    "Cameroon": "base.cm",
    "China": "base.cn",
    "Colombia": "base.co",
    "Costa Rica": "base.cr",
    "Cuba": "base.cu",
    "Cape Verde": "base.cv",
    "Curaçao": "base.cw",
    "Christmas Island": "base.cx",
    "Cyprus": "base.cy",
    "Czech Republic": "base.cz",
    "Germany": "base.de",
    "Djibouti": "base.dj",
    "Denmark": "base.dk",
    "Dominica": "base.dm",
    "Dominican Republic": "base.do",
    "Algeria": "base.dz",
    "Ecuador": "base.ec",
    "Estonia": "base.ee",
    "Egypt": "base.eg",
    "Western Sahara": "base.eh",
    "Eritrea": "base.er",
    "Spain": "base.es",
    "España": "base.es",
    "ESPAÑA": "base.es",
    "Ethiopia": "base.et",
    "Finland": "base.fi",
    "Fiji": "base.fj",
    "Falkland Islands": "base.fk",
    "Micronesia": "base.fm",
    "Faroe Islands": "base.fo",
    "France": "base.fr",
    "Gabon": "base.ga",
    "Grenada": "base.gd",
    "Georgia": "base.ge",
    "French Guiana": "base.gf",
    "Ghana": "base.gh",
    "Gibraltar": "base.gi",
    "Guernsey": "base.gg",
    "Greenland": "base.gl",
    "Gambia": "base.gm",
    "Guinea": "base.gn",
    "Guadeloupe": "base.gp",
    "Equatorial Guinea": "base.gq",
    "Greece": "base.gr",
    "South Georgia and the South Sandwich Islands": "base.gs",
    "Guatemala": "base.gt",
    "Guam": "base.gu",
    "Guinea-Bissau": "base.gw",
    "Guyana": "base.gy",
    "Hong Kong": "base.hk",
    "Heard Island and McDonald Islands": "base.hm",
    "Honduras": "base.hn",
    "Croatia": "base.hr",
    "Haiti": "base.ht",
    "Hungary": "base.hu",
    "Indonesia": "base.id",
    "Ireland": "base.ie",
    "Israel": "base.il",
    "Isle of Man": "base.im",
    "India": "base.in",
    "British Indian Ocean Territory": "base.io",
    "Iraq": "base.iq",
    "Iran": "base.ir",
    "Iceland": "base.is",
    "Italy": "base.it",
    "Jersey": "base.je",
    "Jamaica": "base.jm",
    "Jordan": "base.jo",
    "Japan": "base.jp",
    "Kenya": "base.ke",
    "Kyrgyzstan": "base.kg",
    "Cambodia": "base.kh",
    "Kiribati": "base.ki",
    "Comoros": "base.km",
    "Saint Kitts and Nevis": "base.kn",
    "North Korea": "base.kp",
    "South Korea": "base.kr",
    "Kuwait": "base.kw",
    "Cayman Islands": "base.ky",
    "Kazakhstan": "base.kz",
    "Laos": "base.la",
    "Lebanon": "base.lb",
    "Saint Lucia": "base.lc",
    "Liechtenstein": "base.li",
    "Sri Lanka": "base.lk",
    "Liberia": "base.lr",
    "Lesotho": "base.ls",
    "Lithuania": "base.lt",
    "Luxembourg": "base.lu",
    "Latvia": "base.lv",
    "Libya": "base.ly",
    "Morocco": "base.ma",
    "Monaco": "base.mc",
    "Moldova": "base.md",
    "Montenegro": "base.me",
    "Saint Martin (French part)": "base.mf",
    "Madagascar": "base.mg",
    "Marshall Islands": "base.mh",
    "North Macedonia": "base.mk",
    "Mali": "base.ml",
    "Myanmar": "base.mm",
    "Mongolia": "base.mn",
    "Macau": "base.mo",
    "Northern Mariana Islands": "base.mp",
    "Martinique": "base.mq",
    "Mauritania": "base.mr",
    "Montserrat": "base.ms",
    "Malta": "base.mt",
    "Mauritius": "base.mu",
    "Maldives": "base.mv",
    "Malawi": "base.mw",
    "Mexico": "base.mx",
    "Malaysia": "base.my",
    "Mozambique": "base.mz",
    "Namibia": "base.na",
    "New Caledonia": "base.nc",
    "Niger": "base.ne",
    "Norfolk Island": "base.nf",
    "Nigeria": "base.ng",
    "Nicaragua": "base.ni",
    "Netherlands": "base.nl",
    "Norway": "base.no",
    "Nepal": "base.np",
    "Nauru": "base.nr",
    "Niue": "base.nu",
    "New Zealand": "base.nz",
    "Oman": "base.om",
    "Panama": "base.pa",
    "Peru": "base.pe",
    "French Polynesia": "base.pf",
    "Papua New Guinea": "base.pg",
    "Philippines": "base.ph",
    "Pakistan": "base.pk",
    "Poland": "base.pl",
    "Saint Pierre and Miquelon": "base.pm",
    "Pitcairn Islands": "base.pn",
    "Puerto Rico": "base.pr",
    "State of Palestine": "base.ps",
    "Portugal": "base.pt",
    "Palau": "base.pw",
    "Paraguay": "base.py",
    "Qatar": "base.qa",
    "Réunion": "base.re",
    "Romania": "base.ro",
    "Serbia": "base.rs",
    "Russian Federation": "base.ru",
    "Rwanda": "base.rw",
    "Saudi Arabia": "base.sa",
    "Solomon Islands": "base.sb",
    "Seychelles": "base.sc",
    "Sudan": "base.sd",
    "Sweden": "base.se",
    "Singapore": "base.sg",
    "Saint Helena, Ascension and Tristan da Cunha": "base.sh",
    "Slovenia": "base.si",
    "Svalbard and Jan Mayen": "base.sj",
    "Slovakia": "base.sk",
    "Sierra Leone": "base.sl",
    "San Marino": "base.sm",
    "Senegal": "base.sn",
    "Somalia": "base.so",
    "Suriname": "base.sr",
    "South Sudan": "base.ss",
    "São Tomé and Príncipe": "base.st",
    "El Salvador": "base.sv",
    "Sint Maarten (Dutch part)": "base.sx",
    "Syria": "base.sy",
    "Eswatini": "base.sz",
    "Turks and Caicos Islands": "base.tc",
    "Chad": "base.td",
    "French Southern Territories": "base.tf",
    "Togo": "base.tg",
    "Thailand": "base.th",
    "Tajikistan": "base.tj",
    "Tokelau": "base.tk",
    "Turkmenistan": "base.tm",
    "Tunisia": "base.tn",
    "Tonga": "base.to",
    "Timor-Leste": "base.tl",
    "Türkiye": "base.tr",
    "Trinidad and Tobago": "base.tt",
    "Tuvalu": "base.tv",
    "Taiwan": "base.tw",
    "Tanzania": "base.tz",
    "Ukraine": "base.ua",
    "Uganda": "base.ug",
    "United Kingdom": "base.gb",
    "USA Minor Outlying Islands": "base.um",
    "United States": "base.us",
    "Uruguay": "base.uy",
    "Uzbekistan": "base.uz",
    "Holy See (Vatican City State)": "base.va",
    "Saint Vincent and the Grenadines": "base.vc",
    "Venezuela": "base.ve",
    "Virgin Islands (British)": "base.vg",
    "Virgin Islands (USA)": "base.vi",
    "Vietnam": "base.vn",
    "Vanuatu": "base.vu",
    "Wallis and Futuna": "base.wf",
    "Samoa": "base.ws",
    "Yemen": "base.ye",
    "Mayotte": "base.yt",
    "South Africa": "base.za",
    "Zambia": "base.zm",
    "Zimbabwe": "base.zw",
    "Kosovo": "base.xk",
    # --- Ampliaciones automáticas por errores detectados ---
    # Errores de escritura frecuentes
    "Espana": "base.es",  # España
    "Espan": "base.es",   # España (error tipográfico)
    "Gijon": "base.es",   # Gijón es una ciudad, no país, pero si aparece como país, asignar España
}


def normalize_name(name):
    if not name:
        return ''
    # Quitar tildes, pasar a minúsculas, quitar espacios y caracteres especiales
    name = unicodedata.normalize('NFKD', name)
    name = ''.join([c for c in name if not unicodedata.combining(c)])
    name = name.lower().replace(' ', '_').replace('-', '_')
    name = ''.join([c for c in name if c.isalnum() or c == '_'])
    return name

def get_country_xmlid(name):
    if not name:
        return ''
    xmlid = country_map.get(name.strip())
    if xmlid:
        return xmlid
    # Si no está en el diccionario, devuelve un marcador para revisión manual
    return f"__REVISAR_PAIS__{normalize_name(name)}"

def get_state_xmlid(name):
    if not name:
        return ''
    xmlid = state_map.get(name.strip())
    if xmlid:
        return xmlid
    # Si no está en el diccionario, devuelve un marcador para revisión manual
    return f"__REVISAR_PROVINCIA__{normalize_name(name)}"

