
# Part of Odoo. See LICENSE file for full copyright and licensing details.

{
    'name': 'Website',
    'category': 'Website/Website',
    'sequence': 20,
    'summary': 'Enterprise website builder',
    'website': 'https://www.odoo.com/app/website',
    'depends': [
        'digest',
        'web',
        'html_editor',
        'http_routing',
        'portal',
        'social_media',
        'auth_signup',
        'mail',
        'google_recaptcha',
        'utm',
        'html_builder',
    ],
    'external_dependencies': {
        'python': ['geoip2'],
        'apt': {
            'geoip2': 'python3-geoip2',
        },
    },
    'data': [
        # security.xml first, data.xml need the group to exist (checking it)
        'security/website_security.xml',
        'data/image_library.xml',
        'data/ir_asset.xml',
        'data/ir_cron_data.xml',
        'data/mail_mail_data.xml',
        'data/website_data.xml',
        'data/website_visitor_cron.xml',
        'data/digest_data.xml',
        'views/website_technical_views.xml',
        'views/website_templates.xml',
        'views/snippets/snippets.xml',
        'views/snippets/s_announcement_scroll.xml',
        'views/snippets/s_framed_intro.xml',
        'views/snippets/s_title.xml',
        'views/snippets/s_cover.xml',
        'views/snippets/s_text_cover.xml',
        'views/snippets/s_image_text_box.xml',
        'views/snippets/s_striped_top.xml',
        'views/snippets/s_text_image.xml',
        'views/snippets/s_image_text.xml',
        'views/snippets/s_mockup_image.xml',
        'views/snippets/s_instagram_page.xml',
        'views/snippets/s_image_text_overlap.xml',
        'views/snippets/s_banner.xml',
        'views/snippets/s_bento_block.xml',
        'views/snippets/s_snippet_group.xml',
        'views/snippets/s_text_block.xml',
        'views/snippets/s_features.xml',
        'views/snippets/s_features_wall.xml',
        'views/snippets/s_three_columns.xml',
        'views/snippets/s_key_benefits.xml',
        'views/snippets/s_picture.xml',
        'views/snippets/s_image_punchy.xml',
        'views/snippets/s_bento_grid.xml',
        'views/snippets/s_carousel.xml',
        'views/snippets/s_carousel_intro.xml',
        'views/snippets/s_carousel_cards.xml',
        'views/snippets/s_alert.xml',
        'views/snippets/s_icon_list.xml',
        'views/snippets/s_motto.xml',
        'views/snippets/s_card.xml',
        'views/snippets/s_cards_grid.xml',
        'views/snippets/s_cards_soft.xml',
        'views/snippets/s_share.xml',
        'views/snippets/s_social_media.xml',
        'views/snippets/s_rating.xml',
        'views/snippets/s_hr.xml',
        'views/snippets/s_closer_look.xml',
        'views/snippets/s_awards_list.xml',
        'views/snippets/s_facebook_page.xml',
        'views/snippets/s_whatsapp.xml',
        'views/snippets/s_image_gallery.xml',
        'views/snippets/s_countdown.xml',
        'views/snippets/s_product_catalog.xml',
        'views/snippets/s_comparisons.xml',
        'views/snippets/s_comparisons_horizontal.xml',
        'views/snippets/s_company_team.xml',
        'views/snippets/s_company_team_basic.xml',
        'views/snippets/s_company_team_shapes.xml',
        'views/snippets/s_company_team_detail.xml',
        'views/snippets/s_company_team_spotlight.xml',
        'views/snippets/s_company_team_grid.xml',
        'views/snippets/s_company_team_card.xml',
        'views/snippets/s_call_to_action.xml',
        'views/snippets/s_references.xml',
        'views/snippets/s_references_social.xml',
        'views/snippets/s_references_grid.xml',
        'views/snippets/s_references_lite.xml',
        'views/snippets/s_references_tiles.xml',
        'views/snippets/s_popup.xml',
        'views/snippets/s_faq_list.xml',
        'views/snippets/s_faq_collapse.xml',
        'views/snippets/s_features_grid.xml',
        'views/snippets/s_features_wave.xml',
        'views/snippets/s_tabs.xml',
        'views/snippets/s_tabs_images.xml',
        'views/snippets/s_table_of_content.xml',
        'views/snippets/s_images_constellation.xml',
        'views/snippets/s_chart.xml',
        'views/snippets/s_parallax.xml',
        'views/snippets/s_quotes_carousel.xml',
        'views/snippets/s_numbers_grid.xml',
        'views/snippets/s_quotes_carousel_minimal.xml',
        'views/snippets/s_quotes_carousel_compact.xml',
        'views/snippets/s_numbers.xml',
        'views/snippets/s_numbers_inline.xml',
        'views/snippets/s_contact_info.xml',
        'views/snippets/s_numbers_boxed.xml',
        'views/snippets/s_cta_box.xml',
        'views/snippets/s_cta_centered.xml',
        'views/snippets/s_numbers_framed.xml',
        'views/snippets/s_masonry_block.xml',
        'views/snippets/s_sidegrid.xml',
        'views/snippets/s_media_list.xml',
        'views/snippets/s_services_pack.xml',
        'views/snippets/s_showcase.xml',
        'views/snippets/s_faq_horizontal.xml',
        'views/snippets/s_floating_blocks.xml',
        'views/snippets/s_opening_hours.xml',
        'views/snippets/s_opening_hours_alt.xml',
        'views/snippets/s_timeline.xml',
        'views/snippets/s_timeline_images.xml',
        'views/snippets/s_timeline_list.xml',
        'views/snippets/s_process_steps.xml',
        'views/snippets/s_accordion.xml',
        'views/snippets/s_website_form_info.xml',
        'views/snippets/s_numbers_showcase.xml',
        'views/snippets/s_numbers_charts.xml',
        'views/snippets/s_accordion_image.xml',
        'views/snippets/s_pricelist_boxed.xml',
        'views/snippets/s_adventure.xml',
        'views/snippets/s_image_title.xml',
        'views/snippets/s_bento_grid_avatars.xml',
        'views/snippets/s_key_images.xml',
        'views/snippets/s_kickoff.xml',
        'views/snippets/s_discovery.xml',
        'views/snippets/s_bento_banner.xml',
        'views/snippets/s_striped.xml',
        'views/snippets/s_intro_pill.xml',
        'views/snippets/s_big_number.xml',
        'views/snippets/s_wavy_grid.xml',
        'views/snippets/s_images_mosaic.xml',
        'views/snippets/s_shape_image.xml',
        'views/snippets/s_empowerment.xml',
        'views/snippets/s_split_intro.xml',
        'views/snippets/s_splash_intro.xml',
        'views/snippets/s_text_highlight.xml',
        'views/snippets/s_pricelist_cafe.xml',
        'views/snippets/s_progress_bar.xml',
        'views/snippets/s_blockquote.xml',
        'views/snippets/s_badge.xml',
        'views/snippets/s_color_blocks_2.xml',
        'views/snippets/s_attributes_horizontal.xml',
        'views/snippets/s_attributes_vertical.xml',
        'views/snippets/s_product_list.xml',
        'views/snippets/s_mega_menu_multi_menus.xml',
        'views/snippets/s_mega_menu_menu_image_menu.xml',
        'views/snippets/s_mega_menu_thumbnails.xml',
        'views/snippets/s_mega_menu_little_icons.xml',
        'views/snippets/s_mega_menu_images_subtitles.xml',
        'views/snippets/s_mega_menu_menus_logos.xml',
        'views/snippets/s_mega_menu_odoo_menu.xml',
        'views/snippets/s_mega_menu_big_icons_subtitles.xml',
        'views/snippets/s_mega_menu_cards.xml',
        'views/snippets/s_google_map.xml',
        'views/snippets/s_cta_mockups.xml',
        'views/snippets/s_map.xml',
        'views/snippets/s_text_block_split.xml',
        'views/snippets/s_manifesto.xml',
        'views/snippets/s_bento_features.xml',
        'views/snippets/s_projects_grid.xml',
        'views/snippets/s_banner_contained.xml',
        'views/snippets/s_duo_images.xml',
        'views/snippets/s_hero_about.xml',
        'views/snippets/s_website_form_bold.xml',
        'views/snippets/s_title_split.xml',
        'views/snippets/s_hero_maintenance.xml',
        'views/snippets/s_hero_minimalist.xml',
        'views/snippets/s_launch_countdown.xml',
        'views/snippets/s_projects_grid_minimal.xml',
        'views/snippets/s_features_cards.xml',
        'views/snippets/s_achievements_list.xml',
        'views/snippets/s_text_bold.xml',
        'views/snippets/s_features_image.xml',
        'views/snippets/s_image_features.xml',
        'views/snippets/s_numbers_lite.xml',
        'views/snippets/s_hours_and_place.xml',
        'views/snippets/s_showcase_square.xml',
        'views/snippets/s_services_grid.xml',
        'views/snippets/s_dynamic_snippet.xml',
        'views/snippets/s_dynamic_snippet_carousel.xml',
        'views/snippets/s_banner_product.xml',
        'views/snippets/s_embed_code.xml',
        'views/snippets/s_website_form.xml',
        'views/snippets/s_website_form_overlay.xml',
        'views/snippets/s_title_form.xml',
        'views/snippets/s_searchbar.xml',
        'views/snippets/s_inline_text.xml',
        'views/snippets/s_button.xml',
        'views/snippets/s_freegrid.xml',
        'views/snippets/s_card_offset.xml',
        'views/snippets/s_image.xml',
        'views/snippets/s_icon.xml',
        'views/snippets/s_video.xml',
        'views/snippets/s_cta_badge.xml',
        'views/snippets/s_avatars.xml',
        'views/snippets/s_unveil.xml',
        'views/snippets/s_image_hexagonal.xml',
        'views/snippets/s_striped_center_top.xml',
        'views/snippets/s_numbers_list.xml',
        'views/snippets/s_quadrant.xml',
        'views/snippets/s_cta_card.xml',
        'views/snippets/s_image_frame.xml',
        'views/snippets/s_cta_mobile.xml',
        'views/snippets/s_reviews_wall.xml',
        'views/snippets/s_website_form_cover.xml',
        'views/snippets/s_form_aside.xml',
        'views/snippets/s_banner_connected.xml',
        'views/snippets/s_ecomm_categories_showcase.xml',
        'views/snippets/s_banner_categories.xml',
        'views/snippets/s_animated_cover.xml',
        'views/snippets/s_projects_list.xml',
        'views/snippets/s_about_bold.xml',
        'views/snippets/s_age_verification_popup.xml',
        'views/new_page_template_templates.xml',
        'views/website_views.xml',
        'views/website_pages_views.xml',
        'views/website_controller_pages_views.xml',
        'views/website_visitor_views.xml',
        'views/res_config_settings_views.xml',
        'views/website_rewrite.xml',
        'views/ir_actions_server_views.xml',
        'views/ir_asset_views.xml',
        'views/ir_attachment_views.xml',
        'views/ir_model_views.xml',
        'views/res_partner_views.xml',
        'views/neutralize_views.xml',
        'views/digest_digest_views.xml',
        'wizard/base_language_install_views.xml',
        'wizard/blocked_third_party_domains.xml',
        'wizard/website_robots.xml',
        # Replaces a post_init_hook that should be run on upgrade too.
        'data/update_theme_images.xml',
        'views/website_templates_svg.xml',
        'security/ir.access.csv',
    ],
    'demo': [
        'data/website_demo.xml',
        'data/website_visitor_demo.xml',
    ],
    'application': True,
    'post_init_hook': 'post_init_hook',
    'uninstall_hook': 'uninstall_hook',
    'assets': {
        "im_livechat.assets_embed_core": [
            "website/static/src/mail/core/common/**/*",
        ],
        "mail.assets_public": [
            "website/static/src/mail/core/common/**/*",
        ],
        "portal.assets_chatter_helpers": [
            "website/static/src/mail/core/common/**/*",
        ],
        'web.assets_frontend': [
            'html_builder/static/src/utils/scrolling.js',
            'website/static/src/interactions/**/*',
            'website/static/src/core/**/*',
            'website/static/src/utils/**/*',
            ('remove', 'website/static/src/interactions/**/*.edit.js'),
            # Multi-range is an opt-in feature.
            ('remove', 'website/static/src/interactions/multirange_input.js'),
            # Activated on-demand by website.ripple_effect_js.
            ('remove', 'website/static/src/interactions/ripple_effect.js'),
            ('remove', 'website/static/src/core/website_edit_service.js'),
            ('replace', 'web/static/src/public/public_root_instance.js', 'website/static/src/js/content/website_root_instance.js'),
            'website/static/src/snippets/**/*.js',
            ('remove', 'website/static/src/snippets/**/*.edit.js'),
            'website/static/src/scss/website.scss',
            'website/static/src/scss/portal.scss',
            'website/static/src/scss/website_common.scss',
            'website/static/src/scss/website_controller_page.scss',
            'website/static/src/scss/website.ui.scss',
            'website/static/src/libs/bootstrap/bootstrap.js',
            'website/static/src/js/utils.js',
            'web/static/src/core/autocomplete/*',
            'website/static/src/components/autocomplete_with_pages/*',
            'website/static/src/js/tours/tour_utils.js',
            'website/static/src/js/content/compatibility.js',
            'website/static/src/js/user_custom_javascript.js',
            'website/static/src/js/http_cookie.js',
            'website/static/src/xml/website.xml',
            'website/static/src/xml/website.background.video.xml',
            'website/static/src/xml/website.cookies_warning.xml',
            'website/static/src/js/text_processing.js',
            'website/static/src/js/highlight_utils.js',
            'website/static/src/client_actions/website_preview/website_builder_action.editor.scss',
            'website/static/src/components/user_switch.*',
        ],
        'web.assets_frontend_minimal': [
            'website/static/src/utils/misc.js',
            'website/static/src/js/content/inject_dom.js',
            'website/static/src/js/content/auto_hide_menu.js',
            'website/static/src/js/content/redirect.js',
            'website/static/src/js/content/adapt_content.js',
            'website/static/src/js/content/generate_video_iframe.js',
            'website/static/src/js/content/age_verification_content_blur.js',
        ],
        'web.assets_frontend_lazy': [
            # Remove assets_frontend_minimal
            ('remove', 'website/static/src/utils/misc.js'),
            ('remove', 'website/static/src/js/content/inject_dom.js'),
            ('remove', 'website/static/src/js/content/auto_hide_menu.js'),
            ('remove', 'website/static/src/js/content/redirect.js'),
            ('remove', 'website/static/src/js/content/adapt_content.js'),
            ('remove', 'website/static/src/js/content/generate_video_iframe.js'),
        ],
        'website.assets_inside_builder_iframe': [
            ('include', 'html_builder.assets_inside_builder_iframe'),
            'website/static/src/**/*.edit.*',
            'website/static/src/core/website_edit_service.js',
        ],
        'web._assets_primary_variables': [
            'website/static/src/scss/primary_variables.scss',
            'website/static/src/scss/options/user_values.scss',
            'website/static/src/scss/options/colors/user_color_palette.scss',
            'website/static/src/scss/options/colors/user_gray_color_palette.scss',
            'website/static/src/scss/options/colors/user_theme_color_palette.scss',
        ],
        'web._assets_secondary_variables': [
            ('prepend', 'website/static/src/scss/secondary_variables.scss'),
        ],
        'web.assets_tests': [
            'website/static/tests/tours/**/*',
            'website/static/src/client_actions/website_preview/website_builder_action_test_mode.js',
            'html_builder/static/src/utils/utils_css.js',
        ],
        'web.assets_backend': [
            ('include', 'website.assets_editor'),
            ('include', 'html_editor.assets_link_popover'),
            'html_editor/static/src/main/media/media_dialog/*.js',
            'html_editor/static/src/main/media/media_dialog/**/*',
            'website/static/src/scss/color_palettes.scss',
            'website/static/src/scss/view_hierarchy.scss',
            'website/static/src/scss/website.backend.scss',
            'website/static/src/scss/website_visitor_views.scss',
            'website/static/src/js/backend/**/*',
            'website/static/src/js/tours/tour_utils.js',
            'website/static/src/js/text_processing.js',
            'website/static/src/js/highlight_utils.js',
            'website/static/src/client_actions/*/*',
            ('remove', 'website/static/src/client_actions/website_preview/website_builder_action_test_mode.js'),
            'website/static/src/components/fields/*',
            'website/static/src/components/fullscreen_indication/fullscreen_indication.js',
            'website/static/src/components/fullscreen_indication/fullscreen_indication.scss',
            'website/static/src/components/fullscreen_indication/fullscreen_indication.xml',
            'website/static/src/components/website_loader/website_loader.js',
            'website/static/src/components/website_loader/website_loader.scss',
            'website/static/src/components/views/*',
            'website/static/src/services/website_service.js',
            'website/static/src/js/utils.js',
            'web/static/src/core/autocomplete/*',
            'website/static/src/components/autocomplete_with_pages/*',
            'website/static/src/xml/website.xml',
            'website/static/src/scss/website_controller_page_kanban.scss',
            'website/static/src/mail/core/common/**/*',

            'website/static/src/xml/website_form_editor.xml',
            # TODO when moving options to website: load this from website
            # directly. This file is loaded in assets_wysiwyg in website, but we
            # need to load it here for html_builder.
            'website/static/src/xml/website.cookies_bar.xml',
        ],
        "web.assets_web_dark": [
            'website/static/src/components/dialog/*.dark.scss',
            'website/static/src/scss/website.backend.dark.scss',
            'website/static/src/components/website_loader/website_loader.dark.scss'
        ],
        'web.assets_unit_tests': [
            'website/static/src/client_actions/website_preview/website_builder_action_test_mode.js',
            'website/static/tests/core/**/*',
            'website/static/tests/helpers.js',
            'website/static/tests/interactions/**/*',
            'website/static/tests/builder/**/*',
            ('include', 'website.website_builder_assets'),
            'website/static/tests/mock_server/**/*',
            'website/static/tests/redirect_field.test.js',
            'website/static/tests/new_content_systray_item.test.js',
            'website/static/tests/page_url_field.test.js',
            'website/static/tests/website_loader.test.js',
        ],
        'web.assets_unit_tests_setup': [
            'html_builder/static/src/utils/scrolling.js',
            'web/static/src/public/utils.js',
            'web/static/src/public/lazyloader.js',
            'web/static/src/public/public_root.js',
            'website/static/lib/multirange/*.js',
            'website/static/src/js/content/auto_hide_menu.js',
            'website/static/src/core/**/*',
            'website/static/src/utils/**/*',
            'website/static/src/interactions/**/*',
            'website/static/src/snippets/**/*.js',
            'website/static/src/snippets/**/*.xml',
            'website/static/src/xml/**/*.xml',
            'website/static/src/snippets/s_table_of_content/000.scss',
            'google_recaptcha/static/src/js/recaptcha.js',
            'website/static/src/js/content/generate_video_iframe.js',
        ],
        'web._assets_frontend_helpers': [
            ('prepend', 'website/static/src/scss/bootstrap_overridden.scss'),
        ],
        'web._assets_bootstrap_frontend': [
            ('after', 'web/static/src/scss/utilities_custom.scss', 'html_builder/static/src/scss/utilities_custom.scss'),
        ],
        'html_editor.assets_link_popover': [
            'html_builder/static/src/utils/utils_css.js',
            'website/static/src/js/editor/html_editor.js',
            'website/static/src/xml/html_editor.xml',
        ],
        'website.assets_wysiwyg': [
            ('include', 'web._assets_helpers'),
            'html_editor/static/src/scss/bootstrap_overridden.scss',
            'web/static/src/scss/pre_variables.scss',
            'web/static/lib/bootstrap/scss/_variables.scss',
            'web/static/lib/bootstrap/scss/_variables-dark.scss',
            'web/static/lib/bootstrap/scss/_maps.scss',
            'website/static/src/scss/website.edit_mode.scss',
            'website/static/src/js/send_mail_form.js',
            'website/static/src/xml/website_form.xml',
            'website/static/src/xml/website_form_editor.xml',
            'website/static/src/xml/website.cookies_bar.xml',
            'website/static/src/mail/core/common/**/*',
        ],
        'html_editor.assets_media_dialog': [
            'website/static/src/components/media_dialog/*',
        ],
        'website.assets_editor': [
            ('include', 'web._assets_helpers'),
            'web/static/src/scss/pre_variables.scss',
            'web/static/lib/bootstrap/scss/_variables.scss',
            'web/static/lib/bootstrap/scss/_variables-dark.scss',
            'web/static/lib/bootstrap/scss/_maps.scss',
            'website/static/src/components/resource_editor/**/*',
            'website/static/src/components/edit_head_body_dialog/edit_head_body_dialog.js',
            'website/static/src/components/edit_head_body_dialog/edit_head_body_dialog.scss',
            'website/static/src/components/edit_head_body_dialog/edit_head_body_dialog.xml',
            'website/static/src/utils/**/*',
            'website/static/src/components/dialog/*.js',
            'website/static/src/components/dialog/*.scss',
            'website/static/src/components/dialog/*.xml',
            'website/static/src/components/editor/editor.scss',
            'website/static/src/components/navbar/navbar.js',
            'website/static/src/components/navbar/navbar.scss',
            'website/static/src/components/navbar/navbar.xml',
            'website/static/src/components/burger_menu/burger_menu.js',
            'website/static/src/js/new_content_form.js',
            'website/static/src/services/website_custom_menus.js',
            'website/static/src/js/tours/homepage.js',
            'website/static/src/systray_items/*',
            'website/static/src/client_actions/*/*.xml',
            'website/static/src/components/website_loader/*.xml',
            'website/static/src/js/backend/**/*',

            # Don't include dark mode files in light mode
            ('remove', 'website/static/src/components/dialog/*.dark.scss'),
        ],
        'website.website_builder_assets': [
            ('include', 'html_builder.assets'),
            'website/static/src/scss/website_common.scss',
            'website/static/src/builder/**/*',
            ('remove', 'website/static/src/builder/**/*.edit.*'),
            'website/static/src/js/send_mail_form.js',
        ],
        'html_builder.iframe_add_dialog': [
            'website/static/src/snippets/**/*.preview.scss',
        ],
    },
    'configurator_snippets': {
        'homepage': ['s_cover', 's_text_image', 's_numbers'],
        'about_us': ['s_text_image', 's_image_text', 's_title', 's_company_team'],
        'our_services': ['s_three_columns', 's_quotes_carousel', 's_references'],
        'pricing': ['s_comparisons'],
        'privacy_policy': ['s_faq_collapse'],
    },
    'new_page_templates': {
        'about_us': {
            '0': ['s_title_split', 's_parallax', 's_text_bold', 's_numbers_lite', 's_achievements_list', 's_manifesto', 's_references_grid', 's_company_team_spotlight', 's_call_to_action'],
            '1': ['s_banner_contained', 's_text_block_split', 's_duo_images', 's_process_steps'],
            '2': ['s_splash_intro', 's_shape_image', 's_bento_features', 's_faq_collapse', 's_cta_centered'],
        },
        'services': {
            '0': ['s_title_split', 's_parallax', 's_text_block_split', 's_features', 's_quotes_carousel_minimal', 's_call_to_action'],
            '1': ['s_services_pack', 's_cta_centered'],
            '2': ['s_showcase_square', 's_text_bold', 's_services_grid'],
            '3': ['s_animated_cover', 's_references_lite', 's_achievements_list', 's_numbers_lite', 's_quotes_carousel_compact', 's_website_form_bold'],
            '4': ['s_discovery', 's_features_image', 's_image_features', 's_reviews_wall', 's_call_to_action'],
            '5': ['s_closer_look', 's_features_cards', 's_manifesto', 's_comparisons', 's_faq_collapse', 's_cta_centered'],
        },
        'pricing': {
            '0': ['s_comparisons', 's_references_lite', 's_faq_collapse'],
            '1': ['s_features_image', 's_comparisons_horizontal', 's_image_features', 's_reviews_wall', 's_faq_collapse', 's_call_to_action'],
            '2': ['s_pricelist_boxed'],
            '3': ['s_product_catalog'],
        },
        'portfolio': {
            '0': ['s_title_split', 's_projects_grid_minimal', 's_call_to_action'],
            '1': ['s_title_split', 's_images_wall', 's_quotes_carousel_minimal', 's_cta_centered'],
            '2': ['s_timeline_images', 's_call_to_action'],
            '3': ['s_title', 's_projects_grid', 's_announcement_scroll'],
            '4': ['s_parallax', 's_text_block_split', 's_projects_grid_minimal', 's_opening_hours'],
        },
        'contact_us': {
            '0': ['s_website_form_bold', 's_duo_images'],
            '1': ['s_features', 's_form_aside'],
            '2': ['s_faq_list'],
            '3': ['s_hours_and_place'],
        },
        'utility': {
            '0': ['s_title_split', 's_table_of_content'],
            '1': ['s_title_split', 's_table_of_content'],
            '2': ['s_launch_countdown'],
            '3': ['s_hero_maintenance'],
        },
    },
    'author': 'Odoo S.A.',
    'license': 'LGPL-3',
}
