{
    'name': "HTML Form Builder",
    'version': "1.0.27",
    'author': "Sythil Tech",
    'category': "Tools",
    'support': "steven@sythiltech.com.au",
    'summary': "Manage both internal and external forms",
    'description': "Manage both internal and external forms",
    'license':'LGPL-3',
    'data': [
        'views/html_form.xml',
        'views/html_form_builder_templates.xml',
        'views/snippets.xml',
        'views/website_templates.xml',
        'data/html.form.captcha.csv',
        'data/html.form.field.type.csv',
        'data/html.form.action.type.csv',
        'data/html.form.snippet.action.csv',
        'security/ir.model.access.csv',
    ],
    'demo': [],
    'images':[
        'static/description/1.jpg',
    ],
    'depends': ['website'],
    'installable': True,
}