{
    'name': 'Test ORM',
    'version': '1.0',
    'category': 'Hidden/Tests',
    'description': """A module to test the ORM.""",
    'depends': ['base', 'web', 'web_tour'],
    'installable': True,
    'data': [
        'data/test_access_rights_data.xml',
        'data/test_action_bindings.xml',
        'data/test_inherits.xml',
        'data/test_orm_data.xml',
        'data/test_attributes.xml',
        'data/test_domain.xml',
        'data/test_json_field.xml',
        'data/test_translated_field/test_model_data.xml',
        'security/ir.model.access.csv',
        'security/test_access_rights_security.xml',
        'security/test_orm_security.xml',
        'views/test_orm_views.xml',
        'security/test_access_feedback/ir.model.access.csv',
        'security/test_access_monetary_related/ir.model.access.csv',
        'security/test_action_bindings/ir.model.access.csv',
        'security/test_attributes/ir.model.access.csv',
        'security/test_autovacuum/ir.model.access.csv',
        'security/test_check_access/ir.model.access.csv',
        'security/test_company_checks/ir.model.access.csv',
        'security/test_config_settings/ir.model.access.csv',
        'security/test_convert/ir.model.access.csv',
        'security/test_convert_env/ir.model.access.csv',
        'security/test_domain/ir.model.access.csv',
        # 'security/test_fields/ir.model.access.csv',
        'security/test_html_converter/ir.model.access.csv',
        'security/test_indexed_translation/ir.model.access.csv',
        # 'security/test_inherits/ir.model.access.csv',
        'security/test_ir_rules/ir.model.access.csv',
        'security/test_json_field/ir.model.access.csv',
        # 'security/test_many2many/ir.model.access.csv',
        # 'security/test_one2many/ir.model.access.csv',
        'security/test_performance/ir.model.access.csv',
        # 'security/test_properties/ir.model.access.csv',
        'security/test_qweb_float/ir.model.access.csv',
        # 'security/test_read_group_override/ir.model.access.csv',
        # 'security/test_read_group_private/ir.model.access.csv',
        # 'security/test_read_grouping_sets/ir.model.access.csv',
        # 'security/test_related_translation/ir.model.access.csv',
        # 'security/test_schema/ir.model.access.csv',
        # 'security/test_sort/ir.model.access.csv',
        'security/test_timeit/ir.model.access.csv',
        # 'security/test_views/ir.model.access.csv',
    ],
    'assets': {
        'web.assets_tests': [
            'test_orm/static/tests/tours/constraint.js',
            'test_orm/static/tests/tours/x2many.js',
        ],
    },
    'author': 'Odoo S.A.',
    'license': 'LGPL-3',
}
