{
    'name': 'Test ORM',
    'category': 'Hidden/Tests',
    'description': """A module to test the ORM.""",
    'depends': ['base'],
    'data': [
        # DATA
        'data/test_access_feedback_data.xml',
        'data/test_action_bindings.xml',
        'data/test_translated_field/test_model_data.xml',
        'data/test_domain.xml',
        'data/test_fields.xml',
        'data/test_inherits.xml',
        'data/test_one2many.xml',
        'data/test_properties.xml',

        # SECURITY
        'security/test_access_feedback/ir.model.access.csv',
        'security/test_action_bindings/ir.model.access.csv',
        'security/test_autovacuum/ir.model.access.csv',
        'security/test_check_access/ir.model.access.csv',
        'security/test_check_access/test_check_access.xml',
        'security/test_company_checks/ir.model.access.csv',
        'security/test_convert/ir.model.access.csv',
        'security/test_convert_env/ir.model.access.csv',
        'security/test_domain/ir.model.access.csv',
        'security/test_fields/ir.model.access.csv',
        'security/test_indexed_translation/ir.model.access.csv',
        'security/test_inherits/ir.model.access.csv',
        'security/test_ir_rules/ir.model.access.csv',
        'security/test_many2many/ir.model.access.csv',
        'security/test_one2many/ir.model.access.csv',
        'security/test_performance/ir.model.access.csv',
        'security/test_properties/ir.model.access.csv',
        'security/test_qweb_float/ir.model.access.csv',
        'security/test_read_group_override/ir.model.access.csv',
        'security/test_read_group_private/ir.model.access.csv',
        'security/test_read_grouping_sets/ir.model.access.csv',
        'security/test_related_translation/ir.model.access.csv',
        'security/test_schema/ir.model.access.csv',
        'security/test_search/ir.model.access.csv',
        'security/test_sort/ir.model.access.csv',
        'security/test_views/ir.model.access.csv',
        'security/ir.model.access.csv',

        # VIEWS
        'views/test_views.xml',
    ],
    'author': 'Odoo S.A.',
    'license': 'LGPL-3',
}
