# Part of Odoo. See LICENSE file for full copyright and licensing details.

from odoo import api, fields, models
from odoo.tools import SQL


class UtmCampaign(models.Model):
    _inherit = "utm.campaign"

    quotation_count = fields.Integer(
        "Quotation Count",
        compute="_compute_quotation_count",
        compute_sudo=True,
        groups="sales_team.group_sale_salesman",
    )
    invoiced_amount = fields.Monetary(
        string="Revenues generated by the campaign",
        compute="_compute_sale_invoiced_amount",
        compute_sudo=True,
        groups="sales_team.group_sale_salesman",
        currency_field='currency_id',
    )
    currency_id = fields.Many2one(
        "res.currency",
        string="Currency",
        compute="_compute_currency_id",
        compute_sql="_compute_sql_currency_id",
        compute_sudo=True,
    )

    @api.depends_context('company')
    def _compute_currency_id(self):
        self.currency_id = self.env.company.currency_id

    def _compute_sql_currency_id(self, table):
        return SQL("%s", self.env.company.currency_id.id)

    def _compute_quotation_count(self):
        quotation_data = self.env["sale.order"]._read_group(
            [("campaign_id", "in", self.ids)], ["campaign_id"], ["__count"]
        )
        data_map = {campaign.id: count for campaign, count in quotation_data}
        for campaign in self:
            campaign.quotation_count = data_map.get(campaign.id, 0)

    def _compute_sale_invoiced_amount(self):
        if self.ids:
            self.env["account.move.line"].flush_model([
                "balance",
                "move_id",
                "account_id",
                "display_type",
            ])
            self.env["account.move"].flush_model(["state", "campaign_id", "move_type"])
            query_res = self.env.execute_query_dict(
                SQL(
                    """
                    SELECT move.campaign_id, -SUM(line.balance * COALESCE(currency_rate.rate, 1)) as price_subtotal
                      FROM account_move_line line
                INNER JOIN account_move move ON line.move_id = move.id
                      /* To use the exchange rate effective at the creation of the invoice. */
                      LEFT JOIN LATERAL (
                          SELECT rate
                            FROM res_currency_rate
                           WHERE company_id = line.company_id
                             AND currency_id = %(currency_id)s
                             AND name < line.date
                           ORDER BY name DESC
                           LIMIT 1
                      ) currency_rate
                        ON TRUE
                     WHERE move.state not in ('draft', 'cancel')
                       AND move.campaign_id IN %(campaign_ids)s
                       AND move.move_type IN ('out_invoice', 'out_refund', 'in_invoice', 'in_refund', 'out_receipt', 'in_receipt')
                       AND line.account_id IS NOT NULL
                       AND line.display_type = 'product'
                  GROUP BY move.campaign_id
                    """,  # noqa: E501
                    campaign_ids=tuple(self.ids),
                    currency_id=self.env.company.currency_id.id,
                )
            )
        else:
            query_res = []

        campaigns = self.browse()
        for datum in query_res:
            campaign = self.browse(datum["campaign_id"])
            campaign.invoiced_amount = datum["price_subtotal"]
            campaigns |= campaign
        for campaign in self - campaigns:
            campaign.invoiced_amount = 0

    def action_redirect_to_quotations(self):
        action = self.env["ir.actions.actions"]._for_xml_id(
            "sale.action_quotations_with_onboarding"
        )
        action["domain"] = [("campaign_id", "=", self.id)]
        action["context"] = {"default_campaign_id": self.id}
        return action

    def action_redirect_to_invoiced(self):
        action = self.env["ir.actions.actions"]._for_xml_id("account.action_move_journal_line")
        invoices = self.env["account.move"].search([("campaign_id", "=", self.id)])
        action["context"] = {"create": False, "edit": False, "view_no_maturity": True}
        action["domain"] = [
            ("id", "in", invoices.ids),
            (
                "move_type",
                "in",
                (
                    "out_invoice",
                    "out_refund",
                    "in_invoice",
                    "in_refund",
                    "out_receipt",
                    "in_receipt",
                ),
            ),
            ("state", "not in", ["draft", "cancel"]),
        ]
        return action
