# -*- coding: utf-8 -*-
import common
import test_PUC_buy_1_get_1_free
import test_buy_1_from_category_get_2_dollar_off
import test_buy_1_get_10_percent_off_on_another_product
import test_buy_1_get_1_free
import test_buy_2_get_1_free
import test_purchase_more_than_1500_get_10_percent_off_on_cart
import test_GER_buy_1_get_10_per_off_on_cart
import test_buy_1_refrigerator_get_shipment_free
import test_buy_1_get_coupon
