{
    "name" : "OpenERP Web base",
    "version" : "2.0",
    "depends" : [],
    'active': True,
    'js' : [
        "static/lib/datejs/date-en-US.js",
        "static/lib/jquery/jquery-1.6.2.js",
        "static/lib/jquery.form/jquery.form.js",
        "static/lib/jquery.validate/jquery.validate.js",
        "static/lib/jquery.ba-bbq/jquery.ba-bbq.js",
        "static/lib/jquery.contextmenu/jquery.contextmenu.r2.packed.js",
        "static/lib/jquery.blockUI/jquery.blockUI.js",
        "static/lib/jquery.superfish/js/hoverIntent.js",
        "static/lib/jquery.superfish/js/superfish.js",
        "static/lib/jquery.ui/js/jquery-ui-1.8.9.custom.min.js",
        "static/lib/jquery.ui/js/jquery-ui-timepicker-addon.js",
        "static/lib/jquery.ui.notify/js/jquery.notify.js",
        "static/lib/json/json2.js",
        "static/lib/qweb/qweb2.js",
        "static/lib/underscore/underscore.js",
        "static/lib/underscore/underscore.string.js",
        "static/src/js/boot.js",
        "static/src/js/core.js",
        "static/src/js/dates.js",
        "static/src/js/chrome.js",
        "static/src/js/views.js",
        "static/src/js/data.js",
        "static/src/js/data_export.js",
        "static/src/js/form.js",
        "static/src/js/list.js",
        "static/src/js/list-editable.js",
        "static/src/js/search.js",
        "static/src/js/view_tree.js",
    ],
    'css' : [
        "static/lib/jquery.superfish/css/superfish.css",
        "static/lib/jquery.ui/css/smoothness/jquery-ui-1.8.9.custom.css",
        "static/lib/jquery.ui.notify/css/ui.notify.css",
        "static/src/css/base.css",
        "static/src/css/data_export.css",
    ],
}
