from . import pos_delivery_provider
from . import ir_config_parameter
from . import pos_config
from . import res_config_settings
from . import pos_urban_piper_request
from . import pos_order
from . import pos_payment
from . import pos_session
from . import preparation_display_order
from . import product
from . import product_urban_piper_status
from . import pos_payment_method
from . import product_pricelist
from . import pos_category
