-
  !record {model: product.product, id: product_product_4}:
    uom_id: product_uom_unit
    categ_id: product_category_5
-
  !record {model: product.pricelist, id: customer_pricelist}:
    name: Customer Pricelist
    item_ids:
      - name: Default pricelist
        compute_price: 'formula'
        base: 'pricelist'
        base_pricelist_id: list0 
      - name: 10% Discount on Assemble Computer
        applied_on : '1_product'
        sequence: 1
        product_id: product_product_4
        compute_price: 'formula'
        base: 'list_price'
        price_discount: 10
      - name: 1 surchange on Laptop
        applied_on : '1_product'
        sequence: 1
        product_id: product_product_25
        compute_price: 'formula'
        base: 'list_price'
        price_surcharge: 1
      - name: 5% Discount on all Computer related products
        applied_on : '2_product_category'
        sequence: 1
        min_quantity: 2
        compute_price: 'formula'
        base: 'list_price'
        categ_id: product_category_5
        price_discount: 5
      - name: 30% Discount on all products
        applied_on : '0_product_variant'
        date_start: 2011-12-27
        date_end: 2011-12-31
        compute_price: 'formula'
        price_discount: 30
        sequence: 1
        base: 'list_price'
