-
  !record {model: product.product, id: product_product_4}:
    uom_id: product_uom_unit
    categ_id: product_category_9
-
  !record {model: product.pricelist, id: customer_pricelist}:
    name: Customer Pricelist
    type: sale
    version_id:
      - name: v1.0
        date_start: 2012-01-01
        items_id:
            - name: Default pricelist
              base: -1
              base_pricelist_id: list0 
            - name: 10% Discount on Assemble Computer
              sequence: 1
              product_id: product_product_4
              base: !eval (ref('product.list_price'))
              price_discount: -0.10
            - name: 1 surchange on Laptop
              sequence: 1
              product_id: product_product_25
              base: !eval (ref('product.list_price'))
              price_surcharge: 1
            - name: 5% Discount on all Computer related products
              sequence: 1
              min_quantity: 2
              base: !eval (ref('product.list_price'))
              categ_id: product_category_4
              price_discount: -0.05
      - name: v2.0 (Special Discount on all products during last 5 days in current year)
        date_start: 2011-12-27
        date_end: 2011-12-31
        items_id:
            - name: 30% Discount on all products
              price_discount: -0.30
              sequence: 1
              base: !eval (ref('product.list_price'))
-
  !record {model: product.pricelist, id: supplier_pricelist}:
    name: Supplier Pricelist
    type: sale
    version_id:
      - name: v1.0
        items_id:
            - name: 20% Discount given by my supplier
              sequence: 1
              price_min_margin: 2
              price_max_margin: -5
              product_id: product_product_6
              base: -2
-
  !record {model: pricelist.partnerinfo, id: supplier_pricelist0_product_pc2}:
    suppinfo_id: product_supplierinfo_2
    min_quantity: 3
    price: 785
-
  !record {model: pricelist.partnerinfo, id: supplier_pricelist1_product_pc2}:
    suppinfo_id: product_supplierinfo_2
    min_quantity: 1
    price: 790
