from . import hr_department
from . import hr_recruitment
from . import hr_employee
from . import hr_job
from . import res_config_settings
from . import calendar
from . import digest
from . import utm_campaign
from . import utm_source
from . import res_users
from . import ir_ui_menu
