import base64
from io import BytesIO
import logging
from PIL import Image, ImageOps

from odoo import api, fields, models, _
from odoo.fields import Domain
from odoo.exceptions import UserError

_logger = logging.getLogger(__name__)


epos_template = """
<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/">
    <s:Body>
        <epos-print xmlns="http://www.epson-pos.com/schemas/2011/03/epos-print">
            <image width="576" height="%s" align="center">%s</image>
            <cut type="feed" />
        </epos-print>
    </s:Body>
</s:Envelope>
"""


def thermal_printer_format(data) -> str:
    """Render the report and convert it to a black and white image
    with a width of 576px to fit the ePOS printer paper width"""
    img = Image.open(BytesIO(data)).convert("L")  # convert to grayscale

    if img.width > img.height:
        img = img.rotate(90, expand=True)  # ensure portrait mode

    target_width = 576
    ratio = target_width / img.width
    target_height = int(img.height * ratio)  # Preserve aspect ratio
    img = ImageOps.invert(img).resize((target_width, target_height), Image.ANTIALIAS).convert("1", dither=Image.FLOYDSTEINBERG)
    base64_image = base64.b64encode(img.tobytes()).decode()

    return epos_template % (target_height, base64_image)


class IrActionsReport(models.Model):
    _inherit = "ir.actions.report"

    printer_ip = fields.Char(string="Printer IP")

    @api.model
    def get_print_jobs(self, report_name, docids) -> list:
        """Method to render chatter attachments for ePOS or ZPL printers

        For ePOS, we limit to image attachments to avoid converting PDF to
        images.
        """
        jobs = []
        attachments = self.get_reports_from_chatter(report_name, docids)
        for attachment in attachments:
            name = attachment.name.lower()
            if name.endswith((".jpg", ".png")):
                report_type = "epos"
                report = thermal_printer_format(base64.b64decode(attachment.datas))
            elif ".zpl" in name:
                report_type = "zpl"
                report = base64.b64decode(attachment.datas)
            else:
                continue

            jobs.append({"type": report_type, "report": report})

        return jobs

    def report_action(self, docids=None, data=None, config=True):
        res = super().report_action(docids, data, config)
        if self.printer_ip:
            res["printer_ip"] = self.printer_ip
            # avoid additional orm call when print action is called from python
            res["jobs"] = self.get_print_jobs(self.report_name, docids)
        return res

    def get_reports_from_chatter(self, report_name, docids):
        """Shipping labels and docs are generated by carrier providers
        and are saved as attachments in the chatter"""
        domain = [('res_model', '=', "stock.picking"), ('res_id', 'in', docids)]
        if report_name == 'stock_delivery.report_shipping_labels':
            domain = Domain.AND([domain, [('name', 'ilike', 'Label%')]])
        elif report_name == 'stock_delivery.report_shipping_docs':
            domain = Domain.AND([domain, [('name', 'ilike', 'ShippingDoc%')]])

        chatter_attachments = self.env['ir.attachment'].search(domain, order='id desc')
        if not chatter_attachments:
            _logger.warning("No attachment found for report %s and docids %s", report_name, docids)
            return []
        return chatter_attachments

    def _get_readable_fields(self):
        return super()._get_readable_fields() | {
            "printer_ip",
        }

    def _render_qweb_pdf(self, report_ref, res_ids=None, data=None):
        """Override to ensure the user is informed when trying to print an empty report
        without an actual printer.

        This can happen when trying to print delivery labels, that have empty reports used to
        print the attachments in the chatter with ePOS or IoT.

        If the attachment is a PDF, we download it.
        If there are multiple PDFs, we only print one as we can't make Odoo download multiple at once.
        """
        report = self._get_report(report_ref)
        if report.report_name in ['stock_delivery.report_shipping_labels', 'stock_delivery.report_shipping_docs']:
            attachments = self.get_reports_from_chatter(report.report_name, res_ids)
            if attachments and attachments[0].name.lower().endswith(".pdf"):
                return base64.b64decode(attachments[0].datas), 'pdf'
            raise UserError(_(
                "The report you are trying to print requires an actual printer to be printed.\n"
                "Make sure you configured a printer on the report: '%s'.",
                report.report_name
            ))

        return super()._render_qweb_pdf(report_ref, res_ids, data=data)
