{
    "name": "Course Certifications",
    "version": "1.0",
    "category": "Website/eLearning",
    "summary": "Add certification capabilities to your courses",
    "description": "This module lets you use the full power of certifications within your courses.",
    "author": "Odoo S.A.",
    "license": "LGPL-3",
    "depends": [
        "website_slides",
        "survey",
    ],
    "data": [
        "security/ir.access.csv",
        "security/ir_access.xml",
        "views/slide_channel_partner_views.xml",
        "views/slide_channel_views.xml",
        "views/slide_slide_partner_views.xml",
        "views/slide_slide_views.xml",
        "views/survey_survey_views.xml",
        "views/website_slides_menu_views.xml",
        "views/website_slides_templates_course.xml",
        "views/website_slides_templates_lesson.xml",
        "views/website_slides_templates_lesson_fullscreen.xml",
        "views/website_slides_templates_homepage.xml",
        "views/website_slides_templates_utils.xml",
        "views/survey_templates.xml",
        "views/website_profile.xml",
        "data/mail_template_data.xml",
        "data/gamification_data.xml",
        "views/res_config_settings_views.xml",
    ],
    "demo": [
        "demo/survey_demo.xml",
        "demo/slide_slide_demo.xml",
        "demo/survey.user_input.line.csv",
    ],
    "assets": {
        "web.assets_frontend": [
            "website_slides_survey/static/src/scss/website_slides_survey.scss",
            "website_slides_survey/static/src/js/slides_course_fullscreen_player.js",
            "website_slides_survey/static/src/xml/website_slides_fullscreen.xml",
            "website_slides_survey/static/src/js/public/**/*",
        ],
        "survey.survey_assets": [
            "website_slides_survey/static/src/scss/website_slides_survey_result.scss",
        ],
    },
    "auto_install": True,
    "uninstall_hook": "uninstall_hook",
}
