#!/usr/bin/env python
# -*- coding: utf-8 -*-

import logging
import os
import signal
import sys
import threading
import traceback
import time

import odoo

odoo.tools.config.parse_config(sys.argv[1:])
config = odoo.tools.config

for name in [
    'db_name',
    'addons_path',
    'demo',
    'osv_memory_count_limit',
    'osv_memory_age_limit',
    ]:
    print "%s: %s - %s" % (name, config[name], type(config[name]))

