{
    'name': 'Excel Online Connector',
    'version': '19.0.1.0.0',
    'author': 'Niyu Labs',
    'category': 'Connector',
    'description': """
       The Odoo Excel Online Connector is a powerful integration tool that seamlessly connects your Odoo ERP system with Microsoft Excel, enabling effortless data synchronization and real-time reporting. With this connector, users can pull data from Odoo directly into Excel spreadsheets, automate exports, and generate dynamic reports for accounting, sales, inventory, and more—all without manual data transfers or complex setups  """,
    'summary': """Excel Connector for Odoo Data,
            PowerBI Connector for Odoo Data,
            Power BI Connector for Odoo Data,
            Odoo Excel Connector LibreOffice,
            Odoo Excel Data Connector,
            Odoo to Excel Connector,
            Excel Connect to Odoo,
            Generate ODC Odoo, 
            Auto synchronization data,
            Export Odoo Data Excel,
            Excel Report Connector,
            Project Tasks to Excel,
            Accounting Report to Excel,
            Connect Account Report to Excel,
            LibreOffice Calc Link External Data from Odoo,
            OpenOffice Link External Data from Odoo,
            All In One Excel Report,
            All In One Report,
            Quotations Excel Report,
            Sale Order Excel Report,
            Sales Order Excel Report,
            Request For Quotation Excel Report,
            RFQ Excel Report,
            Supplier Invoice Excel Report,
            Customer Invoice Excel Report,
            Invoice Excel Report,
            Invoice Report,
            Invoices Excel Report,
            Delivery Order Excel Report,
            Delivery Order Report,
            XLS Report,
            XLSX Report,
            Odoo Excel Connector integrates your Odoo to Excel. It allows syncing data from Odoo to Excel or LibreOffice.PowerBI Connector for Odoo Data, Odoo Excel Data Connector, Excel Report Connector, All In One Excel Report, Sales Order Excel Report, Invoice Excel Report, Delivery Order Report, XLSX Report, Odoo LibreOffice Connector, big data connector, tableau connector. MS Excel, Microsoft Excel, MS Excel Connector, Microsoft Excel Connector.""",
    'website': 'https://niyulabs.com',
    'support': "info@niyulabs.com",
    'price': 0,
    'currency': 'USD',
    'live_test_url': 'https://niyulabs.gitbook.io',
    'license': 'OPL-1',
    'depends': ['base', 'web'],
    'images': ['static/description/banner.gif',],
    'data': [
        # 1) Access rights first:
        'security/ir.model.access.csv',
        'views/res_config_settings_views.xml',
        'views/excel_export_task_views.xml',
        # 'data/excel_export_cron.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
}
