# -*- coding: utf-8 -*-
{
    'name': 'Marathon Ventures',
    'summary': 'Salesforce -> Odoo 19 migration of Marathon Ventures CRM/Sales/Traffic schema.',
    'version': '19.0.1.2.1',
    'license': 'LGPL-3',
    'author': 'Marathon Ventures (generated)',
    'website': '',
    'category': 'Custom',
    'depends': ["base", "mail", "contacts", "crm", "sale_management", "product", "calendar"],
    'data': [
        # Groups must load before ACLs that reference them.
        'security/mv_security.xml',
        'security/ir.model.access.csv',
        'data/sequences.xml',
        'data/mv_data.xml',
        'data/days_allowed_seed.xml',
        'data/mv_days_tag_seed.xml',
        'data/filing_email_template.xml',
        'views/menus.xml',
        'views/crm_lead_views.xml',
        'views/mv_advertiser_views.xml',
        'views/mv_agency_double_check_views.xml',
        'views/mv_agency_match_error_accounts_views.xml',
        'views/mv_brands_views.xml',
        'views/mv_broadcast_month_views.xml',
        'views/mv_bundle_pricing_views.xml',
        'views/mv_case_views.xml',
        'views/mv_check_detail_views.xml',
        'views/mv_check_views.xml',
        'views/mv_clearance_list_views.xml',
        'views/mv_clearance_views.xml',
        'views/mv_contract_views.xml',
        'views/mv_contracts_views.xml',
        'views/mv_credit_application_views.xml',
        'views/mv_credit_monitoring_info_views.xml',
        'views/mv_credit_monitoring_views.xml',
        'views/mv_current_quarter_overview_views.xml',
        'views/mv_custom_debug_views.xml',
        'views/mv_deal_views.xml',
        'views/mv_disable_related_schedule_email_views.xml',
        'views/mv_double_checked_deals_views.xml',
        'views/mv_hiatus_excluded_views.xml',
        'views/mv_intacct_entity_views.xml',
        'views/mv_logger_settings_views.xml',
        'views/mv_market_views.xml',
        'views/mv_mass_deal_change_views.xml',
        'views/mv_opportunity_line_item_views.xml',
        'views/mv_other_sales_document_item_views.xml',
        'views/mv_other_sales_document_total_views.xml',
        'views/mv_other_sales_document_views.xml',
        'views/mv_pi_payout_views.xml',
        'views/mv_po_detail_views.xml',
        'views/mv_prelog_batch_networks_views.xml',
        'views/mv_prelog_data_mirror_views.xml',
        'views/mv_prelog_data_mirrors_views.xml',
        'views/mv_prelog_data_views.xml',
        'views/mv_prelog_import_job_views.xml',
        'views/mv_prelog_fuzzy_match_views.xml',
        'views/mv_programs_views.xml',
        'views/mv_pto_views.xml',
        'views/mv_purchase_order_views.xml',
        'views/mv_rating_detail_views.xml',
        'views/mv_rating_estimates_views.xml',
        'views/mv_rating_header_views.xml',
        'views/mv_ratings_compiled_views.xml',
        'views/mv_ratings_compiles_dayparts_views.xml',
        'views/mv_ratings_views.xml',
        'views/mv_raycom_monthly_line_item_views.xml',
        'views/mv_request_views.xml',
        'views/mv_sales_invoice_item_views.xml',
        'views/mv_sales_invoice_payment_views.xml',
        'views/mv_sales_invoice_total_views.xml',
        'views/mv_sales_invoice_views.xml',
        'views/mv_sales_order_item_views.xml',
        'views/mv_sales_order_total_views.xml',
        'views/mv_sales_order_views.xml',
        'views/mv_sales_plan_views.xml',
        'views/mv_sales_quote_item_views.xml',
        'views/mv_sales_quote_total_views.xml',
        'views/mv_sales_quote_views.xml',
        'views/mv_schedules_views.xml',
        'views/mv_sf_credit_memo_detail_views.xml',
        'views/mv_sf_credit_memo_old_views.xml',
        'views/mv_sf_credit_memo_views.xml',
        'views/mv_sf_credit_reference_views.xml',
        'views/mv_split_views.xml',
        'views/mv_spot_data_mirror_views.xml',
        'views/mv_spot_data_mirrors_views.xml',
        'views/mv_spot_data_views.xml',
        'views/mv_postlog_import_views.xml',
        'views/mv_station_views.xml',
        'views/mv_tape_views.xml',
        'views/mv_time_and_expense_detail_views.xml',
        'views/mv_time_and_expense_views.xml',
        'views/mv_traffic_video_asset_views.xml',
        'views/mv_traffic_views.xml',
        'views/mv_video_file_views.xml',
        'views/mv_working_log_views.xml',
        'views/product_template_views.xml',
        'views/res_partner_views.xml',
        'views/res_users_views.xml',
        'views/additional_schedules_wizard_views.xml',
        'views/phase1_deal_views.xml',
        'views/phase1_schedules_views.xml',
        'views/phase1_brands_views.xml',
        'views/deal_revisions_wizard_views.xml',
        'data/phase3_cron.xml',
        'data/phase28_post_log_cron.xml',
        'views/phase3_credit_application_views.xml',
        'views/phase3_credit_memo_views.xml',
        'views/phase3_advertiser_views.xml',
        'views/phase4_chatter_views.xml',
        'views/phase4_views.xml',
        'data/phase5_email_templates.xml',
        'views/phase5_views.xml',
        'views/phase6_dashboards.xml',
        'views/phase7_save_cancel_views.xml',
        'views/phase8_record_type_views.xml',
        'views/phase9_deal_layout_views.xml',
        'views/phase9_deal_system_views.xml',
        'views/phase9_schedule_layout_views.xml',
        'data/phase9_calendar_settings.xml',
        'views/phase10_units_report_tab.xml',
        'views/phase11_capping_tab.xml',
        'views/phase13_layout_views.xml',
        'views/phase14_report_types_views.xml',
        'views/phase14_reports_views.xml',
        'views/phase16_program_daypart_views.xml',
        'views/phase17_dataloader_views.xml',
        'views/phase28_post_log_import_views.xml',
        'views/mv_hide_manage_databases.xml',
        'views/menus_root_action.xml',
        'views/web_noindex.xml',
    ],
    'assets': {
        'web.assets_frontend': [
            'marathon_ventures/static/src/scss/mv_hide_manage_databases.scss',
        ],
        'web.assets_frontend_minimal': [
            'marathon_ventures/static/src/scss/mv_hide_manage_databases.scss',
        ],
        'web.assets_backend': [
            'marathon_ventures/static/src/scss/phase9_deal_layout.scss',
            'marathon_ventures/static/src/scss/phase9_calendar.scss',
            'marathon_ventures/static/src/scss/units_grid.scss',
            'marathon_ventures/static/src/scss/mv_chatter_collapsible.scss',
            'marathon_ventures/static/src/scss/mv_headers_sticky.scss',
            'marathon_ventures/static/src/js/units_grid/units_grid.js',
            'marathon_ventures/static/src/js/units_grid/units_grid.xml',
            'marathon_ventures/static/src/js/capping_grid/capping_grid.js',
            'marathon_ventures/static/src/js/capping_grid/capping_grid.xml',
            'marathon_ventures/static/src/js/chatter_collapsible/mv_chatter_collapsible.js',
            'marathon_ventures/static/src/js/prelog_program_dropdown/prelog_program_dropdown.js',
            'marathon_ventures/static/src/js/prelog_program_dropdown/prelog_program_dropdown.xml',
            'marathon_ventures/static/src/scss/prelog_fuzzy_matching.scss',
            'marathon_ventures/static/src/js/prelog_fuzzy_matching/prelog_fuzzy_matching.js',
            'marathon_ventures/static/src/js/prelog_fuzzy_matching/prelog_fuzzy_matching.xml',
            # Postlog Workbench. Deliberately reuses the prelog stylesheet
            # (shared .mv-fuzzy__* class names) so the two pages cannot drift
            # visually and there is only one place to restyle.
            'marathon_ventures/static/src/js/postlog_matching/postlog_matching.js',
            'marathon_ventures/static/src/js/postlog_matching/postlog_matching.xml',
            'marathon_ventures/static/src/scss/report_builder.scss',
            'marathon_ventures/static/src/js/report_builder/report_builder.js',
            'marathon_ventures/static/src/js/report_builder/report_builder.xml',
            'marathon_ventures/static/src/scss/dataloader_wizard.scss',
            'marathon_ventures/static/src/js/dataloader/dataloader_wizard.js',
            'marathon_ventures/static/src/js/dataloader/dataloader_wizard.xml',
            'marathon_ventures/static/src/js/deal_footer/mv_deal_footer.js',
            'marathon_ventures/static/src/scss/mv_related_tab.scss',
            'marathon_ventures/static/src/js/related_tab/mv_related_tab.js',
            'marathon_ventures/static/src/js/related_tab/mv_related_tab.xml',
            'marathon_ventures/static/src/js/toast_on_save/mv_toast_on_save.js',
            'marathon_ventures/static/src/js/duplicate_new_tab/mv_duplicate_new_tab.js',
            'marathon_ventures/static/src/js/additional_details_toggle/mv_additional_details_toggle.js',
            'marathon_ventures/static/src/scss/mv_days_picker.scss',
            'marathon_ventures/static/src/js/mv_days_picker/mv_days_picker.js',
            'marathon_ventures/static/src/js/mv_days_picker/mv_days_picker.xml',
            'marathon_ventures/static/src/scss/bundle_paperwork_dialog.scss',
            'marathon_ventures/static/src/js/bundle_paperwork/bundle_paperwork_dialog.js',
            'marathon_ventures/static/src/js/bundle_paperwork/bundle_paperwork_dialog.xml',
            'marathon_ventures/static/src/js/partner_default_tab/partner_default_tab.js',
            'marathon_ventures/static/src/scss/mv_email_tags.scss',
            'marathon_ventures/static/src/js/mv_email_tags/mv_email_tags.js',
            'marathon_ventures/static/src/js/mv_email_tags/mv_email_tags.xml',
        ],
        'web.assets_tests': [
            # Browser tour driving the Postlog Workbench; see
            # tests/test_postlog_workbench_ui.py
            'marathon_ventures/static/tests/tours/postlog_workbench_tour.js',
        ],
    },
    'installable': True,
    'application': True,
    'auto_install': False,
    # Phase 14 v4: backfill report_type_id on legacy mv.report rows
    # so the v3 -> v4 migration doesn't strand any data.
    'post_init_hook': 'post_init_hook',
}
