from . import test_common
from . import test_device
from . import test_echo_reply
from . import test_error
from . import test_greeting
from . import test_misc
from . import test_models
from . import test_registry
from . import test_security
from . import test_session
from . import test_static
from . import test_web_server
from . import test_webjson
from . import test_xss
