from . import test_access_propagation
from . import test_attachment_access
from . import test_attachment_split
from . import test_controllers
from . import test_document_access
from . import test_document_attachment_link
from . import test_document_audit_round3_wizards
from . import test_document_chatter
from . import test_document_common
from . import test_document_dangling_link
from . import test_document_document
from . import test_document_document_folder
from . import test_document_download
from . import test_document_embedded_actions
from . import test_document_gc
from . import test_document_multicompany
from . import test_document_multipage
from . import test_document_permission_algebra
from . import test_document_permissions
from . import test_document_public_routes
from . import test_document_request
from . import test_document_search_panel
from . import test_document_sharing
from . import test_document_shortcut
from . import test_document_tag
from . import test_document_type
from . import test_download_blocked_sharing
from . import test_document_thumbnail
from . import test_document_upload
from . import test_document_user_folder
from . import test_document_versioning
from . import test_js
from . import test_kpi_provider
from . import test_link_to_record
from . import test_mail_activity
from . import test_mail_gateway
from . import test_tools
from . import test_mixin_documents_contract
from . import test_wizard_isolation
from .tours import *
