from . import test_controller_contract
from . import test_discuss_channel_expand
from . import test_discuss_tools
from . import test_js
from . import test_fetchmail_server
from . import test_font_to_img
from . import test_ir_mail_server
from . import test_ir_mail_server_audit
from . import test_ir_mail_server_smtpd
from . import test_ir_mail_server_transport
from . import test_ir_model
from . import test_ir_ui_menu
from . import test_ir_websocket
from . import test_link_preview
from . import test_mail_activity
from . import test_mailgate
from . import test_mail_asset_index
from . import test_message_model_column
from . import test_mail_blacklist
from . import test_mail_composer
from . import test_mail_message_access_parity
from . import test_mail_message_search
from . import test_mail_mail
from . import test_mail_message
from . import test_mail_message_translate
from . import test_mail_notification
from . import test_mail_presence
from . import test_mail_render
from . import test_mail_template
from . import test_mail_template_references
from . import test_mail_tools
from . import test_mock_server_contract
from . import test_res_partner
from . import test_res_role
from . import test_res_users
from . import test_service_worker
from . import test_uninstall
from . import test_publisher_warranty
from . import test_update_notification
from . import test_webmanifest
from . import test_websocket_controller

from .discuss import *
from . import test_res_users_notification_type
from . import test_mail_activity_plan_template
