#!/bin/bash
### BEGIN INIT INFO
# Provides:          odoo.py
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start odoo daemon at boot time
# Description:       Enable service provided by daemon.
# X-Interactive:     true
### END INIT INFO
## more info: http://wiki.debian.org/LSBInitScripts

. /lib/lsb/init-functions

PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/bin
NAME=odoo
DESC=odoo
DAEMON=/home/pi/odoo/addons/point_of_sale/tools/posbox/configuration/odoo
PIDFILE_DAEMON=/var/run/${NAME}.pid
PIDFILE_ODOO=/var/run/${NAME}/${NAME}.pid
USER=pi

test -x $DAEMON || exit 0
set -e

function _start() {
    # Wait for time to be synced or AP to start or max 30 seconds
    cnt=30
    while ! test -a /run/systemd/timesync/synchronized && ! ip route | grep 10.11.12.1 && ((cnt--)); do
        sleep 1
    done
    start-stop-daemon --start --quiet --pidfile $PIDFILE_DAEMON --chuid $USER:$USER --background --make-pidfile --exec $DAEMON
}

function _stop() {
    start-stop-daemon --stop --quiet --pidfile $PIDFILE_DAEMON --oknodo --retry 3
    kill -9 $(cat $PIDFILE_ODOO)
    rm -f $PIDFILE_DAEMON $PIDFILE_ODOO
}

function _status() {
    start-stop-daemon --status --quiet --pidfile $PIDFILE_DAEMON
    return $?
}


case "$1" in
        start)
                echo -n "Starting $DESC: "
                _start
                echo "ok"
                ;;
        stop)
                echo -n "Stopping $DESC: "
                _stop
                echo "ok"
                ;;
        restart|force-reload)
                echo -n "Restarting $DESC: "
                _stop
                sleep 1
                _start
                echo "ok"
                ;;
        status)
                echo -n "Status of $DESC: "
                _status && echo "running" || echo "stopped"
                ;;
        *)
                N=/etc/init.d/$NAME
                echo "Usage: $N {start|stop|restart|force-reload|status}" >&2
                exit 1
                ;;
esac

exit 0
