from . import (
    test_attributes,
    test_autovacuum,
    test_backend_differential,
    test_cache_dead_pending,
    test_cache_scan_equivalence,
    test_company_checks,
    test_create_access_batching,
    test_count_field,
    test_domain,
    test_domain_evaluator_parity,
    test_env_operations,
    test_field_get_equivalence_db,
    test_field_groups_sql,
    test_fields,
    test_hotpath_contracts,
    test_index_method,
    test_indexed_translation,
    test_invalidate_pending_write,
    test_json_field_operations,
    test_many2many,
    test_registry_cleanup_scope,
    test_registry_metadata_ondelete,
    test_many2many_operations,
    test_onchange,
    test_one2many,
    test_one2many_read_grouping,
    test_primitives,
    test_properties,
    test_qweb_float,
    test_recordset_operations,
    test_regressions_o2m_and_defaults,
    test_regressions_read_group_and_misc,
    test_related_translation,
    test_schema,
    test_search,
    test_search_display_name,
    test_sort,
    test_traversal,
    test_ui,
    test_unity_read,
    test_user_favorite_mixin,
    test_validation,
    test_views,
    test_web_save,
    test_write_uniform_update,
)
from . import test_translation_write_propagation
from . import test_unlink_invalidation
from . import test_projection_constraints
from . import test_hierarchy_flush
from . import test_many2many_shared_relation
