{
    'name': 'ChatGPT Integration',
    'version': '16.0.1.0.0',
    'license': 'GPL-3',
    'summary': 'Odoo ChatGPT Integration',
    'description': 'Allows the application to leverage the capabilities of the GPT language model to generate human-like responses, providing a more natural and intuitive user experience, without installing OpenAI packages.',
    'author': 'Himanjali Intelligent Automation Private Limited',
    'company': 'Himanjali Intelligent Automation Private Limited',
    'maintainer': 'Himanjali Intelligent Automation Private Limited',
    'website': "https://www.himanjali.com/",
    'depends': ['base', 'base_setup', 'mail'],
    'data': [
        'security/ir.model.access.csv',
        'data/chatgpt_model_data.xml',
        'data/mail_channel_data.xml',
        'data/user_partner_data.xml',
        'views/res_config_settings_views.xml',
    ],
    'images': ['static/description/banner.gif'],
    'installable': True,
    'application': False,
    'auto_install': False,
}
