name: Build and Push Images to Docker Hub

on:
    push:
        branches:
            - production

jobs:
    build-and-push:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Log in to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Build and push Odoo Image
              uses: docker/build-push-action@v6
              with:
                  context: .
                  file: ./Dockerfile # أو حددي المسار الصحيح للـ Dockerfile في مجلدك
                  push: true
                  tags: ${{ secrets.DOCKERHUB_USERNAME }}/odoo:19
