name: CI - Validar Entorno Docker Compose

on:
  push:
    branches: ["19.0", "feature/**", "QA/**"]
  pull_request:
    branches: ["19.0"]

jobs:
  build-and-validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Levantar contenedores con Docker Compose
        working-directory: ./docker-config
        run: docker compose up -d

      - name: Esperar que Odoo arranque
        run: sleep 30

      - name: Verificar que los contenedores están corriendo
        working-directory: ./docker-config
        run: docker compose ps

      - name: Verificar que Odoo responde en el puerto 8069
        run: curl --retry 5 --retry-delay 10 -f http://localhost:8069

      - name: Ejecutar pruebas automatizadas del módulo de descuentos
        working-directory: ./docker-config
        run: |
          docker compose exec -T web odoo server \
            --http-port=8079 \
            --db_host=db \
            --db_user=odoo \
            --db_password=odoo \
            --addons-path=/usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons \
            -d odooips_discount_tests \
            -i validacion_descuento_maximo \
            --without-demo \
            --test-enable \
            --test-tags /validacion_descuento_maximo \
            --stop-after-init \
            --log-level=test

      - name: Apagar contenedores
        if: always()
        working-directory: ./docker-config
        run: docker compose down -v
