
static/js/livesupport_templates.js: static/js/livesupport_templates.html
	python static/js/to_jsonp.py static/js/livesupport_templates.html oe_livesupport_templates_callback > static/js/livesupport_templates.js